Repository lensapp/lens, pull requests merged in 2020-09, with the labels that each got.

#743 Fixing app crash when iterating Events without 'kind' prop defined
  src/renderer/api/kube-api-parse.ts
  src/renderer/navigation.ts
Labels: bug

#778 Detect invalid bundled kubectl
  Makefile
  src/main/kube-auth-proxy.ts
  src/main/kubectl.ts
  src/main/kubectl_spec.ts
Labels: enhancement

#481 Allow for users to enabled release mode debugging
  .gitignore
  src/main/index.ts
  src/main/logger.ts
Labels: enhancement

#776 Allow to override logger for LensBinary
  src/main/helm/helm-repo-manager.ts
  src/main/lens-binary.ts
Labels: enhancement

#780 Update Kubectl version map
  src/main/kubectl.ts
Labels: enhancement

#781 Bump versions of bundled binaries
  package.json
Labels: enhancement

#774 Do not set app to dev mode if debugging flag is passed
  src/common/vars.ts
Labels: bug

#788 Adding margin to last cluster menu icon
  src/renderer/components/cluster-manager/clusters-menu.scss
Labels: bug

#785 Update help texts on Add cluster page
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: enhancement

#789 Try to reconnect non-accessible clusters on activate
  src/main/cluster.ts
Labels: bug

#793 Removing webpack warnings on build
  src/main/window-manager.ts
Labels: chore

#799 Download binaries before building the app
  Makefile
Labels: bug

#641 Some Grammatical Fixes ❤️
  README.md
Labels: chore

#802 Remove double copyright
  src/main/menu.ts
Labels: area/ui, bug

#797 Change order of init for fresh clone
  Makefile
Labels: bug

#718 Update CRD api to use preferred version and implement v1 differences
  src/main/logger.ts
  src/renderer/api/endpoints/crd.api.ts
  src/renderer/api/kube-api-versioned.ts
  src/renderer/components/+custom-resources/crd-details.tsx
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
Labels: area/ui, bug, enhancement

#804 Close Preferences and Cluster Setting on Esc keypress
  src/renderer/components/+cluster-settings/cluster-settings.tsx
  src/renderer/components/+preferences/preferences.tsx
Labels: area/ui, bug, enhancement

#805 Restrict pasted kubeconfig file permissions to only the user
  src/common/cluster-store.ts
  src/common/utils/saveToAppFiles.ts
Labels: enhancement

#623 add drag and drop capabilities for the order of cluster icons on the side bar
  package.json
  src/common/cluster-store.ts
  src/common/cluster-store_test.ts
  src/main/cluster.ts
  src/renderer/components/cluster-icon/cluster-icon.scss
  src/renderer/components/cluster-manager/clusters-menu.tsx
  yarn.lock
Labels: area/ui, bug

#800 Allow user to configure kubectl binary preferences
  src/common/user-store.ts
  src/main/kubectl.ts
  src/main/shell-session.ts
  src/renderer/components/+preferences/kubectl-binaries.tsx
  src/renderer/components/+preferences/preferences.scss
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/input/input.validators.ts
Labels: area/linux, area/macos, area/windows, bug, enhancement

#810 Removing DEBUG env from package.json commands
  package.json
  yarn.lock
Labels: chore

#815 Fixing Cluster Icon margins
  src/renderer/components/cluster-icon/cluster-icon.scss
  src/renderer/components/cluster-manager/clusters-menu.scss
Labels: area/ui, bug

#814 Fix: stale values in Cluster Settings
  src/renderer/components/+cluster-settings/components/cluster-home-dir-setting.tsx
  src/renderer/components/+cluster-settings/components/cluster-name-setting.tsx
  src/renderer/components/+cluster-settings/components/cluster-prometheus-setting.tsx
  src/renderer/components/+cluster-settings/components/cluster-proxy-setting.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
Labels: bug

#794 add progress bar for webpack compilation
  package.json
  webpack.dll.ts
  webpack.main.ts
  webpack.renderer.ts
  yarn.lock
Labels: chore, enhancement

#795 Extensions loading
  .gitignore
  package.json
  src/common/cluster-store.ts
  src/common/vars.ts
  src/extensions/example-extension/README.md
  src/extensions/example-extension/example-extension.ts
  src/extensions/example-extension/package.json
  src/extensions/example-extension/tsconfig.json
  src/extensions/extension-api.ts
  src/extensions/extension-store.ts
  src/extensions/extension.ts
  src/extensions/lens-runtime.ts
  src/extensions/tsconfig.json
  src/main/menu.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+extensions/extensions.route.ts
  src/renderer/components/+extensions/extensions.scss
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+extensions/index.ts
  src/renderer/components/cluster-icon/cluster-icon.scss
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/clusters-menu.scss
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/components/cluster-manager/register-page.ts
  src/renderer/lens-app.tsx
  static/RELEASE_NOTES.md
  tsconfig.json
  types/mocks.d.ts
  webpack.dll.ts
  webpack.renderer.ts
  yarn.lock
Labels: area/extension, enhancement

#835 Remove explicit yarn install call from make build task
  Makefile
Labels: bug

#817 Extensions-api: initial hello-world example
  .eslintrc.js
  .gitignore
  src/extensions/example-extension/example-extension.ts
  src/extensions/example-extension/example-extension.tsx
  src/extensions/example-extension/package.json
  src/extensions/example-extension/tsconfig.json
  src/extensions/extension-api.ts
  src/extensions/extension-store.ts
  src/extensions/lens-extension.ts
  src/extensions/lens-runtime.ts
  src/extensions/register-page.tsx
  src/renderer/bootstrap.tsx
  src/renderer/components/app.tsx
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/components/cluster-manager/register-page.ts
  src/renderer/components/layout/main-layout.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/lens-app.tsx
Labels: area/extension, enhancement

#844 remove make-syncronous and file-type calls from migration
  package.json
  src/common/cluster-store_test.ts
  src/migrations/cluster-store/3.6.0-beta.1.ts
  src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx
  yarn.lock
Labels: bug

#832 Setting new workspace name restrictions
  src/common/workspace-store.ts
  src/common/workspace-store_test.ts
  src/renderer/components/+workspaces/workspaces.tsx
Labels: area/ui, bug

#846 Fix cluster's apiUrl
  src/common/cluster-store_test.ts
  src/main/cluster.ts
Labels: bug

#848 [FIX]: Cluster dashboard not rendered
  src/common/cluster-ipc.ts
  src/common/cluster-store.ts
  src/main/cluster-manager.ts
  src/main/cluster.ts
  src/main/window-manager.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/app.tsx
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/cluster-status.tsx
  src/renderer/components/cluster-manager/cluster-view.route.ts
  src/renderer/components/cluster-manager/lens-views.ts
Labels: area/ui, bug

#857 Fix proxy kubeconfig file permissions
  src/main/kubeconfig-manager.ts
Labels: bug

#856 Preserve path in proxy kubeconfig if present in original kubeconfig
  src/main/context-handler.ts
Labels: bug

#858 App reload in cluster settings
  src/renderer/components/+cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-manager/cluster-view.route.ts
  src/renderer/components/cluster-manager/clusters-menu.tsx
Labels: bug

#892 Remove extra refreshEvents polling
  src/main/cluster.ts
Labels: bug

#887 Inject Host header to k8s client requests
  package.json
  src/main/cluster-manager.ts
  src/main/cluster.ts
  src/main/kubeconfig-manager.ts
  src/main/lens-proxy.ts
  yarn.lock
Labels: bug

#893 Fix windows installer when app directory removed manually
  build/installer.nsh
  package.json
Labels: area/windows, bug

#900 Fix ws upgrade for terminal session
  src/main/lens-proxy.ts
Labels: bug

#906 Fix ingress points rendering if no data available
  src/renderer/components/+network-ingresses/ingress-details.tsx
Labels: area/ui, bug

#916 reduce the main BrowserWindow minimum size
  src/main/window-manager.ts
Labels: area/ui, bug

#917 fix integration tests not deselecting dropdown
  integration/specs/app_spec.ts
Labels: bug

#914 add a zero width space to Badges to fix double click highlighting issue
  src/renderer/components/badge/badge.tsx
Labels: area/ui, bug

#908 Fix service account's imagePullSecrets rendering if secret is not found
  src/renderer/components/+user-management-service-accounts/service-accounts-details.tsx
Labels: area/ui, bug

#938 Optimise cluster activate and refresh
  src/common/cluster-ipc.ts
  src/main/cluster.ts
  src/main/shell-session.ts
  src/renderer/components/+cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-manager/cluster-status.tsx
Labels: bug

#930 fix bug - deleted namespace does not get auto unselected
  src/renderer/components/+namespaces/namespace.store.ts
Labels: area/ui, bug

#935 get focus to dock tab content after resize
  src/renderer/components/dock/editor-panel.tsx
  src/renderer/components/dock/terminal.ts
Labels: bug

#940 Fix background of What's New page with white theme
  src/renderer/components/+whats-new/whats-new.scss
Labels: area/ui, bug

#915 fix Notifications blocking items not visually under them from being interacted with
  src/renderer/components/dock/info-panel.tsx
  src/renderer/components/notifications/notifications.scss
Labels: area/ui, bug

#888 Auto select one and only cluster from pasted config
  integration/specs/app_spec.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/button/button.scss
  src/renderer/components/tooltip/tooltip.tsx
  src/renderer/components/tooltip/withTooltip.tsx
Labels: area/ui, enhancement

#942 reduce height on draggable-top and only render it on macos
  src/renderer/bootstrap.tsx
  src/renderer/components/app.scss
  src/renderer/components/cluster-manager/cluster-manager.tsx
Labels: area/ui, bug

#875 Make download dir option consistent with other settings
  src/common/user-store.ts
  src/main/kubectl.ts
  src/renderer/components/+preferences/kubectl-binaries.tsx
Labels: area/ui, bug

#961 Allow to add the same cluster to multiple workspaces
  src/common/cluster-store.ts
  src/common/cluster-store_test.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: bug

#947 Convert bytes in memory BarChart properly
  src/renderer/components/chart/bar-chart.tsx
Labels: area/ui, bug

#954 Fix iframe ipc flakyness after cluster is removed
  src/common/base-store.ts
  src/common/cluster-ipc.ts
  src/common/cluster-store.ts
  src/main/cluster.ts
  src/main/lens-proxy.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/cluster-manager/lens-views.ts
Labels: area/ui, bug

#956 dropdowns should have 'cursor: pointer;'
  src/renderer/components/select/select.scss
Labels: area/ui, bug

#962 Fix spdy proxy
  src/main/lens-proxy.ts
Labels: bug

#949 Helm components should always use version information
  src/renderer/components/+apps-helm-charts/helm-chart-details.scss
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
  src/renderer/components/dock/install-chart.store.ts
  src/renderer/components/dock/install-chart.tsx
  src/renderer/components/notifications/notifications.store.ts
  src/renderer/components/notifications/notifications.tsx
Labels: bug

#963 Cleanup proxy upgrade handler
  src/main/lens-proxy.ts
Labels: chore

#969 Do not filter contexts when adding new clusters
  src/common/cluster-store.ts
  src/common/cluster-store_test.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: area/ui, bug

#967 Fix reading CRD conditions
  src/renderer/api/endpoints/cert-manager.api.ts
  src/renderer/api/endpoints/crd.api.ts
Labels: area/ui, bug

#964 Helm 3.3.4
  package.json
Labels: area/security, bug

#966 Fix kubeconfig fetching for service account
  src/renderer/components/kubeconfig-dialog/kubeconfig-dialog.tsx
Labels: bug

#972 Add migration to fix kubeconfig paths that point to snap config dir
  src/migrations/cluster-store/index.ts
  src/migrations/cluster-store/snap.ts
Labels: area/linux, bug

#984 Fix: removing pre-defined Input type
  src/renderer/components/input/input.tsx
Labels: area/ui, chore

#890 adding more integration tests
  integration/specs/app_spec.ts
Labels: area/tests, enhancement

#987 make namespace filter multi select and change onChange
  src/renderer/components/+namespaces/namespace-select.tsx
Labels: area/ui, bug

#985 Extensions api types
  .gitignore
  package.json
  src/extensions/example-extension/example-extension.tsx
  src/extensions/extension-api.ts
  src/extensions/extension-store.ts
  src/extensions/lens-extension.ts
  src/extensions/rollup.config.js
  src/extensions/rollup.config.ts
  src/extensions/tsconfig.json
  types/mocks.d.ts
  yarn.lock
Labels: area/extension

#994 Fix CRD conditions rendering
  src/renderer/api/endpoints/crd.api.ts
  src/renderer/components/+custom-resources/crd-resource-details.tsx
Labels: bug

#993 Move in-tree extensions to top-level folder
  extensions/example-extension/README.md
  extensions/example-extension/example-extension.tsx
  extensions/example-extension/package.json
  extensions/example-extension/tsconfig.json
  package.json
  src/extensions/extension-store.ts
Labels: area/extension

#912 refactor overview statuses to be more DRY
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/renderer/components/+workloads-daemonsets/daemonsets.store.ts
  src/renderer/components/+workloads-deployments/deployments.store.ts
  src/renderer/components/+workloads-overview/overview-statuses.tsx
  src/renderer/components/+workloads-replicasets/replicasets.store.ts
  src/renderer/components/+workloads-statefulsets/statefulset.store.ts
  src/renderer/components/+workloads/index.ts
  src/renderer/components/+workloads/workloads.route.ts
  src/renderer/components/+workloads/workloads.stores.ts
  src/renderer/kube-object.store.ts
  src/renderer/utils/rbac.ts
Labels: area/ui, chore

#1001 Fix extension-api module alias on production build
  src/common/vars.ts
Labels: area/extension, bug

#1000 Expose react to extensions
  extensions/example-extension/.gitignore
  extensions/example-extension/example-extension.tsx
  src/extensions/extension-api.ts
Labels: area/extension

#1002 Cleanup production build
  package.json
Labels: area/extension, chore

#998 Add support for Docker Enterprise Container Cloud metrics
  src/common/prometheus-providers.ts
  src/main/prometheus/stacklight.ts
Labels: enhancement

#982 Terminal: set NO_PROXY env for localhost communication
  src/main/kubectl.ts
  src/main/shell-session.ts
Labels: bug

#632 Fix CPU/Memory usage metrics when using prometheus operator.
  src/main/prometheus/operator.ts
Labels: area/metrics, bug
