Repository lensapp/lens, pull requests merged in 2020-12, with the labels that each got.

#1580 add bug label by default on bug issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: chore

#1578 Fix extension status-bar item default styles
  src/renderer/components/cluster-manager/bottom-bar.scss
  src/renderer/components/cluster-manager/bottom-bar.tsx
Labels: area/extension, area/ui, bug

#1585 Fix link to metrics resources
  extensions/metrics-cluster-feature/renderer.tsx
Labels: bug

#1550 Tweak extensions page texts
  docs/extensions/usage/README.md
  docs/extensions/usage/images/extensions.png
  src/renderer/components/+extensions/extensions.tsx
Labels: area/documentation, area/extension, area/ui, enhancement

#1573 Hide disabled workspaces/clusters
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/workspace-store.test.ts
  src/common/cluster-store.ts
  src/common/workspace-store.ts
  src/main/cluster.ts
  src/renderer/components/+workspaces/workspaces.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
Labels: bug

#1584 Add appPreferences guide
  docs/extensions/guides/renderer-extension.md
  docs/extensions/guides/stores.md
Labels: area/documentation

#1579 fix symlinking extensions into .k8slens/extensions folder
  src/extensions/extension-discovery.ts
  src/renderer/components/+extensions/extensions.tsx
Labels: area/extension, bug

#1583 Add basic usage docs for extensions
  docs/extensions/usage/README.md
Labels: area/documentation, area/extension

#1596 Fix extensions installation on Windows
  src/common/utils/tar.ts
  src/renderer/components/+extensions/extensions.tsx
Labels: bug

#1600 lint whole repo
  .eslintrc.js
  extensions/example-extension/package-lock.json
  package.json
  types/dom.d.ts
  types/font-face.d.ts
  webpack.extensions.ts
  webpack.main.ts
  webpack.renderer.ts
Labels: chore

#1606 Add <BottomBar /> support rendering if item is a function
  src/renderer/components/cluster-manager/bottom-bar.test.tsx
  src/renderer/components/cluster-manager/bottom-bar.tsx
Labels: area/extension, bug

#1586 Add Ready status column in the Deployment view
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/renderer/components/+workloads-pods/pod-details-list.tsx
Labels: area/ui, enhancement

#1609 Fix getExtensionPageUrl on Windows
  src/extensions/registries/page-registry.ts
  webpack.extensions.ts
  webpack.main.ts
  webpack.renderer.ts
Labels: area/extension, area/windows, bug

#1616 Detect microk8s distribution
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1617 Detect rancher distros
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1610 Add run tests step to Windows pipeline
  .azure-pipelines.yml
  src/main/__test__/kubeconfig-manager.test.ts
Labels: area/ci

#1621 actually use ResourceQuotaDetails
  src/renderer/components/+config-resource-quotas/resource-quota-details.tsx
Labels: bug

#1622 Detect Mirantis Kubernetes Engine
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1623 Detect Docker Desktop
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1619 Detect kind
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1594 Fix 'cannot read property hide of null' error on quit
  src/main/exit-app.ts
  src/main/window-manager.ts
Labels: bug

#1640 Performance fix when cluster has lots of namespaces
  src/main/__test__/cluster.test.ts
  src/main/cluster.ts
Labels: bug

#1639 Respect static list of allowed namespaces
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/kube-object.store.ts
Labels: bug

#1637 Open file select dialog from onClick event
  src/renderer/components/+extensions/extensions.tsx
Labels: area/linux, bug

#1627 fix URL validator, add some tests
  src/renderer/components/input/__tests__/input_validators.test.ts
  src/renderer/components/input/input_validators.ts
Labels: area/tests, bug

#1645 switch to using public mkdocs for check docs step
  .github/workflows/check-docs.yml
Labels: area/ci, area/documentation

#1648 Split workflow into verify and build jobs
  .github/workflows/main.yml
Labels: area/documentation

#1631 Add timeout to app start and cluster add tracking events
  src/main/window-manager.ts
  src/renderer/components/app.tsx
Labels: bug

#1654 Add dependabot config
  .github/dependabot.yml
Labels: area/ci, area/security

#1638 Fixing SidebarNavItem to rerender when url changes
  src/renderer/components/layout/sidebar.tsx
Labels: area/ui, bug

#1629 Status bar item and kube object menu/detail item extension guides
  docs/extensions/guides/images/kubeobjectdetailitem.png
  docs/extensions/guides/images/kubeobjectdetailitemwithpods.png
  docs/extensions/guides/images/kubeobjectmenuitem.png
  docs/extensions/guides/images/kubeobjectmenuitemdetail.png
  docs/extensions/guides/renderer-extension.md
Labels: area/documentation

#1602 persist extension installation state for the duration of the window's life
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/+extensions/extension-install.store.ts
  src/renderer/components/+extensions/extensions.tsx
Labels: area/extension, area/ui, bug

#1605 store more than largest kube api request amount in the event store
  src/renderer/components/+events/event.store.ts
  src/renderer/kube-object.store.ts
Labels: bug

#1665 Mark conf as dev dependency in extension npm package
  src/extensions/npm/extensions/package.json
Labels: area/extension, bug

#1625 Detect Openshift
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1667 Initial FAQ docs
  docs/faq/README.md
Labels: area/documentation, enhancement

#1662 Add initial KubeObjectListLayout sample
  docs/extensions/guides/images/certificates-crd-list.png
  docs/extensions/guides/kube-object-list-layout.md
Labels: area/documentation

#1589 Tag cluster & workspace as beta features in extension api
  src/common/workspace-store.ts
  src/extensions/core-api/stores.ts
  src/extensions/stores/cluster-store.ts
  src/extensions/stores/workspace-store.ts
  src/main/cluster.ts
Labels: area/documentation, area/extension

#1660 write up on some ways to publish extensions
  docs/extensions/testing-and-publishing/publishing.md
Labels: area/documentation, area/extension

#1663 extension store guide
  docs/extensions/guides/stores.md
  mkdocs.yml
Labels: area/documentation

#1681 yet another minor fix to main readme
  README.md
Labels: area/documentation

#1688 Register cluster page component properly to a route
  src/renderer/components/app.tsx
Labels: area/extension, bug

#1368 Add posibility to add custom helm repository
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/main/helm/helm-repo-manager.ts
  src/renderer/components/+preferences/add-helm-repo-dialog.scss
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/+preferences/preferences.tsx
Labels: area/ui, enhancement

#1692 Query all objects using single api call if admin and namespace list is not overridden
  src/renderer/kube-object.store.ts
Labels: bug

#1698 Fix status brick alignment in pod-menu extension
  extensions/pod-menu/src/logs-menu.tsx
  extensions/pod-menu/src/shell-menu.tsx
Labels: area/ui, bug

#1714 Do not call initMainWindow if windowManager is not ready
  src/main/index.ts
Labels: bug

#1704 Full support for ReplicaSets
  integration/__tests__/app.tests.ts
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/common/rbac.ts
  src/renderer/api/endpoints/pods.api.ts
  src/renderer/api/endpoints/replica-set.api.ts
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-overview/overview-statuses.scss
  src/renderer/components/+workloads-overview/overview-statuses.tsx
  src/renderer/components/+workloads-replicasets/replicaset-scale-dialog.scss
  src/renderer/components/+workloads-replicasets/replicaset-scale-dialog.test.tsx
  src/renderer/components/+workloads-replicasets/replicaset-scale-dialog.tsx
  src/renderer/components/+workloads-replicasets/replicasets.scss
  src/renderer/components/+workloads-replicasets/replicasets.store.ts
  src/renderer/components/+workloads-replicasets/replicasets.tsx
  src/renderer/components/+workloads/workloads.route.ts
  src/renderer/components/+workloads/workloads.stores.ts
  src/renderer/components/+workloads/workloads.tsx
  src/renderer/components/app.tsx
Labels: area/ui, enhancement

#1748 Fix buggy node metrics/chart
  src/renderer/components/+nodes/node-charts.tsx
Labels: area/metrics, bug

#1745 Use correct apiversion for HPA details
  src/renderer/components/+config-autoscalers/hpa-details.tsx
Labels: bug

#1753 Ensure telemetry report is sent on extension start
  extensions/telemetry/src/tracker.ts
Labels: bug

#1538 Add information about the startupProbe
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/renderer/api/endpoints/deployment.api.ts
  src/renderer/api/endpoints/pods.api.ts
  src/renderer/components/+workloads-pods/pod-details-container.tsx
Labels: area/ui, enhancement

#1655 Exclude github actions & docs from azure pipeline
  .azure-pipelines.yml
Labels: area/ci

#1742 Ensure only one app instance
  src/main/index.ts
Labels: bug

#1746 Export the pod-details-list component so that it can be used in Extensions
  src/extensions/renderer-api/components.ts
Labels: area/extension, enhancement

#1766 Switch master branch version to 4.1.0-alpha.0
  package.json
  static/RELEASE_NOTES.md
Labels: chore

#1781 Metrics-cluster-feature: bundle semver package
  extensions/metrics-cluster-feature/package-lock.json
  extensions/metrics-cluster-feature/package.json
Labels: area/extension, bug

#1782 Install in-tree extensions before others
  src/extensions/extension-discovery.ts
Labels: area/extension, bug

#1785 fix extension-filesystem being called in LensRendererExtension
  src/main/extension-filesystem.ts
Labels: bug

#1772 fix "not valid as a React child" error while display crds
  src/renderer/components/+custom-resources/crd-resources.tsx
Labels: area/ui, bug

#1792 Fix openshift distribution detector
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1795 Fix Azure distribution detection
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1798 Fix MacOS error on shutdown
  src/main/index.ts
Labels: area/macos, bug

#1800 Bundle kubectl v1.17.15
  package.json
Labels: bug

#1806 Test different kube versions
  .azure-pipelines-k8s-matrix.yml
  Makefile
Labels: area/ci, enhancement

#1804 Generate metadata.selfLink if response does not have it
  src/renderer/api/api-manager.ts
  src/renderer/api/kube-api.ts
  src/renderer/api/kube-watch-api.ts
  src/renderer/kube-object.store.ts
Labels: bug

#1751 Fix: expand/collapse state for CRD sidebar items
  src/renderer/components/layout/sidebar-context.ts
  src/renderer/components/layout/sidebar-nav-item.scss
  src/renderer/components/layout/sidebar-nav-item.tsx
  src/renderer/components/layout/sidebar.scss
  src/renderer/components/layout/sidebar.tsx
Labels: area/ui, bug

#1821 Kube state metrics 1.9.7
  extensions/metrics-cluster-feature/resources/14-kube-state-metrics-deployment.yml.hb
  extensions/metrics-cluster-feature/src/metrics-feature.ts
Labels: area/metrics, bug

#1825 Fix proxy retry counter cleanup on success
  src/main/lens-proxy.ts
Labels: bug

#1827 Render node list before metrics are available
  src/renderer/components/+nodes/nodes.tsx
Labels: area/ui, bug

#1793 Parse jsonPath expressions
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/utils/__tests__/jsonPath.test.tsx
  src/renderer/utils/jsonPath.ts
Labels: bug

#1826 Fix namespace store subscribe
  src/renderer/components/+namespaces/namespace.store.ts
Labels: bug

#1828 Fix: missing dependent types for Select and Slider components
  package.json
  src/extensions/npm/extensions/package.json
  yarn.lock
Labels: area/extension, bug

#1832 Display node column in pods list
  src/renderer/components/+workloads-pods/pods.scss
  src/renderer/components/+workloads-pods/pods.tsx
  src/renderer/components/badge/badge.scss
  src/renderer/components/badge/badge.tsx
Labels: area/ui, enhancement

#1830 Optimise Cluster.getAllowedResources()
  package.json
  src/main/cluster.ts
  yarn.lock
Labels: bug

#1842 update intro video links
  README.md
  docs/README.md
Labels: area/documentation

#1819 Fix huawei distro detect
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1809 Add kubectl v1.20 to version map
  src/main/kubectl.ts
Labels: bug

#1815 Fix extension loader race conditions
  src/extensions/__tests__/extension-discovery.test.ts
  src/extensions/extension-discovery.ts
  src/extensions/extension-installer.ts
  src/extensions/extension-loader.ts
  src/main/index.ts
Labels: area/extension, bug

#1848 Disable oh-my-zsh auto-update prompt when resolving shell environment
  src/main/shell-session.ts
Labels: bug

#1846 Fix Kubectl 1.18 version in version map
  src/main/kubectl.ts
Labels: bug

#1829 Workloads overview: don't block on store load
  src/renderer/components/+workloads-overview/overview.tsx
Labels: bug

#1817 Fix vmware distro detect
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1816 Fix tencent distribution detect
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1818 Fix alibaba distro detect
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1851 Preserving line breaks when copiyng logs
  src/renderer/components/dock/pod-log-list.tsx
Labels: area/logs, area/ui, bug

#1849 Fix k0s distribution detection
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#1850 Check is persistent volume claims resource to allowed for user
  src/common/rbac.ts
  src/renderer/components/+storage/storage.tsx
  src/renderer/utils/rbac.ts
Labels: bug

#1822 Unify Age column output with kubectl
  src/renderer/utils/__tests__/formatDuration.test.ts
  src/renderer/utils/formatDuration.ts
Labels: enhancement

#1784 Export wizard components
  src/extensions/renderer-api/components.ts
Labels: area/extension, enhancement

#1755 Catch HTTP Errors in case pod metrics resources not exist / access forbidden
  src/renderer/components/+workloads-pods/pods.store.ts
Labels: area/metrics, area/ui, bug

#1771 Clear Add Namespace and Add secret form data on close
  src/renderer/components/+config-secrets/add-secret-dialog.tsx
  src/renderer/components/+namespaces/add-namespace-dialog.tsx
Labels: area/ui, enhancement

#1863 Dock tabs context menu
  __mocks__/@linguiMacro.ts
  __mocks__/imageMock.ts
  package.json
  src/renderer/components/dock/__test__/dock-tabs.test.tsx
  src/renderer/components/dock/dock-tab.tsx
  src/renderer/components/dock/dock-tabs.tsx
  src/renderer/components/dock/dock.store.ts
  src/renderer/components/dock/dock.tsx
  src/renderer/components/menu/menu.tsx
  src/renderer/components/tabs/tabs.tsx
  yarn.lock
Labels: area/ui

#1841 Add tooltip for the node name in the nodes list
  src/renderer/components/+nodes/nodes.tsx
Labels: area/ui, enhancement

#1873 Applying dark colors to dock regardless of active theme
  src/renderer/components/+workloads-pods/pods.store.ts
  src/renderer/components/ace-editor/ace-editor.scss
  src/renderer/components/ace-editor/ace-editor.tsx
  src/renderer/components/dock/pod-log-list.scss
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
Labels: area/ui

#1867 Metrics-cluster-feature: scrape only lens-metrics namespace
  extensions/metrics-cluster-feature/resources/02-configmap.yml.hb
Labels: area/metrics, bug

#1868 Prometheus v2.19.3
  extensions/metrics-cluster-feature/resources/03-statefulset.yml.hb
  extensions/metrics-cluster-feature/resources/10-node-exporter-ds.yml.hb
  extensions/metrics-cluster-feature/src/metrics-feature.ts
Labels: area/metrics, enhancement

#1801 Helm 3.4.2
  package.json
Labels: enhancement

#1860 Add suspend/resume button for CronJobs
  src/renderer/api/api-manager.ts
  src/renderer/api/endpoints/cron-job.api.ts
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
Labels: bug, enhancement

#1799 Electron 9.4.0
  package.json
  yarn.lock
Labels: area/security, bug

#1878 Backport: fix ApiManager.getApiByKind
  src/renderer/api/api-manager.ts
Labels: bug

#1859 Don't open Lens at OS login by default
  src/common/user-store.ts
Labels: bug, enhancement

#1879 Share react-router and react-router-dom libraries to extensions
  src/renderer/bootstrap.tsx
Labels: area/extension, enhancement

#1877 Fixing long list cropping in sidebar
  src/renderer/components/layout/sidebar-nav-item.scss
Labels: area/ui, bug

#1604 add version display to extensions
  src/renderer/components/+extensions/extensions.scss
  src/renderer/components/+extensions/extensions.tsx
Labels: area/extension, area/ui
