Repository lensapp/lens, pull requests merged in 2020-06, with the labels that each got.

#367 Unify scrollbars/paddings across supported OS
  src/renderer/assets/css/app.scss
  src/renderer/components/MainMenu/MainMenu.vue
  src/renderer/components/PreferencesPage.vue
  src/renderer/components/common/ClosePageButton.vue
Labels: bug

#359 typo/translation correction: transit to transmit
  dashboard/client/api/endpoints/pods.api.ts
  dashboard/client/components/+workloads-pods/pod-charts.tsx
  dashboard/locales/en/messages.js
  dashboard/locales/en/messages.po
  dashboard/locales/ru/messages.js
  dashboard/locales/ru/messages.po
  src/main/prometheus/lens.ts
  src/main/prometheus/operator.ts
  src/main/prometheus/provider-registry.ts
Labels: bug

#402 Fix pod shell command on Windows
  dashboard/client/components/+workloads-pods/pod-menu.tsx
Labels: area/windows, bug

#399 Show object reference for all objects
  dashboard/client/api/kube-object.ts
  dashboard/client/api/workload-kube-object.ts
  dashboard/client/components/+workloads-pods/pod-details.tsx
  dashboard/client/components/kube-object/kube-object-meta.tsx
Labels: area/ui, enhancement

#366 Dynamic dashboard UI based on RBAC rules
  dashboard/client/api/json-api.ts
  dashboard/client/api/kube-watch-api.ts
  dashboard/client/api/rbac.ts
  dashboard/client/components/+cluster/cluster.tsx
  dashboard/client/components/+config/config.tsx
  dashboard/client/components/+namespaces/namespace-select.tsx
  dashboard/client/components/+network/network.tsx
  dashboard/client/components/+workloads-overview/overview-statuses.scss
  dashboard/client/components/+workloads-overview/overview-statuses.tsx
  dashboard/client/components/+workloads-overview/overview.tsx
  dashboard/client/components/+workloads/workloads.tsx
  dashboard/client/components/app.tsx
  dashboard/client/components/item-object-list/item-list-layout.tsx
  dashboard/client/components/layout/sidebar.tsx
  dashboard/server/common/license.ts
  src/main/routes/config.ts
Labels: enhancement

#400 Add arch node selector for hybrid clusters
  src/features/metrics/14-kube-state-metrics-deployment.yml.hb
Labels: bug

#411 Kill shell process by pid on Windows
  src/main/shell-session.ts
Labels: bug

#420 Remove Helm release update checker
  dashboard/client/api/endpoints/helm-releases.api.ts
  dashboard/client/components/+apps-releases/release-details.tsx
  dashboard/client/components/+apps-releases/release-menu.tsx
  dashboard/client/components/+apps-releases/releases.tsx
Labels: enhancement

#423 New logo
  build/icon.ico
  build/icon.png
  build/icons/512x512.png
  dashboard/client/components/icon/logo-full.svg
Labels: area/ui, enhancement

#440 Fix icon.ico
  build/icon.ico
Labels: area/windows, bug

#445 Track telemetry pref changed event
  src/renderer/components/PreferencesPage.vue
  src/renderer/store/index.js
Labels: chore, enhancement

#447 Fix resource lists auto-refresh
  dashboard/client/components/item-object-list/item-list-layout.tsx
Labels: bug

#441 Fix parseApi not accepting versions that don't start with 'v'
  dashboard/client/api/kube-api.ts
  dashboard/client/components/+workloads-deployments/deployment-scale-dialog.tsx
  dashboard/client/components/chart/bar-chart.tsx
  dashboard/client/components/chart/chart.tsx
  dashboard/client/components/chart/pie-chart.tsx
  dashboard/client/components/select/select.tsx
  dashboard/package.json
  dashboard/yarn.lock
  src/main/prometheus/lens.ts
Labels: bug

#461 Fix shell env cache
  src/main/shell-session.ts
Labels: bug

#474 Add downloads & slack badges
  README.md
Labels: chore

#472 Display namespace defined in kubeconfig always in the namespace selector
  dashboard/client/components/+namespaces/namespace-select.tsx
  dashboard/client/components/+namespaces/namespace.store.ts
Labels: area/ui, bug

#450 Fix `parseAPI` not working with non-"namespaces" pathnames.
  dashboard/client/api/__test__/parseAPI.test.ts
  dashboard/client/api/kube-api.ts
  dashboard/client/components/+workloads-deployments/deployment-scale-dialog.tsx
  dashboard/client/components/chart/bar-chart.tsx
  dashboard/client/components/chart/chart.tsx
  dashboard/client/components/chart/pie-chart.tsx
  dashboard/client/components/select/select.tsx
  dashboard/client/utils/__tests__/arrays.test.ts
  dashboard/client/utils/arrays.ts
  src/main/prometheus/lens.ts
Labels: bug

#479 Make sure that secret is defined before trying to decode
  dashboard/client/components/+workloads-pods/pod-container-env.tsx
Labels: bug

#464 Handle invalid metric response properly
  dashboard/client/api/endpoints/metrics.api.ts
  dashboard/client/components/+cluster/cluster.store.ts
  dashboard/client/components/+network-ingresses/ingress-charts.tsx
  dashboard/client/components/+workloads-pods/container-charts.tsx
  dashboard/client/components/+workloads-pods/pod-charts.tsx
Labels: bug

#449 Add pod creation integration test
  dashboard/client/components/dock/dock.tsx
  dashboard/client/components/layout/sidebar.tsx
  spec/integration/specs/app_spec.ts
Labels: area/tests, enhancement

#487 Update Helm to 3.2.4
  package.json
Labels: bug

#488 Revert select component
  dashboard/client/components/select/select.tsx
Labels: bug

#496 fix parseApi to not throw and to match apiVersion more specifically
  dashboard/client/api/__test__/parseAPI.test.ts
  dashboard/client/api/api-manager.ts
  dashboard/client/api/kube-api.ts
Labels: bug

#506 Open external links in web browser
  src/renderer/components/ClusterPage.vue
Labels: bug

#492 Fix pasting unicode into terminal sometimes not working
  src/main/index.ts
  src/main/shell-sync.ts
Labels: bug

#509 special case */namespace/* in parseApi, add test
  dashboard/client/api/__test__/parseAPI.test.ts
  dashboard/client/api/kube-api.ts
Labels: bug

#510 modified Kubectl.checkBinary() to test the binary for right version
  src/main/kubectl.ts
Labels: bug

#516 Fix lint issue in kubectl.ts
  src/main/kubectl.ts
Labels: chore

#529 Lint dashboard app automatically
  .eslintrc.js
  Makefile
  dashboard/client/api/endpoints/pods.api.ts
  dashboard/client/components/+network-endpoints/endpoint-details.tsx
  dashboard/client/components/+network-endpoints/endpoint-subset-list.tsx
  dashboard/client/components/+network-services/service-details-endpoint.tsx
  dashboard/client/components/+workloads-pods/pod-container-env.tsx
  dashboard/client/components/+workloads-pods/pod-details.tsx
  dashboard/client/components/+workloads/workloads.tsx
  dashboard/client/components/app.tsx
Labels: chore

#511 Add brew cask in README
  README.md
Labels: area/macos, chore

#532 Document release process
  RELEASE_GUIDE.md
Labels: chore
