Repository lensapp/lens, pull requests merged in 2020-07, with the labels that each got.

#551 Utilize api prefixes from common vars.ts
  src/common/vars.ts
  src/main/router.ts
  src/renderer/api/terminal-api.ts
  types/mocks.d.ts
Labels: chore

#554 Replace webview tag to iframe
  src/main/window-manager.ts
  src/renderer/_vue/assets/css/app.scss
  src/renderer/_vue/assets/css/custom.scss
  src/renderer/_vue/components/BottomBar/BottomBar.vue
  src/renderer/_vue/components/ClusterPage.vue
  src/renderer/_vue/store/modules/clusters.ts
Labels: chore, enhancement

#557 Use LensDev on development environment
  src/main/index.ts
Labels: bug, chore

#559 Show devtools always in menu
  src/main/menu.ts
Labels: area/ui, chore, enhancement

#469 Remove redundant applyHeaders method
  src/main/context-handler.ts
  src/main/proxy.ts
Labels: chore

#466 Kubeconfigs as file references
  src/common/cluster-store.ts
  src/common/cluster-store_spec.ts
  src/common/utils/kubeconfig.ts
  src/features/metrics.ts
  src/features/user-mode.ts
  src/main/cluster-manager.ts
  src/main/cluster.ts
  src/main/context-handler.ts
  src/main/feature-manager.ts
  src/main/helm-release-manager.ts
  src/main/helm-service.ts
  src/main/k8s.ts
  src/main/kube-auth-proxy.ts
  src/main/kubeconfig-manager.ts
  src/main/node-shell-session.ts
  src/main/resource-applier-api.ts
  src/main/routes/config.ts
  src/main/routes/kubeconfig.ts
  src/main/routes/port-forward.ts
  src/main/routes/watch.ts
  src/migrations/cluster-store/3.6.0-beta.1.ts
  src/renderer/_vue/components/AddClusterPage.vue
  src/renderer/_vue/store/modules/kube-contexts.js
Labels: enhancement

#582 fix format duration rounding days error
  src/common/user-store_spec.ts
  src/main/context-handler.ts
  src/main/kubectl.ts
  src/renderer/utils/formatDuration.ts
  src/renderer/utils/formatDuration_spec.ts
  tsconfig.json
Labels: bug

#622 Fix CRD api parsing
  src/renderer/api/kube-api-parse.ts
  src/renderer/api/kube-api-parse_test.ts
Labels: area/ui, bug
