Repository lensapp/lens, pull requests merged in 2020-08, with the labels that each got.

#624 Fix Resource Quota Rendering
  src/renderer/components/+config-resource-quotas/resource-quota-details.tsx
  src/renderer/utils/convertCpu.ts
  src/renderer/utils/convertMemory.ts
  src/renderer/utils/index.ts
  src/renderer/utils/metricUnitsToNumber.ts
  src/renderer/utils/metricUnitsToNumber_test.ts
Labels: bug

#645 cherry-pick: catch and log error from shell sync (#630)
  src/main/index.ts
  src/main/shell-sync.ts
Labels: bug

#659 use the Kubernetes regex for matching system names
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/renderer/api/kube-api-parse.ts
  src/renderer/components/input/input.validators.ts
  src/renderer/components/input/input.validators_test.ts
Labels: bug

#672 fix: 🐛 Change kind to "Endpoints" in renderer
  src/renderer/api/endpoints/endpoint.api.ts
Labels: bug

#658 Add support for customreasourcedefinitions under the v1 API
  src/renderer/api/endpoints/crd.api.ts
  src/renderer/components/+custom-resources/crd.store.ts
Labels: bug

#674 add some simple user store tests
  src/common/user-store_test.ts
Labels: chore

#678 Adding unit tests to ClusterStore
  src/common/cluster-store_test.ts
  src/main/cluster.ts
Labels: area/tests

#690 Update copyright, eula and contact details
  LICENSE
  package.json
  src/common/tracker.ts
  src/main/menu.ts
  src/renderer/themes/kontena-dark.json
  src/renderer/themes/kontena-light.json
  webpack.renderer.ts
Labels: chore

#680 add some basic workspace store tests
  src/common/workspace-store.ts
  src/common/workspace-store_test.ts
Labels: chore

#693 Handle status values that contains an object
  src/renderer/components/+custom-resources/crd-resource-details.tsx
Labels: area/ui, bug

#617 Handle unknown resources properly after they've been created in editor
  src/renderer/api/endpoints/resource-applier.api.ts
Labels: area/ui, bug

#721 Update release notes
  static/RELEASE_NOTES.md
Labels: chore

#723 Fix: incorrect path to install/uninstall feature
  src/main/feature.ts
Labels: bug

#724 Fix: sync in sub-frames for common-stores are broken
  src/common/base-store.ts
  src/common/cluster-ipc.ts
  src/renderer/components/app.tsx
Labels: bug

#452 Add support for PodDisruptionBudgets
  src/common/rbac.ts
  src/renderer/api/endpoints/index.ts
  src/renderer/api/endpoints/poddisruptionbudget.api.ts
  src/renderer/components/+config-pod-disruption-budgets/index.ts
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets-details.scss
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets-details.tsx
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets.route.ts
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets.scss
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets.store.ts
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets.tsx
  src/renderer/components/+config/config.tsx
Labels: enhancement

#732 Increase timeout when doing port-forward through tcpPortUsed.waitUntilUsed
  src/main/routes/port-forward-route.ts
Labels: bug

#694 Add cronjob trigger
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/renderer/api/endpoints/cron-job.api.ts
  src/renderer/api/endpoints/job.api.ts
  src/renderer/components/+workloads-cronjobs/cronjob-trigger-dialog.scss
  src/renderer/components/+workloads-cronjobs/cronjob-trigger-dialog.tsx
  src/renderer/components/+workloads-cronjobs/cronjob.store.ts
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-overview/overview-workload-status.scss
  src/renderer/components/+workloads/workloads-mixins.scss
  src/renderer/components/app.tsx
Labels: area/ui, enhancement

#722 Fix windows dev env
  Makefile
  package.json
  yarn.lock
Labels: chore

#673 add cluster icon migration code
  package.json
  src/common/cluster-store.ts
  src/common/cluster-store_test.ts
  src/migrations/cluster-store/2.7.0-beta.0.ts
  src/migrations/cluster-store/3.6.0-beta.1.ts
  src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx
  test-data/cluster-store-migration-icon.png
  yarn.lock
Labels: bug

#744 Fixing minor light theme issues
  src/renderer/components/+landing-page/landing-page.scss
  src/renderer/components/+workloads-cronjobs/cronjob-trigger-dialog.tsx
  src/renderer/components/chart/chart.tsx
  src/renderer/components/cluster-manager/clusters-menu.scss
  src/renderer/components/cluster-manager/clusters-menu.tsx
Labels: area/ui, enhancement

#754 Use proxy kubeconfig for shell and resource applier
  src/main/resource-applier.ts
  src/main/shell-session.ts
Labels: enhancement

#752 Fix manifests order for Metrics feature
  src/features/metrics/02-service-account.yml
Labels: enhancement

#758 Remove cluster view on cluster remove
  src/renderer/components/cluster-manager/lens-views.ts
Labels: area/ui, bug

#740 Allow user to select Kubeconfig from filesystem
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/common/cluster-store.ts
  src/common/cluster-store_test.ts
  src/common/kube-helpers.ts
  src/common/user-store.ts
  src/common/utils/saveToAppFiles.ts
  src/migrations/cluster-store/3.6.0-beta.1.ts
  src/renderer/components/+add-cluster/add-cluster.scss
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/ace-editor/ace-editor.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/components/dock/dock.scss
  src/renderer/components/input/file-input.tsx
  src/renderer/components/input/index.ts
  src/renderer/components/input/input.tsx
  src/renderer/components/layout/main-layout.scss
  src/renderer/components/layout/main-layout.tsx
  src/renderer/components/layout/wizard-layout.tsx
  src/renderer/components/notifications/notifications.tsx
  src/renderer/components/select/select.tsx
  src/renderer/components/tabs/tabs.scss
  src/renderer/components/tabs/tabs.tsx
Labels: area/ui, enhancement

#681 Change owner of minikube config files to $USER
  .azure-pipelines.yml
Labels: bug

#767 Fix integration tests
  integration/specs/app_spec.ts
Labels: area/tests, bug

#765 Fix: cluster-menu spacing, incorrect cluster-view after switching workspace
  src/common/workspace-store.ts
  src/renderer/components/+landing-page/landing-page.scss
  src/renderer/components/+landing-page/landing-page.tsx
  src/renderer/components/cluster-manager/clusters-menu.scss
  src/renderer/components/cluster-manager/clusters-menu.tsx
Labels: area/ui, bug
