Repository lensapp/lens, pull requests merged in 2020-11, with the labels that each got.

#1190 Fix proxy upgrade socket timeouts
  src/main/lens-proxy.ts
Labels: bug

#1174 License extension
  extensions/license-menu-item/Makefile
  extensions/license-menu-item/main.ts
  extensions/license-menu-item/package-lock.json
  extensions/license-menu-item/package.json
  extensions/license-menu-item/tsconfig.json
  extensions/license-menu-item/webpack.config.ts
  package.json
  src/common/utils/index.ts
  src/common/utils/openExternal.ts
  src/extensions/core-api/utils.ts
  src/main/menu.ts
Labels: area/extension

#1192 Fix UI staleness after network issues
  src/main/cluster-manager.ts
  src/main/cluster.ts
  src/renderer/api/kube-watch-api.ts
  src/renderer/components/app.tsx
  src/renderer/lens-app.tsx
Labels: bug

#1193 Add actions/labeler for auto label PRs
  .github/labeler-config.yml
  .github/workflows/labeler.yml
Labels: area/ci

#1194 Expose more apis for KubeObjectListLayout usage
  src/extensions/renderer-api/k8s-api.ts
  src/extensions/renderer-api/navigation.ts
Labels: area/extension, bug

#1203 Add types for analytics-node
  extensions/telemetry/package-lock.json
  extensions/telemetry/package.json
Labels: area/extension, bug

#1197 Release v4.0.0-alpha.3
  extensions/telemetry/package-lock.json
  package.json
  static/RELEASE_NOTES.md
Labels: area/extension

#1207 Load symlinked extension folders
  src/extensions/extension-manager.ts
Labels: area/extension, bug

#1191 Add +/- buttons in scale deployment popup screen
  .eslintrc.js
  __mocks__/@linguiMacro.ts
  __mocks__/electron.ts
  package.json
  src/jest.setup.ts
  src/renderer/api/endpoints/deployment.api.ts
  src/renderer/components/+workloads-deployments/deployment-scale-dialog.scss
  src/renderer/components/+workloads-deployments/deployment-scale-dialog.test.tsx
  src/renderer/components/+workloads-deployments/deployment-scale-dialog.tsx
  yarn.lock
Labels: area/test, area/ui, dependencies, enhancement

#1211 Fixing return statements in Pod menus extension
  extensions/pod-menu/src/logs-menu.tsx
  extensions/pod-menu/src/shell-menu.tsx
  src/renderer/components/+workloads-pods/pod-details.tsx
Labels: area/extension, area/ui

#1155 Update chart details when selecting another chart
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
Labels: area/ui, bug

#1214 Add CI step to run future extension tests.
  .azure-pipelines.yml
  Makefile
  build/set_npm_version.ts
  extensions/example-extension/Makefile
  extensions/example-extension/package.json
  extensions/license-menu-item/Makefile
  extensions/license-menu-item/package.json
  extensions/metrics-cluster-feature/Makefile
  extensions/metrics-cluster-feature/package.json
  extensions/node-menu/Makefile
  extensions/node-menu/package.json
  extensions/pod-menu/Makefile
  extensions/pod-menu/package.json
  extensions/support-page/Makefile
  extensions/support-page/package.json
  extensions/telemetry/Makefile
  extensions/telemetry/package-lock.json
  extensions/telemetry/package.json
Labels: area/ci, area/extension

#1221 Fix PR auto-labler failure on fork
  .github/workflows/labeler.yml
Labels: area/ci, bug

#1217 add @types/node to devDeps for npm extension
  extensions/support-page/package-lock.json
  extensions/support-page/package.json
  src/extensions/npm/extensions/.gitignore
  src/extensions/npm/extensions/package.json
Labels: area/extension

#1224 Release v4.0.0-alpha.4
  package.json
  static/RELEASE_NOTES.md
Labels: enhancement

#1208 UI for enabling/disabling extensions
  src/common/base-store.ts
  src/extensions/core-api/cluster-feature.ts
  src/extensions/core-api/stores.ts
  src/extensions/extension-loader.ts
  src/extensions/extension-manager.ts
  src/extensions/extension-store.ts
  src/extensions/lens-extension.ts
  src/extensions/registries/base-registry.ts
  src/main/index.ts
  src/main/menu.ts
  src/renderer/components/+extensions/extensions.route.ts
  src/renderer/components/+extensions/extensions.scss
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+extensions/index.ts
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/layout/page-layout.scss
  src/renderer/components/tooltip/tooltip.tsx
Labels: area/extension, area/ui

#1175 Restart deployment
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/renderer/api/endpoints/deployment.api.ts
  src/renderer/api/json-api.ts
  src/renderer/components/+workloads-deployments/deployments.tsx
Labels: enhancement

#1230 Documentation (MKDOCS)
  .github/workflows/main.yml
  README.md
  docs/CNAME
  docs/README.md
  docs/clusters/adding-clusters.md
  docs/clusters/images/add-cluster.png
  docs/clusters/images/cluster-settings.png
  docs/clusters/images/remove-cluster.png
  docs/clusters/removing-clusters.md
  docs/clusters/settings.md
  docs/custom_theme/img/favicon.ico
  docs/custom_theme/main.html
  docs/extensions/capabilities/common-capabilities.md
  docs/extensions/capabilities/overview.md
  docs/extensions/capabilities/theming.md
  docs/extensions/get-started/anatomy.md
  docs/extensions/get-started/wrapping-up.md
  docs/extensions/get-started/your-first-extension.md
  docs/extensions/guides/overview.md
  docs/extensions/guides/renderer-extension.md
  docs/extensions/overview.md
  docs/extensions/testing-and-publishing/bundling.md
  docs/extensions/testing-and-publishing/publishing.md
  docs/extensions/testing-and-publishing/testing.md
  docs/getting-started/downloading-lens.md
  docs/getting-started/images/color-theme.png
  docs/getting-started/images/disabled-telemetry-usage-tracking.png
  docs/getting-started/images/snap-store.png
  docs/getting-started/introductory-videos.md
  docs/getting-started/preferences.md
  docs/img/favicon.ico
  docs/img/lens-intro-video-screenshot.png
  docs/img/lens-logo-icon.svg
  docs/img/play.svg
  docs/stylesheets/extra.css
  docs/supporting/requirements.md
  mkdocs.yml
  mkdocs/Dockerfile
  mkdocs/requirements.txt
  package.json
  src/main/menu.ts
Labels: area/ci, area/documentation

#1254 Docs: enable syntax highlight for code blocks
  mkdocs.yml
Labels: area/documentation, enhancement

#1256 Renaming theme .json files
  src/common/user-store.ts
  src/renderer/components/dock/terminal.ts
  src/renderer/theme.store.ts
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
Labels: area/ui

#1249 Fix proxy upgrade socket timeouts
  src/main/lens-proxy.ts
Labels: bug

#1266 New Documentation: Contributing section
  docs/contributing/README.md
  docs/contributing/development.md
  docs/contributing/documentation.md
  docs/contributing/maintainers.md
  docs/contributing/promotion.md
Labels: area/documentation

#1264 Docs: extension testing
  docs/extensions/testing-and-publishing/testing.md
Labels: area/documentation, area/extension

#1265 Docs: Extension Anatomy
  docs/extensions/get-started/anatomy.md
Labels: area/documentation, area/extension

#1259 Docs: extension common capabilities
  docs/extensions/capabilities/common-capabilities.md
Labels: area/documentation, area/extension

#1233 Extensions api fixes
  src/extensions/extension-loader.ts
  src/extensions/extension-manager.ts
  src/extensions/extensions-store.ts
  src/extensions/lens-extension.ts
  src/main/index.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+extensions/extensions.scss
  src/renderer/components/+extensions/extensions.tsx
Labels: area/extension, area/ui, bug

#1272 Remove PR auto labler
  .github/labeler-config.yml
  .github/workflows/labeler.yml
Labels: area/ci

#1278 ApiManager.registerStore should be simplified
  src/renderer/api/api-manager.ts
  src/renderer/api/kube-api.ts
  src/renderer/components/+cluster/cluster.store.ts
  src/renderer/components/+config-autoscalers/hpa.store.ts
  src/renderer/components/+config-maps/config-maps.store.ts
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets.store.ts
  src/renderer/components/+config-resource-quotas/resource-quotas.store.ts
  src/renderer/components/+config-secrets/secrets.store.ts
  src/renderer/components/+custom-resources/crd.store.ts
  src/renderer/components/+events/event.store.ts
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/+network-endpoints/endpoints.store.ts
  src/renderer/components/+network-ingresses/ingress.store.ts
  src/renderer/components/+network-policies/network-policy.store.ts
  src/renderer/components/+network-services/services.store.ts
  src/renderer/components/+nodes/nodes.store.ts
  src/renderer/components/+pod-security-policies/pod-security-policies.store.ts
  src/renderer/components/+storage-classes/storage-class.store.ts
  src/renderer/components/+storage-volume-claims/volume-claim.store.ts
  src/renderer/components/+storage-volumes/volumes.store.ts
  src/renderer/components/+user-management-roles-bindings/role-bindings.store.ts
  src/renderer/components/+user-management-roles/roles.store.ts
  src/renderer/components/+user-management-service-accounts/service-accounts.store.ts
  src/renderer/components/+workloads-cronjobs/cronjob.store.ts
  src/renderer/components/+workloads-daemonsets/daemonsets.store.ts
  src/renderer/components/+workloads-deployments/deployments.store.ts
  src/renderer/components/+workloads-jobs/job.store.ts
  src/renderer/components/+workloads-pods/pods.store.ts
  src/renderer/components/+workloads-replicasets/replicasets.store.ts
  src/renderer/components/+workloads-statefulsets/statefulset.store.ts
Labels: enhancement

#1273 Fix Documentation: Contributing
  docs/contributing/promotion.md
  mkdocs.yml
Labels: area/documentation

#1250 Add webpack hot-reload/cache plugins to improve Lens DX
  package.json
  src/common/vars.ts
  src/main/router.ts
  webpack.main.ts
  webpack.renderer.ts
  yarn.lock
Labels: dependencies, enhancement

#1114 Log search
  .azure-pipelines.yml
  integration/__tests__/app.tests.ts
  src/common/__tests__/search-store.test.ts
  src/common/search-store.ts
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
  src/renderer/components/dock/pod-log-controls.tsx
  src/renderer/components/dock/pod-log-search.scss
  src/renderer/components/dock/pod-log-search.tsx
  src/renderer/components/dock/pod-logs.scss
  src/renderer/components/dock/pod-logs.store.ts
  src/renderer/components/dock/pod-logs.tsx
  src/renderer/components/input/index.ts
  src/renderer/components/input/input.tsx
  src/renderer/components/input/search-input-url.tsx
  src/renderer/components/input/search-input.scss
  src/renderer/components/input/search-input.tsx
  src/renderer/components/item-object-list/item-list-layout.scss
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/table/table.tsx
  src/renderer/components/virtual-list/virtual-list.scss
  src/renderer/components/virtual-list/virtual-list.tsx
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
  src/renderer/themes/theme-vars.scss
  types/dom.d.ts
Labels: area/ci, area/test, area/ui, enhancement

#702 Add mechanism for users to specify accessible namespaces
  locales/en/messages.po
  locales/fi/messages.po
  locales/ru/messages.po
  src/common/cluster-store.ts
  src/main/cluster.ts
  src/renderer/components/+cluster-settings/components/cluster-accessible-namespaces.tsx
  src/renderer/components/+cluster-settings/general.tsx
  src/renderer/components/editable-list/editable-list.scss
  src/renderer/components/editable-list/editable-list.tsx
  src/renderer/components/editable-list/index.ts
Labels: enhancement

#1269 add some overview documentation to the getting started page
  docs/extensions/get-started/overview.md
  docs/extensions/get-started/your-first-extension.md
Labels: area/documentation

#1267 Docs: extension styling and theming
  docs/extensions/capabilities/color-reference.md
  docs/extensions/capabilities/images/css-vars-in-devtools.png
  docs/extensions/capabilities/images/theme-selector.png
  docs/extensions/capabilities/styling.md
  docs/extensions/capabilities/theming.md
  mkdocs.yml
  src/renderer/components/app.scss
  src/renderer/components/radio/radio.scss
  src/renderer/components/vars.scss
Labels: area/documentation

#1105 implemented app menu testing support
  integration/__tests__/app.tests.ts
  src/main/menu.ts
  src/renderer/components/+preferences/preferences.tsx
Labels: area/ci, area/tests

#1297 Expose CRD api to extensions
  src/extensions/renderer-api/k8s-api.ts
  src/renderer/api/endpoints/index.ts
Labels: area/extension, enhancement

#1299 Fix KubeObjectDetails example in common capabilities
  docs/extensions/capabilities/common-capabilities.md
Labels: area/documentation, bug

#1234 Keeping Icon focus state only for keyboard
  package.json
  src/renderer/components/app.tsx
  src/renderer/components/drawer/drawer.scss
  src/renderer/components/icon/icon.scss
  src/renderer/components/kube-object/kube-object-menu.tsx
  src/renderer/components/layout/main-layout.tsx
  yarn.lock
Labels: area/ui

#1304 Do not expose registries to extensions
  src/extensions/core-api/index.ts
Labels: area/extension, enhancement

#1303 Removing !important statements from theme variables
  src/common/__tests__/user-store.test.ts
  src/common/user-store.ts
  src/renderer/components/app.scss
  src/renderer/theme.store.ts
Labels: area/ui, enhancement

#1087 Fix rendering of boolean values in CRDs
  src/common/utils/saveToAppFiles.ts
  src/renderer/api/api-manager.ts
  src/renderer/api/endpoints/crd.api.ts
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/drawer/drawer-item.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/components/spinner/spinner.scss
  src/renderer/components/spinner/spinner.tsx
  src/renderer/components/table/table-cell.tsx
  src/renderer/utils/__tests__/display-booleans.test.tsx
  src/renderer/utils/display-booleans.ts
  src/renderer/utils/index.ts
  tsconfig.json
Labels: area/ui, bug, dependencies

#1307 Generate extension api reference docs using library mode
  .github/workflows/main.yml
  docs/extensions/typedoc-readme.md.tpl
  mkdocs.yml
  package.json
  yarn.lock
Labels: area/documentation, area/extension

#1319 Expose all custom k8s api classes via extension api
  src/extensions/renderer-api/k8s-api.ts
Labels: area/extension, bug

#1322 Expose registration and related component interfaces to extensions
  src/extensions/core-api/index.ts
  src/extensions/interfaces/index.ts
  src/extensions/interfaces/registrations.ts
Labels: area/extension, enhancement

#1327 Fix: allow to fetch kube-api objects with label & field selectors
  src/renderer/api/kube-api-versioned.ts
  src/renderer/api/kube-api.ts
Labels: bug, enhancement

#1326 Expose kube object store types to extensions
  src/extensions/renderer-api/k8s-api.ts
Labels: area/extension

#1323 Remove windowManager from extension api
  docs/extensions/typedoc-readme.md.tpl
  extensions/support-page/main.ts
  extensions/support-page/package-lock.json
  src/extensions/core-api/index.ts
  src/extensions/lens-main-extension.ts
  src/extensions/renderer-api/index.ts
  src/extensions/renderer-api/navigation.ts
  src/main/index.ts
  src/main/tray.ts
  src/main/window-manager.ts
  src/renderer/navigation.ts
Labels: area/extension, bug

#1328 Refactoring: removed kube versioned api
  src/extensions/renderer-api/k8s-api.ts
  src/renderer/api/endpoints/crd.api.ts
  src/renderer/api/kube-api-versioned.ts
  src/renderer/api/kube-api.ts
Labels: enhancement

#1335 Allow to specify KubeObjectDetailRegistration priority
  src/extensions/registries/kube-object-detail-registry.ts
  src/renderer/components/+config-autoscalers/hpa-details.tsx
  src/renderer/components/+config-maps/config-map-details.tsx
  src/renderer/components/+events/kube-event-details.tsx
  src/renderer/components/+network-endpoints/endpoint-details.tsx
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+network-policies/network-policy-details.tsx
  src/renderer/components/+network-services/service-details.tsx
  src/renderer/components/+nodes/node-details.tsx
  src/renderer/components/+storage-classes/storage-class-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+storage-volumes/volume-details.tsx
  src/renderer/components/+user-management-roles-bindings/role-binding-details.tsx
  src/renderer/components/+user-management-roles/role-details.tsx
  src/renderer/components/+user-management-service-accounts/service-accounts-details.tsx
  src/renderer/components/+workloads-cronjobs/cronjob-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-jobs/job-details.tsx
  src/renderer/components/+workloads-pods/pod-details.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
Labels: area/extension, area/ui, enhancement

#1345 Add LensRendererExtension.navigate
  src/extensions/lens-renderer-extension.ts
  src/main/window-manager.ts
  src/renderer/navigation.ts
Labels: area/extension, enhancement

#1350 Add extension development instructions for Windows users
  docs/extensions/get-started/your-first-extension.md
Labels: area/documentation, enhancement

#1334 PageRegistration & BaseRegistry refactoring
  docs/extensions/capabilities/common-capabilities.md
  docs/extensions/get-started/anatomy.md
  extensions/support-page/main.ts
  extensions/support-page/renderer.tsx
  extensions/support-page/src/support.route.ts
  extensions/support-page/src/support.scss
  extensions/support-page/src/support.tsx
  integration/__tests__/app.tests.ts
  src/extensions/dynamic-page.tsx
  src/extensions/extension-loader.ts
  src/extensions/interfaces/registrations.ts
  src/extensions/lens-extension.ts
  src/extensions/lens-main-extension.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/app-preference-registry.ts
  src/extensions/registries/base-registry.ts
  src/extensions/registries/cluster-feature-registry.ts
  src/extensions/registries/index.ts
  src/extensions/registries/kube-object-detail-registry.ts
  src/extensions/registries/kube-object-menu-registry.ts
  src/extensions/registries/kube-object-status-registry.ts
  src/extensions/registries/page-menu-registry.ts
  src/extensions/registries/page-registry.ts
  src/extensions/registries/status-bar-registry.ts
  src/extensions/renderer-api/navigation.ts
  src/renderer/components/+apps/apps.tsx
  src/renderer/components/+config/config.route.ts
  src/renderer/components/+config/config.tsx
  src/renderer/components/+custom-resources/custom-resources.tsx
  src/renderer/components/+network/network.route.ts
  src/renderer/components/+network/network.tsx
  src/renderer/components/+storage/storage.route.ts
  src/renderer/components/+storage/storage.tsx
  src/renderer/components/+user-management/user-management.route.ts
  src/renderer/components/+user-management/user-management.tsx
  src/renderer/components/+workloads/workloads.route.ts
  src/renderer/components/+workloads/workloads.tsx
  src/renderer/components/app.tsx
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/components/layout/tab-layout.tsx
  src/renderer/navigation.ts
Labels: area/extension, enhancement

#1339 Update styling docs and add example on theme switch detection
  docs/extensions/capabilities/color-reference.md
  docs/extensions/capabilities/styling.md
Labels: area/documentation, area/extension, area/ui

#1366 Upgrade cache pipeline task
  .azure-pipelines.yml
Labels: area/ci, bug

#1359 Fix Landing Page width
  src/renderer/components/+landing-page/landing-page.scss
Labels: area/ui

#1363 Docs: fixing typos in styling
  docs/extensions/capabilities/color-reference.md
  docs/extensions/capabilities/styling.md
Labels: area/documentation

#1370 Exit pipeline if extensions build or tests fail
  .azure-pipelines.yml
  Makefile
  extensions/example-extension/main.ts
Labels: area/ci, enhancement

#1312 Remove Makefile from all intree extensions
  .gitignore
  Makefile
  extensions/example-extension/Makefile
  extensions/example-extension/main.ts
  extensions/example-extension/package-lock.json
  extensions/example-extension/package.json
  extensions/example-extension/yarn.lock
  extensions/license-menu-item/Makefile
  extensions/license-menu-item/package-lock.json
  extensions/license-menu-item/package.json
  extensions/license-menu-item/yarn.lock
  extensions/metrics-cluster-feature/Makefile
  extensions/metrics-cluster-feature/package-lock.json
  extensions/metrics-cluster-feature/package.json
  extensions/metrics-cluster-feature/yarn.lock
  extensions/node-menu/Makefile
  extensions/node-menu/package-lock.json
  extensions/node-menu/package.json
  extensions/node-menu/yarn.lock
  extensions/pod-menu/Makefile
  extensions/pod-menu/package-lock.json
  extensions/pod-menu/package.json
  extensions/pod-menu/yarn.lock
  extensions/support-page/Makefile
  extensions/support-page/package-lock.json
  extensions/support-page/package.json
  extensions/support-page/yarn.lock
  extensions/telemetry/Makefile
  extensions/telemetry/package-lock.json
  extensions/telemetry/package.json
  extensions/telemetry/yarn.lock
  package.json
Labels: area/extension, chore

#1374 Default PageRegistration.routePath to path based on id
  src/extensions/registries/__tests__/page-registry.test.ts
  src/extensions/registries/page-menu-registry.ts
  src/extensions/registries/page-registry.ts
Labels: area/extension, bug

#1373 add retry cap to handleStaticFile to prevent an infitite loop
  package.json
  src/main/router.ts
  webpack.renderer.ts
Labels: bug

#1380 Fix PageRegistry.getByPageMenuTarget issue when package name has special chars
  src/extensions/registries/__tests__/page-registry.test.ts
  src/extensions/registries/page-registry.ts
Labels: area/extension, bug

#1381 Fix support extension menu route
  extensions/support-page/main.ts
Labels: area/extension, bug

#1382 Workspace layout minor fixes
  src/renderer/components/+workspaces/workspaces.tsx
  src/renderer/components/layout/wizard-layout.scss
Labels: area/ui

#1379 Docs: reworked Extension Development > Getting Started sections
  docs/clusters/adding-clusters.md
  docs/clusters/removing-clusters.md
  docs/extensions/README.md
  docs/extensions/capabilities/styling.md
  docs/extensions/get-started/anatomy.md
  docs/extensions/get-started/overview.md
  docs/extensions/get-started/wrapping-up.md
  docs/extensions/get-started/your-first-extension.md
  docs/extensions/testing-and-publishing/testing.md
  docs/getting-started/README.md
  docs/getting-started/preferences.md
  docs/supporting/requirements.md
  mkdocs.yml
Labels: area/documentation

#1384 Use latest alpine version (3.12) for shell sessions
  src/main/node-shell-session.ts
Labels: enhancement

#1371 Exporting active theme to extensions
  src/extensions/renderer-api/index.ts
  src/extensions/renderer-api/theming.ts
Labels: area/extension, area/ui, enhancement

#1392 Adding Extensions menu item for non-mac menu
  src/main/menu.ts
Labels: area/extension, bug

#1387 Generate extension-api .d.ts and .js files using tsc
  .eslintrc.js
  Makefile
  package.json
  src/common/utils/debouncePromise.ts
  src/extensions/extension-api.ts
  src/extensions/npm/extensions/.gitignore
  src/extensions/npm/extensions/package.json
  src/extensions/rollup.config.js
  src/extensions/rollup.config.ts
  tsconfig.extensions.json
  tsconfig.json
  yarn.lock
Labels: area/extension, enhancement

#1386 PageRegistration / PageMenuRegistration fixes & more simplification
  extensions/support-page/main.ts
  extensions/support-page/renderer.tsx
  src/extensions/lens-main-extension.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/__tests__/page-registry.test.ts
  src/extensions/registries/base-registry.ts
  src/extensions/registries/page-menu-registry.ts
  src/extensions/registries/page-registry.ts
  src/renderer/components/app.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/navigation.ts
Labels: area/extension, bug, enhancement

#1377 set "allowJs" to false in tsconfig
  tsconfig.json
Labels: chore

#988 cleanup main side of metrics route for readability
  src/main/cluster.ts
  src/main/routes/metrics-route.ts
Labels: area/ui, chore

#1402 Reworked remaining docs
  docs/contributing/README.md
  docs/contributing/documentation.md
  docs/contributing/maintainers.md
  docs/contributing/promotion.md
  docs/extensions/README.md
  docs/extensions/capabilities/color-reference.md
  docs/extensions/capabilities/common-capabilities.md
  docs/extensions/capabilities/styling.md
  docs/extensions/testing-and-publishing/testing.md
  docs/supporting/requirements.md
Labels: area/documentation

#1407 Cache make build-extensions
  .azure-pipelines.yml
  Makefile
  extensions/example-extension/yarn.lock
  extensions/license-menu-item/yarn.lock
  extensions/metrics-cluster-feature/yarn.lock
  extensions/node-menu/yarn.lock
  extensions/pod-menu/yarn.lock
  extensions/support-page/yarn.lock
  extensions/telemetry/yarn.lock
Labels: area/ci, area/extension, enhancement

#1417 Remove make init from the readme
  README.md
Labels: area/documentation, chore

#1419 Showing colors in logs
  src/renderer/components/dock/pod-logs.scss
  src/renderer/components/dock/pod-logs.tsx
Labels: area/logs, area/ui

#1414 Track service start and stop events
  src/main/cluster-manager.ts
  src/main/exit-app.ts
  src/main/index.ts
  src/main/menu.ts
  src/main/tray.ts
  src/main/window-manager.ts
Labels: bug, enhancement

#1427 Extension Guides documentation
  docs/extensions/guides/README.md
  docs/extensions/guides/main-extension.md
  mkdocs.yml
Labels: area/documentation

#1428 Add computed name property to cluster
  src/main/cluster.ts
  src/main/tray.ts
  src/renderer/components/cluster-icon/cluster-icon.tsx
  src/renderer/components/layout/main-layout.tsx
Labels: area/ui, bug

#1420 Reorder File menu
  src/main/menu.ts
Labels: enhancement

#1416 Catch errors when responding from proxy error
  src/main/lens-proxy.ts
Labels: bug

#1433 kube-auth-proxy: accept only target cluster hostname
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/kube-auth-proxy.ts
Labels: area/security

#1225 Refactor ipc module
  src/common/base-store.ts
  src/common/cluster-frames.ts
  src/common/cluster-ipc.ts
  src/common/cluster-store.ts
  src/common/ipc.ts
  src/common/workspace-store.ts
  src/extensions/cluster-feature.ts
  src/extensions/extension-loader.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/cluster.ts
  src/main/kube-auth-proxy.ts
  src/main/window-manager.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+cluster-settings/cluster-settings.tsx
  src/renderer/components/+cluster-settings/components/remove-cluster-button.tsx
  src/renderer/components/app.tsx
  src/renderer/components/cluster-manager/cluster-status.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/lens-app.tsx
  src/renderer/navigation.ts
Labels: area/extension, area/ui, enhancement

#1440 Fix TypeError: Cannot read property 'stopServer' of undefined
  src/main/__test__/cluster.test.ts
  src/main/cluster.ts
Labels: bug

#1447 Fix extensionLoader error on dev environments
  src/extensions/extension-loader.ts
  src/main/index.ts
Labels: bug

#1445 Search by Pod Ip
  src/renderer/components/+workloads-pods/pods.tsx
Labels: area/ui, enhancement

#1431 Make BaseStore abstract
  extensions/telemetry/src/telemetry-preferences-store.ts
  src/common/base-store.ts
  src/extensions/extension-store.ts
Labels: area/extension

#1452 Allow extension cluster menus to have a parent
  src/extensions/registries/page-menu-registry.ts
  src/renderer/components/app.tsx
  src/renderer/components/layout/sidebar.tsx
Labels: area/extension, enhancement

#1454 fix SwitchCase indent rule in eslint
  .eslintrc.js
  src/main/prometheus/lens.ts
  src/main/prometheus/operator.ts
  src/main/prometheus/stacklight.ts
  src/main/shell-session.ts
  src/renderer/api/endpoints/hpa.api.ts
  src/renderer/api/index.ts
  src/renderer/api/kube-api-parse.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+cluster/cluster.store.ts
  src/renderer/components/+config-autoscalers/hpa-details.tsx
  src/renderer/components/+config-resource-quotas/add-quota-dialog.tsx
  src/renderer/components/ace-editor/ace-editor.tsx
  src/renderer/components/dock/terminal.ts
  src/renderer/components/file-picker/file-picker.tsx
  src/renderer/components/icon/icon.tsx
  src/renderer/components/input/input.tsx
  src/renderer/components/item-object-list/filter-icon.tsx
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.tsx
  src/renderer/components/menu/menu.tsx
  src/renderer/components/tooltip/tooltip.tsx
  src/renderer/kube-object.store.ts
Labels: chore

#1459 Fix extension cluster menu highlight/routing issues
  src/renderer/components/app.tsx
  src/renderer/components/layout/sidebar.tsx
Labels: area/extension, bug

#1463 Fix: light theme terminal selection color
  src/renderer/components/dock/terminal-window.scss
  src/renderer/themes/lens-light.json
Labels: area/ui, bug

#1439 Support networking.k8s.io/v1 for Ingress
  src/renderer/api/__tests__/kube-api.test.ts
  src/renderer/api/endpoints/ingress.api.ts
  src/renderer/api/kube-api.ts
  src/renderer/components/+network-ingresses/ingress-details.tsx
Labels: enhancement

#1465 Catch errors when responding from proxy error
  src/main/lens-proxy.ts
Labels: bug

#1467 Fix TypeError: Cannot read property 'stopServer' of undefined
  src/main/cluster.ts
Labels: bug

#1464 Add app focus event tracking
  src/main/window-manager.ts
Labels: bug

#1466 kube-auth-proxy: accept only target cluster hostname
  src/main/kube-auth-proxy.ts
Labels: area/security

#1443 Report metrics status in telemetry data
  extensions/telemetry/src/tracker.ts
Labels: area/extension, enhancement

#1479 Replace deprecated stable helm repository with bitnami
  integration/__tests__/app.tests.ts
  src/main/helm/helm-repo-manager.ts
Labels: bug

#1480 Add contributing/development pages
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Makefile
  README.md
  docs/contributing/development.md
  docs/contributing/documentation.md
  docs/contributing/github_workflow.md
  docs/contributing/testing.md
Labels: area/documentation

#1473 added support page to docs
  docs/support/README.md
  mkdocs.yml
Labels: area/documentation

#1469 Replace support-page extension with a link to the documentation support page
  extensions/support-page/main.ts
  extensions/support-page/package-lock.json
  extensions/support-page/package.json
  extensions/support-page/renderer.tsx
  extensions/support-page/src/support.scss
  extensions/support-page/src/support.tsx
  extensions/support-page/tsconfig.json
  extensions/support-page/webpack.config.ts
  package.json
  src/main/menu.ts
Labels: enhancement

#1478 Catch errors when fetching chart or chart values fails
  src/main/routes/helm-route.ts
Labels: bug

#1451 Report enabled extensions
  extensions/telemetry/main.ts
  extensions/telemetry/src/tracker.ts
  src/extensions/core-api/app.ts
  src/extensions/extensions-store.ts
Labels: area/extension, enhancement

#1474 change BaseRegistry to only have one type parameter
  src/common/utils/index.ts
  src/common/utils/rectify-array.ts
  src/extensions/registries/base-registry.ts
  src/extensions/registries/page-registry.ts
  src/renderer/utils/index.ts
Labels: area/extension

#1490 add extensions to lint & lint:fix
  .eslintrc.js
  extensions/example-extension/page.tsx
  extensions/example-extension/renderer.tsx
  extensions/kube-object-event-status/renderer.tsx
  extensions/license-menu-item/main.ts
  extensions/metrics-cluster-feature/renderer.tsx
  extensions/metrics-cluster-feature/src/metrics-feature.ts
  extensions/node-menu/renderer.tsx
  extensions/pod-menu/renderer.tsx
  extensions/telemetry/src/telemetry-preferences-store.ts
  extensions/telemetry/src/tracker.ts
  package.json
Labels: area/extension, chore

#1476 Doc/renderer extension guide
  docs/extensions/guides/main-extension.md
  docs/extensions/guides/renderer-extension.md
Labels: area/documentation

#1491 Fix azure pipeline yarn cache
  .azure-pipelines.yml
Labels: area/ci, bug

#1482 Watch for added/removed local extensions
  package.json
  src/extensions/extension-discovery.ts
  src/extensions/extension-installer.ts
  src/extensions/extension-loader.ts
  src/extensions/extension-manager.ts
  src/extensions/lens-extension.ts
  src/main/index.ts
  src/renderer/components/+extensions/extensions.tsx
  yarn.lock
Labels: area/extension, enhancement

#1481 Track more events from adding a cluster
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: enhancement

#1502 Add LensRendererExtension.isEnabledForCluster
  src/extensions/extension-loader.ts
  src/extensions/lens-extension.ts
  src/extensions/lens-renderer-extension.ts
Labels: area/extension, enhancement

#1501 Fix Documentation: Support
  docs/support/README.md
Labels: area/documentation

#1411 Add documentation on how to use Lens Extension Generator
  docs/extensions/get-started/your-first-extension.md
  docs/extensions/guides/generator.md
  docs/extensions/guides/images/hello-lens.png
  docs/extensions/guides/images/hello-world.png
  mkdocs.yml
Labels: area/documentation

#1245 Add designated folder for extensions
  extensions/metrics-cluster-feature/renderer.tsx
  integration/__tests__/app.tests.ts
  integration/helpers/utils.ts
  src/common/vars.ts
  src/extensions/extension-loader.ts
  src/extensions/lens-extension.ts
  src/main/extension-filesystem.ts
  src/main/index.ts
  src/renderer/bootstrap.tsx
Labels: area/extension, area/test

#1504 remove @observable.shallow from Lens(M|R)Extension
  src/extensions/lens-main-extension.ts
  src/extensions/lens-renderer-extension.ts
Labels: area/extension

#1485 Resolve extension enabled status when loading it
  src/extensions/extension-discovery.ts
  src/extensions/extensions-store.ts
Labels: area/extension, bug

#1456 Allow to install packed extensions from URL or local file
  package.json
  src/common/utils/downloadFile.ts
  src/common/utils/escapeRegExp.ts
  src/common/utils/index.ts
  src/common/utils/tar.ts
  src/common/vars.ts
  src/extensions/extension-discovery.ts
  src/extensions/lens-extension.ts
  src/extensions/registries/__tests__/page-registry.test.ts
  src/extensions/registries/page-registry.ts
  src/main/menu.ts
  src/renderer/components/+add-cluster/add-cluster.scss
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+extensions/extensions.scss
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/clipboard/clipboard.scss
  src/renderer/components/clipboard/clipboard.tsx
  src/renderer/components/clipboard/index.ts
  src/renderer/components/dock/pod-log-controls.tsx
  src/renderer/components/icon/icon.tsx
  src/renderer/components/input/drop-file-input.scss
  src/renderer/components/input/drop-file-input.tsx
  src/renderer/components/input/index.ts
  src/renderer/components/input/input.scss
  src/renderer/components/input/input.tsx
  src/renderer/components/input/search-input.scss
  src/renderer/components/kubeconfig-dialog/kubeconfig-dialog.tsx
  src/renderer/components/layout/wizard-layout.tsx
  src/renderer/components/notifications/notifications.store.ts
  src/renderer/components/notifications/notifications.tsx
  src/renderer/components/tooltip/tooltip.scss
  src/renderer/utils/copyToClipboard.ts
  src/renderer/utils/downloadFile.ts
  src/renderer/utils/index.ts
  src/renderer/utils/saveFile.ts
  yarn.lock
Labels: area/extension, enhancement

#1510 Tweak install extension ux
  src/renderer/components/+extensions/extensions.scss
  src/renderer/components/+extensions/extensions.tsx
Labels: area/extension, area/ui, enhancement

#1512 Fix: Unhandled exception for <DropFileInput disabled={true}/>
  src/renderer/components/input/drop-file-input.tsx
Labels: bug

#1505 [BREAKING]: remove deprecated routePath before GA
  docs/extensions/capabilities/common-capabilities.md
  docs/extensions/get-started/anatomy.md
  extensions/example-extension/package.json
  extensions/example-extension/renderer.tsx
  src/extensions/extension-discovery.ts
  src/extensions/registries/page-registry.ts
Labels: area/extension

#1515 Change add-cluster to single column layout
  docs/clusters/adding-clusters.md
  docs/clusters/images/add-cluster.png
  src/renderer/components/+add-cluster/add-cluster.scss
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: area/ui, enhancement

#1514 Fix pod usage metrics on Kubernetes >=1.19
  src/main/prometheus/lens.ts
  src/main/prometheus/operator.ts
  src/main/prometheus/stacklight.ts
Labels: area/metrics, bug

#1520 Fix workspace flaky tests
  integration/__tests__/app.tests.ts
Labels: area/ci

#1507 [BREAKING]: refine and document cluster feature api
  extensions/metrics-cluster-feature/src/metrics-feature.ts
  src/extensions/cluster-feature.ts
Labels: area/extension, enhancement

#1522 Installing extensions UI improvements
  package.json
  src/common/utils/downloadFile.ts
  src/renderer/components/+cluster-settings/components/cluster-proxy-setting.tsx
  src/renderer/components/+extensions/extensions.scss
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+preferences/kubectl-binaries.tsx
  src/renderer/components/dock/pod-log-search.tsx
  src/renderer/components/input/drop-file-input.tsx
  src/renderer/components/input/input.scss
  src/renderer/components/input/input.tsx
  src/renderer/components/input/input_validators.ts
  src/renderer/components/input/search-input.tsx
  yarn.lock
Labels: area/extension, bug, enhancement

#1422 Add starting point for mobx related documentaion
  docs/extensions/guides/README.md
  docs/extensions/guides/working-with-mobx.md
  mkdocs.yml
Labels: area/documentation, area/extension

#1521 Replace cluster warning event polling with watches
  src/main/cluster.ts
  src/renderer/components/app.tsx
  src/renderer/components/cluster-icon/cluster-icon.tsx
Labels: enhancement

#1438 Store prometheus cluster metadata based on metrics request responses
  extensions/telemetry/src/tracker.ts
  src/common/cluster-store.ts
  src/main/cluster.ts
  src/main/context-handler.ts
  src/main/routes/metrics-route.ts
Labels: enhancement

#1499 Use webpack instead of tsc to output extension-api.ts
  package.json
  tsconfig.extensions.json
  webpack.extensions.ts
Labels: area/extension

#1524 Add extension uninstall
  src/extensions/__tests__/extension-loader.test.ts
  src/extensions/__tests__/lens-extension.test.ts
  src/extensions/extension-discovery.ts
  src/extensions/extension-loader.ts
  src/extensions/lens-extension.ts
  src/extensions/registries/__tests__/page-registry.test.ts
  src/renderer/components/+extensions/extensions.scss
  src/renderer/components/+extensions/extensions.tsx
Labels: area/extension

#1516 Pod logs refactoring
  src/renderer/components/dock/pod-log-controls.scss
  src/renderer/components/dock/pod-log-controls.tsx
  src/renderer/components/dock/pod-log-list.scss
  src/renderer/components/dock/pod-log-list.tsx
  src/renderer/components/dock/pod-logs.scss
  src/renderer/components/dock/pod-logs.tsx
Labels: area/logs, area/ui

#1527 cluster feature extension guide
  docs/extensions/guides/README.md
  docs/extensions/guides/renderer-extension.md
  src/extensions/cluster-feature.ts
Labels: area/documentation, area/extension

#1540 Add initial Helm documentation
  docs/helm/README.md
  docs/helm/images/helm-charts.png
Labels: area/documentation, enhancement

#1545 Include *.yml* files from in-tree extensions
  package.json
Labels: area/extension, bug

#1539 Disable Uninstall and Enable/Disable buttons while uninstalling
  package.json
  src/extensions/__tests__/extension-loader.test.ts
  src/extensions/__tests__/lens-extension.test.ts
  src/extensions/extension-discovery.ts
  src/extensions/extension-loader.ts
  src/extensions/lens-extension.ts
  src/extensions/registries/__tests__/page-registry.test.ts
  src/jest.setup.ts
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/button/button.scss
  yarn.lock
Labels: area/extension, enhancement

#1549 Fix: add-cluster page D&D is broken
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: bug

#1551 Disable extension install button while installing
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/+extensions/extensions.tsx
Labels: area/extension, area/ui

#1541 lint the repo as a github action
  .azure-pipelines.yml
  .github/workflows/linter.yml
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
Labels: area/ci

#1554 remove unused data field in abstract BaseStore
  src/common/base-store.ts
Labels: chore

#1562 Electron 9.3.5
  package.json
  yarn.lock
Labels: area/security, bug

#1546 Add extension-api facades to cluster & workspace stores
  src/extensions/core-api/stores.ts
  src/extensions/stores/cluster-store.ts
  src/extensions/stores/workspace-store.ts
Labels: area/extension, bug

#1576 Add section for extension testing
  docs/extensions/testing-and-publishing/testing.md
Labels: area/documentation, area/extension, area/test

#1577 bump eslint-plugin-unused-imports to 1.0.1
  package.json
  yarn.lock
Labels: chore
