Repository lensapp/lens, pull requests merged in 2020-04, with the labels that each got.

#185 Add kubectl/helm download mirror select to preferences
  src/common/user-store.ts
  src/main/cluster.ts
  src/main/helm-cli.ts
  src/main/index.ts
  src/main/kubectl.ts
  src/main/lens-binary.ts
  src/renderer/components/PreferencesPage.vue
Labels: bug, enhancement

#214 Catch ipc errors on proxy exit
  src/main/kube-auth-proxy.ts
Labels: bug

#217 Always end watch stream if connection to kube-api ends
  src/main/proxy.ts
  src/main/router.ts
  src/main/routes/watch.ts
Labels: bug

#220 Bundle helm3 binary
  .eslintrc.js
  build/download_helm.ts
  package.json
  src/main/helm-cli.ts
  src/main/index.ts
  src/main/lens-binary.ts
  src/renderer/components/PreferencesPage.vue
Labels: bug, enhancement

#233 Fix bundled helm3 binary on windows
  src/main/lens-binary.ts
Labels: bug

#231 Initial port-forward implementation for services
  dashboard/client/api/endpoints/service.api.ts
  dashboard/client/components/+network-services/service-details.scss
  dashboard/client/components/+network-services/service-details.tsx
  dashboard/client/components/+network-services/service-ports.scss
  dashboard/client/components/+network-services/service-ports.tsx
  src/main/router.ts
  src/main/routes/port-forward.ts
Labels: bug, enhancement

#236 Fix jobs sorting if condition is empty
  dashboard/client/components/+workloads-jobs/jobs.tsx
Labels: bug

#241 Fix use of bundled kubectl
  __mocks__/electron.js
  package.json
  spec/src/main/kubectl_spec.ts
  src/common/__mocks__/user-store.ts
  src/main/kubectl.ts
Labels: bug

#244 Hide object-list applied filters by default
  dashboard/client/components/item-object-list/item-list-layout.tsx
Labels: enhancement

#246 Implement endpoints section
  dashboard/client/api/endpoints/endpoint.api.ts
  dashboard/client/api/endpoints/index.ts
  dashboard/client/components/+network-endpoints/endpoint-details.scss
  dashboard/client/components/+network-endpoints/endpoint-details.tsx
  dashboard/client/components/+network-endpoints/endpoint-subset-list.scss
  dashboard/client/components/+network-endpoints/endpoint-subset-list.tsx
  dashboard/client/components/+network-endpoints/endpoints.route.ts
  dashboard/client/components/+network-endpoints/endpoints.scss
  dashboard/client/components/+network-endpoints/endpoints.store.ts
  dashboard/client/components/+network-endpoints/endpoints.tsx
  dashboard/client/components/+network-endpoints/index.ts
  dashboard/client/components/+network-services/service-details-endpoint.tsx
  dashboard/client/components/+network-services/service-details.scss
  dashboard/client/components/+network-services/service-details.tsx
  dashboard/client/components/+network/network.tsx
Labels: enhancement

#242 Fix default workspace remove
  src/common/workspace-store.ts
  src/renderer/components/EditWorkspacePage.vue
Labels: bug

#243 Fix issues with crd plugins
  dashboard/client/api/endpoints/cert-manager.api.ts
  dashboard/client/components/+config/config.tsx
  dashboard/client/components/+custom-resources/certmanager.k8s.io/certificate-details.tsx
  dashboard/client/components/+custom-resources/certmanager.k8s.io/certificates.tsx
  dashboard/client/components/+custom-resources/crd.store.ts
  dashboard/client/components/kube-object/kube-object-details.tsx
  dashboard/client/components/layout/main-layout.tsx
  dashboard/client/components/layout/sidebar.tsx
Labels: bug

#257 Display emptyDir medium and size limit
  dashboard/client/api/endpoints/pods.api.ts
  dashboard/client/components/+workloads-pods/pod-details.tsx
Labels: enhancement

#259 Show pod terminating status
  dashboard/client/api/endpoints/pods.api.ts
  dashboard/client/components/+workloads/workloads-mixins.scss
Labels: bug, enhancement

#263 Electron 6.1.10
  .yarnrc
  package.json
  yarn.lock
Labels: bug

#273 Do not timeout watch requests
  src/main/context-handler.ts
  src/main/proxy.ts
Labels: bug

#275 Fix pod shell error if no access to nodes
  dashboard/client/api/endpoints/pods.api.ts
  dashboard/client/components/+workloads-pods/pod-menu.tsx
Labels: bug

#276 Fix list sort by age
  dashboard/client/components/+config-maps/config-maps.tsx
  dashboard/client/components/+config-resource-quotas/resource-quotas.tsx
  dashboard/client/components/+config-secrets/secrets.tsx
  dashboard/client/components/+custom-resources/certmanager.k8s.io/issuers.tsx
  dashboard/client/components/+custom-resources/crd-resources.tsx
  dashboard/client/components/+events/events.tsx
  dashboard/client/components/+namespaces/namespaces.tsx
  dashboard/client/components/+network-endpoints/endpoints.tsx
  dashboard/client/components/+network-ingresses/ingresses.tsx
  dashboard/client/components/+network-policies/network-policies.tsx
  dashboard/client/components/+network-services/services.tsx
  dashboard/client/components/+nodes/nodes.tsx
  dashboard/client/components/+pod-security-policies/pod-security-policies.tsx
  dashboard/client/components/+storage-classes/storage-classes.tsx
  dashboard/client/components/+storage-volume-claims/volume-claims.tsx
  dashboard/client/components/+storage-volumes/volumes.tsx
  dashboard/client/components/+user-management-roles-bindings/role-bindings.tsx
  dashboard/client/components/+user-management-roles/roles.tsx
  dashboard/client/components/+user-management-service-accounts/service-accounts.tsx
  dashboard/client/components/+workloads-cronjobs/cronjobs.tsx
  dashboard/client/components/+workloads-daemonsets/daemonsets.tsx
  dashboard/client/components/+workloads-deployments/deployments.tsx
  dashboard/client/components/+workloads-jobs/jobs.tsx
  dashboard/client/components/+workloads-pods/pods.tsx
  dashboard/client/components/+workloads-replicasets/replicasets.tsx
  dashboard/client/components/+workloads-statefulsets/statefulsets.tsx
Labels: bug

#277 Always refresh stores when object list is mounted
  dashboard/client/components/item-object-list/item-list-layout.tsx
Labels: bug

#278 Update @kubernetes/client-node to 0.11.1
  package.json
  patches/@kubernetes+client-node+0.11.0.patch
  src/main/feature.ts
  src/main/node-shell-session.ts
  src/main/routes/watch.ts
  yarn.lock
Labels: bug

#274 Cache terminall shell env
  src/main/node-shell-session.ts
  src/main/shell-session.ts
Labels: enhancement

#285 Show node events in node details
  dashboard/client/components/+events/event.store.ts
  dashboard/client/components/+nodes/node-details.tsx
Labels: enhancement

#286 Show always Events title in resource details
  dashboard/client/components/+events/kube-event-details.tsx
Labels: enhancement

#292 Enable code folding in resource editor
  dashboard/client/components/ace-editor/ace-editor.tsx
Labels: enhancement

#284 Fix missing spaces in container command
  dashboard/client/components/+workloads-pods/pod-details-container.tsx
Labels: bug

#293 Check also beta.kubernetes.io/os selector for windows pod shell
  dashboard/client/api/endpoints/pods.api.ts
Labels: bug

#294 Terminal dock tab improvements
  dashboard/client/components/+nodes/node-menu.tsx
  dashboard/client/components/+workloads-pods/pod-menu.tsx
  dashboard/client/components/dock/dock-tab.scss
  dashboard/client/components/dock/terminal-tab.tsx
Labels: enhancement

#313 Cleanup cluster webview loading
  src/renderer/components/ClusterPage.vue
Labels: bug

#314 Terminal tab auto-close fixes
  dashboard/client/components/dock/terminal-tab.tsx
  src/main/shell-session.ts
Labels: bug

#301 Update metrics feature components
  src/features/metrics.ts
  src/features/metrics/03-statefulset.yml.hb
  src/features/metrics/05-clusterrole.yml
  src/features/metrics/10-node-exporter-ds.yml.hb
  src/features/metrics/12-kube-state-metrics-clusterrole.yml
  src/features/metrics/14-kube-state-metrics-deployment.yml.hb
  src/features/user-mode.ts
  src/main/cluster-manager.ts
  src/main/cluster.ts
  src/main/feature-manager.ts
  src/main/feature.ts
  src/renderer/components/ClusterSettings/Features/Components/Metrics.vue
  src/renderer/components/ClusterSettings/Features/Components/UserMode.vue
  src/renderer/store/modules/clusters.ts
Labels: enhancement

#326 Fix node shell session regression
  src/main/node-shell-session.ts
Labels: bug

#325 Rebuild locales & fix translation bugs
  dashboard/client/components/+nodes/node-menu.tsx
  dashboard/client/components/+workloads-pods/pod-menu.tsx
  dashboard/locales/en/messages.js
  dashboard/locales/en/messages.po
  dashboard/locales/ru/messages.js
  dashboard/locales/ru/messages.po
Labels: bug
