Repository lensapp/lens, pull requests merged in 2021-11, with the labels that each got.

#4203 Fix the broken ingress metrics, the namespace is needed in the opts.
  src/common/k8s-api/endpoints/ingress.api.ts
Labels: bug, area/metrics

#4208 Fix <a href...> visibility
  src/renderer/components/+add-cluster/add-cluster.scss
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/app.scss
  src/renderer/components/error-boundary/error-boundary.scss
Labels: bug, area/ui

#4188 Use spec.serviceName as an externalIP if nothing else
  src/common/k8s-api/endpoints/service.api.ts
  src/renderer/components/+network-services/service-details.tsx
  src/renderer/components/+network-services/services.tsx
Labels: bug

#4196 Lint: no-template-curly-in-string (error)
  .eslintrc.js
  src/main/kubectl.ts
Labels: chore

#4197 Lint: no-unused-expressions (error)
  .eslintrc.js
  src/common/getTSLoader.ts
  src/renderer/components/+catalog/hotbar-toggle-menu-item.tsx
  src/renderer/components/+preferences/editor.tsx
  src/renderer/components/+workloads-deployments/deployment-scale-dialog.tsx
  src/renderer/components/+workloads-pods/pod-container-env.tsx
  src/renderer/components/+workloads-replicasets/replicaset-scale-dialog.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-scale-dialog.tsx
  src/renderer/components/menu/menu.tsx
Labels: chore

#4199 Lint: space-before-function-paren (error)
  .eslintrc.js
  src/common/utils/buildUrl.ts
  src/renderer/components/+user-management/+service-accounts/details.tsx
  src/renderer/components/dock/terminal.store.ts
  src/renderer/utils/interval.ts
Labels: chore

#4214 Release/v5.2.6 beta.0
  .azure-pipelines-k8s-matrix.yml
  .azure-pipelines.yml
  .yarnrc
  package.json
  src/main/context-handler.ts
  src/main/kube-auth-proxy.ts
  src/main/lens-proxy.ts
  src/main/window-manager.ts
  yarn.lock
Labels: skip-changelog

#4221 Reduce JSON-API logging
  src/common/k8s-api/json-api.ts
Labels: enhancement

#4217 Release/v5.2.6 beta.1
  .yarnrc
  package.json
  src/main/window-manager.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+cluster/cluster-issues.tsx
  src/renderer/components/+cluster/cluster-overview.tsx
  src/renderer/components/app.tsx
  src/renderer/components/cluster-manager/lens-views.ts
  src/renderer/components/error-boundary/error-boundary.tsx
  src/renderer/lens-app.tsx
  yarn.lock
Labels: skip-changelog

#4185 Prevent injection of expired "DST Root CA X3" from host CA stores; Electron to 13.6
  .yarnrc
  package.json
  src/common/__tests__/system-ca.test.ts
  src/common/system-ca.ts
  src/common/utils/promise-exec.ts
  src/main/helm/helm-chart-manager.ts
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-repo-manager.ts
  src/main/index.ts
  src/main/kubectl.ts
  src/main/resource-applier.ts
  src/renderer/lens-app.tsx
  types/mocks.d.ts
  yarn.lock
Labels: bug, blocker

#4222 Release 5.3.0-alpha.8
  package.json
Labels: skip-changelog

#4238 Fix lint error
  src/common/system-ca.ts
Labels: bug

#4236 Fix catalog button border-radius when modal is shown
  src/renderer/components/+catalog/catalog-add-button.scss
Labels: bug, area/ui

#4215 Fix trying to download kubectl from [object Object]
  src/main/kubectl.ts
Labels: bug, blocker

#4242 Display namespace for subject on ClusterRoleBinding details
  src/renderer/components/+user-management/+cluster-role-bindings/details.tsx
  src/renderer/components/+user-management/+role-bindings/details.tsx
Labels: enhancement, area/ui

#4230 RELEASE GUIDE: fix formatting, add a clarification
  RELEASE_GUIDE.md
Labels: area/documentation

#4243 Properly propagate promises in Kubectl.ensureKubectl to avoid UnhandledPromiseRejections
  src/main/kubectl.ts
Labels: bug

#4248 Fix auto-update on macOS not working
  src/main/app-updater.ts
Labels: bug, area/macos, blocker

#4252 Fix metrics configuration via catalog
  src/main/cluster-manager.ts
Labels: bug, area/extension

#4255 Fix impl of 'Fix metrics configuration via catalog'
  src/main/cluster-manager.ts
Labels: bug, area/extension, blocker

#4256 Fix auto update not working for AppImage
  src/main/app-updater.ts
  src/main/index.ts
Labels: bug, area/linux, blocker, autoupdate

#4231 Release/v5.2.6
  package.json
  src/common/k8s-api/__tests__/crd.test.ts
  src/common/k8s-api/endpoints/crd.api.ts
  src/common/k8s-api/endpoints/resource-applier.api.ts
  src/common/k8s-api/json-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/k8s-api/kube-object.ts
  src/main/resource-applier.ts
  src/main/router.ts
  src/main/routes/resource-applier-route.ts
  src/main/utils/http-responses.ts
  src/renderer/components/+config-autoscalers/hpa-details.tsx
  src/renderer/components/+config-limit-ranges/limit-range-details.tsx
  src/renderer/components/+config-maps/config-map-details.tsx
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets-details.tsx
  src/renderer/components/+config-resource-quotas/resource-quota-details.tsx
  src/renderer/components/+config-secrets/secret-details.tsx
  src/renderer/components/+custom-resources/crd-details.tsx
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/+events/event-details.tsx
  src/renderer/components/+events/kube-event-details.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+network-endpoints/endpoint-details.tsx
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+network-policies/network-policy-details.tsx
  src/renderer/components/+network-services/service-details.tsx
  src/renderer/components/+nodes/node-details.tsx
  src/renderer/components/+pod-security-policies/pod-security-policy-details.tsx
  src/renderer/components/+storage-classes/storage-class-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+storage-volumes/volume-details.tsx
  src/renderer/components/+workloads-cronjobs/cronjob-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-deployments/deployment-scale-dialog.test.tsx
  src/renderer/components/+workloads-jobs/job-details.tsx
  src/renderer/components/+workloads-pods/pod-details.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-replicasets/replicaset-scale-dialog.test.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-scale-dialog.test.tsx
  src/renderer/components/dock/__test__/log-tab.store.test.ts
  src/renderer/components/dock/create-resource.tsx
  src/renderer/components/dock/dock.store.ts
  src/renderer/components/dock/edit-resource.store.ts
  src/renderer/components/dock/edit-resource.tsx
  src/renderer/components/dock/editor-panel.tsx
  src/renderer/components/dock/log-tab.store.ts
  src/renderer/components/kube-object-menu/kube-object-menu.tsx
  src/renderer/components/kube-object-meta/kube-object-meta.tsx
  src/renderer/utils/createStorage.ts
  yarn.lock
Labels: skip-changelog

#4253 Fix not being able to sync kube config files on linux
  src/renderer/initializers/catalog-category-registry.tsx
Labels: bug, area/linux, blocker

#4259 release v5.3.0-alpha.9
  package.json
Labels: skip-changelog

#4271 cleaned up logging from port-forward-store
  src/renderer/port-forward/port-forward.store.ts
Labels: bug

#4274 log kubectl port-forward stderr output as debug
  src/main/routes/port-forward-route.ts
Labels: bug

#4269 Display loading spinner while switching between helm charts
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
Labels: bug, area/ui

#4276 Fix crash on HorizontalPodAutoscalers view
  src/renderer/components/+config-autoscalers/hpa.tsx
Labels: bug

#4285 Block shell websocket connections from non-lens renderers
  src/main/index.ts
  src/main/lens-proxy.ts
  src/main/proxy-functions/shell-api-request.ts
  src/main/shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/renderer/api/terminal-api.ts
Labels: bug, area/security, blocker

#3624 Support window nodes for node-shells
  src/common/k8s-api/endpoints/nodes.api.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-json-api.ts
  src/main/cluster-manager.ts
  src/main/shell-session/node-shell-session.ts
Labels: bug

#4293 Add Webstorm configurations
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/encodings.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jsLinters/eslint.xml
  .idea/lens.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/prettier.xml
  .idea/vcs.xml
  .idea/webResources.xml
Labels: chore

#4286 Use .status.phase instead of computing it for Pod.getStatusMessage
  src/common/k8s-api/endpoints/pods.api.ts
  src/renderer/components/+workloads-pods/pods.tsx
Labels: bug

#4287 Specify GiB for lens prometheus metrics instead of GB
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
Labels: bug, area/metrics

#4258 Keep shell processes alive between network offline periods
  src/main/index.ts
  src/main/proxy-functions/shell-api-request.ts
  src/main/shell-session/local-shell-session.ts
  src/main/shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/renderer/api/terminal-api.ts
Labels: bug, area/terminal

#4298 Change base64 functions to be exported not as object children
  src/common/utils/base64.ts
  src/common/utils/index.ts
Labels: chore

#4297 Make ws:// authentication more timing safe
  src/main/proxy-functions/shell-api-request.ts
  src/renderer/api/terminal-api.ts
Labels: enhancement, area/security

#4289 release v5.3.0-alpha.10
  package.json
Labels: skip-changelog

#4267 Fix crash in IngressDetails
  src/common/k8s-api/endpoints/ingress.api.ts
Labels: bug

#4244 Correctly catch and notify user about NodeShell pod failures
  src/main/lens-proxy.ts
  src/main/proxy-functions/kube-api-request.ts
  src/main/proxy-functions/types.ts
  src/main/shell-session/node-shell-session.ts
  src/renderer/api/websocket-api.ts
  src/renderer/components/dock/terminal-window.tsx
  src/renderer/components/dock/terminal.ts
Labels: bug

#4308 Handle aborted responses in lens proxy
  src/main/lens-proxy.ts
Labels: bug

#4189 Fix: Catalog's visibility columns menu -> Empty title for Icon
  src/common/utils/makeCss.ts
  src/renderer/components/+catalog/catalog-entity-item.tsx
  src/renderer/components/+catalog/catalog.module.css
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/icon/push_pin.svg
Labels: bug, area/ui

#4301 Use forked node-fetch
  package.json
  yarn.lock
Labels: bug

#4094 Fix race condition in refreshViews
  src/main/catalog/catalog-entity-registry.ts
  src/main/cluster-manager.ts
  src/main/initializers/ipc.ts
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/cluster-manager/lens-views.ts
  src/renderer/lens-app.tsx
Labels: bug, blocker

#4291 Release/v5.2.7
  .yarnrc
  package.json
  src/common/__tests__/system-ca.test.ts
  src/common/system-ca.ts
  src/common/utils/promise-exec.ts
  src/main/helm/helm-chart-manager.ts
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-repo-manager.ts
  src/main/index.ts
  src/main/kubectl.ts
  src/main/lens-proxy.ts
  src/main/proxy-functions/shell-api-request.ts
  src/main/resource-applier.ts
  src/main/shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/renderer/api/terminal-api.ts
  src/renderer/lens-app.tsx
  types/mocks.d.ts
  yarn.lock
Labels: skip-changelog

#4305 Close issues with 'needs-information' after 60 days
  .github/workflows/stale.yml
Labels: area/ci

#4321 Add possibility to define non-generic KubeApi to forRemoteCluster
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
Labels: enhancement, area/extension

#4325 Implement KubeApi.patch
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/k8s-api/kube-object.ts
Labels: enhancement, area/extension

#4266 Improve cluster connection visibility
  src/common/cluster-store.ts
  src/common/cluster-types.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/cluster.ts
  src/main/context-handler.ts
  src/main/kube-auth-proxy.ts
  src/main/kubeconfig-manager.ts
  src/main/window-manager.ts
  src/renderer/components/cluster-manager/cluster-status.tsx
Labels: bug

#4132 Always override PATH when syncing from shell
  src/main/shell-sync.ts
  src/main/utils/shell-env.ts
Labels: bug

#4313 Make Delete/Remove menu item consistent as Delete
  src/renderer/components/menu/menu-actions.tsx
Labels: bug, area/ui

#4288 Fix CRDs not updating in Sidebar
  src/renderer/components/+custom-resources/crd-list.tsx
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  src/renderer/components/layout/sidebar.tsx
Labels: bug

#4284 Reduce logging on failure to get cluster metrics
  src/main/routes/metrics-route.ts
Labels: chore

#4327 release v5.3.0-alpha.11
  package.json
Labels: skip-changelog

#4330 Use specific version of actions/stale
  .github/workflows/stale.yml
Labels: chore

#4329 Tweak release drafter template
  .github/release-drafter.yml
Labels: chore

#4337 Use propagationPolicy=Background by default for delete
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/endpoints/job.api.ts
  src/common/k8s-api/kube-api.ts
Labels: enhancement, area/extension

#4339 Export KubeStatus to extensions api
  src/extensions/main-api/k8s-api.ts
  src/extensions/renderer-api/k8s-api.ts
Labels: enhancement, area/extension

#4332 Fix crash when finding CRD's preferred version
  src/common/k8s-api/__tests__/crd.test.ts
  src/common/k8s-api/endpoints/crd.api.ts
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
Labels: bug

#4341 Made 'Forward...' buttons have primary style
  src/renderer/components/+network-services/service-port-component.tsx
  src/renderer/components/+workloads-pods/pod-container-port.tsx
Labels: bug, area/ui, area/port-forwarding

#4342 Fix edit-resource by correctly saving first draft
  src/renderer/components/dock/edit-resource.tsx
Labels: bug, p0

#4349 Allow to call KubeApi.delete without namespace parameter
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
Labels: bug, area/extension

#4351 Fix typo KubeObject.nonEditiablePathPrefixes > KubeObject.nonEditablePathPrefixes
  src/common/k8s-api/kube-object.ts
Labels: chore

#4353 Fixing setting page bottom margin
  src/renderer/components/layout/setting-layout.scss
Labels: bug, area/ui

#4355 Catalog pin icon too far from entity name
  src/renderer/components/+catalog/catalog.module.css
Labels: bug, area/ui

#4279 <Menu/> styles fine-tuning
  src/renderer/components/item-object-list/item-list-layout.scss
  src/renderer/components/menu/menu.scss
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
Labels: enhancement, area/ui

#4228 Display resource load errors seperately from list of items
  src/common/k8s-api/kube-object.store.ts
  src/common/k8s-api/kube-watch-api.ts
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.scss
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
Labels: bug

#4358 Allow to scroll table columns with labels (badges)
  src/renderer/components/+catalog/catalog-entity-item.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+config-autoscalers/hpa.tsx
  src/renderer/components/+config-secrets/secrets.tsx
  src/renderer/components/+namespaces/namespaces.tsx
  src/renderer/components/+workloads-daemonsets/daemonsets.tsx
  src/renderer/components/badge/badge.module.css
  src/renderer/components/badge/badge.tsx
  src/renderer/components/item-object-list/item-list-layout.scss
  src/renderer/components/table/table-cell.scss
  src/renderer/components/table/table-cell.tsx
Labels: bug, area/ui

#4347 Further tweaking to the release drafter description
  .github/release-drafter.yml
Labels: chore

#4365 Add timeout option to KubeApi.watch
  src/common/k8s-api/kube-api.ts
Labels: enhancement

#4364 Fix drawer icons unexpected outline
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/menu/menu-actions.scss
Labels: bug, area/ui, blocker

#4356 Fix concurrent loadItems in CatalogEntityStore
  src/common/item.store.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/components/+catalog/catalog-entity.store.tsx
Labels: bug

#4362 release v5.3.0-beta.0
  package.json
Labels: skip-changelog

#4343 Use actions@stale/v4 instead of actions@stale/4
  .github/workflows/stale.yml
Labels: chore

#4366 Release v5.3.0-beta.1
  package.json
Labels: skip-changelog

#4373 Ensure Drawer copyTitle() copies everything after the first ':'
  src/renderer/components/drawer/drawer.tsx
Labels: bug, area/port-forwarding

#4372 Prefer ref over findDOMNode to make unit tests not flaky
  src/renderer/components/dialog/dialog.tsx
Labels: bug

#4346 Fix handling of PTYs when renderer is reloaded
  src/main/shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/renderer/api/terminal-api.ts
  src/renderer/api/websocket-api.ts
  src/renderer/components/dock/terminal.store.ts
  src/renderer/components/dock/terminal.ts
Labels: bug

#4375 Fix documentation around components examples
  docs/extensions/capabilities/common-capabilities.md
  docs/extensions/guides/renderer-extension.md
  docs/extensions/guides/resource-stack.md
Labels: area/documentation

#4378 Fix material icons flash on app load
  src/renderer/components/fonts.scss
Labels: bug, area/ui

#4368 Update built-in extensions package-lock.json
  extensions/kube-object-event-status/package-lock.json
  extensions/metrics-cluster-feature/package-lock.json
  extensions/node-menu/package-lock.json
  extensions/pod-menu/package-lock.json
Labels: chore

#4379 Maximize window on topbar double click
  src/renderer/components/layout/topbar.module.css
  src/renderer/components/layout/topbar.tsx
Labels: enhancement, area/ui

#4377 Fixing cluster dropdown focus state
  src/renderer/components/layout/sidebar-cluster.module.css
  src/renderer/components/layout/sidebar-cluster.tsx
Labels: bug, area/ui

#4374 Add keepalive option in JsonApi.getResponse
  src/common/k8s-api/json-api.ts
Labels: bug

#4381 release v5.3.0-beta.2
  package.json
Labels: skip-changelog

#4020 Improve bootstrap logging for help with iframe debugging
  src/common/base-store.ts
  src/common/cluster-store.ts
  src/common/hotbar-store.ts
  src/common/user-store/user-store.ts
  src/common/weblink-store.ts
  src/extensions/extension-store.ts
  src/extensions/extensions-store.ts
  src/main/extension-filesystem.ts
  src/renderer/bootstrap.tsx
  src/renderer/cluster-frame.tsx
  src/renderer/initializers/kube-object-detail-registry.tsx
  src/renderer/root-frame.tsx
Labels: chore

#4391 Fix kube rejecting lens-metrics installation
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
Labels: bug, p0

#4390 Fix windows AllUsers installs not updating correctly
  package.json
Labels: bug, area/windows, blocker

#4387 Fix race condition in LensViews.handleVisibleClusterChange
  src/renderer/components/cluster-manager/lens-views.ts
Labels: bug, blocker

#4393 Catch and display load errors for WorkloadsOverview
  src/extensions/registries/workloads-overview-detail-registry.ts
  src/renderer/components/+workloads-overview/overview-statuses.scss
  src/renderer/components/+workloads-overview/overview-statuses.tsx
  src/renderer/components/+workloads-overview/overview.scss
  src/renderer/components/+workloads-overview/overview.tsx
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  src/renderer/initializers/workloads-overview-detail-registry.tsx
Labels: bug

#4384 Fix all-or-nothing when initially loading extensions
  src/extensions/extension-discovery.ts
Labels: bug, blocker

#4396 Improve local shell CWD setting
  src/common/utils/paths.ts
  src/main/shell-session/shell-session.ts
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/__tests__/cluster-local-terminal-settings.test.tsx
  src/renderer/components/cluster-settings/components/cluster-home-dir-setting.tsx
  src/renderer/components/cluster-settings/components/cluster-local-terminal-settings.tsx
  src/renderer/components/cluster-settings/components/index.ts
Labels: enhancement

#4404 Add unit tests for BaseStore
  src/common/__tests__/base-store.test.ts
  src/common/base-store.ts
Labels: chore, area/extension

#4395 Fix cwd not being respected for local shells on windows
  src/main/shell-session/local-shell-session.ts
Labels: bug, area/windows

#4273 Broadcast cluster's disconnected state before stopping KubeAuthProxy
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/utils.ts
  src/main/__test__/cluster.test.ts
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/cluster.ts
  src/main/kube-auth-proxy.ts
  src/renderer/components/cluster-manager/lens-views.ts
Labels: bug

#4316 Cleanup Prometheus detection
  src/main/__test__/context-handler.test.ts
  src/main/context-handler.ts
  src/main/prometheus/helm.ts
  src/main/prometheus/lens.ts
  src/main/prometheus/operator.ts
  src/main/prometheus/provider-registry.ts
  src/main/prometheus/stacklight.ts
  src/main/routes/metrics-route.ts
Labels: chore, area/metrics

#4412 Revert "Broadcast cluster's disconnected state before stopping KubeAuthProxy"
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/utils.ts
  src/main/__test__/cluster.test.ts
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/cluster.ts
  src/main/kube-auth-proxy.ts
  src/renderer/components/cluster-manager/lens-views.ts
Labels: area/ci

#4407 release v5.3.0-beta.3
  integration/__tests__/cluster-pages.tests.ts
  package.json
Labels: skip-changelog

#4388 Retry watch if timeout set, but request was not retried
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
Labels: bug

#4411 Fix cluster dropdown invisible overlay
  src/renderer/components/animate/animate.scss
  src/renderer/components/animate/animate.tsx
Labels: bug, area/ui, blocker

#4413 Revert "attempt to fix integration test inexplicably failing (2) (ski…
  integration/__tests__/cluster-pages.tests.ts
Labels: chore

#4416 release v5.3.0-beta.4
  package.json
Labels: skip-changelog

#4421 Upgrade typescript to 4.5
  package.json
  yarn.lock
Labels: enhancement

#4419 Release v5.3.0
  package.json
Labels: skip-changelog

#4415 Fix: display of entity name while connecting
  src/renderer/components/cluster-manager/cluster-status.tsx
  src/renderer/components/cluster-manager/cluster-view.tsx
Labels: bug

#4422 Allow to navigate to created resource details from notification
  src/common/k8s-api/api-manager.ts
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/dock/create-resource.tsx
  src/renderer/components/notifications/notifications.tsx
Labels: enhancement, area/ui

#4357 Mobx package upgrade
  package.json
  src/common/base-store.ts
  src/common/configure-packages.ts
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/delete-cluster-dialog/delete-cluster-dialog.tsx
  src/renderer/components/dock/dock.store.ts
  yarn.lock
Labels: chore, autoupdate

#4338 Introduce a way to use injectables
  package.json
  src/renderer/bootstrap.tsx
  src/renderer/components/getDi.tsx
  src/renderer/components/getDiForUnitTesting.tsx
  yarn.lock
Labels: enhancement

#4425 Change KubernetesCluster's settings menuItem's icon to a cog
  src/common/catalog-entities/kubernetes-cluster.ts
Labels: enhancement, area/ui

#4392 Cleanup OverviewWorkloadStatus, remove findDOMNode
  src/renderer/components/+workloads-overview/overview-workload-status.tsx
Labels: chore

#3961 Add more file system metrics to the pod and container graphs
  src/common/k8s-api/endpoints/daemon-set.api.ts
  src/common/k8s-api/endpoints/deployment.api.ts
  src/common/k8s-api/endpoints/job.api.ts
  src/common/k8s-api/endpoints/metrics.api.ts
  src/common/k8s-api/endpoints/namespaces.api.ts
  src/common/k8s-api/endpoints/pods.api.ts
  src/common/k8s-api/endpoints/replica-set.api.ts
  src/common/k8s-api/endpoints/stateful-set.api.ts
  src/main/prometheus/lens.ts
  src/main/prometheus/operator.ts
  src/main/prometheus/stacklight.ts
  src/renderer/components/+workloads-pods/container-charts.tsx
  src/renderer/components/+workloads-pods/pod-charts.tsx
Labels: enhancement, area/metrics

#4438 Fix lint
  src/renderer/components/+workloads-pods/container-charts.tsx
Labels: chore

#4441 Add a query param for filtering port forwards by clusterId
  src/main/routes/port-forward-route.ts
  src/renderer/port-forward/port-forward.store.ts
Labels: enhancement

#4433 Fix hotbar items drag-n-drop bugs
  src/common/hotbar-store.ts
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: bug, area/ui

#4345 Fix detail views not watching child components
  src/common/k8s-api/cluster-context.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/k8s-api/kube-object.ts
  src/common/k8s-api/kube-watch-api.ts
  src/renderer/cluster-frame.tsx
  src/renderer/components/+cluster/cluster-overview.tsx
  src/renderer/components/+events/kube-event-details.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+network-services/service-details.tsx
  src/renderer/components/+nodes/node-details.tsx
  src/renderer/components/+storage-classes/storage-class-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+workloads-cronjobs/cronjob-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-jobs/job-details.tsx
  src/renderer/components/+workloads-overview/overview.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/context.ts
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  src/renderer/components/layout/sidebar.tsx
Labels: bug, p0

#4216 Correctly handle promises and rejections around cluster connection
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/cluster.ts
  src/main/kube-auth-proxy.ts
  src/main/kubeconfig-manager.ts
Labels: bug

#4394 Fix not being able to remove role bindings via the UI
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
Labels: bug

#4440 Add support for resizing Drawers
  src/renderer/components/drawer/drawer.scss
  src/renderer/components/drawer/drawer.tsx
  src/renderer/components/resizing-anchor/resizing-anchor.scss
  src/renderer/components/resizing-anchor/resizing-anchor.tsx
Labels: enhancement, area/ui

#4437 Add Check-For-Updates in menu and some notifications
  build/set_build_version.ts
  src/common/ipc/update-available.ipc.ts
  src/main/app-updater.ts
  src/main/menu.ts
  src/renderer/ipc/index.tsx
Labels: enhancement, area/ui, autoupdate

#3990 Refactor Nodes view metrics renderer
  src/common/k8s-api/endpoints/nodes.api.ts
  src/renderer/components/+nodes/nodes.tsx
Labels: chore

#4461 Center text vertically in notifications
  src/renderer/components/notifications/notifications.scss
Labels: bug

#4462 Fix getLatestApiPrefixGroup to not fail when options.apiBase is not provided
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
Labels: bug

#4436 Prefer usage of preference over autoselection
  src/main/context-handler.ts
Labels: bug, area/metrics, area/rbac

#4465 Release/v5.3.1
  package.json
  src/common/base-store.ts
  src/common/configure-packages.ts
  src/common/hotbar-store.ts
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/cluster-context.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/k8s-api/kube-object.ts
  src/common/k8s-api/kube-watch-api.ts
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/cluster.ts
  src/main/context-handler.ts
  src/main/kube-auth-proxy.ts
  src/main/kubeconfig-manager.ts
  src/renderer/cluster-frame.tsx
  src/renderer/components/+cluster/cluster-overview.tsx
  src/renderer/components/+events/kube-event-details.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+network-services/service-details.tsx
  src/renderer/components/+nodes/node-details.tsx
  src/renderer/components/+storage-classes/storage-class-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+workloads-cronjobs/cronjob-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-jobs/job-details.tsx
  src/renderer/components/+workloads-overview/overview.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/cluster-manager/cluster-status.tsx
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/context.ts
  src/renderer/components/delete-cluster-dialog/delete-cluster-dialog.tsx
  src/renderer/components/dock/dock.store.ts
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/components/hotbar/hotbar-menu.tsx
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/components/notifications/notifications.scss
  yarn.lock
Labels: skip-changelog
