Repository lensapp/lens, pull requests merged in 2021-01, with the labels that each got.

#1888 Fix Electron 9.4 frame ipc bug
  src/common/cluster-frames.ts
  src/common/cluster-ipc.ts
  src/common/ipc.ts
  src/main/window-manager.ts
  src/renderer/components/app.tsx
Labels: bug

#1880 Expose NamespaceSelect component to extensions
  src/extensions/renderer-api/components.ts
Labels: area/extension, enhancement

#1897 Reset stores before loading them
  src/renderer/components/item-object-list/item-list-layout.tsx
Labels: bug

#1901 Fix encoding typo in ClusterAccessibleNamespaces component title
  src/renderer/components/+cluster-settings/components/cluster-accessible-namespaces.tsx
Labels: bug

#1854 remove array desctructor of Object.values, which is brittle
  src/renderer/components/+nodes/node-charts.tsx
Labels: chore

#1908 Fix Windows tray icon click
  src/main/tray.ts
Labels: area/windows, bug

#1915 Windows: support only bash for development
  Makefile
  docs/contributing/development.md
Labels: area/documentation, area/windows, chore

#1916 Disable telemetry extension during integration tests
  .azure-pipelines.yml
Labels: area/ci, enhancement

#1919 Fix: events pages incorrect tooltip
  src/renderer/components/+events/events.tsx
Labels: bug

#1913 bump uuid and @types/uuid to 8.3.x
  package.json
  yarn.lock
Labels: dependencies

#1599 gitignore .vscode
  .gitignore
Labels: chore

#1936 Fixing object API after editing resouce
  src/renderer/api/endpoints/resource-applier.api.ts
Labels: bug

#1831 Fix auto-update to use Lens notifications, and add update confirmation
  .azure-pipelines.yml
  Makefile
  integration/specs/app_spec.ts
  package.json
  scripts/integration.sh
  src/common/ipc.ts
  src/common/utils/delay.ts
  src/common/utils/index.ts
  src/main/app-updater.ts
  src/main/index.ts
  src/main/kube-auth-proxy.ts
  src/main/window-manager.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/button/button.scss
  src/renderer/components/button/button.tsx
  src/renderer/components/notifications/notifications.scss
  src/renderer/components/notifications/notifications.store.tsx
  src/renderer/components/notifications/notifications.tsx
  src/renderer/lens-app.tsx
  src/renderer/theme.store.ts
  src/renderer/themes/kontena-dark.json
  src/renderer/themes/kontena-light.json
  src/renderer/themes/theme-vars.scss
  webpack.renderer.ts
Labels: enhancement

#1938 Fixing multiline logs wrapping
  src/renderer/components/dock/pod-log-list.scss
Labels: area/logs, bug

#1940 Fix fill the gaps logic in normalize metrics
  src/renderer/api/endpoints/metrics.api.ts
Labels: area/ui, bug

#1532 Column filters
  src/common/user-store.ts
  src/renderer/components/+workloads-pods/pods.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/item-object-list/table-menu.scss
  src/renderer/components/menu/menu-actions.tsx
  src/renderer/components/table/table-cell.tsx
Labels: area/ui, enhancement

#1796 Add support for LimitRange
  integration/__tests__/app.tests.ts
  src/common/rbac.ts
  src/extensions/renderer-api/k8s-api.ts
  src/renderer/api/endpoints/index.ts
  src/renderer/api/endpoints/limit-range.api.ts
  src/renderer/components/+config-limit-ranges/index.ts
  src/renderer/components/+config-limit-ranges/limit-range-details.scss
  src/renderer/components/+config-limit-ranges/limit-range-details.tsx
  src/renderer/components/+config-limit-ranges/limit-ranges.route.ts
  src/renderer/components/+config-limit-ranges/limit-ranges.scss
  src/renderer/components/+config-limit-ranges/limit-ranges.store.ts
  src/renderer/components/+config-limit-ranges/limit-ranges.tsx
  src/renderer/components/+config/config.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/utils/rbac.ts
Labels: area/ui, enhancement

#1950 Prevent initializing clusters multiple times
  src/main/cluster-manager.ts
  src/main/cluster.ts
Labels: bug

#1789 Rework additional extension guides
  docs/extensions/guides/images/clusterpagemenus.png
  docs/extensions/guides/images/globalpagemenus.png
  docs/extensions/guides/renderer-extension.md
  mkdocs.yml
Labels: area/documentation

#1802 Rework extensions guides
  docs/extensions/guides/working-with-mobx.md
  mkdocs.yml
Labels: area/documentation

#1803 Rework extensions guides
  docs/extensions/guides/stores.md
Labels: area/documentation

#1972 only generate docs for releases
  .github/workflows/main.yml
Labels: area/documentation

#1960 do not assume that bitnami is guanteed to be in the helm repo list
  integration/__tests__/app.tests.ts
Labels: area/test

#1965 Enable default workspace on first boot
  src/common/__tests__/workspace-store.test.ts
  src/common/workspace-store.ts
Labels: bug

#1964 Fix: chart.digest is the same for all charts and not suited as unique id
  src/renderer/api/endpoints/helm-charts.api.ts
Labels: bug

#1994 Upgrade shell-env to 3.0.1
  package.json
  yarn.lock
Labels: bug

#1970 Add age column to cluster overview
  src/renderer/components/+cluster/cluster-issues.tsx
Labels: area/ui

#1996 [4.0] Fix extension cluster submenu re-render
  src/renderer/components/app.tsx
Labels: area/extension, bug

#1995 Fixing log tab layout colors
  src/renderer/components/dock/info-panel.scss
  src/renderer/components/dock/log-controls.tsx
  src/renderer/components/select/select.scss
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
  src/renderer/themes/theme-vars.scss
Labels: area/ui

#2002 Fixing tolerations list layout
  src/renderer/api/workload-kube-object.ts
  src/renderer/components/+workloads-pods/__tests__/pod-tolerations.test.tsx
  src/renderer/components/+workloads-pods/pod-details-tolerations.scss
  src/renderer/components/+workloads-pods/pod-details-tolerations.tsx
  src/renderer/components/+workloads-pods/pod-tolerations.scss
  src/renderer/components/+workloads-pods/pod-tolerations.tsx
  src/renderer/components/drawer/drawer-item.scss
  src/renderer/components/drawer/drawer-param-toggler.tsx
  src/renderer/components/drawer/drawer.scss
Labels: area/ui, enhancement

#1918 Load k8s resources only for selected namespaces
  src/common/rbac.ts
  src/common/user-store.ts
  src/main/cluster.ts
  src/renderer/api/kube-watch-api.ts
  src/renderer/components/+apps-releases/release.store.ts
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/+user-management-roles-bindings/role-bindings.store.ts
  src/renderer/components/+user-management-roles/roles.store.ts
  src/renderer/components/+workloads-overview/overview-statuses.tsx
  src/renderer/components/+workloads-overview/overview.tsx
  src/renderer/components/+workloads-pods/pods.tsx
  src/renderer/components/item-object-list/item-list-layout.scss
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/item-object-list/page-filters.store.ts
  src/renderer/components/item-object-list/table-menu.scss
  src/renderer/components/table/table-cell.tsx
  src/renderer/item.store.ts
  src/renderer/kube-object.store.ts
Labels: bug, enhancement

#2000 Display CPU usage percentage with adequate accuracy
  src/renderer/components/+nodes/nodes.tsx
Labels: area/ui, bug

#1980 Fix azure pipeline integration test exit code
  .azure-pipelines.yml
Labels: area/ci, bug

#2015 Fix Helm repositories and pod logs integration tests
  integration/__tests__/app.tests.ts
  integration/helpers/utils.ts
Labels: area/ci, blocker, bug

#2024 Fixing misaligned table columns
  src/renderer/components/item-object-list/item-list-layout.tsx
Labels: area/ui, bug

#2027 Fix extension cluster submenu re-render (port #1996 to master)
  src/renderer/components/app.tsx
Labels: area/extension, bug

#1984 Generic logs view with Pod selector
  extensions/pod-menu/package-lock.json
  extensions/pod-menu/src/logs-menu.tsx
  package.json
  src/common/search-store.ts
  src/extensions/renderer-api/components.ts
  src/renderer/api/kube-json-api.ts
  src/renderer/components/+workloads-daemonsets/daemonsets.store.ts
  src/renderer/components/+workloads-jobs/job.store.ts
  src/renderer/components/+workloads-pods/pods.store.ts
  src/renderer/components/+workloads-replicasets/replicasets.store.ts
  src/renderer/components/+workloads-statefulsets/statefulset.store.ts
  src/renderer/components/dock/__test__/log-resource-selector.test.tsx
  src/renderer/components/dock/__test__/log-tab.store.test.ts
  src/renderer/components/dock/__test__/pod.mock.ts
  src/renderer/components/dock/dock-tabs.tsx
  src/renderer/components/dock/dock.store.ts
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/log-controls.tsx
  src/renderer/components/dock/log-list.tsx
  src/renderer/components/dock/log-resource-selector.tsx
  src/renderer/components/dock/log-tab.store.ts
  src/renderer/components/dock/log.store.ts
  src/renderer/components/dock/logs.tsx
  src/renderer/kube-object.store.ts
  yarn.lock
Labels: area/logs, area/ui

#2031 Better extensionRoutes.keys() iteration
  src/renderer/components/app.tsx
Labels: chore

#2028 Bundle kubectl 1.18.15
  package.json
  src/main/kubectl.ts
Labels: bug

#2029 Enabling configurable columns for all major tables
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
  src/renderer/components/+apps-releases/releases.tsx
  src/renderer/components/+config-autoscalers/hpa.tsx
  src/renderer/components/+config-limit-ranges/limit-ranges.tsx
  src/renderer/components/+config-maps/config-maps.tsx
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets.tsx
  src/renderer/components/+config-resource-quotas/resource-quotas.tsx
  src/renderer/components/+config-secrets/secrets.tsx
  src/renderer/components/+custom-resources/crd-list.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/+events/events.tsx
  src/renderer/components/+namespaces/namespaces.tsx
  src/renderer/components/+network-endpoints/endpoints.tsx
  src/renderer/components/+network-ingresses/ingresses.tsx
  src/renderer/components/+network-policies/network-policies.tsx
  src/renderer/components/+network-services/services.tsx
  src/renderer/components/+nodes/nodes.tsx
  src/renderer/components/+pod-security-policies/pod-security-policies.tsx
  src/renderer/components/+storage-classes/storage-classes.tsx
  src/renderer/components/+storage-volume-claims/volume-claims.tsx
  src/renderer/components/+storage-volumes/volumes.tsx
  src/renderer/components/+user-management-roles-bindings/role-bindings.tsx
  src/renderer/components/+user-management-roles/roles.tsx
  src/renderer/components/+user-management-service-accounts/service-accounts.tsx
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-daemonsets/daemonsets.tsx
  src/renderer/components/+workloads-deployments/deployments.tsx
  src/renderer/components/+workloads-jobs/jobs.tsx
  src/renderer/components/+workloads-replicasets/replicasets.tsx
  src/renderer/components/+workloads-statefulsets/statefulsets.tsx
Labels: area/ui

#2041 Makefile: regenerate node_modules if yarn.lock changes
  Makefile
Labels: area/ci, chore

#2037 Fix jest window.matchMedia() error warnings
  src/renderer/components/dock/__test__/dock-tabs.test.tsx
Labels: chore
