Repository lensapp/lens, pull requests merged in 2021-05, with the labels that each got.

#2672 Fix dashboard showing in the background when connect error happens
  src/renderer/components/cluster-manager/cluster-view.tsx
Labels: area/ui, bug

#2629 Add browse all tab to catalog page
  src/renderer/components/+catalog/catalog-entity.store.ts
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, enhancement

#2693 Include create resource templates in build
  package.json
Labels: bug, chore

#2689 Fix tar file being removed before extension install
  src/renderer/components/+extensions/extensions.tsx
Labels: area/extension, blocker, bug, merge/master

#2698 Cleanup Cluster, ClusterManger, et al.
  src/common/__tests__/cluster-store.test.ts
  src/common/cluster-store.ts
  src/extensions/core-api/index.ts
  src/main/__test__/cluster.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/cluster-detectors/base-cluster-detector.ts
  src/main/cluster-manager.ts
  src/main/cluster.ts
  src/main/context-handler.ts
  src/main/index.ts
  src/main/k8s-request.ts
  src/main/kube-auth-proxy.ts
  src/main/kubeconfig-manager.ts
  src/main/port.ts
  src/main/port_spec.ts
  src/main/proxy/index.ts
  src/main/proxy/lens-proxy.ts
  src/main/proxy/ws-upgrade.ts
  src/main/routes/metrics-route.ts
  src/main/routes/port-forward-route.ts
  src/main/utils/get-port.ts
  src/main/window-manager.ts
  src/migrations/hotbar-store/5.0.0-alpha.0.ts
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/remove-cluster-button.tsx
Labels: blocker, bug

#2691 Hotbar inner drag-n-drop
  src/common/__tests__/hotbar-store.test.ts
  src/common/hotbar-store.ts
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/components/hotbar/hotbar-menu.tsx
  src/renderer/components/hotbar/hotbar-selector.scss
  src/renderer/components/hotbar/hotbar-selector.tsx
  src/renderer/components/layout/page-layout.scss
Labels: area/ui, enhancement

#2697 fixed blank disabled Select element option (affected workspaces menu)
  src/renderer/components/select/select.scss
Labels: area/ci, area/ui, bug, merge/master

#2700 release v4.2.4
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2695 Publish npm package via gh actions
  .azure-pipelines.yml
  .github/workflows/publish-npm.yml
  Makefile
Labels: area/ci, chore

#2692 Fix kubeconfig-sync issues
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/minikube.ts
  src/common/__tests__/cluster-store.test.ts
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/cluster-store.ts
  src/extensions/core-api/index.ts
  src/main/__test__/cluster.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/catalog-pusher.ts
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/catalog-sources/kubeconfig-sync.ts
  src/main/cluster-detectors/base-cluster-detector.ts
  src/main/cluster-manager.ts
  src/main/cluster.ts
  src/main/context-handler.ts
  src/main/index.ts
  src/main/k8s-request.ts
  src/main/kube-auth-proxy.ts
  src/main/kubeconfig-manager.ts
  src/main/port.ts
  src/main/port_spec.ts
  src/main/proxy/index.ts
  src/main/proxy/lens-proxy.ts
  src/main/proxy/ws-upgrade.ts
  src/main/routes/metrics-route.ts
  src/main/routes/port-forward-route.ts
  src/main/utils/get-port.ts
  src/main/window-manager.ts
  src/migrations/hotbar-store/5.0.0-alpha.0.ts
  src/renderer/components/+add-cluster/add-cluster.scss
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/remove-cluster-button.tsx
  src/renderer/components/layout/__test__/main-layout-header.test.tsx
Labels: blocker, bug

#2703 Fix cluster disconnect not switching to catalog
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/cluster-manager/lens-views.ts
Labels: area/ui, bug

#2704 Fixing hotbar drag-n-drop animation issues
  src/common/__tests__/hotbar-store.test.ts
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: area/ui, bug

#2706 Fix ClusterScoped kube APIs not subscribing
  src/common/utils/__tests__/splitArray.test.ts
  src/common/utils/splitArray.ts
  src/renderer/components/app.tsx
  src/renderer/kube-object.store.ts
Labels: blocker, bug

#2711 release v5.0.0-beta.3
  package.json
Labels: skip-changelog

#2719 Create cluster object also for non-local sources
  src/main/cluster-manager.ts
Labels: blocker, bug

#2721 Fix auto-update exiting too fast
  src/main/app-updater.ts
Labels: autoupdate, blocker, bug

#2722 Release v5.0.0-beta.4
  package.json
Labels: skip-changelog

#2744 relax kube api data type validation (to allow metrics-server resources)
  src/renderer/api/__tests__/kube-object.test.ts
  src/renderer/api/endpoints/pod-metrics.api.ts
  src/renderer/api/kube-object.ts
Labels: area/metrics, bug

#2258 Only show the UserManagement tab in the sidebar if the sub menus are allowed for that cluster
  src/common/rbac.ts
  src/main/cluster.ts
  src/renderer/components/+user-management/user-management.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/utils/rbac.ts
Labels: area/ui, enhancement

#2679 Add tag command, update guide, add PR templates
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  Makefile
  RELEASE_GUIDE.md
  package.json
  scripts/tag-release.sh
Labels: chore

#2701 Cherry-Pick from v4.2.4
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/select/select.scss
Labels: chore

#2712 Switch main's route handlers to be static functions
  src/common/vars.ts
  src/main/__test__/router.test.ts
  src/main/lens-api.ts
  src/main/router.ts
  src/main/routes/helm-route.ts
  src/main/routes/kubeconfig-route.ts
  src/main/routes/metrics-route.ts
  src/main/routes/port-forward-route.ts
  src/main/routes/resource-applier-route.ts
  src/main/routes/version-route.ts
  src/main/utils/http-responses.ts
Labels: chore

#2757 Removing color reference from docs
  docs/extensions/capabilities/color-reference.md
  docs/extensions/capabilities/styling.md
  mkdocs.yml
Labels: area/documentation, area/extension, area/ui

#2759 Exporting chart components to extensions
  src/extensions/renderer-api/components.ts
Labels: area/extension, area/ui

#2710 Hotbar disabled items
  package.json
  src/common/__tests__/hotbar-store.test.ts
  src/common/hotbar-store.ts
  src/migrations/hotbar-store/5.0.0-beta.5.ts
  src/migrations/hotbar-store/index.ts
  src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx
  src/renderer/components/hotbar/hotbar-cell.tsx
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
  src/renderer/components/hotbar/hotbar-selector.tsx
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
Labels: area/ui, bug

#2776 Add license header to more files
  .github/workflows/license-header.yml
  src/jest.setup.ts
  src/migrations/cluster-store/2.0.0-beta.2.ts
  src/migrations/cluster-store/2.4.1.ts
  src/migrations/cluster-store/2.6.0-beta.2.ts
  src/migrations/cluster-store/2.6.0-beta.3.ts
  src/migrations/cluster-store/2.7.0-beta.0.ts
  src/migrations/cluster-store/2.7.0-beta.1.ts
  src/migrations/cluster-store/3.6.0-beta.1.ts
  src/migrations/cluster-store/index.ts
  src/migrations/cluster-store/snap.ts
  src/migrations/hotbar-store/5.0.0-alpha.0.ts
  src/migrations/hotbar-store/5.0.0-alpha.2.ts
  src/migrations/hotbar-store/5.0.0-beta.5.ts
  src/migrations/hotbar-store/index.ts
  src/migrations/migration-wrapper.ts
  src/migrations/user-store/2.1.0-beta.4.ts
  src/migrations/user-store/5.0.0-alpha.3.ts
  src/migrations/user-store/file-name-migration.ts
  src/migrations/user-store/index.ts
Labels: area/ci, area/tests, chore

#2770 include the hotbar index in the label displayed for a hotbar
  src/common/hotbar-store.ts
  src/renderer/components/hotbar/hotbar-display-label.ts
  src/renderer/components/hotbar/hotbar-remove-command.tsx
  src/renderer/components/hotbar/hotbar-selector.tsx
  src/renderer/components/hotbar/hotbar-switch-command.tsx
Labels: area/ui, enhancement

#2781 Remove universal analytics types
  package.json
  yarn.lock
Labels: chore

#2793 Delete node shell container on exit
  src/main/shell-session/node-shell-session.ts
Labels: bug

#2792 Update node shell to use Alpine 3.13
  src/main/shell-session/node-shell-session.ts
Labels: chore

#2794 Remove custom GA Tags script. Use built in GA.
  docs/custom_theme/main.html
  mkdocs.yml
Labels: area/documentation, chore

#2790 Show active item in hotbar & allow to pin/unpin
  src/common/__tests__/hotbar-store.test.ts
  src/common/hotbar-store.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: area/ui, enhancement

#2795 Re-implement deployment revisions
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-deployments/deployment-replicasets.scss
  src/renderer/components/+workloads-deployments/deployment-replicasets.tsx
Labels: area/ui, enhancement

#2758 Add connect/disconnect methods to KubernetesCluster kind
  src/common/catalog-entities/kubernetes-cluster.ts
Labels: area/extension, enhancement

#2799 Catalog entity WebLink.kind 'KubernetesCluster' > 'WebLink'
  src/common/catalog-entities/web-link.ts
Labels: bug

#2714 Show lens-metrics on cluster settings
  extensions/metrics-cluster-feature/renderer.tsx
  extensions/metrics-cluster-feature/resources/01-namespace.yml.hb
  extensions/metrics-cluster-feature/resources/03-service.yml.hb
  extensions/metrics-cluster-feature/resources/03-statefulset.yml.hb
  extensions/metrics-cluster-feature/resources/10-node-exporter-ds.yml.hb
  extensions/metrics-cluster-feature/resources/14-kube-state-metrics-deployment.yml.hb
  extensions/metrics-cluster-feature/src/metrics-feature.ts
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
  extensions/metrics-cluster-feature/tsconfig.json
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog/catalog-entity.ts
  src/common/cluster-ipc.ts
  src/common/k8s/resource-stack.ts
  src/extensions/cluster-feature.ts
  src/extensions/core-api/cluster-feature.ts
  src/extensions/core-api/index.ts
  src/extensions/registries/entity-setting-registry.ts
  src/extensions/renderer-api/components.ts
  src/extensions/renderer-api/k8s-api.ts
  src/main/cluster-manager.ts
  src/main/resource-applier.ts
  src/renderer/api/catalog-entity.ts
  src/renderer/components/+catalog/catalog-add-button.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+entity-settings/entity-settings.tsx
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-metrics-setting.scss
  src/renderer/components/cluster-settings/components/cluster-metrics-setting.tsx
  src/renderer/components/cluster-settings/components/cluster-prometheus-setting.tsx
  src/renderer/components/cluster-settings/components/remove-cluster-button.tsx
  src/renderer/components/cluster-settings/components/show-metrics.tsx
  src/renderer/components/drawer/drawer.scss
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/menu/menu.scss
Labels: area/extension, area/ui, enhancement

#2802 relax kube api data type validation (to allow metrics-server resources)
  src/renderer/api/__tests__/kube-object.test.ts
  src/renderer/api/endpoints/pod-metrics.api.ts
  src/renderer/api/kube-object.ts
Labels: bug

#2809 Removes links to ClusterFeature API docs as these no longer exist
  docs/extensions/guides/renderer-extension.md
  docs/extensions/typedoc-readme.md.tpl
Labels: area/documentation, bug

#2807 Bundle in-tree extensions as npm/tgz
  Makefile
  extensions/.gitignore
  extensions/kube-object-event-status/package-lock.json
  extensions/kube-object-event-status/package.json
  extensions/kube-object-event-status/webpack.config.js
  extensions/metrics-cluster-feature/package-lock.json
  extensions/metrics-cluster-feature/package.json
  extensions/metrics-cluster-feature/webpack.config.js
  extensions/node-menu/package-lock.json
  extensions/node-menu/package.json
  extensions/node-menu/webpack.config.js
  extensions/pod-menu/package-lock.json
  extensions/pod-menu/package.json
  extensions/pod-menu/webpack.config.js
  package.json
  src/extensions/extension-discovery.ts
Labels: area/ci, area/extension, chore

#2810 Docs theme switch fix
  mkdocs.yml
Labels: area/documentation, chore

#2816 Filter out unknown catalog entities
  src/common/catalog/catalog-category-registry.ts
  src/common/utils/extended-map.ts
  src/renderer/api/__tests__/catalog-entity-registry.test.ts
  src/renderer/api/catalog-entity-registry.ts
Labels: blocker, bug

#2824 Refactor CatalogEntityRegistry from common to main
  src/common/catalog/catalog-category-registry.ts
  src/common/catalog/index.ts
  src/extensions/core-api/catalog.ts
  src/extensions/lens-main-extension.ts
  src/main/catalog-pusher.ts
  src/main/catalog-sources/kubeconfig-sync.ts
  src/main/catalog/__tests__/catalog-entity-registry.test.ts
  src/main/catalog/catalog-entity-registry.ts
  src/main/catalog/index.ts
  src/main/cluster-manager.ts
  src/main/index.ts
  src/renderer/api/__tests__/catalog-entity-registry.test.ts
Labels: enhancement

#2829 Handle missing data on disabled hotbar items
  src/renderer/components/hotbar/hotbar-icon.tsx
Labels: blocker, bug

#2815 Fix kube sync items not visible on reopening
  src/main/catalog-pusher.ts
  src/main/index.ts
  src/renderer/api/catalog-entity-registry.ts
Labels: blocker, bug

#2833 Allow unpin disabled hotbar items
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: area/ui, bug

#2811 Adding eslint-plugin-react-hooks
  .eslintrc.js
  package.json
  yarn.lock
Labels: chore

#2834 release v5.0.0-beta.6
  package.json
Labels: skip-changelog

#2761 Fix namespace selector gradients
  src/renderer/components/+namespaces/namespace-select-filter.scss
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/+namespaces/namespace-select.scss
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/select/select.scss
Labels: area/ui, bug

#2846 Bump prometheus and kube-state-metrics for arm+other arch support
  extensions/metrics-cluster-feature/resources/03-statefulset.yml.hb
  extensions/metrics-cluster-feature/resources/14-kube-state-metrics-deployment.yml.hb
Labels: area/metrics, chore

#2852 Add icon column to catalog list
  src/renderer/components/+catalog/catalog.scss
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/avatar/avatar.tsx
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
Labels: area/ui, enhancement

#2857 Fix OpenLens svg logo
  src/renderer/components/icon/logo-lens.svg
Labels: area/ui, bug

#2855 Fix Extensions browse icon onClick event
  src/renderer/components/+extensions/install.module.css
  src/renderer/components/+extensions/install.tsx
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/hotbar/hotbar-selector.tsx
  src/renderer/components/material-tooltip/material-tooltip.tsx
Labels: area/ui, bug

#2836 Remove getOrDefault from ExtendedObservableMap
  src/common/utils/extended-map.ts
  src/main/catalog-sources/kubeconfig-sync.ts
Labels: chore

#2820 Show event last-seen column in addition to age
  src/renderer/components/+events/events.tsx
Labels: area/ui, bug

#2853 Shorter kubeconfig-sync file label
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/catalog-sources/kubeconfig-sync.ts
Labels: area/ui, enhancement

#2869 Prevent dependabot from introducing bump PRs for major versions
  .dependabot/config.yml
Labels: chore

#2862 Fix metrics-cluster-feature missing resources folder
  extensions/metrics-cluster-feature/package.json
Labels: blocker, bug

#2868 Remove unused Prettier package
  package.json
  yarn.lock
Labels: chore

#2870 Preload pods/events on nodes page
  src/renderer/components/+nodes/nodes.tsx
Labels: area/ui, bug

#2867 Fix makefile parallel jobs
  Makefile
Labels: chore

#2874 Timeout shell env sync
  src/main/shell-sync.ts
Labels: bug

#2880 Fix spelling and grammar in Ipc docs
  docs/extensions/guides/ipc.md
  src/extensions/ipc/ipc-renderer.ts
Labels: area/documentation, chore

#2861 Show all node resources in node view
  src/renderer/api/endpoints/nodes.api.ts
  src/renderer/components/+nodes/node-details-resources.scss
  src/renderer/components/+nodes/node-details-resources.tsx
  src/renderer/components/+nodes/node-details.tsx
Labels: area/ui, enhancement

#2877 Remove non-extension API docs
  docs/CNAME
  docs/README.md
  docs/clusters/adding-clusters.md
  docs/clusters/images/add-cluster.png
  docs/clusters/images/cluster-context-menu.png
  docs/clusters/images/cluster-settings-features.png
  docs/clusters/images/cluster-settings-general.png
  docs/clusters/images/cluster-settings-removal.png
  docs/clusters/images/cluster-settings-status.png
  docs/clusters/images/cluster-settings.png
  docs/clusters/images/remove-cluster.png
  docs/clusters/removing-clusters.md
  docs/clusters/settings.md
  docs/contributing/README.md
  docs/contributing/development.md
  docs/contributing/documentation.md
  docs/contributing/github_workflow.md
  docs/contributing/maintainers.md
  docs/contributing/promotion.md
  docs/contributing/testing.md
  docs/extensions/README.md
  docs/extensions/get-started/your-first-extension.md
  docs/extensions/guides/generator.md
  docs/extensions/guides/renderer-extension.md
  docs/faq/README.md
  docs/getting-started/README.md
  docs/getting-started/images/color-theme.png
  docs/getting-started/images/disabled-telemetry-usage-tracking.png
  docs/getting-started/images/snap-store.png
  docs/getting-started/introductory-videos.md
  docs/getting-started/preferences.md
  docs/helm/README.md
  docs/helm/images/helm-charts.png
  docs/support/README.md
  docs/supporting/requirements.md
  mkdocs.yml
Labels: area/documentation

#2260 Cleanup pod log store
  src/renderer/components/dock/log.store.ts
Labels: chore

#2891 fix regression from #2260
  src/renderer/components/dock/log.store.ts
Labels: chore

#2890 Fix Navigation.navigate to work with fragments
  src/renderer/navigation/helpers.ts
Labels: bug

#2879 Rework extension API into parts
  extensions/kube-object-event-status/package/package.json
  extensions/kube-object-event-status/renderer.tsx
  extensions/kube-object-event-status/src/resolver.tsx
  extensions/metrics-cluster-feature/renderer.tsx
  extensions/metrics-cluster-feature/src/metrics-feature.ts
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
  extensions/node-menu/renderer.tsx
  extensions/node-menu/src/node-menu.tsx
  extensions/pod-menu/renderer.tsx
  extensions/pod-menu/src/logs-menu.tsx
  extensions/pod-menu/src/shell-menu.tsx
  src/extensions/common-api/app.ts
  src/extensions/common-api/catalog.ts
  src/extensions/common-api/event-bus.ts
  src/extensions/common-api/index.ts
  src/extensions/common-api/registrations.ts
  src/extensions/common-api/stores.ts
  src/extensions/common-api/types.ts
  src/extensions/common-api/utils.ts
  src/extensions/core-api/types.ts
  src/extensions/extension-api.ts
  src/extensions/extension-loader.ts
  src/extensions/interfaces/catalog.ts
  src/extensions/main-api/index.ts
  src/extensions/renderer-api/index.ts
  src/main/index.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/renderer/bootstrap.tsx
Labels: area/extension, blocker, chore

#2886 Fix: cluster commands disappeared from Command Palette
  src/common/__tests__/cluster-store.test.ts
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/cluster-store.ts
  src/extensions/registries/command-registry.ts
  src/main/cluster.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/api/catalog-entity.ts
  src/renderer/components/+cluster/cluster-overview.tsx
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+nodes/node-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-pods/pod-details-container.tsx
  src/renderer/components/+workloads-pods/pod-details.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/cluster-settings/cluster-settings.command.ts
  src/renderer/components/cluster-settings/components/cluster-metrics-setting.tsx
  src/renderer/components/command-palette/command-container.tsx
  src/renderer/components/command-palette/command-dialog.tsx
  src/renderer/lens-app.tsx
Labels: bug

#2889 Fix BaseRegistry's items observable map
  src/extensions/registries/base-registry.ts
Labels: bug

#2835 Fix: don't remove clear all of groupKinds when running disposer
  src/common/__tests__/catalog-category-registry.test.ts
  src/common/catalog/catalog-category-registry.ts
Labels: blocker, bug

#2899 Use type-fest's TypedArray for ReadableWebToNodeStream
  src/renderer/utils/readableStream.ts
Labels: chore

#2898 Extension Api docs should point to generated index files
  docs/extensions/typedoc-readme.md.tpl
Labels: area/documentation

#2902 Fix main->renderer catalog entity sync issue
  src/main/catalog-pusher.ts
  src/renderer/api/__tests__/catalog-entity-registry.test.ts
  src/renderer/api/catalog-entity-registry.ts
Labels: bug

#2812 Typed catalog category events
  package.json
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog/catalog-entity.ts
  src/renderer/components/+catalog/catalog-add-button.tsx
  src/renderer/components/+catalog/catalog-entity.store.ts
  yarn.lock
Labels: area/extension, enhancement

#2915 Use in-tree extension tgz package only in production builds
  src/extensions/extension-discovery.ts
Labels: bug

#2920 Add homepage to package.json
  package.json
Labels: chore
