Repository lensapp/lens, pull requests merged in 2021-03, with the labels that each got.

#2238 Removing unused chart files
  src/renderer/components/chart/background-block.plugin.ts
  src/renderer/components/chart/useRealTimeMetrics.ts
Labels: chore

#1956 Ignore clusters with invalid kubeconfig
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/kube-helpers.test.ts
  src/common/cluster-store.ts
  src/common/ipc/index.ts
  src/common/ipc/invalid-kubeconfig/index.ts
  src/common/kube-helpers.ts
  src/main/cluster.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/dock/create-resource.tsx
  src/renderer/components/notifications/notifications.tsx
  src/renderer/ipc/index.tsx
  src/renderer/ipc/invalid-kubeconfig-handler.tsx
Labels: bug

#2263 log JSON api calls when in DEBUG mode
  src/renderer/api/index.ts
Labels: chore

#2244 Render only secret name on pod details without access to secrets
  src/renderer/components/+workloads-pods/pod-details-secrets.scss
  src/renderer/components/+workloads-pods/pod-details-secrets.tsx
Labels: bug

#2261 Cleanup add namespace dialog
  src/renderer/components/+namespaces/add-namespace-dialog.tsx
Labels: chore

#2253 Fix: preventing <App/> to render on cluster refresh
  src/renderer/components/+config/config.route.ts
  src/renderer/components/+network/network.route.ts
  src/renderer/components/+pod-security-policies/index.ts
  src/renderer/components/+pod-security-policies/pod-security-policies.route.ts
  src/renderer/components/+storage/storage.route.ts
  src/renderer/components/+user-management/user-management.route.ts
  src/renderer/components/+user-management/user-management.tsx
  src/renderer/components/+workloads/workloads.route.ts
  src/renderer/components/app.tsx
  src/renderer/components/command-palette/command-container.tsx
  src/renderer/components/layout/main-layout-header.tsx
Labels: bug

#2232 Broadcast update available only after downloading update
  src/main/app-updater.ts
Labels: bug

#2274 Release v4.1.4
  package.json
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/kube-helpers.test.ts
  src/common/cluster-store.ts
  src/common/ipc/index.ts
  src/common/ipc/invalid-kubeconfig/index.ts
  src/common/kube-helpers.ts
  src/common/rbac.ts
  src/main/cluster.ts
  src/main/lens-proxy.ts
  src/main/shell-session.ts
  src/renderer/api/endpoints/helm-releases.api.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+config/config.route.ts
  src/renderer/components/+network/network.route.ts
  src/renderer/components/+pod-security-policies/index.ts
  src/renderer/components/+pod-security-policies/pod-security-policies.route.ts
  src/renderer/components/+storage/storage.route.ts
  src/renderer/components/+user-management/user-management.route.ts
  src/renderer/components/+user-management/user-management.tsx
  src/renderer/components/+workloads-pods/pod-details-secrets.scss
  src/renderer/components/+workloads-pods/pod-details-secrets.tsx
  src/renderer/components/+workloads/workloads.route.ts
  src/renderer/components/app.tsx
  src/renderer/components/chart/background-block.plugin.ts
  src/renderer/components/chart/useRealTimeMetrics.ts
  src/renderer/components/command-palette/command-container.tsx
  src/renderer/components/dock/create-resource.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/layout/main-layout-header.tsx
  src/renderer/components/notifications/notifications.tsx
  src/renderer/ipc/index.tsx
  src/renderer/ipc/invalid-kubeconfig-handler.tsx
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2285 Release 4.2.0-alpha.1
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2286 Update copyright year
  LICENSE
  mkdocs.yml
  package.json
  src/extensions/npm/extensions/package.json
  src/main/menu.ts
Labels: area/documentation, chore

#2288 Add more information to a helm chart's ID
  src/renderer/api/endpoints/helm-charts.api.ts
Labels: bug

#2287 Add workflow to notify on new PR conflicts
  .github/workflows/maintenance.yml
Labels: chore

#2280 Refactoring usages of renderer/utils/createStorage
  integration/__tests__/app.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/__tests__/workspace.tests.ts
  src/renderer/components/+cluster/cluster-overview.store.ts
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/dock/__test__/dock-tabs.test.tsx
  src/renderer/components/dock/dock-tab.store.ts
  src/renderer/components/dock/dock.store.ts
  src/renderer/components/dock/dock.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/layout/main-layout.scss
  src/renderer/components/layout/main-layout.tsx
  src/renderer/components/layout/sidebar-context.ts
  src/renderer/components/layout/sidebar-item.scss
  src/renderer/components/layout/sidebar-item.tsx
  src/renderer/components/layout/sidebar-nav-item.tsx
  src/renderer/components/layout/sidebar-storage.ts
  src/renderer/components/layout/sidebar.scss
  src/renderer/components/layout/sidebar.tsx
  src/renderer/hooks/useStorage.ts
  src/renderer/utils/__tests__/createStorage.test.ts
  src/renderer/utils/createStorage.ts
Labels: enhancement

#2252 Add image sha256 in pod inspector
  src/renderer/components/+workloads-pods/pod-details-container.tsx
Labels: area/ui

#2241 Apply custom filters after selecting source
  src/renderer/components/item-object-list/item-list-layout.tsx
Labels: area/ui, bug

#2273 Fix font-size on <code>
  src/renderer/components/app.scss
Labels: bug

#2295 Fix update available notification able to show twice
  src/renderer/ipc/index.tsx
Labels: area/ui, bug

#2047 Basic workspace overview
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/minikube.ts
  integration/helpers/utils.ts
  src/main/cluster.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+cluster-settings/cluster-settings.tsx
  src/renderer/components/+landing-page/landing-page.scss
  src/renderer/components/+landing-page/landing-page.tsx
  src/renderer/components/+landing-page/workspace-cluster-menu.tsx
  src/renderer/components/+landing-page/workspace-cluster.store.ts
  src/renderer/components/+landing-page/workspace-overview.scss
  src/renderer/components/+landing-page/workspace-overview.tsx
  src/renderer/components/+workspaces/workspaces.tsx
  src/renderer/components/cluster-manager/clusters-menu.scss
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/layout/page-layout.scss
Labels: area/ui, blocker, enhancement

#2194 Allow to define the path of the shell in app preferences
  src/common/user-store.ts
  src/main/shell-session.ts
  src/renderer/components/+preferences/preferences.tsx
Labels: enhancement

#2276 Add horizontal scrolling to NamespaceSelect
  src/renderer/components/+namespaces/namespace-select.scss
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/select/select.tsx
Labels: area/ui, enhancement

#2325 Fixing workspace menu icon color
  src/renderer/components/cluster-manager/clusters-menu.scss
Labels: area/ui, bug

#2318 Release 4.2.0-beta.1
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2330 Fix: cluster-settings page back-button navigation is broken
  src/main/window-manager.ts
  src/renderer/navigation/events.ts
Labels: area/ui, bug

#2321 add debug prints for actions against the navigation object
  src/renderer/navigation/history.ts
Labels: chore

#2299 Cleanup SearchStore
  src/common/__tests__/search-store.test.ts
  src/common/search-store.ts
  src/renderer/components/dock/log-list.tsx
  src/renderer/components/dock/log.store.ts
Labels: chore

#2334 Start hidden on autostart
  src/common/user-store.ts
  src/main/index.ts
  src/main/window-manager.ts
Labels: enhancement

#2316 Add terminal shortcut for mac os
  src/renderer/components/dock/terminal.ts
Labels: area/macos, enhancement

#2304 Navigation menu in Preferences
  package.json
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+landing-page/landing-page.scss
  src/renderer/components/+preferences/helm-charts.scss
  src/renderer/components/+preferences/helm-charts.tsx
  src/renderer/components/+preferences/kubectl-binaries.tsx
  src/renderer/components/+preferences/preferences.scss
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/cluster-manager/bottom-bar.scss
  src/renderer/components/cluster-manager/cluster-manager.scss
  src/renderer/components/layout/page-layout.scss
  src/renderer/components/layout/page-layout.tsx
  src/renderer/components/scroll-spy/__tests__/scroll-spy.test.tsx
  src/renderer/components/scroll-spy/scroll-spy.tsx
  src/renderer/components/tree-view/index.ts
  src/renderer/components/tree-view/tree-view.scss
  src/renderer/components/tree-view/tree-view.tsx
  src/renderer/hooks/index.ts
  src/renderer/hooks/useMutationObserver.ts
  yarn.lock
Labels: area/ui, enhancement

#2297 Fix Lens not clearing other KUBECONFIG env vars
  src/main/__test__/shell-session.test.ts
  src/main/shell-session.ts
Labels: bug

#2337 Move clearKubeconfigEnvVars to separate file
  src/main/__test__/shell-session.test.ts
  src/main/shell-session.ts
  src/main/utils/clear-kube-env-vars.ts
Labels: area/tests, blocker, bug

#2342 Fix workspace overview switching and enabled state storage
  src/common/workspace-store.ts
  src/renderer/components/+landing-page/landing-page.tsx
  src/renderer/components/+landing-page/workspace-overview.tsx
Labels: area/ui, blocker, bug

#2351 Fix extension command palette loading
  src/extensions/extension-loader.ts
  src/extensions/registries/index.ts
Labels: area/extension, blocker, bug

#2349 Fix: closing workspace menu after clicking on iframe
  src/renderer/components/cluster-manager/cluster-manager.scss
  src/renderer/components/cluster-manager/clusters-menu.scss
  src/renderer/components/layout/page-layout.scss
  src/renderer/components/menu/menu.tsx
Labels: area/ui, bug

#2272 Add common app routes to the protocol renderer router
  docs/clusters/adding-clusters.md
  docs/extensions/README.md
  docs/getting-started/README.md
  docs/getting-started/preferences.md
  extensions/telemetry/renderer.tsx
  src/common/protocol-handler/router.ts
  src/common/utils/buildUrl.ts
  src/extensions/registries/app-preference-registry.ts
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/lens-app.tsx
  src/renderer/navigation/helpers.ts
  src/renderer/navigation/history.ts
  src/renderer/navigation/index.ts
  src/renderer/navigation/protocol-handlers.ts
  src/renderer/protocol-handler/app-handlers.ts
  src/renderer/protocol-handler/index.ts
  webpack.extensions.ts
Labels: area/documentation, enhancement

#2358 Fix global pages z-index order
  src/renderer/components/cluster-manager/cluster-manager.scss
Labels: area/ui, blocker, bug

#2279 Persist local-storage in external json-file
  integration/__tests__/cluster-pages.tests.ts
  package.json
  src/renderer/components/+cluster/cluster-overview.store.ts
  src/renderer/components/+custom-resources/crd-list.tsx
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/dock/__test__/dock-tabs.test.tsx
  src/renderer/components/dock/create-resource.store.ts
  src/renderer/components/dock/dock-tab.store.ts
  src/renderer/components/dock/dock.store.ts
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/edit-resource.store.ts
  src/renderer/components/dock/edit-resource.tsx
  src/renderer/components/dock/install-chart.store.ts
  src/renderer/components/dock/log-tab.store.ts
  src/renderer/components/dock/upgrade-chart.store.ts
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/layout/main-layout.scss
  src/renderer/components/layout/main-layout.tsx
  src/renderer/components/layout/sidebar-context.ts
  src/renderer/components/layout/sidebar-item.scss
  src/renderer/components/layout/sidebar-item.tsx
  src/renderer/components/layout/sidebar-nav-item.scss
  src/renderer/components/layout/sidebar-nav-item.tsx
  src/renderer/components/layout/sidebar-storage.ts
  src/renderer/components/layout/sidebar.scss
  src/renderer/components/layout/sidebar.tsx
  src/renderer/hooks/useStorage.ts
  src/renderer/utils/__tests__/storageHelper.test.ts
  src/renderer/utils/createStorage.ts
  src/renderer/utils/index.ts
  src/renderer/utils/storageHelper.ts
  yarn.lock
Labels: bug

#2339 release v4.2.0-rc.1
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2364 Fix: editing resource is broken when another resource is being editing
  src/renderer/components/dock/edit-resource.tsx
Labels: area/ui, blocker, bug

#2372 Fix: Recreate proxy kubeconfig if it is deleted
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/cluster.ts
  src/main/context-handler.ts
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-service.ts
  src/main/kubeconfig-manager.ts
  src/main/node-shell-session.ts
  src/main/resource-applier.ts
  src/main/routes/kubeconfig-route.ts
  src/main/routes/port-forward-route.ts
  src/main/shell-session.ts
Labels: bug

#2065 Change Cluster Settings button to be consistent with cluster icon menu
  src/common/cluster-store.ts
  src/renderer/components/cluster-manager/cluster-actions.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/components/cluster-manager/index.tsx
  src/renderer/components/layout/__test__/main-layout-header.test.tsx
  src/renderer/components/layout/main-layout-header.tsx
Labels: area/ui, enhancement

#2363 Fix: incorrect subscribing event name to navigate in cluster view
  src/main/index.ts
  src/main/window-manager.ts
  src/renderer/components/cluster-manager/cluster-actions.tsx
  src/renderer/components/layout/__test__/main-layout-header.test.tsx
  src/renderer/lens-app.tsx
  src/renderer/navigation/events.ts
Labels: area/ui, bug

#733 add user-store file name migration
  src/common/user-store.ts
  src/migrations/user-store/file-name-migration.ts
  src/migrations/user-store/index.ts
Labels: chore

#2173 Add notification to user to add accessible namespaces
  src/common/ipc/cluster.ipc.ts
  src/common/ipc/index.ts
  src/common/ipc/update-available.ipc.ts
  src/main/cluster.ts
  src/renderer/components/+cluster-settings/cluster-settings.tsx
  src/renderer/components/+cluster-settings/components/cluster-accessible-namespaces.tsx
  src/renderer/components/app.scss
  src/renderer/components/layout/sub-title.tsx
  src/renderer/ipc/index.tsx
Labels: area/ui, enhancement

#2366 Fix: highlight sidebar's active section
  src/renderer/components/+custom-resources/custom-resources.tsx
  src/renderer/components/layout/sidebar-item.tsx
  src/renderer/components/layout/sidebar.tsx
Labels: area/ui, bug

#2378 release v4.2.0-rc.2
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2385 Set initial cursor position for the editor to beginning
  src/renderer/components/ace-editor/ace-editor.tsx
Labels: area/ui, bug

#2388 Proxy should listen only on loopback device
  src/main/lens-proxy.ts
Labels: area/security, bug

#2384 Get rid of SidebarItem.props.subMenus in favour of props.children
  src/renderer/components/layout/sidebar-item.tsx
  src/renderer/components/layout/sidebar.tsx
Labels: enhancement

#2387 Add security policy
  SECURITY.md
Labels: area/documentation, area/security

#2398 Fix path traversal bug in router
  src/main/__test__/router.test.ts
  src/main/router.ts
Labels: area/security, bug

#2400 release v4.2.0-rc.3
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2365 Wrapping ReactSelect styles into CacheProvider
  package.json
  src/renderer/bootstrap.tsx
  src/renderer/components/+namespaces/namespace-select-filter.scss
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/+namespaces/namespace-select.scss
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/select/select.tsx
  yarn.lock
Labels: area/ui, bug

#2256 Restrict extension version of ClusterStore
  src/common/__tests__/cluster-store.test.ts
  src/common/cluster-store.ts
  src/extensions/stores/cluster-store.ts
Labels: area/extension, bug

#2034 Fix unit tests and make tests fail if a promise rejects after the test harness is finishes
  Makefile
  integration/__tests__/app.tests.ts
  package.json
  scripts/test.sh
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/search-store.test.ts
  src/common/__tests__/user-store.test.ts
  src/common/__tests__/workspace-store.test.ts
  src/common/base-store.ts
  src/jest.setup.ts
  src/renderer/api/__tests__/kube-api-parse.test.ts
  src/renderer/api/__tests__/kube-api.test.ts
  src/renderer/components/+workloads-pods/__tests__/pod-tolerations.test.tsx
  src/renderer/components/dock/__test__/log-resource-selector.test.tsx
  src/renderer/components/dock/__test__/log-tab.store.test.ts
Labels: area/tests, chore

#2048 Improve tray initialization and logging
  src/main/tray.ts
Labels: area/ui, chore

#2262 Notify user if Helm list fails
  src/main/routes/helm-route.ts
  src/renderer/components/+apps-releases/release.store.ts
Labels: area/ui, bug

#2259 Fix integration test lifecycle fuctions not failing tests
  integration/__tests__/app.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/__tests__/command-palette.tests.ts
  integration/__tests__/workspace.tests.ts
  integration/helpers/utils.ts
Labels: area/tests, chore

#2067 Improve correctness and efficiency in some of pods api helper functions
  src/renderer/api/__tests__/pods.test.ts
  src/renderer/api/endpoints/pods.api.ts
Labels: area/tests, chore
