Repository lensapp/lens, pull requests merged in 2021-06, with the labels that each got.

#2787 Add notification in renderer if lens protocol handler fails to find any routes
  src/common/protocol-handler/router.ts
  src/main/index.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/main/protocol-handler/router.ts
  src/renderer/components/notifications/notifications.tsx
  src/renderer/protocol-handler/app-handlers.tsx
  src/renderer/protocol-handler/router.ts
  src/renderer/protocol-handler/router.tsx
Labels: area/ui, enhancement

#2934 Expose NamespaceSelectFilter component to Extensions API
  src/extensions/renderer-api/components.ts
Labels: enhancement

#2928 Fix ClusterView bugs
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/cluster-manager/lens-views.ts
Labels: area/ui, blocker, bug

#2924 Fix getReleases returning inconsistent data types
  src/main/helm/helm-release-manager.ts
  src/renderer/api/endpoints/helm-releases.api.ts
  src/renderer/api/kube-object.ts
Labels: bug

#2930 Update react-select types
  package.json
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/select/select.tsx
  yarn.lock
Labels: area/extension, bug

#2932 Show entity kind on catalog browse-all list
  src/renderer/components/+catalog/catalog-entity.store.ts
  src/renderer/components/+catalog/catalog.scss
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, enhancement

#2909 Improve how kubernetes cluster status is resolved
  src/common/cluster-ipc.ts
  src/main/catalog/catalog-entity-registry.ts
  src/main/cluster-manager.ts
  src/renderer/components/cluster-manager/lens-views.ts
Labels: bug

#2918 Revert point docs to versioned docs
  src/common/vars.ts
Labels: bug, merge/master

#2743 Remove `isClusterScoped` from `ItemListLayout`
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
  src/renderer/components/+custom-resources/crd-details.tsx
  src/renderer/components/+custom-resources/crd-list.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/+namespaces/namespaces.tsx
  src/renderer/components/+nodes/nodes.tsx
  src/renderer/components/+pod-security-policies/pod-security-policies.tsx
  src/renderer/components/+storage-classes/storage-classes.tsx
  src/renderer/components/+storage-volumes/volumes.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/layout/__test__/main-layout-header.test.tsx
Labels: area/extension, area/ui, enhancement

#2959 Fix app crash when logTabData does not exist in store
  src/renderer/components/dock/log-list.tsx
Labels: area/ui, bug

#2961 Cleanup cluster views on unmount
  src/renderer/components/cluster-manager/cluster-view.tsx
Labels: area/ui, blocker, bug

#2955 Fixed #2954: Rollback should include current version as well.
  src/renderer/components/+apps-releases/release-rollback-dialog.tsx
Labels: enhancement

#2964 Fix drawer closing on updating kube objects
  src/renderer/kube-object.store.ts
Labels: bug

#2946 Set in-tree extensions package.json version on build
  build/set_build_version.ts
  extensions/kube-object-event-status/package.json
  extensions/metrics-cluster-feature/package.json
  extensions/node-menu/package.json
  extensions/pod-menu/package.json
Labels: area/ci, blocker, bug

#2962 Readd NamespaceSelectFilter to releases.tsx
  src/renderer/components/+apps-releases/releases.tsx
Labels: bug

#2888 Make a master tag of the extensions API
  .github/workflows/publish-master-npm.yml
  .github/workflows/publish-release-npm.yml
  Makefile
  build/set_npm_version.ts
Labels: area/extension, enhancement

#2963 Await `onActivate`/`onDeactive` of extensions
  src/extensions/extension-loader.ts
  src/extensions/lens-extension.ts
Labels: area/extension, bug

#2952 Remove Namespace filter from ItemListLayout
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/item-object-list/filter-icon.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/item-object-list/page-filters-select.tsx
  src/renderer/components/item-object-list/page-filters.store.ts
Labels: chore

#2935 Remove try/catch around lens:// route, as that happens in route()
  src/main/index.ts
Labels: chore

#2893 Remove old extensions on build
  Makefile
Labels: chore

#2716 Simplify add cluster view
  package.json
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/kube-helpers.test.ts
  src/common/__tests__/user-store.test.ts
  src/common/cluster-store.ts
  src/common/kube-helpers.ts
  src/common/user-store.ts
  src/common/utils/index.ts
  src/common/utils/paths.ts
  src/main/catalog-sources/kubeconfig-sync.ts
  src/main/cluster.ts
  src/main/kubeconfig-manager.ts
  src/migrations/cluster-store/3.6.0-beta.1.ts
  src/renderer/api/kube-watch-api.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/cluster-manager/cluster-status.tsx
  src/renderer/components/cluster-settings/components/cluster-proxy-setting.tsx
  yarn.lock
Labels: area/ui, enhancement

#2975 Fix catalog table column widths
  src/renderer/components/+catalog/catalog.scss
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, bug

#2953 Cherry pick commits from 4.2
  src/common/vars.ts
Labels: chore

#2597 Wait for LensApp to report that the view has loaded before showing main window
  src/main/index.ts
  src/main/window-manager.ts
  src/renderer/lens-app.tsx
Labels: chore

#2976 Fix NPM_RELEASE_TAG in Makefile
  Makefile
Labels: area/ci, area/extension

#2940 Upgrade `typedoc`
  docs/extensions/typedoc-readme.md.tpl
  package.json
  typedoc.json
  yarn.lock
Labels: area/documentation, blocker

#2927 Add container attach feature
  extensions/pod-menu/renderer.tsx
  extensions/pod-menu/src/attach-menu.tsx
  integration/__tests__/cluster-pages.tests.ts
Labels: area/ui, enhancement

#2943 Fix hotbar light theme colors
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
Labels: area/ui, bug

#2956 Make customizing ItemListLayout header explicitly reducable
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
  src/renderer/components/+apps-releases/releases.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+custom-resources/crd-list.scss
  src/renderer/components/+custom-resources/crd-list.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/+events/events.tsx
  src/renderer/components/input/search-input-url.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/kube-object/kube-object-list-layout.tsx
  src/renderer/utils/rbac.ts
Labels: area/extension, enhancement, semver-major

#2912 Release v5.0.0-beta.7
  package.json
Labels: skip-changelog

#2998 Turn off --strict in verify-docs
  package.json
Labels: area/ci, area/documentation

#2982 Remove unnecessary 'onlyVisibleForSource'
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog/catalog-entity.ts
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
Labels: area/extension, enhancement, semver-major

#2983 Fix tag-release script
  scripts/tag-release.sh
Labels: chore, semver-patch

#2897 Add new temp workflow to help with docs sync
  .github/workflows/mkdocs-manual.yml
Labels: area/ci

#2896 Amend the docs nav menu
  mkdocs.yml
Labels: area/documentation

#3011 Update job to use node version 12
  .github/workflows/mkdocs-manual.yml
Labels: area/ci

#3012 Update job to add in version of docs to be deployed by mike
  .github/workflows/mkdocs-manual.yml
Labels: area/ci

#3013 Update job to change title and sync css from master branch
  .github/workflows/mkdocs-manual.yml
Labels: area/ci

#3010 Clean up empty pod log entries
  src/renderer/components/dock/log.store.ts
Labels: area/logs, area/ui, bug

#2884 Initial support for validating extension engines.lens version
  src/common/vars.ts
  src/extensions/__tests__/extension-discovery.test.ts
  src/extensions/__tests__/lens-extension.test.ts
  src/extensions/extension-discovery.ts
  src/extensions/extension-installer.ts
  src/extensions/extension-loader.ts
  src/extensions/lens-extension.ts
  src/extensions/registries/__tests__/page-registry.test.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/+extensions/installed-extensions.module.css
  src/renderer/components/+extensions/installed-extensions.tsx
Labels: area/extension, area/ui, enhancement

#2938 Fix shell-env timeout
  src/main/shell-session/shell-session.ts
  src/main/shell-sync.ts
  src/main/utils/shell-env.ts
Labels: bug

#3015 CatalogEnitityDrawerMenu should have actions running left to right
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
Labels: area/ui, bug

#3001 Set build version before building extensions
  Makefile
Labels: area/ci, blocker

#3018 Fix catalog layout bugs
  src/renderer/components/+catalog/catalog.module.css
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, bug

#2887 Minor cleanup of ExtensionDiscovery
  src/extensions/extension-discovery.ts
Labels: chore

#2821 Switch to more specific IPC helpers
  src/common/base-store.ts
  src/common/cluster-ipc.ts
  src/common/cluster-store.ts
  src/common/ipc/ipc.ts
  src/common/ipc/type-enforced-ipc.ts
  src/extensions/extension-discovery.ts
  src/extensions/extension-loader.ts
  src/extensions/ipc/ipc-main.ts
  src/main/cluster-manager.ts
  src/main/index.ts
  src/main/initializers/index.ts
  src/main/initializers/ipc.ts
  src/main/menu.ts
  src/main/window-manager.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/components/cluster-manager/cluster-status.tsx
  src/renderer/components/command-palette/command-container.tsx
  src/renderer/navigation/events.ts
Labels: chore

#3016 Fix buildNumber to be consistent for all package.json's
  build/set_build_version.ts
Labels: area/ci, chore

#3022 Fix dependabot config
  .dependabot/config.yml
Labels: dependencies

#3009 Add manual restart required to update notification
  src/renderer/ipc/index.tsx
Labels: area/ui, enhancement

#3034 Unset activeEntity on unmount
  src/renderer/components/cluster-manager/cluster-view.tsx
Labels: area/ui, bug

#3035 Fix catalog entity context menu duplicate entries
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
Labels: area/ui, blocker, bug

#3036 release v5.0.0-beta.8
  package.json
Labels: skip-changelog

#3040 Allow installing extensions by dist-tag
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/input/input_validators.ts
Labels: bug

#3041 Only run `make build` on azure
  .azure-pipelines.yml
Labels: area/ci, blocker, bug

#3050 Add kubeWorkloadsOverviewItems example to docs
  docs/extensions/capabilities/common-capabilities.md
Labels: area/documentation, enhancement

#3048 Fix manage cluster proxy settings
  src/renderer/components/cluster-manager/cluster-status.scss
  src/renderer/components/cluster-manager/cluster-status.tsx
Labels: area/ui, bug

#3049 Fix top-bar extension render errors
  docs/extensions/capabilities/common-capabilities.md
  src/extensions/registries/topbar-registry.ts
  src/renderer/components/layout/__tests__/topbar.test.tsx
  src/renderer/components/layout/topbar.tsx
Labels: area/documentation, area/extension, bug

#2426 Add checks to block edits to key fields
  src/renderer/api/kube-object.ts
Labels: bug

#3026 Adding tracking of mainWindow's visibility to ProtocolRouter, open main view on valid lens://
  src/main/index.ts
  src/main/protocol-handler/router.ts
Labels: bug

#3027 Fix extensions not having the same version as Lens
  build/set_build_version.ts
Labels: blocker, chore

#3066 Bring back support for custom cluster icons
  src/common/catalog-entities/kubernetes-cluster.ts
  src/main/cluster-manager.ts
  src/renderer/components/+catalog/catalog-entity-details.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-icon-settings.tsx
  src/renderer/components/cluster-settings/components/index.ts
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
Labels: area/ui, enhancement

#3067 Catalog menu restyling
  src/renderer/components/+catalog/catalog-menu.module.css
  src/renderer/components/+catalog/catalog-menu.tsx
  src/renderer/components/+catalog/catalog-tree.module.css
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, enhancement

#3072 Fix height resizing of VirtualList
  package.json
  src/renderer/components/virtual-list/virtual-list.tsx
  yarn.lock
Labels: area/ui, bug

#3073 Re-enable strict mode in docs vlidation. Bump mkdocs-material version
  mkdocs.yml
  mkdocs/requirements.txt
  package.json
Labels: area/documentation

#3076 Update `extensions/**/package-lock.json` to v0.0.1
  extensions/kube-object-event-status/package-lock.json
  extensions/metrics-cluster-feature/package-lock.json
  extensions/node-menu/package-lock.json
  extensions/pod-menu/package-lock.json
Labels: chore

#3078 Check cluster connected status from cluster.status.phase property
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
Labels: bug

#3087 Add React.Fragment with key property to entity settings navigation
  src/renderer/components/+entity-settings/entity-settings.tsx
Labels: bug

#3063 release v5.0.0-beta.9
  .azure-pipelines.yml
  package.json
Labels: skip-changelog

#3089 Do not make watch requests without resourceVersion
  src/renderer/kube-object.store.ts
Labels: bug

#3084 Catch exceptions when trying to load namespaces from api
  src/renderer/components/+namespaces/namespace.store.ts
Labels: bug

#3085 Fixing visibility of extension global pages
  src/renderer/components/cluster-manager/cluster-manager.scss
Labels: area/extension, area/ui, bug

#3083 Set correct namespace for the subject when creating new role binding
  src/renderer/components/+user-management/+role-bindings/dialog.tsx
Labels: bug

#3088 Use new config structure for mkdocs versioning feature
  mkdocs.yml
Labels: area/documentation

#2923 Add context menu entry for deleting local clusters
  src/common/__tests__/cluster-store.test.ts
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog/catalog-entity.ts
  src/common/cluster-ipc.ts
  src/common/cluster-store.ts
  src/common/hotbar-store.ts
  src/common/utils/index.ts
  src/main/__test__/cluster.test.ts
  src/main/catalog-pusher.ts
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/catalog-sources/kubeconfig-sync.ts
  src/main/cluster-manager.ts
  src/main/cluster.ts
  src/main/helm/helm-release-manager.ts
  src/main/index.ts
  src/main/initializers/ipc.ts
  src/main/kubectl.ts
  src/main/promise-exec.ts
  src/main/proxy/lens-proxy.ts
  src/main/resource-applier.ts
  src/migrations/cluster-store/3.6.0-beta.1.ts
  src/renderer/components/+catalog/catalog-entity-details.tsx
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/+catalog/catalog-entity.store.ts
  src/renderer/components/+catalog/catalog.module.css
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/ipc/index.tsx
  src/renderer/ipc/invalid-kubeconfig-handler.tsx
Labels: blocker, enhancement

#3093 Fix catalog list icon font size
  src/renderer/components/+catalog/catalog.module.css
Labels: area/ui, bug

#3097 Allow to search catalog by source
  src/renderer/components/+catalog/catalog-entity.store.ts
Labels: area/ui, enhancement

#3098 Allow to hide/show catalog list columns
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, enhancement

#3102 Update catalog url params on category change
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, bug

#3105 ClusterStore.storedKubeConfigFolder should be usabled everywhere
  src/common/cluster-store.ts
Labels: bug

#3094 updated cluster features docs
  docs/extensions/capabilities/common-capabilities.md
  docs/extensions/guides/images/clusterfeature.png
  docs/extensions/guides/resource-stack.md
Labels: area/documentation

#3091 lens:// routing shouldn't ignore intree extensions
  src/common/protocol-handler/router.ts
  src/extensions/extension-loader.ts
Labels: blocker, bug

#3074 Add migration details for extension api docs
  docs/README.md
  docs/extensions/capabilities/common-capabilities.md
  docs/extensions/extension-migration.md
  docs/extensions/guides/README.md
  docs/extensions/guides/catalog.md
  docs/extensions/guides/images/clusterfeature.png
  docs/extensions/guides/main-extension.md
  docs/extensions/guides/renderer-extension.md
  docs/extensions/guides/resource-stack.md
  mkdocs.yml
Labels: area/documentation

#3079 Transition workspaces to hotbars
  package.json
  src/migrations/hotbar-store/5.0.0-beta.11.ts
  src/migrations/hotbar-store/index.ts
Labels: blocker, enhancement

#2098 Use allocatable instead of capacity for node resources.
  src/main/prometheus/lens.ts
  src/main/prometheus/operator.ts
  src/main/prometheus/stacklight.ts
  src/renderer/api/endpoints/cluster.api.ts
  src/renderer/api/endpoints/nodes.api.ts
  src/renderer/components/+cluster/cluster-pie-charts.tsx
  src/renderer/components/+nodes/node-charts.tsx
  src/renderer/components/+nodes/nodes.tsx
Labels: area/metrics, bug

#3113 Depedabot config should be in .github/
  .dependabot/config.yml
  .github/dependabot.yml
Labels: chore

#3123 Rename PageLayout to SettingLayout
  src/extensions/renderer-api/components.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+entity-settings/entity-settings.tsx
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/layout/page-layout.tsx
  src/renderer/components/layout/setting-layout.scss
  src/renderer/components/layout/setting-layout.tsx
Labels: area/extension, area/ui, bug

#3109 Set grouping on local settings
  src/renderer/initializers/entity-settings-registry.ts
Labels: blocker, bug

#3125 Expose MainLayout to extensions
  src/extensions/renderer-api/components.ts
  src/renderer/components/layout/main-layout.tsx
Labels: area/extension, enhancement

#3110 Switch sync buttons on windows
  src/renderer/components/+preferences/kubeconfig-syncs.tsx
Labels: area/windows, blocker, bug

#3122 Remove login layout
  src/renderer/components/layout/login-layout.scss
  src/renderer/components/layout/login-layout.tsx
Labels: chore

#3127 Highlight Welcome page community link
  src/extensions/registries/welcome-menu-registry.ts
  src/renderer/components/+welcome/welcome.scss
  src/renderer/components/+welcome/welcome.tsx
  src/renderer/initializers/welcome-menu-registry.ts
Labels: area/ui, bug

#3118 renderer extension guide updates for 5.0 (WIP)
  docs/extensions/guides/images/clusterpagemenus.png
  docs/extensions/guides/renderer-extension.md
Labels: area/documentation

#3130 Always open main window if lens:// are routed
  src/main/protocol-handler/router.ts
Labels: blocker, bug

#3134 Fix set of cluster entity icon src
  src/common/catalog-entities/kubernetes-cluster.ts
  src/main/cluster-manager.ts
Labels: blocker, bug

#3138 Mark typed-emitter as a dependency for @k8slens/extensions
  src/extensions/npm/extensions/package.json
Labels: area/extension, blocker, bug

#3139 Use beta release channel for rc builds
  build/set_build_version.ts
Labels: area/ci, bug

#3141 Release v5.0.0-beta.10
  .github/release-drafter.yml
  Makefile
  package.json
  scripts/tag-release.sh
  src/migrations/hotbar-store/5.0.0-beta.10.ts
  src/migrations/hotbar-store/index.ts
Labels: skip-changelog

#3145 Transparent background for custom icons
  src/renderer/components/avatar/avatar.tsx
Labels: area/ui, bug

#3148 Treat bundled extensions as enabled in protocol router
  src/common/protocol-handler/router.ts
Labels: blocker, bug

#3154 [v4.2] Electron 9.4.4
  package.json
  yarn.lock
Labels: autoupdate, bug

#3153 Show led only for clusters
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
Labels: area/ui, bug

#3156 Cleaning settings page view
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
  src/renderer/components/+entity-settings/entity-settings.tsx
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+extensions/notice.tsx
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-accessible-namespaces.tsx
  src/renderer/components/cluster-settings/components/cluster-icon-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-kubeconfig.tsx
  src/renderer/components/cluster-settings/components/cluster-metrics-setting.tsx
  src/renderer/components/cluster-settings/components/cluster-prometheus-setting.tsx
  src/renderer/components/cluster-settings/components/cluster-show-metrics.tsx
  src/renderer/components/editable-list/editable-list.scss
  src/renderer/components/editable-list/editable-list.tsx
  src/renderer/components/file-picker/file-picker.tsx
  src/renderer/components/input/input.scss
  src/renderer/components/layout/setting-layout.scss
  src/renderer/components/layout/setting-layout.tsx
  src/renderer/components/select/select.scss
Labels: area/ui, bug

#3157 Fix catalog list flashing
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, blocker, bug

#3160 Show error notification if user tries to remove the last hotbar
  src/renderer/components/hotbar/__tests__/hotbar-remove-command.test.tsx
  src/renderer/components/hotbar/hotbar-remove-command.tsx
Labels: bug

#3159 Wait for extensions when doing protocol handler routing
  src/common/protocol-handler/router.ts
  src/main/index.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/main/protocol-handler/router.ts
Labels: area/extension, bug

#3038 Fix <Icon>'s not using tooltip and fix toolbar not being boolean
  extensions/node-menu/src/node-menu.tsx
  extensions/pod-menu/src/attach-menu.tsx
  extensions/pod-menu/src/logs-menu.tsx
  extensions/pod-menu/src/shell-menu.tsx
  integration/__tests__/cluster-pages.tests.ts
  src/renderer/components/+apps-releases/release-menu.tsx
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/+user-management/+service-accounts/view.tsx
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-deployments/deployments.tsx
  src/renderer/components/+workloads-replicasets/replicasets.tsx
  src/renderer/components/+workloads-statefulsets/statefulsets.tsx
  src/renderer/components/dock/dock-tab.tsx
  src/renderer/components/file-picker/file-picker.tsx
  src/renderer/components/icon/icon.tsx
  src/renderer/components/kube-object/kube-object-menu.tsx
  src/renderer/components/menu/menu-actions.tsx
Labels: area/ui, bug

#3164 Release v4.2.5
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#3163 Navigate back to last viewed catalog catagory
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/cluster-manager/cluster-topbar.tsx
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/utils/createStorage.ts
Labels: bug

#3168 Fix integration test not assigning to clusterAdded correctly
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/utils.ts
Labels: area/tests, bug

#3176 Release v5.0.0-beta.11
  package.json
Labels: skip-changelog

#3186 Fixing context menu for hotbar icons
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: area/ui, blocker, bug

#3178 Fix hotbar migration of workspaces
  integration/helpers/utils.ts
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/hotbar-store.test.ts
  src/common/__tests__/user-store.test.ts
  src/common/base-store.ts
  src/common/cluster-store.ts
  src/common/hotbar-store.ts
  src/common/user-store.ts
  src/common/weblink-store.ts
  src/extensions/__tests__/extension-discovery.test.ts
  src/extensions/extension-loader.ts
  src/extensions/extension-store.ts
  src/extensions/extensions-store.ts
  src/main/__test__/context-handler.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/catalog-sources/general.ts
  src/main/catalog-sources/index.ts
  src/main/catalog-sources/weblinks.ts
  src/main/extension-filesystem.ts
  src/main/index.ts
  src/main/initializers/general-entities.ts
  src/main/initializers/index.ts
  src/main/initializers/stores.ts
  src/main/initializers/weblinks.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/migrations/cluster-store/5.0.0-beta.10.ts
  src/migrations/hotbar-store/5.0.0-alpha.0.ts
  src/migrations/hotbar-store/5.0.0-beta.10.ts
  src/migrations/hotbar-store/5.0.0-beta.5.ts
  src/migrations/user-store/file-name-migration.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+catalog/catalog-entity-details.tsx
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/dock/__test__/log-resource-selector.test.tsx
  src/renderer/components/hotbar/__tests__/hotbar-remove-command.test.tsx
  src/renderer/components/hotbar/hotbar-add-command.tsx
  src/renderer/initializers/index.ts
  src/renderer/initializers/stores.ts
  src/renderer/theme.store.ts
Labels: blocker, bug

#3185 Fix broken links after updating general docs of lens-ide
  docs/README.md
  docs/extensions/get-started/your-first-extension.md
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: area/documentation

#3162 Remove padding for custom icons
  src/renderer/components/hotbar/hotbar-icon.scss
Labels: area/ui, bug

#3171 Update distro label on clusters
  src/main/cluster-manager.ts
Labels: area/ui, bug

#3187 Track extension provisions and check bundled for routing
  Makefile
  src/common/protocol-handler/router.ts
  src/extensions/extension-discovery.ts
  src/extensions/extension-loader.ts
  src/extensions/extensions-store.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/main/protocol-handler/router.ts
Labels: blocker, bug

#3188 release v5.0.0-beta.12
  package.json
Labels: skip-changelog

#3189 Don't clear searchUrlParam on every change
  src/renderer/components/item-object-list/page-filters-list.tsx
  src/renderer/components/item-object-list/page-filters.store.ts
Labels: bug

#3190 HotbarIcon's refering to unknown entities should be removalable
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: blocker, bug

#3200 Filtering out clusters by metadata.id in hotbar migrations
  src/migrations/hotbar-store/5.0.0-beta.10.ts
Labels: bug, migrations

#3208 Fix cluster-store and hotbar-store migrations
  src/common/cluster-store.ts
  src/migrations/cluster-store/5.0.0-beta.13.ts
  src/migrations/hotbar-store/5.0.0-beta.10.ts
Labels: blocker, bug

#3209 release v5.0.0
  build/set_build_version.ts
  package.json
Labels: skip-changelog

#3196 Fix using default hotbars
  src/common/hotbar-store.ts
Labels: bug

#3220 Add esbuild/esbuild-loader to reduce memory usage when `make dev`
  package.json
  src/common/getTSLoader.ts
  webpack.main.ts
  webpack.renderer.ts
  yarn.lock
Labels: chore

#3222 Fixing Catalog columns alignment
  src/renderer/components/virtual-list/virtual-list.scss
Labels: area/ui, bug

#3213 Allow Node panel to open for virtual nodes
  src/renderer/components/+nodes/node-details-resources.tsx
Labels: bug
