Repository lensapp/lens, pull requests merged in 2021-02, with the labels that each got.

#2043 update extensions' package-lock files
  extensions/example-extension/package-lock.json
  extensions/license-menu-item/package-lock.json
  extensions/metrics-cluster-feature/package-lock.json
  extensions/node-menu/package-lock.json
  extensions/telemetry/package-lock.json
Labels: chore

#2053 Add deb & rpm packages
  integration/helpers/utils.ts
  package.json
Labels: area/ci, area/linux, enhancement

#2055 Add release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: area/ci

#2058 Fix release-drafter yaml error
  .github/workflows/release-drafter.yml
Labels: area/ci, bug

#2054 Fix: charts stripes alignment
  src/renderer/components/chart/bar-chart.tsx
  src/renderer/components/chart/zebra-stripes.plugin.ts
Labels: area/ui, bug

#1957 Initial command palette feature
  integration/__tests__/app.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/__tests__/command-palette.tests.ts
  integration/__tests__/workspace.tests.ts
  integration/helpers/minikube.ts
  integration/helpers/utils.ts
  package.json
  src/common/ipc.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/command-registry.ts
  src/extensions/renderer-api/components.ts
  src/main/cluster-manager.ts
  src/main/index.ts
  src/main/menu.ts
  src/renderer/components/+apps/apps.command.ts
  src/renderer/components/+apps/index.ts
  src/renderer/components/+cluster-settings/cluster-settings.command.ts
  src/renderer/components/+cluster-settings/components/cluster-workspace-setting.tsx
  src/renderer/components/+cluster-settings/index.ts
  src/renderer/components/+config/config.command.ts
  src/renderer/components/+config/index.ts
  src/renderer/components/+network/index.ts
  src/renderer/components/+network/network.command.ts
  src/renderer/components/+nodes/index.ts
  src/renderer/components/+nodes/node.command.ts
  src/renderer/components/+preferences/preferences.route.ts
  src/renderer/components/+workloads/index.ts
  src/renderer/components/+workloads/workloads.command.ts
  src/renderer/components/+workspaces/add-workspace.tsx
  src/renderer/components/+workspaces/edit-workspace.tsx
  src/renderer/components/+workspaces/index.ts
  src/renderer/components/+workspaces/remove-workspace.tsx
  src/renderer/components/+workspaces/workspace-menu.scss
  src/renderer/components/+workspaces/workspace-menu.tsx
  src/renderer/components/+workspaces/workspaces.route.ts
  src/renderer/components/+workspaces/workspaces.scss
  src/renderer/components/+workspaces/workspaces.tsx
  src/renderer/components/app.tsx
  src/renderer/components/cluster-manager/bottom-bar.tsx
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/components/command-palette/command-container.scss
  src/renderer/components/command-palette/command-container.tsx
  src/renderer/components/command-palette/command-dialog.tsx
  src/renderer/components/command-palette/index.ts
  src/renderer/components/dock/dock.tsx
  src/renderer/components/input/input.tsx
  src/renderer/lens-app.tsx
Labels: area/extension, area/ui, enhancement

#2061 Add exclude-labels to release-drafter
  .github/release-drafter.yml
Labels: area/ci, chore, skip-changelog

#2044 Add missing envFrom.secretRef property to IPodContainer
  src/renderer/api/endpoints/pods.api.ts
Labels: enhancement

#2020 Allow namespace to specified on role creation
  src/renderer/components/+user-management-roles/add-role-dialog.tsx
Labels: area/ui, enhancement

#1978 Allow for changing installation directory on Windows
  package.json
Labels: area/windows, enhancement

#2062 Fix release-drafter yaml error
  .github/release-drafter.yml
Labels: area/ci, bug, skip-changelog

#2059 Tray: change order of items, Open first
  src/main/tray.ts
Labels: area/ui, enhancement

#2066 Watch-api requests optimization
  src/main/__test__/cluster.test.ts
  src/main/cluster.ts
  src/renderer/api/kube-watch-api.ts
Labels: bug, enhancement

#2064 Release v4.1.0-alpha.2
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2068 Allow to quick select/deselect all namespaces in `NamespaceSelect`
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/item-object-list/page-filters.store.ts
Labels: bug, enhancement

#2081 Fix snap packaging
  .github/release-drafter.yml
  integration/helpers/utils.ts
  package.json
Labels: area/ci, area/linux, blocker, bug

#2063 KubeObjectStore & KubeWatchApi fixes and optimizations
  src/main/__test__/cluster.test.ts
  src/main/cluster.ts
  src/renderer/api/kube-watch-api.ts
  src/renderer/components/+apps-releases/release.store.ts
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/+events/kube-event-details.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/+nodes/node-details.tsx
  src/renderer/components/+user-management-roles-bindings/add-role-binding-dialog.tsx
  src/renderer/components/+workloads-cronjobs/cronjob-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-jobs/job-details.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/app.tsx
  src/renderer/components/dock/upgrade-chart.store.ts
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/kube-object.store.ts
Labels: blocker, enhancement

#1945 In-app survey extension
  extensions/survey/main.ts
  extensions/survey/package-lock.json
  extensions/survey/package.json
  extensions/survey/renderer.tsx
  extensions/survey/src/refiner-js.d.ts
  extensions/survey/src/survey-preference.tsx
  extensions/survey/src/survey-preferences-store.ts
  extensions/survey/src/survey.ts
  extensions/survey/tsconfig.json
  extensions/survey/webpack.config.js
  package.json
Labels: area/extension, blocker, enhancement

#1598 Convert StatusBarRegistration to use components field
  docs/extensions/capabilities/common-capabilities.md
  docs/extensions/guides/generator.md
  docs/extensions/guides/renderer-extension.md
  docs/extensions/testing-and-publishing/testing.md
  src/extensions/registries/status-bar-registry.ts
  src/renderer/components/cluster-manager/bottom-bar.test.tsx
  src/renderer/components/cluster-manager/bottom-bar.tsx
Labels: area/documentation, area/extension, bug

#1955 Add more log entries on start up
  src/common/utils/app-version.ts
  src/main/developer-tools.ts
  src/main/index.ts
  src/main/lens-proxy.ts
  src/main/router.ts
  src/main/routes/index.ts
  src/main/routes/version-route.ts
  src/main/window-manager.ts
Labels: enhancement

#2084 Fix: select all namespaces
  src/renderer/api/kube-watch-api.ts
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/+namespaces/namespace.store.ts
Labels: bug, enhancement

#2082 Fix BarChart component to return "No metrics" immediately if metrics data are missing
  src/renderer/components/chart/bar-chart.tsx
Labels: bug

#1973 add custom configuration for dependabot
  .dependabot/config.yml
Labels: chore, dependencies

#2094 Fix Lens icon size in macOS
  build/icons/512x512.png
  build/icons/512x512@2x.png
Labels: area/ui, bug

#2101 Release v4.1.0-beta.1
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2095 Refactor watches to use native k8s api
  package.json
  src/main/lens-proxy.ts
  src/main/router.ts
  src/main/routes/index.ts
  src/main/routes/watch-route.ts
  src/renderer/api/json-api.ts
  src/renderer/api/kube-api.ts
  src/renderer/api/kube-watch-api.ts
  src/renderer/components/+apps-releases/release.store.ts
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/+events/kube-event-details.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/+nodes/node-details.tsx
  src/renderer/components/+user-management-roles-bindings/add-role-binding-dialog.tsx
  src/renderer/components/+workloads-cronjobs/cronjob-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-jobs/job-details.tsx
  src/renderer/components/+workloads-overview/overview-statuses.tsx
  src/renderer/components/+workloads-overview/overview.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/app.tsx
  src/renderer/components/context.ts
  src/renderer/components/dock/upgrade-chart.store.ts
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/item-object-list/page-filters.store.ts
  src/renderer/components/kube-object/kube-object-list-layout.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/item.store.ts
  src/renderer/kube-object.store.ts
  yarn.lock
Labels: bug

#2105 Fix: export Dialog to extensions-api
  package.json
  src/renderer/components/dialog/dialog.tsx
  webpack.extensions.ts
Labels: area/extension, bug

#1941 Add auto-update notifications and confirmation
  docs/extensions/capabilities/color-reference.md
  src/common/ipc/__tests__/type-enforced-ipc.test.ts
  src/common/ipc/index.ts
  src/common/ipc/ipc.ts
  src/common/ipc/type-enforced-ipc.ts
  src/common/ipc/update-available/index.ts
  src/common/utils/delay.ts
  src/common/utils/index.ts
  src/main/app-updater.ts
  src/main/index.ts
  src/main/tray.ts
  src/main/window-manager.ts
  src/renderer/components/+workloads-overview/overview-statuses.tsx
  src/renderer/components/button/button.scss
  src/renderer/components/button/button.tsx
  src/renderer/components/notifications/notifications.scss
  src/renderer/components/notifications/notifications.store.tsx
  src/renderer/components/notifications/notifications.tsx
  src/renderer/ipc/index.tsx
  src/renderer/lens-app.tsx
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
  src/renderer/themes/theme-vars.scss
Labels: area/linux, area/macos, area/ui, area/windows, bug

#2091 Fix: saving apiManager store keys with string type
  src/renderer/api/api-manager.ts
Labels: area/extension, bug

#2106 Release v4.1.0-beta.2
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2108 Remove unnecessary subscribeStores from cluster overview
  src/renderer/components/+cluster/cluster-overview.tsx
Labels: bug

#2104 Fix: preventing namespace filter jumping scroll
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/+workloads-overview/overview-statuses.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
Labels: area/ui, blocker, bug

#2121 Don't show warning badge if cluster is offline
  src/renderer/components/cluster-icon/cluster-icon.tsx
Labels: area/ui, bug

#2113 Fix: compact-mode for Workloads overview -> Events
  src/renderer/api/endpoints/events.api.ts
  src/renderer/components/+events/events.tsx
  src/renderer/components/kube-object/kube-object-list-layout.tsx
Labels: bug

#2112 Improve kube watch error handling
  src/renderer/api/kube-api.ts
  src/renderer/api/kube-object.ts
  src/renderer/api/kube-watch-api.ts
  src/renderer/kube-object.store.ts
Labels: blocker, bug

#2120 Cleanup iframe when cluster is disconnected
  src/renderer/components/cluster-manager/lens-views.ts
Labels: bug

#2129 Release v4.1.0-rc.1
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2124 Fix: making error boundary layout responsive
  src/renderer/components/error-boundary/error-boundary.scss
  src/renderer/components/error-boundary/error-boundary.tsx
Labels: area/ui, bug

#2138 Fix accessible namespaces functionality under restrictive RBAC
  src/main/cluster.ts
  src/renderer/components/context.ts
Labels: blocker, bug

#2140 fix accessible namespaces reset on cluster disconnect
  src/main/cluster.ts
Labels: blocker, bug

#2136 Handle suspend/resume error from watch stream read
  package.json
  src/renderer/api/kube-api.ts
  src/renderer/utils/readableStream.ts
  yarn.lock
Labels: blocker, bug

#2142 Fix: list each namespace seperately if from accessibleNamespaces
  src/renderer/kube-object.store.ts
Labels: blocker, bug

#2145 Activate survey extension only in main renderer process
  extensions/survey/renderer.tsx
Labels: area/extension, blocker, bug

#2149 Fix events list default sort column
  src/renderer/components/+events/events.tsx
Labels: area/ui, bug

#2148 Fix tailCount renderering in removeItemsDialog
  src/renderer/components/item-object-list/item-list-layout.tsx
Labels: area/ui, bug

#2154 Release v4.1.0-rc.2
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2157 Register existing store with new apiBase when re-registering Kube API
  src/renderer/api/api-manager.ts
Labels: blocker, bug

#2163 Adding paddings to auto-update notification elements
  src/renderer/components/notifications/notifications.scss
  src/renderer/ipc/index.tsx
Labels: area/ui, bug

#2147 Listen for before-quit-for-update to allow will-quit to use default flow
  src/main/index.ts
Labels: blocker, bug

#2139 Fix: load releases for all namespaces at once
  src/renderer/components/+apps-releases/release.store.ts
Labels: bug

#2162 Release v4.1.0
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2143 return undefined instead of localhost from getClusterIdFromHost
  src/common/__tests__/cluster-store.test.ts
  src/common/cluster-store.ts
Labels: bug

#2165 Fix: keep highlighted table row during navigation in the details panel
  src/renderer/components/kube-object/kube-object-details.tsx
  src/renderer/navigation/page-param.ts
Labels: bug

#2174 Fix isLoadingAll within KubeObjectStore.loadItems
  src/renderer/kube-object.store.ts
Labels: bug

#2168 Windows: use SHELL for terminal if set
  src/main/shell-session.ts
Labels: area/windows, bug

#2161 Add test for re-registering store
  src/renderer/api/__tests__/api-manager.test.ts
Labels: area/tests, skip-changelog

#2175 Release v4.1.1
  package.json
  src/common/__tests__/cluster-store.test.ts
  src/common/cluster-store.ts
  src/main/shell-session.ts
  src/renderer/components/kube-object/kube-object-details.tsx
  src/renderer/kube-object.store.ts
  src/renderer/navigation/page-param.ts
  static/RELEASE_NOTES.md
  yarn.lock
Labels: skip-changelog

#2141 Fix: events sorting with compact=true is broken
  src/renderer/api/kube-object.ts
  src/renderer/components/+events/event.store.ts
  src/renderer/components/+events/events.tsx
  src/renderer/components/+workloads-deployments/deployment-scale-dialog.test.tsx
  src/renderer/components/+workloads-replicasets/replicaset-scale-dialog.test.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-scale-dialog.test.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/table/table.tsx
Labels: bug

#2181 Trigger quitAndInstall after update-downloaded event
  src/main/app-updater.ts
Labels: bug

#2183 Wait for cluster to be ready before loading iframe
  src/renderer/components/cluster-manager/lens-views.ts
Labels: bug

#2155 Fix Documentation: fix broken link in getting-started page
  docs/getting-started/README.md
Labels: area/documentation

#2190 Fix duplicate cluster iframes
  src/renderer/components/cluster-manager/lens-views.ts
Labels: bug

#2184 Bump master version to v4.2.0-alpha.0
  package.json
Labels: chore, skip-changelog

#2186 Release v4.1.2
  package.json
  src/main/app-updater.ts
  src/renderer/components/cluster-manager/lens-views.ts
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2182 Fix: proper sorting resources by age column
  src/renderer/api/endpoints/helm-releases.api.ts
  src/renderer/api/endpoints/persistent-volume.api.ts
  src/renderer/api/kube-object.ts
  src/renderer/components/+config-limit-ranges/limit-ranges.tsx
  src/renderer/components/+config-maps/config-maps.tsx
  src/renderer/components/+config-resource-quotas/resource-quotas.tsx
  src/renderer/components/+config-secrets/secrets.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/+namespaces/namespaces.tsx
  src/renderer/components/+network-endpoints/endpoints.tsx
  src/renderer/components/+network-ingresses/ingresses.tsx
  src/renderer/components/+network-policies/network-policies.tsx
  src/renderer/components/+network-services/services.tsx
  src/renderer/components/+nodes/nodes.tsx
  src/renderer/components/+pod-security-policies/pod-security-policies.tsx
  src/renderer/components/+storage-classes/storage-classes.tsx
  src/renderer/components/+storage-volume-claims/volume-claims.tsx
  src/renderer/components/+storage-volumes/volumes.tsx
  src/renderer/components/+user-management-roles-bindings/role-bindings.tsx
  src/renderer/components/+user-management-roles/roles.tsx
  src/renderer/components/+user-management-service-accounts/service-accounts.tsx
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-daemonsets/daemonsets.tsx
  src/renderer/components/+workloads-deployments/deployments.tsx
  src/renderer/components/+workloads-jobs/jobs.tsx
  src/renderer/components/+workloads-pods/pods.tsx
  src/renderer/components/+workloads-replicasets/replicasets.tsx
  src/renderer/components/+workloads-statefulsets/statefulsets.tsx
  src/renderer/components/chart/bar-chart.tsx
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.tsx
  src/renderer/utils/__tests__/formatDuration.test.ts
Labels: area/ui, bug

#2185 Fix: don't reset selected namespaces to defaults in case of "All namespaces" on page reload
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/+namespaces/namespace.store.ts
Labels: bug

#2203 fix RoleBindings Namespace and Bindings field not displaying the correct data
  src/renderer/components/+user-management-roles-bindings/role-bindings.tsx
Labels: area/ui, bug

#2201 Fix: allow scrolling in main-layout's content area
  src/renderer/components/layout/main-layout.scss
Labels: area/ui, bug

#2128 Fix auto update on quit with newer version
  src/main/app-updater.ts
Labels: area/linux, area/windows, bug

#2202 Fix Documentation: Using Helm Charts
  docs/helm/README.md
Labels: area/documentation, bug

#2204 Fix RoleBindingDetails not rendering the name of the role binding
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
  src/renderer/components/+apps-releases/release-details.tsx
  src/renderer/components/+apps-releases/release-menu.tsx
  src/renderer/components/+cluster/cluster-pie-charts.tsx
  src/renderer/components/+config-limit-ranges/limit-range-details.tsx
  src/renderer/components/+config-resource-quotas/add-quota-dialog.tsx
  src/renderer/components/+config-secrets/add-secret-dialog.tsx
  src/renderer/components/+config-secrets/secret-details.tsx
  src/renderer/components/+namespaces/add-namespace-dialog.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+network-policies/network-policy-details.tsx
  src/renderer/components/+network-services/service-details.tsx
  src/renderer/components/+network-services/service-port-component.tsx
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/+storage-classes/storage-class-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+user-management-roles-bindings/add-role-binding-dialog.tsx
  src/renderer/components/+user-management-roles-bindings/role-binding-details.tsx
  src/renderer/components/+user-management-roles/add-role-dialog.tsx
  src/renderer/components/+user-management-service-accounts/create-service-account-dialog.tsx
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-deployments/deployments.tsx
  src/renderer/components/+workloads-pods/pod-container-port.tsx
  src/renderer/components/+workloads-replicasets/replicasets.tsx
  src/renderer/components/+workloads-statefulsets/statefulsets.tsx
  src/renderer/components/dock/create-resource.tsx
  src/renderer/components/dock/dock-tab.tsx
  src/renderer/components/dock/edit-resource.tsx
  src/renderer/components/dock/install-chart.tsx
  src/renderer/components/dock/log-search.tsx
  src/renderer/components/dock/upgrade-chart.tsx
  src/renderer/components/error-boundary/error-boundary.tsx
  src/renderer/components/menu/menu-actions.tsx
Labels: area/ui, bug

#2167 Display environment variables coming from secret in pod details
  src/renderer/components/+workloads-pods/pod-container-env.tsx
Labels: bug

#2158 Fix: deprecated helm chart filtering
  src/main/helm/__mocks__/helm-chart-manager.ts
  src/main/helm/__tests__/helm-service.test.ts
  src/main/helm/helm-chart-manager.ts
  src/main/helm/helm-service.ts
  src/renderer/api/endpoints/helm-charts.api.ts
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
Labels: bug

#2160 Add persistent volumes info to storage class submenu
  src/renderer/api/endpoints/persistent-volume.api.ts
  src/renderer/components/+storage-classes/storage-class-details.tsx
  src/renderer/components/+storage-classes/storage-class.store.ts
  src/renderer/components/+storage-volumes/volume-details-list.scss
  src/renderer/components/+storage-volumes/volume-details-list.tsx
  src/renderer/components/+storage-volumes/volumes.scss
  src/renderer/components/+storage-volumes/volumes.store.ts
Labels: area/ui, enhancement

#2211 StatusBarRegistration's component field must be optional for backwards compatability
  src/extensions/registries/status-bar-registry.ts
Labels: area/extension, blocker, bug

#2217 Fix loading all namespaces for users with limited cluster access
  src/renderer/api/kube-api.ts
  src/renderer/components/+namespaces/namespace.store.ts
Labels: bug

#2218 Release v4.1.3
  docs/getting-started/README.md
  docs/helm/README.md
  package.json
  src/extensions/registries/status-bar-registry.ts
  src/main/app-updater.ts
  src/main/helm/__mocks__/helm-chart-manager.ts
  src/main/helm/__tests__/helm-service.test.ts
  src/main/helm/helm-chart-manager.ts
  src/main/helm/helm-service.ts
  src/renderer/api/endpoints/helm-charts.api.ts
  src/renderer/api/kube-api.ts
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
  src/renderer/components/+apps-releases/release-details.tsx
  src/renderer/components/+apps-releases/release-menu.tsx
  src/renderer/components/+cluster/cluster-pie-charts.tsx
  src/renderer/components/+config-limit-ranges/limit-range-details.tsx
  src/renderer/components/+config-resource-quotas/add-quota-dialog.tsx
  src/renderer/components/+config-secrets/add-secret-dialog.tsx
  src/renderer/components/+config-secrets/secret-details.tsx
  src/renderer/components/+namespaces/add-namespace-dialog.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/+network-policies/network-policy-details.tsx
  src/renderer/components/+network-services/service-details.tsx
  src/renderer/components/+network-services/service-port-component.tsx
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/+storage-classes/storage-class-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+user-management-roles-bindings/add-role-binding-dialog.tsx
  src/renderer/components/+user-management-roles-bindings/role-binding-details.tsx
  src/renderer/components/+user-management-roles-bindings/role-bindings.tsx
  src/renderer/components/+user-management-roles/add-role-dialog.tsx
  src/renderer/components/+user-management-service-accounts/create-service-account-dialog.tsx
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-deployments/deployments.tsx
  src/renderer/components/+workloads-pods/pod-container-env.tsx
  src/renderer/components/+workloads-pods/pod-container-port.tsx
  src/renderer/components/+workloads-replicasets/replicasets.tsx
  src/renderer/components/+workloads-statefulsets/statefulsets.tsx
  src/renderer/components/dock/create-resource.tsx
  src/renderer/components/dock/dock-tab.tsx
  src/renderer/components/dock/edit-resource.tsx
  src/renderer/components/dock/install-chart.tsx
  src/renderer/components/dock/log-search.tsx
  src/renderer/components/dock/upgrade-chart.tsx
  src/renderer/components/error-boundary/error-boundary.tsx
  src/renderer/components/layout/main-layout.scss
  src/renderer/components/menu/menu-actions.tsx
  static/RELEASE_NOTES.md
Labels: skip-changelog

#1949 Add lens:// protocol handling with a routing mechanism
  Makefile
  docs/extensions/guides/README.md
  docs/extensions/guides/images/routing-diag.png
  docs/extensions/guides/protocol-handlers.md
  docs/getting-started/README.md
  package.json
  scripts/test.sh
  src/common/ipc/ipc.ts
  src/common/protocol-handler/error.ts
  src/common/protocol-handler/index.ts
  src/common/protocol-handler/router.ts
  src/common/utils/delay.ts
  src/common/utils/index.ts
  src/common/utils/type-narrowing.ts
  src/extensions/extension-loader.ts
  src/extensions/extensions-store.ts
  src/extensions/interfaces/registrations.ts
  src/extensions/lens-extension.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/protocol-handler-registry.ts
  src/main/app-updater.ts
  src/main/index.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/main/protocol-handler/index.ts
  src/main/protocol-handler/router.ts
  src/main/window-manager.ts
  src/renderer/lens-app.tsx
  src/renderer/navigation/index.ts
  src/renderer/navigation/protocol-handlers.ts
  src/renderer/protocol-handler/index.ts
  src/renderer/protocol-handler/router.ts
  src/renderer/utils/index.ts
  yarn.lock
Labels: area/documentation, area/linux, area/macos, area/windows, enhancement

#2226 Extract chart version ignoring numbers in chart name
  src/renderer/api/endpoints/helm-releases.api.ts
Labels: area/helm, bug

#2229 Flush response headers always when proxy gets a response
  src/main/lens-proxy.ts
Labels: bug

#2132 Fix(rbac): pdp should have policy group
  src/common/rbac.ts
Labels: bug

#2198 Pass Lens wslenvs to terminal session on Windows
  src/main/shell-session.ts
Labels: area/windows, bug

#2234 Fix protocol log line grammer
  src/main/index.ts
Labels: chore
