Repository lensapp/lens, pull requests merged in 2021-04, with the labels that each got.

#2421 Fix StorageHelper.get() returning null after clearing
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/dock/dock-tab.store.ts
  src/renderer/hooks/useStorage.ts
  src/renderer/utils/__tests__/storageHelper.test.ts
  src/renderer/utils/createStorage.ts
  src/renderer/utils/storageHelper.ts
Labels: blocker, bug

#2001 Fix lens node shell
  src/main/node-shell-session.ts
Labels: bug

#2401 Use a POST with a form body when querying Prometheus.
  src/main/cluster.ts
Labels: bug

#2353 Save sorting order when changing view
  src/renderer/components/+cluster/cluster-issues.tsx
  src/renderer/components/+pod-security-policies/pod-security-policies.tsx
  src/renderer/components/+storage-volumes/volume-details-list.tsx
  src/renderer/components/+workloads-pods/pod-details-list.tsx
  src/renderer/components/+workloads-pods/pod-tolerations.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/table/table.storage.ts
  src/renderer/components/table/table.tsx
Labels: area/ui, bug

#2432 release v4.2.0
  SECURITY.md
  package.json
  src/main/__test__/router.test.ts
  src/main/lens-proxy.ts
  src/main/router.ts
  src/renderer/components/ace-editor/ace-editor.tsx
  src/renderer/components/layout/sidebar-item.tsx
  src/renderer/components/layout/sidebar.tsx
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2446 Preferences page redesign
  extensions/survey/renderer.tsx
  extensions/telemetry/renderer.tsx
  integration/__tests__/app.tests.ts
  integration/helpers/utils.ts
  src/extensions/registries/app-preference-registry.ts
  src/renderer/components/+landing-page/landing-page.scss
  src/renderer/components/+preferences/helm-charts.scss
  src/renderer/components/+preferences/helm-charts.tsx
  src/renderer/components/+preferences/kubectl-binaries.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/app.scss
  src/renderer/components/button/button.scss
  src/renderer/components/input/input.scss
  src/renderer/components/layout/page-layout.scss
  src/renderer/components/layout/page-layout.tsx
  src/renderer/components/select/select.scss
  src/renderer/components/select/select.tsx
  src/renderer/components/switch/form-switcher.tsx
  src/renderer/components/switch/index.ts
  src/renderer/components/switch/switcher.tsx
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
  src/renderer/themes/theme-vars.scss
Labels: area/ui, enhancement

#2456 Use whole page for workspace overview
  src/renderer/components/+landing-page/workspace-overview.scss
Labels: area/ui, bug

#2464 add codeowners file
  .github/CODEOWNERS
Labels: chore

#2468 fix node shell failure to open (#2467)
  src/main/node-shell-session.ts
Labels: bug

#2471 Export sub-title component to extensions API
  src/extensions/renderer-api/components.ts
Labels: area/extension, enhancement

#2477 release v4.2.1
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2496 Style Catalog sidebar to look similar as dashboard one
  src/renderer/components/+catalog/catalog.scss
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, enhancement

#2472 Electron 9.4.4
  .yarnrc
  package.json
  yarn.lock
Labels: area/security, bug

#2495 Improve CatalogEntityRegistry types & add tests
  src/common/__tests__/catalog-entity-registry.test.ts
  src/common/catalog-entities/web-link.ts
  src/common/catalog-entity-registry.ts
  src/extensions/lens-main-extension.ts
  src/main/cluster-manager.ts
Labels: area/extension, area/tests, enhancement

#2469 cleanup shell sessions
  src/main/lens-proxy.ts
  src/main/node-shell-session.ts
  src/main/shell-session.ts
  src/main/shell-session/index.ts
  src/main/shell-session/local-shell-session.ts
  src/main/shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
Labels: chore

#2501 Broadcast failure to list namespaces less frequently
  src/main/cluster.ts
Labels: bug, merge/master

#2509 Test using GH Actions
  .azure-pipelines.yml
  .github/workflows/test.yml
Labels: area/ci

#2513 Publish binaries to s3 bucket
  package.json
Labels: area/ci

#2514 Release v5.0.0-alpha.1
  .azure-pipelines.yml
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2516 modified kubeconfig manager test to avoid intermittent ENXIO error
  src/main/__test__/kubeconfig-manager.test.ts
Labels: area/ci, area/tests, bug

#2435 Add support for installing extensions by name
  src/common/protocol-handler/router.ts
  src/common/utils/downloadFile.ts
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/confirm-dialog/confirm-dialog.tsx
  src/renderer/components/input/input.tsx
  src/renderer/components/input/input_validators.ts
  src/renderer/protocol-handler/app-handlers.ts
Labels: enhancement

#2517 Cache node_modules on GH actions
  .github/workflows/test.yml
Labels: area/ci, chore

#2497 Allow register actions to "add to catalog" button
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/minikube.ts
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog-entity.ts
  src/renderer/api/catalog-entity.ts
  src/renderer/components/+catalog/catalog-add-button.scss
  src/renderer/components/+catalog/catalog-add-button.tsx
  src/renderer/components/+catalog/catalog-entity.store.ts
  src/renderer/components/+catalog/catalog.tsx
Labels: area/extension, area/ui, enhancement

#2377 Fix Extension Docs
  docs/extensions/capabilities/common-capabilities.md
  docs/extensions/capabilities/styling.md
  docs/extensions/get-started/anatomy.md
  docs/extensions/get-started/overview.md
  docs/extensions/get-started/wrapping-up.md
  docs/extensions/get-started/your-first-extension.md
  docs/extensions/guides/README.md
  docs/extensions/guides/generator.md
  docs/extensions/guides/kube-object-list-layout.md
  docs/extensions/guides/main-extension.md
  docs/extensions/guides/renderer-extension.md
  docs/extensions/guides/stores.md
  docs/extensions/testing-and-publishing/testing.md
  mkdocs.yml
Labels: area/documentation, merge/master

#2522 Use gh actions for build status
  README.md
Labels: chore

#2526 Fix catalog sidebar paddings
  src/renderer/components/+catalog/catalog.scss
Labels: area/ui, bug

#2500 Fix CRD versions not being provided
  src/renderer/api/__tests__/crd.test.ts
  src/renderer/api/endpoints/crd.api.ts
Labels: blocker, bug, merge/master

#2355 Fix being able to view clusters outside the current workspace
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/workspace-store.test.ts
  src/common/__tests__/workspace.test.ts
  src/common/cluster-store.ts
  src/common/workspace-store.ts
  src/extensions/stores/cluster-store.ts
  src/extensions/stores/workspace-store.ts
  src/main/cluster.ts
  src/main/index.ts
  src/migrations/workspace-store/4.2.0-beta.1.ts
  src/migrations/workspace-store/index.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+cluster-settings/cluster-settings.command.ts
  src/renderer/components/+cluster-settings/cluster-settings.tsx
  src/renderer/components/+cluster/cluster-overview.tsx
  src/renderer/components/+landing-page/landing-page.tsx
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+nodes/node-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-pods/pod-details-container.tsx
  src/renderer/components/+workloads-pods/pod-details.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/+workspaces/add-workspace.tsx
  src/renderer/components/+workspaces/workspaces.tsx
  src/renderer/components/cluster-icon/cluster-icon.tsx
  src/renderer/components/cluster-manager/cluster-actions.tsx
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/cluster-manager/clusters-menu.tsx
  src/renderer/components/command-palette/command-container.tsx
  src/renderer/components/command-palette/command-dialog.tsx
  src/renderer/ipc/index.tsx
Labels: blocker, bug

#2414 fix: proper sorting resources by age column (#2182 followup)
  src/renderer/components/+cluster/cluster-issues.tsx
Labels: blocker, bug, merge/master

#2521 Exporting SearchInput component to extensions
  src/extensions/renderer-api/components.ts
Labels: area/extension, enhancement

#2532 Test also push to branches on gh actions
  .github/workflows/test.yml
Labels: area/ci, chore

#2499 Allow to control catalog entity menu item visibility based on source
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog-entity.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/hotbar/hotbar-icon.tsx
Labels: area/extension, enhancement

#2327 YAML Templates in Create Resource dock tab
  package.json
  src/renderer/components/dock/create-resource.scss
  src/renderer/components/dock/create-resource.store.ts
  src/renderer/components/dock/create-resource.tsx
  templates/create-resource/ClusterRole.yaml
  templates/create-resource/ClusterRoleBinding.yaml
  templates/create-resource/ConfigMap.yaml
  templates/create-resource/CronJob.yaml
  templates/create-resource/DeamonSet.yaml
  templates/create-resource/Deployment.yaml
  templates/create-resource/Ingress.yaml
  templates/create-resource/Job.yaml
  templates/create-resource/NetworkPolicy.yaml
  templates/create-resource/PersistentVolume.yaml
  templates/create-resource/PersistentVolumeClaim.yaml
  templates/create-resource/ReplicaSet.yaml
  templates/create-resource/ReplicationController.yaml
  templates/create-resource/Role.yaml
  templates/create-resource/RoleBinding.yaml
  templates/create-resource/Secret.yaml
  templates/create-resource/Service.yaml
  templates/create-resource/StatefulSet.yaml
  yarn.lock
Labels: area/ui, enhancement

#2533 Retry yarn/npm install steps on gh actions
  .github/workflows/test.yml
  Makefile
Labels: area/ci

#2515 Fix releases not reloading when selecting namespaces
  integration/helpers/utils.ts
  src/renderer/components/+apps-helm-charts/helm-chart.store.ts
  src/renderer/components/+apps-releases/release.store.ts
  src/renderer/components/+apps-releases/releases.tsx
  src/renderer/components/+landing-page/workspace-cluster.store.ts
  src/renderer/components/context.ts
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/item.store.ts
  src/renderer/kube-object.store.ts
Labels: area/ui, blocker, bug, merge/master

#2417 Refactor StorageHelper to be clearer in its constructor
  src/renderer/utils/__tests__/storageHelper.test.ts
  src/renderer/utils/storageHelper.ts
Labels: chore, merge/master

#2527 Move catalog to top-level module in extension api
  extensions/metrics-cluster-feature/renderer.tsx
  extensions/metrics-cluster-feature/src/metrics-feature.ts
  extensions/telemetry/src/tracker.ts
  src/extensions/cluster-feature.ts
  src/extensions/core-api/catalog.ts
  src/extensions/core-api/index.ts
  src/extensions/core-api/stores.ts
Labels: area/extension, enhancement

#2545 Workaround broken reverse name lookup on gh actions
  .github/workflows/test.yml
Labels: area/ci

#2538 release v4.2.2
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#1078 Pre-Validate kubeconfig before making available in Lens
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/kube-helpers.test.ts
  src/common/kube-helpers.ts
  src/common/user-store.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: area/ui, bug, merge/master

#2428 display close button on deleted kube details page
  src/renderer/components/kube-object/kube-object-list-layout.tsx
  src/renderer/components/kube-object/kube-object-menu.tsx
Labels: bug

#2268 Lens should point to the release docs
  src/common/vars.ts
Labels: blocker, bug, merge/master

#2569 Fix how integration tests activate adding a cluster via SpeedDial
  integration/helpers/minikube.ts
Labels: area/ci, area/tests

#2551 Fix initial hotbar not showing
  src/common/__tests__/hotbar-store.test.ts
  src/common/hotbar-store.ts
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: area/ui, bug

#2344 Fix custom resource loading spinner appears above extensions' cluster menus
  src/renderer/components/layout/sidebar.tsx
  src/renderer/components/spinner/spinner.scss
  src/renderer/components/spinner/spinner.tsx
Labels: area/ui, blocker, bug, merge/master

#2298 Conditionally render status icon for kube meta
  src/extensions/registries/kube-object-status-registry.ts
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.tsx
  src/renderer/components/kube-object/kube-object-meta.tsx
Labels: blocker, chore, merge/master

#2565 Fix: HPA's not sortable by age
  src/renderer/components/+config-autoscalers/hpa.tsx
Labels: bug, merge/master

#2523 Add ability to configure the locale timezone
  package.json
  src/common/user-store.ts
  src/renderer/components/+events/event-details.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/+workloads-pods/pod-details-container.tsx
  src/renderer/components/dock/log-list.tsx
  src/renderer/components/dock/log.store.ts
  src/renderer/components/kube-object/kube-object-meta.tsx
  src/renderer/components/locale-date/index.ts
  src/renderer/components/locale-date/locale-date.tsx
  yarn.lock
Labels: area/ui, enhancement

#2466 Increase npm version to 7.9
  package.json
  yarn.lock
Labels: chore

#2542 Don't bundle extension with eula on default build
  .azure-pipelines.yml
  .bundled-extensions.json
  .github/workflows/test.yml
  LICENSE
  Makefile
  README.md
  extensions/example-extension/.gitignore
  extensions/example-extension/README.md
  extensions/example-extension/main.ts
  extensions/example-extension/package-lock.json
  extensions/example-extension/package.json
  extensions/example-extension/page.tsx
  extensions/example-extension/renderer.tsx
  extensions/example-extension/tsconfig.json
  extensions/example-extension/webpack.config.js
  extensions/license-menu-item/main.ts
  extensions/license-menu-item/package-lock.json
  extensions/license-menu-item/package.json
  extensions/license-menu-item/tsconfig.json
  extensions/license-menu-item/webpack.config.ts
  extensions/survey/main.ts
  extensions/survey/package-lock.json
  extensions/survey/package.json
  extensions/survey/renderer.tsx
  extensions/survey/src/refiner-js.d.ts
  extensions/survey/src/survey-preference.tsx
  extensions/survey/src/survey-preferences-store.ts
  extensions/survey/src/survey.ts
  extensions/survey/tsconfig.json
  extensions/survey/webpack.config.js
  extensions/telemetry/main.ts
  extensions/telemetry/package-lock.json
  extensions/telemetry/package.json
  extensions/telemetry/renderer.tsx
  extensions/telemetry/src/telemetry-preference.tsx
  extensions/telemetry/src/telemetry-preferences-store.ts
  extensions/telemetry/src/tracker.ts
  extensions/telemetry/tsconfig.json
  extensions/telemetry/webpack.config.js
  integration/__tests__/app.tests.ts
  integration/helpers/utils.ts
  package.json
  src/common/utils/app-version.ts
  src/extensions/extension-discovery.ts
  webpack.renderer.ts
Labels: area/ci, chore

#2264 Refactor helm-release.api to use free functions instead of an object
  src/renderer/api/endpoints/helm-releases.api.ts
  src/renderer/components/+apps-releases/release-details.tsx
  src/renderer/components/+apps-releases/release-rollback-dialog.tsx
  src/renderer/components/+apps-releases/release.store.ts
  src/renderer/components/dock/upgrade-chart.store.ts
Labels: chore

#1862 Add support for viewing 'User-supplied values' of helm release
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-service.ts
  src/main/routes/helm-route.ts
  src/renderer/api/endpoints/helm-releases.api.ts
  src/renderer/components/+apps-releases/release-details.tsx
  src/renderer/components/dock/upgrade-chart.store.ts
Labels: enhancement

#2575 Display a pod as terminating even if it isn't running
  src/renderer/api/endpoints/pods.api.ts
Labels: area/ui, bug

#2265 Refactor helm-chart.api and improve kube validation and error handling
  src/common/utils/type-narrowing.ts
  src/renderer/api/__tests__/kube-object.test.ts
  src/renderer/api/endpoints/helm-charts.api.ts
  src/renderer/api/json-api.ts
  src/renderer/api/kube-api.ts
  src/renderer/api/kube-json-api.ts
  src/renderer/api/kube-object.ts
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
  src/renderer/components/+apps-helm-charts/helm-chart.store.ts
  src/renderer/components/dock/install-chart.store.ts
  src/renderer/utils/cancelableFetch.ts
Labels: area/documentation, chore, merge/master

#2582 Show openlens on splash
  static/splash.html
Labels: area/ui, enhancement

#2583 Revert "Increase npm version to 7.9"
  package.json
  yarn.lock
Labels: blocker, bug

#2584 Fix chart upgrade screen by coercing the chart version to semver
  src/renderer/components/+apps-helm-charts/helm-chart.store.ts
Labels: area/helm, bug

#2580 Use productName from package.json
  package.json
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/vars.ts
  src/extensions/npm/extensions/package.json
  src/main/app-updater.ts
  src/main/index.ts
  src/main/menu.ts
  src/main/tray.ts
  src/renderer/ipc/invalid-kubeconfig-handler.tsx
  src/renderer/template.html
Labels: bug

#2554 Reserve cluster proxy port just in time
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/cluster.ts
  src/main/kubeconfig-manager.ts
Labels: bug

#2585 Improve documentation of Singleton functions, change to createInstance
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/hotbar-store.test.ts
  src/common/__tests__/user-store.test.ts
  src/common/utils/singleton.ts
  src/extensions/__tests__/extension-discovery.test.ts
  src/extensions/__tests__/extension-loader.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/index.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/dock/__test__/log-resource-selector.test.tsx
  src/renderer/components/layout/__test__/main-layout-header.test.tsx
  src/renderer/lens-app.tsx
  src/renderer/utils/__tests__/storageHelper.test.ts
Labels: area/documentation, chore

#2552 Hotbar command palette + switching
  package.json
  src/common/__tests__/hotbar-store.test.ts
  src/common/hotbar-store.ts
  src/migrations/hotbar-store/5.0.0-alpha.0.ts
  src/migrations/hotbar-store/5.0.0-alpha.2.ts
  src/migrations/hotbar-store/index.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/hotbar/hotbar-add-command.tsx
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/components/hotbar/hotbar-menu.tsx
  src/renderer/components/hotbar/hotbar-remove-command.tsx
  src/renderer/components/hotbar/hotbar-switch-command.tsx
  src/renderer/components/hotbar/hotbar.commands.tsx
Labels: area/ui, enhancement

#2589 Fix HotbarStore merge conflict
  src/common/__tests__/hotbar-store.test.ts
Labels: blocker, bug

#2544 Release v5.0.0-alpha.2
  Makefile
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2588 Allow nodemon restart via rs<enter>
  package.json
Labels: chore

#2257 add doc describing ItemStore.sortItems
  src/renderer/item.store.ts
Labels: area/documentation, chore

#2210 Refactor AddRemoveButtons's renderButtons method to be just a filter map
  src/renderer/components/add-remove-buttons/add-remove-buttons.tsx
Labels: chore

#2595 fix cleanup in createStorage racing the creation of ClusterStore
  src/renderer/utils/createStorage.ts
Labels: bug

#2591 Initialize HelmRepoManager on demand
  src/main/helm/helm-repo-manager.ts
  src/main/helm/helm-service.ts
  src/main/index.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/+preferences/helm-charts.tsx
Labels: bug

#2606 Add icon to catalog category
  src/common/catalog-entities/icons/kubernetes.svg
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog-entities/web-link.ts
  src/common/catalog-entity.ts
  src/renderer/api/catalog-category-registry.ts
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/icon/icon.tsx
Labels: area/extension, area/ui, enhancement

#2578 Makefile should use in-tree npm binary
  Makefile
Labels: chore

#2600 Enable search on catalog
  src/renderer/components/+catalog/catalog-entity.store.ts
  src/renderer/components/+catalog/catalog.tsx
Labels: area/ui, enhancement

#2596 Allow to define entity setting priority
  src/extensions/registries/entity-setting-registry.ts
Labels: area/extension, enhancement

#2581 Remove downloads from release drafter template
  .github/release-drafter.yml
Labels: area/ci, chore

#2608 Use generated background color for hotbar icons
  package.json
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
  yarn.lock
Labels: area/ui, enhancement

#2604 Add tooltip to hotbar index
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: area/ui, enhancement

#2611 Fix: don't assign to priority in getItemsForKind
  src/extensions/registries/entity-setting-registry.ts
  src/extensions/registries/kube-object-detail-registry.ts
Labels: bug

#2612 Switch CatalogEntity and CatalogCategory abstract classes
  src/common/__tests__/catalog-entity-registry.test.ts
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog-entities/web-link.ts
  src/common/catalog-entity.ts
  src/common/catalog/catalog-category-registry.ts
  src/common/catalog/catalog-entity-registry.ts
  src/common/catalog/catalog-entity.ts
  src/common/catalog/index.ts
  src/extensions/core-api/catalog.ts
  src/extensions/interfaces/catalog.ts
  src/extensions/lens-main-extension.ts
  src/extensions/registries/command-registry.ts
  src/extensions/registries/entity-setting-registry.ts
  src/main/catalog-pusher.ts
  src/main/cluster-manager.ts
  src/main/index.ts
  src/renderer/api/__tests__/catalog-entity-registry.test.ts
  src/renderer/api/catalog-category-registry.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/api/catalog-entity.ts
  src/renderer/components/+catalog/catalog-entity.store.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/hotbar/hotbar-icon.tsx
Labels: blocker, chore

#2610 Support non-ascii characters in entity names
  package.json
  src/common/utils/index.ts
  src/common/utils/iter.ts
  src/renderer/components/hotbar/hotbar-icon.tsx
  yarn.lock
Labels: enhancement

#2618 Disable webpack minimize
  extensions/kube-object-event-status/webpack.config.js
  extensions/metrics-cluster-feature/webpack.config.js
  extensions/node-menu/webpack.config.js
  extensions/pod-menu/webpack.config.js
  package.json
  webpack.renderer.ts
  yarn.lock
Labels: chore

#2566 Fix: logs data disapearing causing crashes
  src/renderer/components/dock/log-controls.tsx
  src/renderer/components/dock/logs.tsx
Labels: bug, merge/master

#2623 Release v5.0.0-alpha.3
  .azure-pipelines.yml
  Makefile
  build/set_build_version.ts
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2619 Helm 3.5.4
  package.json
Labels: enhancement

#2627 release v4.2.3
  package.json
  static/RELEASE_NOTES.md
Labels: skip-changelog

#2628 Cherry-pick from 4.2.3
  src/common/__tests__/cluster-store.test.ts
  src/common/base-store.ts
  src/common/cluster-store.ts
  src/common/ipc/ipc.ts
  src/common/protocol-handler/router.ts
  src/common/utils/disposer.ts
  src/common/utils/downloadFile.ts
  src/common/utils/index.ts
  src/common/utils/type-narrowing.ts
  src/common/vars.ts
  src/extensions/__tests__/extension-discovery.test.ts
  src/extensions/extension-discovery.ts
  src/extensions/extension-loader.ts
  src/extensions/registries/kube-object-status-registry.ts
  src/main/logger.ts
  src/renderer/api/__tests__/kube-object.test.ts
  src/renderer/api/endpoints/helm-charts.api.ts
  src/renderer/api/json-api.ts
  src/renderer/api/kube-api.ts
  src/renderer/api/kube-json-api.ts
  src/renderer/api/kube-object.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
  src/renderer/components/+apps-helm-charts/helm-chart.store.ts
  src/renderer/components/+config-autoscalers/hpa.tsx
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/+extensions/extension-install.store.ts
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/button/button.tsx
  src/renderer/components/confirm-dialog/confirm-dialog.tsx
  src/renderer/components/dock/install-chart.store.ts
  src/renderer/components/dock/log-controls.tsx
  src/renderer/components/dock/logs.tsx
  src/renderer/components/input/input.tsx
  src/renderer/components/input/input_validators.ts
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.tsx
  src/renderer/components/kube-object/kube-object-meta.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/components/spinner/spinner.scss
  src/renderer/components/spinner/spinner.tsx
  src/renderer/protocol-handler/app-handlers.ts
  src/renderer/utils/cancelableFetch.ts
Labels: chore, skip-changelog

#2637 Extensible welcome page
  integration/__tests__/app.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/__tests__/command-palette.tests.ts
  integration/helpers/utils.ts
  src/extensions/extension-loader.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/index.ts
  src/extensions/registries/welcome-menu-registry.ts
  src/main/menu.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+welcome/index.ts
  src/renderer/components/+welcome/welcome.route.ts
  src/renderer/components/+welcome/welcome.scss
  src/renderer/components/+welcome/welcome.tsx
  src/renderer/components/+whats-new/index.tsx
  src/renderer/components/+whats-new/whats-new.route.ts
  src/renderer/components/+whats-new/whats-new.scss
  src/renderer/components/+whats-new/whats-new.tsx
  src/renderer/components/cluster-manager/bottom-bar.tsx
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/lens-app.tsx
  static/RELEASE_NOTES.md
Labels: area/extension, area/ui, enhancement

#2638 Hotbar visual improvements
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/hotbar-store.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: area/ui, enhancement

#2631 Asyncronously recompute the placement of an open <Menu>
  src/renderer/components/menu/menu.tsx
Labels: area/ui, bug

#2635 Show cluster metrics settings always
  src/renderer/components/cluster-settings/cluster-settings.tsx
Labels: bug

#2639 Fixing CatalogAddButton
  src/renderer/components/+catalog/catalog-add-button.scss
  src/renderer/components/+catalog/catalog-add-button.tsx
Labels: area/ui, bug

#2640 Fix zsh zdotdir
  src/main/shell-session/shell-session.ts
Labels: bug

#2587 Flatten user preferences in user store
  src/common/__tests__/user-store.test.ts
  src/common/request.ts
  src/common/user-store.ts
  src/common/utils/index.ts
  src/common/utils/toggle-set.ts
  src/main/kubectl.ts
  src/main/shell-session/local-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/migrations/user-store/5.0.0-alpha.3.ts
  src/migrations/user-store/index.ts
  src/renderer/components/+preferences/kubectl-binaries.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/dock/log-list.tsx
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/locale-date/locale-date.tsx
  src/renderer/theme.store.ts
Labels: chore

#2642 Command palette restyling
  src/renderer/components/animate/animate.scss
  src/renderer/components/command-palette/command-container.scss
  src/renderer/components/command-palette/command-container.tsx
  src/renderer/components/command-palette/command-dialog.tsx
  src/renderer/components/hotbar/hotbar-remove-command.tsx
  src/renderer/components/hotbar/hotbar-switch-command.tsx
Labels: area/ui, enhancement

#2647 Azure fix for 5.0.0-alpha.4
  .azure-pipelines.yml
Labels: area/ci, skip-changelog

#2645 release v5.0.0-alpha.4
  .azure-pipelines.yml
  package.json
Labels: skip-changelog

#2651 Hotbar icon status led
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
Labels: area/ui, enhancement

#2660 release v5.0.0-beta.1
  package.json
Labels: skip-changelog

#2654 Refactor / fix cluster view visibility
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/cluster-status.tsx
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/cluster-manager/lens-views.ts
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: area/ui, bug

#2655 fix(renderer-log): multiple spaces merge into one
  src/renderer/components/dock/log-list.scss
Labels: area/logs, area/ui

#2622 Electron-updater 4.3.8
  yarn.lock
Labels: bug

#2661 Ignore failures due to files in bundled folder
  src/extensions/extension-discovery.ts
Labels: chore

#2665 Set product name to window title
  src/main/window-manager.ts
  src/renderer/template.html
Labels: area/ui, bug

#2669 Show entity source on tooltip + use it for color
  src/renderer/components/hotbar/hotbar-icon.tsx
Labels: area/ui, enhancement

#2667 Removing add/delete empty cells feature from hotbar
  src/common/hotbar-store.ts
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: area/ui, enhancement

#2668 Fix hotbar icon kind on light theme
  src/renderer/components/hotbar/hotbar-icon.scss
Labels: area/ui, bug

#2644 fix getNodeWarningConditions
  src/common/__tests__/kube-helpers.test.ts
  src/common/kube-helpers.ts
Labels: bug

#2657 Fix display name on accessible namespaces notification
  src/renderer/ipc/index.tsx
Labels: bug

#2266 Fix KubeObjectStore not correctly tracking loading of namespaces
  src/common/utils/index.ts
  src/common/utils/reject-promise.ts
  src/renderer/api/kube-api.ts
  src/renderer/kube-object.store.ts
Labels: area/ui, bug

#2675 release v5.0.0-beta.2
  Makefile
  package.json
Labels: skip-changelog

#2567 Add the ability to sync kube config files
  integration/helpers/minikube.ts
  package.json
  src/common/__tests__/catalog-entity-registry.test.ts
  src/common/__tests__/kube-helpers.test.ts
  src/common/__tests__/user-store.test.ts
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog/catalog-entity-registry.ts
  src/common/catalog/catalog-entity.ts
  src/common/cluster-store.ts
  src/common/kube-helpers.ts
  src/common/user-store.ts
  src/common/utils/extended-map.ts
  src/common/utils/index.ts
  src/common/utils/iter.ts
  src/extensions/lens-main-extension.ts
  src/main/catalog-pusher.ts
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/catalog-sources/index.ts
  src/main/catalog-sources/kubeconfig-sync.ts
  src/main/cluster-manager.ts
  src/main/cluster.ts
  src/main/index.ts
  src/renderer/api/__tests__/catalog-entity-registry.test.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+catalog/catalog.scss
  src/renderer/components/+preferences/kubeconfig-syncs.tsx
  src/renderer/components/+preferences/preferences.scss
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/mui-base-theme.tsx
  yarn.lock
Labels: area/ui, enhancement

#2682 Replacing material <Tooltip/> global styles
  src/renderer/components/+catalog/catalog-add-button.scss
  src/renderer/components/+catalog/catalog-add-button.tsx
Labels: area/ui, bug
