Repository lensapp/lens, pull requests merged in 2021-08, with the labels that each got.

#3452 Ignore certain file globs when under dir kube sync
  package.json
  src/main/catalog-sources/kubeconfig-sync.ts
  yarn.lock
Labels: bug

#3267 Update kubectl to v1.21.2
  package.json
  src/main/kubectl.ts
Labels: bug

#3432 Add new SentryTransport to winston
  package.json
  src/common/sentry.ts
  src/main/logger.ts
  yarn.lock
Labels: chore

#3529 Simplify most of the KubeObjectDetailRegistry initial values
  src/renderer/components/+config-autoscalers/hpa-details.tsx
  src/renderer/initializers/kube-object-detail-registry.tsx
Labels: area/extension, chore

#3531 Cleanup integration and unit tests
  __mocks__/windowMock.ts
  integration/__tests__/app.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/__tests__/command-palette.tests.ts
  integration/helpers/utils.ts
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/render-delay/__tests__/render-delay.test.tsx
Labels: area/tests, chore

#3561 Update in-tree extensions webpack
  extensions/kube-object-event-status/package-lock.json
  extensions/kube-object-event-status/package.json
  extensions/node-menu/package-lock.json
  extensions/node-menu/package.json
  extensions/pod-menu/package-lock.json
  extensions/pod-menu/package.json
Labels: area/security, dependencies

#3179 Notify user of error if confirmation dialog rejects promise
  src/renderer/components/confirm-dialog/confirm-dialog.tsx
Labels: area/ui, enhancement

#3542 Fix custom resources not having a fallback details component
  src/renderer/api/kube-object.ts
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/kube-object/kube-object-details.tsx
  src/renderer/initializers/kube-object-detail-registry.tsx
Labels: blocker, bug, p0

#2985 PR authors must label their PRs
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/release-drafter.yml
  .github/workflows/require-type-labels.yml
Labels: area/ci, p1

#3428 Create c&p folder before starting kube sync
  src/main/catalog-sources/kubeconfig-sync.ts
  src/main/index.ts
Labels: bug, p0

#3546 Inject handlers into LensProxy to remove circular-deps
  src/main/index.ts
  src/main/k8s-request.ts
  src/main/kubeconfig-manager.ts
  src/main/lens-proxy.ts
  src/main/proxy-functions/index.ts
  src/main/proxy-functions/kube-api-request.ts
  src/main/proxy-functions/shell-api-request.ts
  src/main/proxy-functions/types.ts
  src/main/window-manager.ts
Labels: chore

#3585 Fix license-header gh action error
  .github/workflows/license-header.yml
Labels: area/ci

#3582 Add background-color, box-shadow and padding to .ClusterStatus
  src/renderer/components/cluster-manager/cluster-status.module.css
  src/renderer/components/cluster-manager/cluster-status.scss
  src/renderer/components/cluster-manager/cluster-status.tsx
Labels: bug

#3589 Fix k0s distribution detector
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug, blocker

#3595 Fix apiBase initialization on main
  src/common/k8s-api/index.ts
  src/common/k8s-api/kube-api.ts
  src/main/lens-proxy.ts
Labels: bug, area/extension, blocker

#3596 Allow to pass KubeObjectStore.api via constructor
  src/common/k8s-api/kube-object.store.ts
  src/renderer/components/+custom-resources/crd-resource.store.ts
Labels: enhancement, area/extension, semver/minor

#3584 Log lens-metrics status request failures
  extensions/metrics-cluster-feature/src/metrics-feature.ts
Labels: chore

#3597 Expose KubeObjectStore to main extension
  src/extensions/main-api/k8s-api.ts
Labels: enhancement, area/extension, semver/minor

#2949 Replace Ace editor with Monaco
  integration/__tests__/cluster-pages.tests.ts
  package.json
  src/common/__tests__/search-store.test.ts
  src/common/routes/preferences.ts
  src/common/user-store/preferences-helpers.ts
  src/common/user-store/user-store.ts
  src/extensions/registries/__tests__/page-registry.test.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+add-cluster/add-cluster.scss
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+apps-releases/release-details.scss
  src/renderer/components/+apps-releases/release-details.tsx
  src/renderer/components/+custom-resources/crd-details.tsx
  src/renderer/components/+preferences/editor.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/+user-management/+cluster-roles/add-dialog.scss
  src/renderer/components/+user-management/+roles/add-dialog.scss
  src/renderer/components/+workloads-pods/pod-details-affinities.tsx
  src/renderer/components/ace-editor/ace-editor.tsx
  src/renderer/components/ace-editor/index.ts
  src/renderer/components/dock/__test__/dock-tabs.test.tsx
  src/renderer/components/dock/__test__/log-resource-selector.test.tsx
  src/renderer/components/dock/__test__/log-tab.store.test.ts
  src/renderer/components/dock/create-resource.tsx
  src/renderer/components/dock/dock.scss
  src/renderer/components/dock/dock.store.ts
  src/renderer/components/dock/edit-resource.store.ts
  src/renderer/components/dock/editor-panel.tsx
  src/renderer/components/dock/install-chart.store.ts
  src/renderer/components/dock/monaco-model-manager.ts
  src/renderer/components/dock/upgrade-chart.store.ts
  src/renderer/components/kubeconfig-dialog/kubeconfig-dialog.scss
  src/renderer/components/kubeconfig-dialog/kubeconfig-dialog.tsx
  src/renderer/monaco-themes/Clouds Midnight.json
  src/renderer/theme.store.ts
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
  yarn.lock
Labels: enhancement, p2

#3602 Add back sentry winston logger transport
  src/common/logger-transports/index.ts
  src/common/logger-transports/sentry.ts
  src/common/logger.ts
Labels: bug

#3610 release v5.2.0-beta.1
  .github/workflows/require-type-labels.yml
  package.json
Labels: skip-changelog

#3598 Replace no-unused-imports rule to "warning" in dev environment
  .eslintrc.js
  package.json
Labels: chore

#3616 Fixing binaries path Input field
  src/renderer/components/+preferences/kubectl-binaries.tsx
Labels: bug, area/ui

#3575 feat: Add the ability to copy k8s object name
  src/renderer/components/drawer/drawer.scss
  src/renderer/components/drawer/drawer.tsx
Labels: enhancement, area/ui

#3601 Remove @types/circular-dependency-plugin
  package.json
  yarn.lock
Labels: dependencies

#3619 Fix StatefulSet.getImages to handle null case
  src/common/k8s-api/endpoints/stateful-set.api.ts
Labels: bug

#3629 Fix KubeApi.watch leak on abort
  src/common/k8s-api/json-api.ts
  src/common/k8s-api/kube-api.ts
Labels: bug, blocker

#3630 Fix nodes view observability
  src/renderer/components/+nodes/nodes.tsx
Labels: bug, area/ui, blocker

#3631 Release v5.2.0-beta.2
  package.json
Labels: skip-changelog

#3632 Fix metrics loading on Ingress, PVC and StatefulSet details
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
Labels: bug, area/metrics

#3492 Validate and set defaults for HelmChart creation
  src/common/k8s-api/__tests__/helm-charts.api.test.ts
  src/common/k8s-api/endpoints/helm-charts.api.ts
Labels: bug, p2

#3640 Remove patch-package
  package.json
  yarn.lock
Labels: chore

#3643 Display top bar in welcome screen
  src/renderer/components/+welcome/__test__/welcome.test.tsx
  src/renderer/components/+welcome/welcome.tsx
  src/renderer/components/cluster-manager/welcome-topbar.tsx
Labels: enhancement

#3646 Always display a Node's taints' values
  src/renderer/components/+nodes/node-details.tsx
Labels: enhancement, area/ui

#3648 Fix .eslintrc.js
  .eslintrc.js
Labels: chore

#3657 Fix name copy on Helm details
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
  src/renderer/components/+apps-releases/release-details.tsx
  src/renderer/components/drawer/drawer.tsx
Labels: bug, area/ui

#3658 Fix @material-ui/core console errors
  package.json
  yarn.lock
Labels: bug

#3663 Add WelcomeBanner.width extension API
  src/extensions/registries/welcome-banner-registry.ts
  src/renderer/components/+welcome/__test__/welcome.test.tsx
  src/renderer/components/+welcome/welcome.scss
  src/renderer/components/+welcome/welcome.tsx
Labels: enhancement

#3635 Fix filtering deprecated charts
  src/common/k8s-api/endpoints/helm-charts.api.ts
  src/common/logger.ts
  src/common/utils/sort-compare.ts
  src/main/helm/__mocks__/helm-chart-manager.ts
  src/main/helm/__tests__/helm-service.test.ts
  src/main/helm/helm-chart-manager.ts
  src/main/helm/helm-repo-manager.ts
  src/main/helm/helm-service.ts
  src/renderer/components/+apps-helm-charts/helm-chart-details.scss
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
Labels: bug

#3667 Fix: font-size jumping in Catalog sidebar
  src/renderer/components/+catalog/catalog-tree.module.css
Labels: bug, area/ui

#3695 Test build on macOS/arm64
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: area/ci

#3700 Build and release amd64 & arm64 together (macOS)
  .azure-pipelines.yml
  .github/workflows/test.yml
  Makefile
  build/download_helm.ts
  build/download_kubectl.ts
  package.json
  src/main/helm/helm-cli.ts
Labels: area/macos, area/ci, blocker

#3696 Topbar history buttons
  src/main/window-manager.ts
  src/renderer/components/+catalog/catalog-menu.module.css
  src/renderer/components/+catalog/catalog-menu.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+welcome/__test__/welcome.test.tsx
  src/renderer/components/+welcome/welcome.tsx
  src/renderer/components/app.tsx
  src/renderer/components/cluster-manager/cluster-topbar.tsx
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/cluster-manager/welcome-topbar.tsx
  src/renderer/components/layout/__tests__/topbar.test.tsx
  src/renderer/components/layout/sidebar.scss
  src/renderer/components/layout/sidebar.tsx
  src/renderer/components/layout/topbar.module.css
  src/renderer/components/layout/topbar.tsx
  src/renderer/remote-helpers/history-updater.ts
Labels: enhancement, area/ui

#3647 Support filtering catalog entities
  src/common/utils/__tests__/iter.test.ts
  src/common/utils/iter.ts
  src/extensions/lens-renderer-extension.ts
  src/main/catalog/catalog-entity-registry.ts
  src/renderer/api/__tests__/catalog-entity-registry.test.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/components/+catalog/catalog-entity.store.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: enhancement, area/extension
