Repository lensapp/lens, pull requests merged in 2021-09, with the labels that each got.

#3707 Ignore clusters without kubeconfigPath on kubeconfig sync migration
  src/migrations/user-store/5.0.3-beta.1.ts
Labels: bug

#3668 Fix node shell secret pulling
  src/main/cluster.ts
  src/main/shell-session/node-shell-session.ts
  src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx
Labels: bug, blocker

#3706 Allow to configure default namespace used in terminal
  src/common/cluster-types.ts
  src/main/cluster.ts
  src/main/kubeconfig-manager.ts
  src/renderer/components/cluster-settings/components/cluster-home-dir-setting.tsx
Labels: enhancement, area/terminal

#3708 Expose logger to extensions
  src/extensions/common-api/index.ts
Labels: enhancement, area/extension

#3705 Fix bundling of helm on linux/windows
  package.json
Labels: bug, area/windows, area/linux, blocker

#3711 Detect rancher desktop
  src/main/cluster-detectors/distribution-detector.ts
Labels: enhancement

#3709 Use correct userData directory (OpenLensDev) on dev mode
  src/main/index.ts
Labels: bug, blocker

#3712 Fix the wrong color of welcome banner carousel indicator
  src/renderer/components/+welcome/welcome.tsx
Labels: bug, area/ui

#3714 Restore telemetry tab to Preferences page
  src/renderer/components/+preferences/preferences.tsx
Labels: bug, area/ui

#3716 Upgrade @types/node to v14
  package.json
  yarn.lock
Labels: chore

#3717 Make ipc.boradcast not stopping at uncaught exceptions, improve typing, improve error logs
  src/common/ipc/ipc.ts
Labels: chore

#3719 Fix the back/forward button on topbar
  src/renderer/components/layout/__tests__/topbar.test.tsx
  src/renderer/components/layout/topbar.tsx
  src/renderer/remote-helpers/history-updater.ts
Labels: bug, area/ui

#3720 Make back/forward/refresh work the same as the arrow buttons in topbar
  src/main/menu.ts
  src/main/window-manager.ts
Labels: chore

#3731 Release v5.2.0-beta.4
  package.json
Labels: skip-changelog

#3742 Slow down the carousel (default is 4000 ms)
  src/renderer/components/+welcome/welcome.tsx
Labels: area/ui, chore

#3740 TopBar home icon
  src/common/catalog/catalog-category-registry.ts
  src/main/catalog-sources/general.ts
  src/main/catalog-sources/helpers/general-active-sync.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+welcome/__test__/welcome.test.tsx
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/layout/__tests__/topbar.test.tsx
  src/renderer/components/layout/topbar.tsx
Labels: enhancement, area/ui

#3732 Add namespace to the message.
  src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx
Labels: enhancement

#3751 Use entity name as cluster name in sidebar
  src/main/initializers/ipc.ts
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-name-setting.tsx
  src/renderer/components/layout/sidebar.tsx
Labels: bug, area/ui, blocker

#3753 Don't add active entity automatically to a hotbar
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: bug, area/ui, blocker

#3755 release v5.2.0
  package.json
Labels: skip-changelog

#3737 Automatically check next pre-release channel
  build/set_build_version.ts
  package.json
  src/main/app-updater.ts
  src/main/utils/__test__/update-channel.test.ts
  src/main/utils/update-channel.ts
  yarn.lock
Labels: enhancement, autoupdate

#3744 Use PATCH verb to scale deployments and statefulsets
  src/common/k8s-api/__tests__/deployment.api.test.ts
  src/common/k8s-api/__tests__/stateful-set.api.test.ts
  src/common/k8s-api/endpoints/deployment.api.ts
  src/common/k8s-api/endpoints/stateful-set.api.ts
Labels: bug

#3759 Fix development on M1 (Apple Silicon)
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement, area/macos

#3784 Remove @materil-ui/core deprecation warning
  src/renderer/mui-base-theme.tsx
Labels: chore

#3766 Allow KubeApi connect directly to remote k8s
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
  src/extensions/main-api/k8s-api.ts
  src/extensions/renderer-api/k8s-api.ts
Labels: enhancement, area/extension

#3704 updating release guide with more details
  RELEASE_GUIDE.md
Labels: chore

#3785 Stop Sentry from capturing console.error and logger.error
  src/common/logger.ts
  src/common/sentry.ts
Labels: chore

#3718 Add CatalogCategory filter to the extension API
  src/common/__tests__/catalog-category-registry.test.ts
  src/common/catalog/catalog-category-registry.ts
  src/extensions/lens-renderer-extension.ts
  src/renderer/api/catalog-category-registry.ts
  src/renderer/components/+catalog/catalog-menu.tsx
  src/renderer/components/+catalog/catalog.tsx
Labels: enhancement, area/extension

#3786 Expose forRemoteCluster in the extension API.
  src/extensions/main-api/k8s-api.ts
  src/extensions/renderer-api/k8s-api.ts
Labels: enhancement

#3722 Add catalogAddMenu filter to CatalogCategory
  package.json
  src/common/catalog-entities/__tests__/kubernetes-cluster.test.ts
  src/common/catalog/catalog-entity.ts
  src/renderer/components/+catalog/__tests__/catalog-add-button.test.tsx
  src/renderer/components/+catalog/catalog-add-button.tsx
  yarn.lock
Labels: enhancement

#3765 Sidebar cluster avatar
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/utils.ts
  src/main/window-manager.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+welcome/__test__/welcome.test.tsx
  src/renderer/components/+welcome/welcome.tsx
  src/renderer/components/cluster-manager/cluster-manager.scss
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/components/layout/sidebar.module.css
  src/renderer/components/layout/sidebar.tsx
  src/renderer/components/layout/topbar.module.css
  src/renderer/components/layout/topbar.tsx
Labels: enhancement, area/ui

#3783 Fix sass warnings
  src/renderer/components/+apps-helm-charts/helm-charts.scss
  src/renderer/components/+cluster/cluster-issues.scss
  src/renderer/components/+config-maps/config-map-details.scss
  src/renderer/components/+config-resource-quotas/add-quota-dialog.scss
  src/renderer/components/+config-secrets/add-secret-dialog.scss
  src/renderer/components/+config-secrets/secret-details.scss
  src/renderer/components/+events/events.scss
  src/renderer/components/+namespaces/namespace-select-filter.scss
  src/renderer/components/+namespaces/namespace-select.scss
  src/renderer/components/+preferences/add-helm-repo-dialog.scss
  src/renderer/components/+user-management/+cluster-role-bindings/dialog.scss
  src/renderer/components/+user-management/+cluster-role-bindings/view.scss
  src/renderer/components/+user-management/+cluster-roles/view.scss
  src/renderer/components/+user-management/+role-bindings/dialog.scss
  src/renderer/components/+user-management/+role-bindings/view.scss
  src/renderer/components/+user-management/+roles/view.scss
  src/renderer/components/+user-management/+service-accounts/secret.scss
  src/renderer/components/app.scss
  src/renderer/components/cluster-manager/bottom-bar.scss
  src/renderer/components/drawer/drawer-item.scss
  src/renderer/components/icon/icon.scss
  src/renderer/components/input/input.scss
  src/renderer/components/item-object-list/page-filters-list.scss
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.scss
  src/renderer/components/layout/sidebar-item.scss
  src/renderer/components/layout/sidebar.module.css
  src/renderer/components/menu/menu-actions.scss
  src/renderer/components/resizing-anchor/resizing-anchor.scss
  src/renderer/components/select/select.scss
  src/renderer/components/stepper/stepper.scss
  src/renderer/components/table/table.mixins.scss
  src/renderer/components/tabs/tabs.scss
Labels: area/ui, chore

#3809 Second click on list item closes the details view
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
  src/renderer/components/+apps-releases/releases.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+cluster/cluster-issues.tsx
  src/renderer/components/kube-detail-params/params.ts
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
Labels: enhancement

#3812 Fix fallback to bundled kubectl
  src/main/kubectl.ts
Labels: bug

#3817 Fix cluster's accessibleNamespaces being reset on restarting Lens
  src/common/catalog-entities/kubernetes-cluster.ts
  src/main/cluster-manager.ts
Labels: bug

#3798 Don't change permissions when deleting a cluster
  package.json
  src/renderer/components/delete-cluster-dialog/save-config.ts
  yarn.lock
Labels: bug

#3800 Draggable region on macOS should be the same as the main header
  src/renderer/components/app.scss
Labels: enhancement, area/macos

#3664 Fix check for user exec command
  package.json
  src/common/custom-errors.ts
  src/common/kube-helpers.ts
  src/renderer/components/+add-cluster/add-cluster.scss
  src/renderer/components/+add-cluster/add-cluster.tsx
  yarn.lock
Labels: bug, p2

#3795 Fix shell connection readiness heuristic
  src/renderer/api/terminal-api.ts
  src/renderer/components/dock/terminal.store.ts
Labels: bug, area/windows

#3799 Upgrade all testing linux CI machines to Ubuntu-20.04
  .azure-pipelines-k8s-matrix.yml
  .azure-pipelines.yml
  .github/workflows/test.yml
Labels: area/ci

#3822 Fix test GH action to run on all branches
  .github/workflows/test.yml
Labels: area/ci

#3827 Revert "Fix check for user exec command"
  package.json
  src/common/custom-errors.ts
  src/common/kube-helpers.ts
  src/renderer/components/+add-cluster/add-cluster.scss
  src/renderer/components/+add-cluster/add-cluster.tsx
  yarn.lock
Labels: bug

#3828 Release v5.2.2
  package.json
  src/common/custom-errors.ts
  src/common/kube-helpers.ts
  src/renderer/components/+add-cluster/add-cluster.scss
  src/renderer/components/+add-cluster/add-cluster.tsx
  yarn.lock
Labels: skip-changelog

#3824 Fix reference error when opening cluster view
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/components/app.tsx
Labels: bug

#3836 Fix node-fetch load on renderer
  src/main/window-manager.ts
  webpack.main.ts
  webpack.renderer.ts
Labels: bug

#3823 Fix error due to async validators for <Input>
  src/renderer/components/input/input.tsx
Labels: bug

#3842 Emit contextMenuOpen for WebLink CatalogEntity
  src/common/catalog-entities/web-link.ts
Labels: bug

#3848 Release v5.2.3
  package.json
  src/main/window-manager.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/components/app.tsx
  src/renderer/components/input/input.tsx
  webpack.main.ts
  webpack.renderer.ts
Labels: skip-changelog

#3854 Fix long name layout in Cluster Settings
  src/renderer/components/+entity-settings/entity-settings.module.css
  src/renderer/components/+entity-settings/entity-settings.tsx
Labels: bug, area/ui

#3867 [UX]: navigation to cluster overview from sidebar's top icon
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/layout/sidebar.tsx
Labels: enhancement, area/ui

#3868 Add error message for no contexts in add cluster page
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: enhancement

#3875 Fix missing query parameter
  src/common/k8s-api/kube-object.store.ts
Labels: bug

#3874 Disable log file writing on renderer
  src/common/logger.ts
Labels: bug

#3877 Use Ubuntu 18.04 for builds
  .azure-pipelines-k8s-matrix.yml
  .azure-pipelines.yml
  .github/workflows/test.yml
Labels: area/ci

#3876 Release/v5.2.4
  package.json
  src/common/k8s-api/kube-object.store.ts
  src/common/logger.ts
  src/renderer/components/+entity-settings/entity-settings.module.css
  src/renderer/components/+entity-settings/entity-settings.tsx
Labels: skip-changelog

#3883 Fix title of service account dialog
  src/renderer/components/kubeconfig-dialog/kubeconfig-dialog.tsx
Labels: bug

#3885 added details for making a patch release
  RELEASE_GUIDE.md
Labels: area/documentation

#3820 Electron 13.4.0
  .yarnrc
  package.json
  src/main/window-manager.ts
  yarn.lock
Labels: bug, area/security

#3890 Detect log follow requests
  src/main/__test__/lens-proxy.test.ts
  src/main/context-handler.ts
  src/main/lens-proxy.ts
  src/main/routes/helm-route.ts
  src/main/utils/parse-query.ts
Labels: bug

#3295 Added ability to add custom port on pod and service port forwarding
  src/main/router.ts
  src/main/routes/port-forward-route.ts
  src/renderer/components/+network-services/service-port-component.scss
  src/renderer/components/+network-services/service-port-component.tsx
  src/renderer/components/+workloads-pods/pod-container-port.scss
  src/renderer/components/+workloads-pods/pod-container-port.tsx
Labels: enhancement, p3

#3906 updated expired community slack invite link with permanent one
  src/common/vars.ts
Labels: bug

#3807 Redirect from /catalog to last catalog page
  src/common/routes/catalog.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/cluster-view.tsx
  src/renderer/components/layout/topbar.tsx
Labels: enhancement, area/ui

#3866 Fix menu rendering on when slightly off screen
  src/renderer/components/menu/menu.scss
  src/renderer/components/menu/menu.tsx
Labels: bug, area/ui

#3904 Add terminal copy on select
  src/common/user-store/preferences-helpers.ts
  src/common/user-store/user-store.ts
  src/renderer/components/+preferences/application.tsx
  src/renderer/components/dock/terminal.ts
Labels: enhancement, area/terminal

#3915 Make default catalog action to open entity
  integration/helpers/utils.ts
  src/renderer/components/+catalog/catalog.tsx
Labels: enhancement
