Repository lensapp/lens, pull requests merged in 2021-12, with the labels that each got.

#4467 Fix NetworkPolicy engresses not having node/pod selectors displayed
  src/common/k8s-api/endpoints/daemon-set.api.ts
  src/common/k8s-api/endpoints/deployment.api.ts
  src/common/k8s-api/endpoints/job.api.ts
  src/common/k8s-api/endpoints/network-policy.api.ts
  src/common/k8s-api/endpoints/persistent-volume-claims.api.ts
  src/common/k8s-api/endpoints/poddisruptionbudget.api.ts
  src/common/k8s-api/endpoints/replica-set.api.ts
  src/common/k8s-api/endpoints/stateful-set.api.ts
  src/common/k8s-api/kube-object.ts
  src/renderer/components/+network-policies/__tests__/network-policy-details.test.tsx
  src/renderer/components/+network-policies/network-policy-details.module.css
  src/renderer/components/+network-policies/network-policy-details.tsx
Labels: bug

#4463 Log cluster model if adding a cluster fails when syncing from catalog
  src/main/cluster-manager.ts
Labels: chore

#4478 Fix KubeApi.create not populating kind and apiVersion
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
Labels: bug, blocker

#4477 Fix light theme pin icon visibility
  package.json
  src/renderer/cluster-frame.tsx
  src/renderer/components/icon/icon.scss
  src/renderer/components/layout/sidebar-cluster.module.css
  yarn.lock
Labels: bug, area/ui

#4420 Use PartialDeep for patch type
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
  src/renderer/components/+namespaces/namespaces.tsx
  src/renderer/components/+workloads-pods/pods.tsx
Labels: bug

#4479 Release/v5.3.2
  package.json
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/endpoints/daemon-set.api.ts
  src/common/k8s-api/endpoints/deployment.api.ts
  src/common/k8s-api/endpoints/job.api.ts
  src/common/k8s-api/endpoints/network-policy.api.ts
  src/common/k8s-api/endpoints/persistent-volume-claims.api.ts
  src/common/k8s-api/endpoints/poddisruptionbudget.api.ts
  src/common/k8s-api/endpoints/replica-set.api.ts
  src/common/k8s-api/endpoints/stateful-set.api.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.ts
  src/renderer/components/+network-policies/__tests__/network-policy-details.test.tsx
  src/renderer/components/+network-policies/network-policy-details.module.css
  src/renderer/components/+network-policies/network-policy-details.tsx
Labels: skip-changelog

#4483 Fixing unexpected avatar width shrink
  src/renderer/components/avatar/avatar.module.css
Labels: bug, area/ui

#4481 add debug for locating startup issues
  src/main/index.ts
Labels: chore

#4492 catch app.getPath() errors (when standard platform paths are missing)
  src/common/app-paths.ts
Labels: bug

#4502 Fix error notifications not being displayed for CreateResource tab
  src/renderer/components/dock/create-resource.tsx
Labels: bug, area/ui

#4485 Fix IngressApi being registered with a wrong new apiBase
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api-parse.ts
  src/common/k8s-api/kube-api.ts
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/+custom-resources/crd.store.ts
Labels: bug

#4522 Fixes a typo in kubeconfig sync "add"-button label
  src/renderer/initializers/catalog-category-registry.tsx
Labels: bug

#4537 Upgrade mock-fs to v5
  package.json
  yarn.lock
Labels: dependencies

#4496 Export KubeJsonApi to extensions
  src/common/k8s-api/kube-json-api.ts
  src/extensions/renderer-api/k8s-api.ts
  src/main/shell-session/node-shell-session.ts
Labels: chore, area/extension

#4534 Add tooltip for cluster name in sidebar
  src/renderer/components/layout/__tests__/sidebar-cluster.test.tsx
  src/renderer/components/layout/sidebar-cluster.module.css
  src/renderer/components/layout/sidebar-cluster.tsx
Labels: bug, area/ui

#4536 Fix freeze after closing terminal on windows
  src/main/shell-session/shell-session.ts
Labels: bug, area/windows, area/terminal

#4533 Fix crash in ClusterStatus
  src/renderer/components/cluster-manager/cluster-status.tsx
Labels: bug, area/ui

#4544 Special case goBack to navigate to catalog if no where to go back to
  src/renderer/components/layout/setting-layout.tsx
Labels: bug

#4538 Remove unnecesarry TerminalApi.destroy and TerminalApi.reconnect overloads
  src/renderer/api/terminal-api.ts
Labels: chore

#4549 Add some gh and jq help to the release guide
  RELEASE_GUIDE.md
Labels: chore

#4535 Use electron.clipboard for all clipboard uses
  src/renderer/components/clipboard/clipboard.scss
  src/renderer/components/clipboard/clipboard.tsx
  src/renderer/components/clipboard/index.ts
  src/renderer/components/dialog/logs-dialog.tsx
  src/renderer/components/kubeconfig-dialog/kubeconfig-dialog.tsx
  src/renderer/utils/copyToClipboard.ts
  src/renderer/utils/index.ts
Labels: bug

#4558 Fix ERR_UNSAFE_PORT from LensProxy
  src/main/lens-proxy.ts
Labels: bug

#4554 Fix extension engine range not working for some ^ ranges
  src/extensions/__tests__/extension-compatibility.test.ts
  src/extensions/extension-compatibility.ts
Labels: bug, area/extension

#4500 Fix crash on NetworkPolicy when matchLabels is missing
  src/renderer/components/+network-policies/__tests__/network-policy-details.test.tsx
  src/renderer/components/+network-policies/network-policy-details.module.css
  src/renderer/components/+network-policies/network-policy-details.tsx
Labels: bug

#4569 Fix crash with InstallChart
  src/renderer/components/dock/install-chart.tsx
Labels: bug

#4557 Remove all 'NonBreakingSpace' characters from the repo
  .eslintrc.js
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
  src/common/ipc/ipc.ts
  src/common/utils/readableStream.ts
  src/main/lens-binary.ts
  src/main/window-manager.ts
  src/migrations/hotbar-store/5.0.0-beta.10.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/components/+catalog/catalog-add-button.tsx
  src/renderer/components/+events/events.tsx
  src/renderer/components/+preferences/application.tsx
  src/renderer/components/dock/terminal.ts
Labels: chore

#4587 Update ogre-tools for improved types of withInjectables
  package.json
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/kube-object-menu/kube-object-menu.tsx
  yarn.lock
Labels: chore

#4503 Add support for customizing the extension install registry URL
  src/common/user-store/preferences-helpers.ts
  src/common/user-store/user-store.ts
  src/common/utils/index.ts
  src/renderer/components/+extensions/attempt-install-by-info/attempt-install-by-info.tsx
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+extensions/get-base-registry-url/get-base-registry-url.injectable.ts
  src/renderer/components/+extensions/get-base-registry-url/get-base-registry-url.tsx
  src/renderer/components/+preferences/application.tsx
Labels: enhancement

#4514 Replace all uses of promiseExec with promiseExecFile
  integration/__tests__/app-preferences.tests.ts
  src/common/system-ca.ts
  src/common/utils/promise-exec.ts
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-repo-manager.ts
  src/main/helm/helm-service.ts
  src/main/kubectl.ts
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
Labels: bug, area/security

#4588 Fix <Extensions> not building
  src/renderer/components/+extensions/extensions.tsx
Labels: chore

#4590 Add getBaseRegistryUrl dep to attemptInstallByInfoInjectable
  src/renderer/components/+extensions/attempt-install-by-info/attempt-install-by-info.injectable.ts
Labels: bug

#4576 Upgrade to latest version of @typescript-eslint/* pkgs
  package.json
  yarn.lock
Labels: dependencies

#4602 Less noisy metrics-not-available error logging
  src/main/routes/metrics-route.ts
Labels: chore

#4594 Show all helm release statuses
  src/main/helm/helm-release-manager.ts
Labels: bug, area/helm

#4582 Remove unnecessary CatalogEntityItem
  src/common/__tests__/hotbar-store.test.ts
  src/common/catalog/catalog-entity.ts
  src/renderer/components/+catalog/catalog-entity-details.tsx
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/+catalog/catalog-entity.store.tsx
  src/renderer/components/+catalog/catalog.test.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+catalog/helpers.tsx
Labels: chore

#4605 Fix: added missing styles at Cluster Issues view
  src/renderer/components/+cluster/cluster-issues.module.scss
  src/renderer/components/+cluster/cluster-issues.tsx
Labels: bug, area/ui

#4606 DRY: light theme sass mixin
  src/renderer/components/+add-cluster/add-cluster.module.scss
  src/renderer/components/+namespaces/namespace-select-filter.scss
  src/renderer/components/checkbox/checkbox.scss
  src/renderer/components/checkbox/checkbox.tsx
  src/renderer/components/delete-cluster-dialog/delete-cluster-dialog.tsx
  src/renderer/components/kube-object-details/kube-object-details.scss
  src/renderer/components/kubeconfig-dialog/kubeconfig-dialog.module.scss
  src/renderer/components/menu/menu.scss
  src/renderer/components/mixins.scss
  src/renderer/port-forward/port-forward-dialog.tsx
Labels: bug, area/ui
