Repository lensapp/lens, pull requests merged in 2021-10, with the labels that each got.

#3925 Update electron to 13.5.1 to enable X509_V_FLAG_TRUSTED_FIRST flag in BoringSSL
  .yarnrc
  package.json
  yarn.lock
Labels: bug

#3924 Update electron to 12.2.1
  .github/workflows/test.yml
  .yarnrc
  package.json
  yarn.lock
Labels: bug

#3858 Fix kube-api watch leak on window unload
  src/renderer/bootstrap.tsx
  src/renderer/components/app.tsx
  src/renderer/lens-app.tsx
Labels: bug

#3930 Pin @k8slens/extensions dependencies instead of wildcarding them
  src/extensions/npm/extensions/package.json
Labels: area/ci

#3926 Release v5.2.5
  package.json
  src/common/vars.ts
  src/extensions/npm/extensions/package.json
  src/main/__test__/lens-proxy.test.ts
  src/main/context-handler.ts
  src/main/lens-proxy.ts
  src/main/routes/helm-route.ts
  src/main/utils/parse-query.ts
Labels: skip-changelog

#3938 Check "user-supplied values only" by default when viewing a helm release
  src/renderer/components/+apps-releases/release-details.tsx
Labels: enhancement

#3931 Add missing locale date in event view
  src/renderer/components/+events/kube-event-details.tsx
Labels: bug

#3776 Make editor editable when user-supplied values is selected
  src/renderer/components/+apps-releases/release-details.tsx
Labels: bug

#3939 Added tooltipOnParentHover to taint tooltip on nodes list page
  src/renderer/components/+nodes/nodes.tsx
Labels: bug

#3950 Specify tableId for DeploymentReplicaSets
  src/renderer/components/+workloads-deployments/deployment-replicasets.tsx
Labels: bug

#3928 Don't override entity source on cluster icons
  src/main/cluster-manager.ts
Labels: bug, area/extension

#3674 Use JSON patch for editing components
  package.json
  src/common/k8s-api/endpoints/resource-applier.api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/k8s-api/kube-object.ts
  src/main/resource-applier.ts
  src/main/router.ts
  src/main/routes/resource-applier-route.ts
  src/main/utils/http-responses.ts
  src/renderer/components/+config-maps/config-map-details.tsx
  src/renderer/components/+workloads-deployments/deployment-scale-dialog.test.tsx
  src/renderer/components/+workloads-replicasets/replicaset-scale-dialog.test.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-scale-dialog.test.tsx
  src/renderer/components/dock/create-resource.tsx
  src/renderer/components/dock/edit-resource.store.ts
  src/renderer/components/dock/edit-resource.tsx
  src/renderer/components/dock/editor-panel.tsx
  src/renderer/components/kube-object-menu/kube-object-menu.tsx
  yarn.lock
Labels: bug

#3653 Fix prometheus operator support
  src/common/k8s-api/endpoints/persistent-volume-claims.api.ts
  src/main/prometheus/operator.ts
Labels: bug

#3911 Before hook for onRun of Catalog entities
  package.json
  src/extensions/lens-renderer-extension.ts
  src/extensions/renderer-api/catalog.ts
  src/jest.setup.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/components/+catalog/catalog-entity-details.tsx
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/+catalog/catalog-entity-item.tsx
  src/renderer/components/+catalog/catalog-entity.store.tsx
  src/renderer/components/+catalog/catalog-menu.module.css
  src/renderer/components/+catalog/catalog-menu.tsx
  src/renderer/components/+catalog/catalog.test.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/activate-entity-command/activate-entity-command.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
  src/renderer/components/icon/icon.tsx
  yarn.lock
Labels: enhancement, blocker, catalog

#4194 release v5.3.0-alpha.7
  package.json
Labels: skip-changelog
