Repository lensapp/lens, pull requests merged in 2021-07, with the labels that each got.

#3194 Fixing tooltips to use single component
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+extensions/install.tsx
  src/renderer/components/cluster-manager/catalog-topbar.tsx
  src/renderer/components/cluster-manager/cluster-topbar.tsx
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
  src/renderer/components/hotbar/hotbar-icon.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
  src/renderer/components/hotbar/hotbar-selector.tsx
  src/renderer/components/material-tooltip/material-tooltip.tsx
  src/renderer/components/tooltip/tooltip.scss
  src/renderer/components/tooltip/tooltip.tsx
Labels: area/ui, bug

#3230 Always check if ref is active in virtual-list
  src/renderer/components/virtual-list/virtual-list.tsx
Labels: bug

#3037 Change tray icon
  build/build_tray_icon.ts
  build/tray/trayIconDarkTemplate.png
  build/tray/trayIconDarkTemplate@2x.png
  build/tray/trayIconDarkTemplate@3x.png
  build/tray/trayIconTemplate.png
  build/tray/trayIconTemplate@2x.png
  build/tray/trayIconTemplate@3x.png
Labels: area/ui

#3211 Correctly migrate duplicate clusters in workspaces
  src/common/cluster-store.ts
  src/main/cluster.ts
  src/migrations/cluster-store/5.0.0-beta.13.ts
  src/migrations/hotbar-store/5.0.0-beta.10.ts
Labels: bug

#3241 Increase shell sync timeout
  src/main/utils/shell-env.ts
Labels: bug

#3231 Allow users to disconnect from clusters that fail to connect
  src/common/catalog-entities/kubernetes-cluster.ts
  src/main/cluster-manager.ts
Labels: enhancement

#3228 Cap cpu chart label values to 2 decimal points
  src/renderer/components/+cluster/cluster-pie-charts.tsx
Labels: area/ui, bug

#3205 Use kubeconfigPath for delete synced clusters confirmation
  src/common/catalog-entities/kubernetes-cluster.ts
Labels: bug

#3229 Set ownerReference to manually triggered cron jobs
  src/renderer/components/+workloads-cronjobs/cronjob-trigger-dialog.tsx
Labels: bug

#3261 Don't set prerelease version info when non-prerelease
  build/set_build_version.ts
Labels: area/extension, bug

#3191 Don't clear cluster icon on cancel
  src/renderer/components/cluster-settings/components/cluster-icon-settings.tsx
Labels: bug

#3262 Remove rc note because we don't use rc anymore
  build/set_build_version.ts
Labels: chore

#3264 Set build.appId
  package.json
Labels: area/macos, bug

#3268 Revert "Set build.appId"
  package.json
Labels: skip-changelog

#3269 Release v5.0.1
  package.json
Labels: skip-changelog

#3274 Fix problem with in-tree extension load
  build/set_build_version.ts
  src/extensions/extension-discovery.ts
Labels: blocker, bug

#3275 Release v5.0.2
  package.json
Labels: skip-changelog

#3172 Don't clear searchValue on CommandDialog onBlur
  src/renderer/components/command-palette/command-dialog.tsx
Labels: area/ui, bug

#3059 Add new workflow to automatically add new issues and prs to the lens project
  .github/actions/add-card-to-project/Dockerfile
  .github/actions/add-card-to-project/action.yml
  .github/actions/add-card-to-project/entrypoint.sh
  .github/workflows/add-to-project-board.yaml
Labels: area/ci

#3278 Run integration tests against real build
  .github/workflows/test.yml
  Makefile
  package.json
Labels: area/ci, area/tests, bug

#3167 Reduce transition duration for <Tab>'s
  src/renderer/components/tabs/tabs.scss
Labels: area/ui, bug

#2708 Formalize the to/from Store rules for UserStore
  src/common/__tests__/user-store.test.ts
  src/common/user-store/index.ts
  src/common/user-store/preferences-helpers.ts
  src/common/user-store/user-store.ts
  src/renderer/theme.store.ts
Labels: chore

#3225 Unblock subsequent Singleton.createInstance()
  src/common/utils/singleton.ts
  src/migrations/helpers.ts
  src/migrations/hotbar-store/5.0.0-beta.10.ts
Labels: bug

#3286 Await kubeconfigPathP for fish shell args
  src/main/shell-session/local-shell-session.ts
Labels: bug

#3291 Fix unhandled exception in visibility handler
  src/common/catalog-entities/kubernetes-cluster.ts
  src/main/catalog/catalog-entity-registry.ts
  src/main/initializers/ipc.ts
Labels: bug

#3281 Fixing initial scroll-to-bottom in pod logs
  src/renderer/components/dock/__test__/to-bottom.test.tsx
  src/renderer/components/dock/log-list.scss
  src/renderer/components/dock/log-list.tsx
  src/renderer/components/dock/log.store.ts
  src/renderer/components/dock/to-bottom.tsx
Labels: area/logs, area/ui, bug

#3303 Add logging on proxy error
  src/main/proxy/lens-proxy.ts
Labels: bug

#3302 Fix table columns being hidden after changing any user preference
  src/common/user-store/user-store.ts
Labels: blocker, bug

#3227 Automatically sync all kubeConfigPaths
  extensions/kube-object-event-status/package/package.json
  package.json
  src/common/user-store/index.ts
  src/common/user-store/user-store.ts
  src/main/index.ts
  src/migrations/hotbar-store/5.0.0-beta.10.ts
  src/migrations/user-store/5.0.3-beta.1.ts
  src/migrations/user-store/index.ts
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
Labels: blocker, bug

#3311 Fix user-store/5.0.3-beta.1.ts comment
  src/migrations/hotbar-store/5.0.0-beta.10.ts
Labels: chore

#3315 Cleanup sentry integration
  src/common/sentry.ts
  src/common/utils/index.ts
  src/common/utils/isValidSentryDsn.ts
  src/common/utils/isValidURL.ts
  src/common/vars.ts
  src/main/index.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/lens-app.tsx
Labels: chore

#3324 New spinner for cluster connect status page
  src/renderer/components/cluster-manager/cluster-status.scss
  src/renderer/components/cluster-manager/cluster-status.tsx
Labels: area/ui, enhancement

#3046 Fork-ts-checker-webpack-plugin 5.2.1
  package.json
  yarn.lock
Labels: chore

#3336 Remove `<CubeSpinner>` and `<AppInit>` as both are unused
  src/renderer/components/app-init/app-init.scss
  src/renderer/components/app-init/app-init.tsx
  src/renderer/components/spinner/cube-spinner.scss
  src/renderer/components/spinner/cube-spinner.tsx
  src/renderer/components/spinner/index.ts
Labels: chore

#2919 Selecting one namespace at a time
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/+namespaces/namespace.store.ts
Labels: area/ui, enhancement

#3323 Sync activeEntity to cluster renderer
  src/renderer/components/app.tsx
Labels: area/extension, bug, semver-patch

#3325 Fix Sentry integration bugs
  src/common/sentry.ts
  src/common/vars.ts
  src/main/index.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+preferences/preferences.tsx
Labels: bug

#3353 Set res.statusCode before flushing headers
  src/main/proxy/lens-proxy.ts
Labels: bug

#3355 Fix not being able to configure non-Lens prometheus settings
  src/main/prometheus/helm.ts
  src/main/prometheus/lens.ts
  src/main/prometheus/operator.ts
  src/main/prometheus/stacklight.ts
Labels: area/metrics, bug

#3249 Make node shell image configurable
  src/common/cluster-store.ts
  src/main/cluster.ts
  src/main/shell-session/node-shell-session.ts
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx
  src/renderer/components/cluster-settings/components/index.ts
  src/renderer/initializers/entity-settings-registry.ts
Labels: enhancement

#3313 Ignore extensions' clusters when adding to kubeConfigSync
  src/common/__tests__/user-store.test.ts
  src/common/utils/__tests__/paths.test.ts
  src/common/utils/paths.ts
  src/migrations/user-store/5.0.3-beta.1.ts
Labels: blocker, bug

#3360 release v5.1.0-beta.1
  package.json
Labels: skip-changelog

#2754 Add SystemName validation to AccessibleNamespaces
  src/renderer/components/cluster-settings/components/cluster-accessible-namespaces.tsx
  src/renderer/components/editable-list/editable-list.scss
  src/renderer/components/editable-list/editable-list.tsx
  src/renderer/components/input/input.tsx
Labels: area/ui, enhancement

#3361 Check for unset pod spec
  src/renderer/api/__tests__/pods.api.test.ts
  src/renderer/api/endpoints/pods.api.ts
Labels: bug

#3340 Provide better typing for dock tabs
  src/renderer/components/dock/__test__/dock-tabs.test.tsx
  src/renderer/components/dock/create-resource.store.ts
  src/renderer/components/dock/create-resource.tsx
  src/renderer/components/dock/dock-tab.tsx
  src/renderer/components/dock/dock-tabs.tsx
  src/renderer/components/dock/dock.store.ts
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/edit-resource.store.ts
  src/renderer/components/dock/edit-resource.tsx
  src/renderer/components/dock/install-chart.store.ts
  src/renderer/components/dock/install-chart.tsx
  src/renderer/components/dock/log-tab.store.ts
  src/renderer/components/dock/logs.tsx
  src/renderer/components/dock/terminal-window.tsx
  src/renderer/components/dock/terminal.store.ts
  src/renderer/components/dock/upgrade-chart.store.ts
  src/renderer/components/dock/upgrade-chart.tsx
Labels: chore

#3369 Removing limits and requests from Pod metrics
  src/renderer/components/+workloads-pods/container-charts.tsx
  src/renderer/components/+workloads-pods/pod-charts.tsx
Labels: area/ui, bug

#1397 Badge: option to show short/full versions of contents
  src/renderer/components/+apps-releases/release-details.scss
  src/renderer/components/+apps-releases/release-details.tsx
  src/renderer/components/+catalog/catalog-entity.store.tsx
  src/renderer/components/+config-autoscalers/hpa-details.scss
  src/renderer/components/+config-autoscalers/hpa-details.tsx
  src/renderer/components/+config-autoscalers/hpa.scss
  src/renderer/components/+config-autoscalers/hpa.tsx
  src/renderer/components/+config-secrets/secrets.tsx
  src/renderer/components/+custom-resources/crd-details.scss
  src/renderer/components/+custom-resources/crd-details.tsx
  src/renderer/components/+custom-resources/crd-resource-details.scss
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/+custom-resources/crd.mixins.scss
  src/renderer/components/+nodes/node-details.scss
  src/renderer/components/+nodes/nodes-mixins.scss
  src/renderer/components/+workloads-cronjobs/cronjob-details.scss
  src/renderer/components/+workloads-deployments/deployment-details.scss
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-jobs/job-details.scss
  src/renderer/components/+workloads-pods/pod-details-container.scss
  src/renderer/components/+workloads-pods/pod-details.tsx
  src/renderer/components/+workloads-pods/pods.tsx
  src/renderer/components/+workloads/workloads-mixins.scss
  src/renderer/components/badge/badge.module.css
  src/renderer/components/badge/badge.tsx
  src/renderer/components/chart/chart.scss
  src/renderer/components/chart/chart.tsx
  src/renderer/components/chart/pie-chart.scss
  src/renderer/components/cluster-settings/components/cluster-show-metrics.tsx
  src/renderer/components/dock/info-panel.scss
  src/renderer/components/drawer/drawer-item.scss
  src/renderer/components/hotbar/hotbar-selector.scss
  src/renderer/components/hotbar/hotbar-selector.tsx
  src/renderer/components/icon/icon.scss
  src/renderer/components/item-object-list/page-filters-list.tsx
  src/renderer/components/table/table.mixins.scss
Labels: area/ui, enhancement

#3362 Remove win-ca/pem before publish & catch inject error
  .azure-pipelines.yml
  Makefile
  src/common/system-ca.ts
Labels: area/windows, bug

#3371 remove unused filenamify package
  package.json
Labels: chore

#3358 Catch empty string error is parseKubeApi
  src/renderer/api/__tests__/kube-api-parse.test.ts
  src/renderer/api/api-manager.ts
  src/renderer/api/kube-api-parse.ts
  src/renderer/components/kube-object/kube-object-details.tsx
Labels: bug

#3331 Fix `.TableHead.sticky` in for details panels
  src/renderer/components/+nodes/node-details-resources.tsx
  src/renderer/components/+workloads-pods/pod-details-list.scss
  src/renderer/components/table/table-head.scss
Labels: area/ui, bug

#3334 Remove conflicting classNames under quota-entries
  src/renderer/components/+config-resource-quotas/add-quota-dialog.tsx
Labels: chore

#3380 Update yarn.lock
  yarn.lock
Labels: chore

#3381 release v5.1.0-beta.2
  package.json
Labels: skip-changelog

#3390 release v5.1.0
  package.json
Labels: skip-changelog

#3393 Stringify errors that get sent to notifications
  src/renderer/components/notifications/notifications.tsx
Labels: blocker, bug

#3392 Fix clusters not being defined
  src/migrations/cluster-store/5.0.0-beta.10.ts
Labels: blocker, bug

#3394 Failing to load KubeStateMetrics should only warn
  src/renderer/components/+workloads-pods/pods.store.ts
Labels: bug

#3395 getPortFrom should log the lines it retrived if it fails to get a port
  src/main/utils/get-port.ts
Labels: chore

#3399 Failing to load chart releases should only warn
  src/renderer/components/+apps-releases/release.store.ts
Labels: area/helm, bug

#3181 Fix spelling
  docs/extensions/get-started/anatomy.md
  docs/extensions/guides/generator.md
  docs/extensions/guides/kube-object-list-layout.md
  docs/extensions/guides/main-extension.md
  docs/extensions/guides/resource-stack.md
  docs/extensions/guides/stores.md
  docs/extensions/testing-and-publishing/publishing.md
  src/common/__tests__/catalog-category-registry.test.ts
  src/common/hotbar-store.ts
  src/common/user-store/preferences-helpers.ts
  src/common/utils/extended-map.ts
  src/extensions/__tests__/extension-loader.test.ts
  src/extensions/ipc/ipc-main.ts
  src/extensions/lens-extension.ts
  src/main/__test__/context-handler.test.ts
  src/main/helm/helm-repo-manager.ts
  src/main/index.ts
  src/main/tray.ts
  src/renderer/api/kube-api-parse.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+apps-releases/release.store.ts
  src/renderer/components/+apps-releases/releases.tsx
  src/renderer/components/+extensions/extension-install.store.ts
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/cluster-manager/bottom-bar.test.tsx
  src/renderer/components/cluster-settings/components/cluster-accessible-namespaces.tsx
  src/renderer/components/error-boundary/error-boundary.tsx
  src/renderer/components/file-picker/file-picker.tsx
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.tsx
  src/renderer/components/markdown-viewer/markdown-viewer.scss
  src/renderer/components/notifications/notifications.store.tsx
  src/renderer/components/resizing-anchor/resizing-anchor.tsx
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
  src/renderer/themes/theme-vars.scss
  src/renderer/utils/__tests__/jsonPath.test.tsx
  src/renderer/utils/jsonPath.ts
Labels: area/ci, chore

#3384 Display toleration's value in pod-details
  src/renderer/api/workload-kube-object.ts
  src/renderer/components/+workloads-pods/pod-tolerations.tsx
Labels: bug

#3349 Fix broken shell when workdir not exists
  src/main/shell-session/local-shell-session.ts
  src/main/shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
Labels: bug

#3414 release v5.1.1
  package.json
Labels: skip-changelog

#3401 Catch Cluster create error in cluster-manager
  src/main/cluster-manager.ts
Labels: bug

#3416 Check metadata labels is an object in getRoleLabels
  src/renderer/api/endpoints/nodes.api.ts
Labels: bug

#3412 Check KubeObject.metadata is defined in getOwnerRefs
  src/renderer/api/kube-object.ts
Labels: bug

#3421 Fix KubeObjectStore loadAll error message
  src/renderer/kube-object.store.ts
Labels: bug

#3420 Skip previously bundled extensions
  src/extensions/extension-compatibility.ts
  src/extensions/extension-discovery.ts
Labels: area/extension, bug

#3426 Fix HPA visibility
  src/common/rbac.ts
Labels: bug

#3425 Log as errors the places where getPortFrom can fail
  src/main/proxy/lens-proxy.ts
  src/main/routes/port-forward-route.ts
Labels: chore

#3431 release v5.1.2
  package.json
Labels: skip-changelog

#3441 Use all namespaces for cluster overview warnings
  src/renderer/components/+cluster/cluster-issues.tsx
Labels: bug

#3442 Failing to loadAll should only warn
  src/renderer/kube-object.store.ts
Labels: chore

#3433 Fix permissions issue on ServiceDetails under RBAC
  src/renderer/components/+network-services/service-details.tsx
Labels: bug

#3434 Fix styling on cluster roles and bindings
  src/renderer/components/+user-management/+cluster-role-bindings/details.scss
  src/renderer/components/+user-management/+cluster-role-bindings/details.tsx
  src/renderer/components/+user-management/+cluster-roles/add-dialog.scss
  src/renderer/components/+user-management/+cluster-roles/add-dialog.tsx
  src/renderer/components/+user-management/+cluster-roles/details.scss
Labels: bug

#3430 Sort cronjob last scheduled time by number
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
Labels: bug

#3440 When viewing a specific release, select its namespace
  src/renderer/components/+apps-releases/release.store.ts
  src/renderer/components/+apps-releases/releases.tsx
Labels: bug

#3450 Fix misaligned spinner at cluster load
  src/renderer/components/cluster-manager/cluster-status.scss
  src/renderer/components/cluster-manager/cluster-status.tsx
Labels: area/ui, bug

#3448 Removing dependency @types/shelljs
  package.json
  yarn.lock
Labels: chore

#3338 Cleanup <EventEmitter>
  src/common/__tests__/event-emitter.test.ts
  src/common/event-emitter.ts
Labels: chore

#3333 Add ability to trim the value from <Input>
  src/renderer/components/+config-resource-quotas/add-quota-dialog.tsx
  src/renderer/components/+config-secrets/add-secret-dialog.tsx
  src/renderer/components/+namespaces/add-namespace-dialog.tsx
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/+user-management/+service-accounts/create-dialog.tsx
  src/renderer/components/+workloads-cronjobs/cronjob-trigger-dialog.tsx
  src/renderer/components/input/input.tsx
Labels: bug

#3427 Wait for a file to be stable before computing diff
  src/main/catalog-sources/kubeconfig-sync.ts
Labels: bug

#3455 Enable codeql analysis
  .github/workflows/codeql-analysis.yml
Labels: area/ci, area/security

#3337 Wait for shell to bring up prompt before sending commands
  src/renderer/api/terminal-api.ts
  src/renderer/components/dock/terminal.store.ts
Labels: bug

#3461 Default to empty array for 500Beta13 migration
  src/migrations/cluster-store/5.0.0-beta.13.ts
Labels: blocker, bug

#3459 Bundled extensions are always compatible in dev mode
  src/extensions/extension-compatibility.ts
Labels: area/extension, blocker, bug

#3316 Fix onRun not executing everywhere :hover is defined for HotbarIcon
  src/renderer/components/hotbar/hotbar-icon.tsx
Labels: area/ui, bug

#3297 Turn on tailwind JIT mode, and upgrade to 2.2.4
  package.json
  tailwind.config.js
  yarn.lock
Labels: area/ui, enhancement

#3460 Fix typings for KubeObjectDetailsRegistration
  src/extensions/registries/kube-object-detail-registry.ts
  src/renderer/components/kube-object/kube-object-details.tsx
Labels: area/extension, blocker, bug

#3477 release v5.1.3
  package.json
Labels: skip-changelog

#3424 Improving metric queries
  src/main/cluster.ts
  src/renderer/api/endpoints/cluster.api.ts
  src/renderer/api/endpoints/daemon-set.api.ts
  src/renderer/api/endpoints/deployment.api.ts
  src/renderer/api/endpoints/ingress.api.ts
  src/renderer/api/endpoints/job.api.ts
  src/renderer/api/endpoints/metrics.api.ts
  src/renderer/api/endpoints/namespaces.api.ts
  src/renderer/api/endpoints/nodes.api.ts
  src/renderer/api/endpoints/persistent-volume-claims.api.ts
  src/renderer/api/endpoints/pods.api.ts
  src/renderer/api/endpoints/replica-set.api.ts
  src/renderer/api/endpoints/stateful-set.api.ts
  src/renderer/components/+cluster/cluster-overview.store.ts
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+network-ingresses/ingress.store.ts
  src/renderer/components/+nodes/node-details.tsx
  src/renderer/components/+nodes/nodes.store.ts
  src/renderer/components/+nodes/nodes.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+storage-volume-claims/volume-claim.store.ts
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonsets.store.ts
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-deployments/deployments.store.ts
  src/renderer/components/+workloads-jobs/job-details.tsx
  src/renderer/components/+workloads-pods/pod-details.tsx
  src/renderer/components/+workloads-pods/pods.store.ts
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-replicasets/replicasets.store.ts
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset.store.ts
Labels: area/ui, enhancement

#2981 Improve Table typing and remove annotations on callbacks
  src/renderer/api/__tests__/api-manager.test.ts
  src/renderer/api/__tests__/crd.test.ts
  src/renderer/api/__tests__/kube-api.test.ts
  src/renderer/api/api-manager.ts
  src/renderer/api/endpoints/resource-applier.api.ts
  src/renderer/api/kube-api.ts
  src/renderer/api/kube-object.ts
  src/renderer/api/kube-watch-api.ts
  src/renderer/components/+apps-helm-charts/helm-charts.tsx
  src/renderer/components/+apps-releases/releases.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+config-autoscalers/hpa.tsx
  src/renderer/components/+config-limit-ranges/limit-ranges.tsx
  src/renderer/components/+config-maps/config-maps.tsx
  src/renderer/components/+config-pod-disruption-budgets/pod-disruption-budgets.tsx
  src/renderer/components/+config-resource-quotas/resource-quotas.tsx
  src/renderer/components/+config-secrets/add-secret-dialog.tsx
  src/renderer/components/+config-secrets/secrets.tsx
  src/renderer/components/+custom-resources/crd-list.tsx
  src/renderer/components/+custom-resources/crd-resource.store.ts
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/+custom-resources/crd.store.ts
  src/renderer/components/+events/events.tsx
  src/renderer/components/+namespaces/namespace.store.ts
  src/renderer/components/+namespaces/namespaces.tsx
  src/renderer/components/+network-endpoints/endpoints.tsx
  src/renderer/components/+network-ingresses/ingresses.tsx
  src/renderer/components/+network-policies/network-policies.tsx
  src/renderer/components/+network-services/services.tsx
  src/renderer/components/+nodes/nodes.tsx
  src/renderer/components/+pod-security-policies/pod-security-policies.tsx
  src/renderer/components/+storage-classes/storage-classes.tsx
  src/renderer/components/+storage-volume-claims/volume-claims.tsx
  src/renderer/components/+storage-volumes/volumes.tsx
  src/renderer/components/+user-management/+cluster-role-bindings/view.tsx
  src/renderer/components/+user-management/+cluster-roles/view.tsx
  src/renderer/components/+user-management/+role-bindings/view.tsx
  src/renderer/components/+user-management/+roles/view.tsx
  src/renderer/components/+user-management/+service-accounts/view.tsx
  src/renderer/components/+workloads-cronjobs/cronjob-trigger-dialog.tsx
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-daemonsets/daemonsets.tsx
  src/renderer/components/+workloads-deployments/deployments.tsx
  src/renderer/components/+workloads-jobs/jobs.tsx
  src/renderer/components/+workloads-overview/overview-statuses.tsx
  src/renderer/components/+workloads-pods/pod-tolerations.tsx
  src/renderer/components/+workloads-pods/pods.tsx
  src/renderer/components/+workloads-replicasets/replicasets.tsx
  src/renderer/components/+workloads-statefulsets/statefulsets.tsx
  src/renderer/components/+workloads/workloads.stores.ts
  src/renderer/components/dock/edit-resource.store.ts
  src/renderer/components/item-object-list/item-list-layout.tsx
  src/renderer/components/kube-object/kube-object-details.tsx
  src/renderer/components/kube-object/kube-object-list-layout.tsx
  src/renderer/components/kube-object/kube-object-meta.tsx
  src/renderer/components/table/table.tsx
  src/renderer/initializers/kube-object-detail-registry.tsx
  src/renderer/item.store.ts
  src/renderer/kube-object.store.ts
Labels: area/extension, enhancement

#3489 Filter out undefined values in hotbar-store migration
  src/migrations/hotbar-store/5.0.0-beta.10.ts
Labels: bug

#3385 Treat default weblinks same as any other weblinks
  package.json
  src/common/catalog-entities/web-link.ts
  src/common/weblink-store.ts
  src/main/catalog-sources/weblinks.ts
  src/migrations/weblinks-store/5.1.4.ts
  src/migrations/weblinks-store/index.ts
Labels: bug

#3494 Fix entity settings menu order
  src/renderer/components/+entity-settings/entity-settings.tsx
Labels: area/ui, bug

#3497 Fix input default value warning
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/input/input.tsx
Labels: area/ui, bug

#3475 Display hint to user on how to add items in an EditableList
  src/renderer/components/editable-list/editable-list.tsx
  src/renderer/components/input/input.tsx
Labels: bug

#3507 Fix entity accessibleNamespaces
  src/main/cluster-manager.ts
Labels: blocker, bug

#3505 Fix auto cleanup of Extension's IPC classes
  src/extensions/ipc/ipc-main.ts
  src/extensions/ipc/ipc-renderer.ts
  src/renderer/navigation/events.ts
Labels: area/extension, blocker, bug

#3511 increase timeout for getPortFrom()
  src/main/utils/get-port.ts
Labels: bug

#3486 Fix workload overview status sorting
  src/renderer/api/kube-json-api.ts
  src/renderer/components/+workloads-cronjobs/cronjob.store.ts
  src/renderer/components/+workloads-daemonsets/daemonsets.store.ts
  src/renderer/components/+workloads-deployments/deployments.store.ts
  src/renderer/components/+workloads-jobs/job.store.ts
  src/renderer/components/+workloads-pods/pods.store.ts
  src/renderer/components/+workloads-replicasets/replicasets.store.ts
  src/renderer/components/+workloads-statefulsets/statefulset.store.ts
  src/renderer/components/__tests__/cronjob.store.test.ts
  src/renderer/components/__tests__/daemonset.store.test.ts
  src/renderer/components/__tests__/deployments.store.test.ts
  src/renderer/components/__tests__/job.store.test.ts
  src/renderer/components/__tests__/pods.store.test.ts
  src/renderer/components/__tests__/replicaset.store.test.ts
  src/renderer/components/__tests__/statefulset.store.test.ts
  src/renderer/components/badge/badge.module.css
  src/renderer/components/chart/chart.tsx
Labels: area/ui, bug

#3496 Installing tailwindcss/nesting plugin
  package.json
  postcss.config.js
  src/renderer/components/+catalog/catalog-tree.module.css
  src/renderer/components/+extensions/install.module.css
  yarn.lock
Labels: chore

#3502 Only stopPropagration in onClick for the itemMenu
  src/renderer/components/item-object-list/item-list-layout.tsx
Labels: bug

#3490 Improve <NamespaceSelectFilter>'s UX
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/+namespaces/namespace-select.tsx
  src/renderer/components/input/input.tsx
Labels: area/ui, enhancement

#3462 Warn if ClusterPageMenuRegistration is a subMenu and has an Icon
  src/renderer/components/layout/sidebar.tsx
Labels: area/extension, chore

#3454 Set defaults for EndpointSubsets
  src/renderer/api/__tests__/endpoint.api.test.ts
  src/renderer/api/endpoints/endpoint.api.ts
Labels: bug

#3520 Fix crd resources watch issue
  src/renderer/components/+custom-resources/crd-resources.tsx
Labels: blocker, bug

#3524 Fix KubernetesClusters overriding entity names too often
  src/main/cluster-manager.ts
Labels: blocker, bug

#3504 Remove package open
  package.json
  yarn.lock
Labels: dependencies

#3528 Set default type params for KubeObjectDetail related APIs
  src/extensions/registries/kube-object-detail-registry.ts
  src/renderer/components/kube-object/kube-object-details.tsx
Labels: area/extension, bug

#3537 Fixing <Tab/> onKeyDown error
  src/renderer/components/tabs/tabs.tsx
Labels: area/ui, bug
