Repository lensapp/lens, pull requests merged in 2022-01, with the labels that each got.

#4627 Removing JS adding #terminal-init so that unit tests don't have global state
  src/renderer/components/app.scss
  src/renderer/components/dock/terminal.ts
  src/renderer/template.html
Labels: bug

#4553 Fix CRD.getPreferedVersion() to work based on apiVersion
  src/common/k8s-api/__tests__/crd.test.ts
  src/common/k8s-api/endpoints/crd.api.ts
Labels: bug

#4577 Add eslint:recommended lint rule
  .eslintrc.js
  src/common/__tests__/cluster-store.test.ts
  src/common/k8s-api/__tests__/kube-object.test.ts
  src/common/k8s-api/endpoints/crd.api.ts
  src/common/k8s-api/endpoints/ingress.api.ts
  src/common/k8s-api/endpoints/metrics.api.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/protocol-handler/router.ts
  src/common/search-store.ts
  src/common/utils/defineGlobal.ts
  src/common/utils/iter.ts
  src/common/utils/tar.ts
  src/main/helm/helm-repo-manager.ts
  src/main/initializers/ipc.ts
  src/main/kubectl.ts
  src/main/shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/migrations/cluster-store/2.0.0-beta.2.ts
  src/migrations/cluster-store/2.6.0-beta.3.ts
  src/renderer/components/+config-autoscalers/hpa-details.tsx
  src/renderer/components/+extensions/get-base-registry-url/get-base-registry-url.tsx
  src/renderer/components/file-picker/file-picker.tsx
  src/renderer/components/icon/icon.tsx
  src/renderer/components/input/input_validators.ts
  src/renderer/components/menu/menu.tsx
  src/renderer/utils/createStorage.ts
Labels: chore

#4607 Keep port-forward objects around when not running
  src/main/router.ts
  src/main/routes/port-forward-route.ts
  src/renderer/components/+network-port-forwards/port-forward-menu.tsx
  src/renderer/components/+network-port-forwards/port-forwards.tsx
  src/renderer/components/+network-services/service-port-component.tsx
  src/renderer/components/+network/network-mixins.scss
  src/renderer/components/+workloads-pods/pod-container-port.tsx
  src/renderer/port-forward/port-forward-dialog.tsx
  src/renderer/port-forward/port-forward-item.ts
  src/renderer/port-forward/port-forward-notify.tsx
  src/renderer/port-forward/port-forward-utils.ts
  src/renderer/port-forward/port-forward.store.ts
Labels: enhancement, area/port-forwarding

#4668 ensure old, saved port-forwards get loaded
  src/renderer/port-forward/port-forward.store.ts
Labels: bug, area/port-forwarding

#4675 Fix crash for KubeObjectStore.loadAll()
  src/common/k8s-api/kube-object.store.ts
Labels: bug

#4674 Fix Kubectl.downloadKubectl()
  src/main/kubectl.ts
Labels: bug

#4385 Reroute to landing page from previously registered extension cluster pages
  src/extensions/registries/page-registry.ts
  src/renderer/cluster-frame.tsx
  src/renderer/components/+404/index.ts
  src/renderer/components/+404/not-found.tsx
Labels: bug

#4666 Allow to customize terminal theme
  src/common/user-store/preferences-helpers.ts
  src/common/user-store/user-store.ts
  src/renderer/components/+preferences/application.tsx
  src/renderer/components/dock/dock.scss
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/terminal.ts
  src/renderer/theme.store.ts
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
Labels: enhancement, area/ui

#4682 Revert "Allow to customize terminal theme (#4666)"
  src/common/user-store/preferences-helpers.ts
  src/common/user-store/user-store.ts
  src/renderer/components/+preferences/application.tsx
  src/renderer/components/dock/dock.scss
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/terminal.ts
  src/renderer/theme.store.ts
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
Labels: area/ui, chore

#4687 replacing the deprecated substr() with slice()
  src/common/k8s-api/endpoints/crd.api.ts
  src/common/utils/getRandId.ts
Labels: chore

#4679 Fix: remove hotbar name from status bar
  src/renderer/bootstrap.tsx
  src/renderer/components/cluster-manager/active-hotbar-name.tsx
  src/renderer/components/cluster-manager/bottom-bar.test.tsx
  src/renderer/components/hotbar/hotbar-selector.module.scss
  src/renderer/components/hotbar/hotbar-selector.tsx
  src/renderer/components/tooltip/tooltip.scss
  src/renderer/components/tooltip/tooltip.tsx
  src/renderer/initializers/index.ts
  src/renderer/initializers/status-bar-registry.tsx
Labels: bug, area/ui

#4702 Support extending KubernetesCluster in extensions
  docs/extensions/guides/README.md
  docs/extensions/guides/extending-kubernetes-cluster.md
  mkdocs.yml
  src/common/catalog-entities/kubernetes-cluster.ts
  src/extensions/extension-loader/extension-loader.ts
  src/extensions/lens-extension.ts
  src/main/catalog/catalog-entity-registry.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
  src/renderer/frames/root-frame/init-root-frame/init-root-frame.ts
Labels: enhancement, area/extension

#4692 fix inputs not blurring when pressing enter
  src/renderer/components/editable-list/editable-list.tsx
  src/renderer/components/input/input.tsx
  src/renderer/components/wizard/wizard.tsx
Labels: bug, area/ui

#4671 Refactor app-preferences-registry to use di
  .eslintrc.js
  package.json
  src/extensions/common-api/registrations.ts
  src/extensions/extension-loader/extension-loader.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/index.ts
  src/renderer/components/+preferences/app-preferences/app-preference-registration.d.ts
  src/renderer/components/+preferences/app-preferences/app-preferences.injectable.ts
  src/renderer/components/+preferences/app-preferences/get-app-preferences.ts
  src/renderer/components/+preferences/application.tsx
  src/renderer/components/+preferences/extension-settings.tsx
  src/renderer/components/+preferences/extensions.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/+preferences/telemetry.tsx
  src/renderer/initializers/registries.ts
  yarn.lock
Labels: chore

#4708 Add support for custom columns on catalog categories
  Makefile
  docs/extensions/guides/README.md
  docs/extensions/guides/catalog.md
  docs/extensions/guides/main-extension.md
  src/common/catalog/catalog-entity.ts
  src/common/utils/__tests__/bind.test.ts
  src/common/utils/collection-functions.ts
  src/common/utils/index.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/renderer-api/components.ts
  src/extensions/renderer-extensions.injectable.ts
  src/renderer/components/+catalog/__tests__/custom-columns.test.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+catalog/custom-category-columns.injectable.tsx
  src/renderer/components/+catalog/custom-category-columns.ts
  src/renderer/components/+catalog/get-category-columns.injectable.ts
  src/renderer/components/+catalog/internal-category-columns.tsx
  src/renderer/components/table/table-cell.tsx
Labels: enhancement, area/extension, blocker

#4688 PortForwards on main process no longer need to track the protocol
  src/main/routes/port-forward-route.ts
  src/main/routes/port-forward/port-forward.ts
  src/main/routes/port-forward/route-port-forward/route-port-forward.ts
  src/renderer/port-forward/port-forward-store/port-forward-store.ts
Labels: chore

#4721 Release/v5.3.4
  integration/__tests__/app-preferences.tests.ts
  package.json
  src/common/cluster-types.ts
  src/common/k8s-api/__tests__/crd.test.ts
  src/common/k8s-api/endpoints/crd.api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/system-ca.ts
  src/common/utils/promise-exec.ts
  src/extensions/__tests__/extension-compatibility.test.ts
  src/extensions/extension-compatibility.ts
  src/main/cluster-manager.ts
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-repo-manager.ts
  src/main/helm/helm-service.ts
  src/main/kubectl.ts
  src/main/lens-proxy.ts
  src/main/prometheus/operator.ts
  src/main/routes/metrics-route.ts
  src/renderer/components/+network-policies/__tests__/network-policy-details.test.tsx
  src/renderer/components/+network-policies/network-policy-details.module.css
  src/renderer/components/+network-policies/network-policy-details.tsx
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/clipboard/clipboard.scss
  src/renderer/components/clipboard/clipboard.tsx
  src/renderer/components/cluster-settings/components/cluster-icon-settings.tsx
  src/renderer/components/dialog/logs-dialog.tsx
  src/renderer/components/kubeconfig-dialog/kubeconfig-dialog.tsx
  src/renderer/components/layout/close-button.scss
  src/renderer/components/layout/close-button.tsx
  src/renderer/components/layout/setting-layout.scss
  src/renderer/components/layout/setting-layout.tsx
  src/renderer/components/select/select.scss
  src/renderer/utils/index.ts
  tailwind.config.js
Labels: skip-changelog

#4694 Font settings for editor and ternimal
  src/common/routes/preferences.ts
  src/common/user-store/preferences-helpers.ts
  src/common/user-store/user-store.ts
  src/common/vars.ts
  src/renderer/components/+preferences/application.tsx
  src/renderer/components/+preferences/editor.tsx
  src/renderer/components/+preferences/preferences.tsx
  src/renderer/components/+preferences/terminal.tsx
  src/renderer/components/dock/terminal/terminal.ts
Labels: enhancement, area/ui

#4710 Fix infinite render loop in release details
  package.json
  src/common/k8s-api/endpoints/helm-releases.api.ts
  src/renderer/components/+apps-releases/create-release/create-release.injectable.ts
  src/renderer/components/+apps-releases/delete-release/delete-release.injectable.ts
  src/renderer/components/+apps-releases/release-details.tsx
  src/renderer/components/+apps-releases/release-details/release-details.injectable.ts
  src/renderer/components/+apps-releases/release-details/release-details.scss
  src/renderer/components/+apps-releases/release-details/release-details.tsx
  src/renderer/components/+apps-releases/release-details/release-route-parameters.injectable.ts
  src/renderer/components/+apps-releases/release-details/release-values.injectable.ts
  src/renderer/components/+apps-releases/release-details/release.injectable.ts
  src/renderer/components/+apps-releases/release-details/user-supplied-values-are-shown.injectable.ts
  src/renderer/components/+apps-releases/release-menu.tsx
  src/renderer/components/+apps-releases/release-rollback-dialog.tsx
  src/renderer/components/+apps-releases/release-store.injectable.ts
  src/renderer/components/+apps-releases/release.store.ts
  src/renderer/components/+apps-releases/releases.injectable.ts
  src/renderer/components/+apps-releases/releases.tsx
  src/renderer/components/+apps-releases/removable-releases.injectable.ts
  src/renderer/components/+apps-releases/removable-releases.ts
  src/renderer/components/+apps-releases/rollback-release/rollback-release.injectable.ts
  src/renderer/components/+apps-releases/update-release/update-release.injectable.ts
  src/renderer/components/dock/install-chart.tsx
  src/renderer/components/dock/upgrade-chart-store/upgrade-chart-store.injectable.ts
  src/renderer/components/dock/upgrade-chart-store/upgrade-chart.store.ts
  src/renderer/components/dock/upgrade-chart.tsx
  src/renderer/components/drawer/drawer.tsx
  src/renderer/frames/cluster-frame/cluster-frame.tsx
  src/renderer/frames/root-frame/root-frame.tsx
  src/renderer/navigation/history.injectable.ts
  src/renderer/navigation/history.ts
  src/renderer/navigation/observable-history.injectable.ts
  yarn.lock
Labels: bug

#4733 Add extension API for registering custom category views
  docs/extensions/guides/catalog.md
  src/common/utils/collection-functions.ts
  src/extensions/common-api/registrations.ts
  src/extensions/lens-renderer-extension.ts
  src/renderer/components/+catalog/__tests__/custom-views.test.ts
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+catalog/custom-category-columns.injectable.tsx
  src/renderer/components/+catalog/custom-views.injectable.ts
  src/renderer/components/+catalog/custom-views.ts
Labels: enhancement, area/extension

#4737 Fix: keep ItemListLayout scrollable with custom catalog category views
  src/renderer/components/+catalog/catalog.module.scss
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/layout/main-layout.module.scss
Labels: bug, area/ui

#4738 Fix pod logs dock tab
  src/common/utils/collection-functions.ts
  src/extensions/renderer-api/components.ts
  src/renderer/components/dock/__test__/log-resource-selector.test.tsx
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/log-store/reloaded-log-store.injectable.ts
  src/renderer/components/dock/logs.tsx
  src/renderer/components/dock/logs/__test__/log-resource-selector.test.tsx
  src/renderer/components/dock/logs/__test__/log-tab.store.test.ts
  src/renderer/components/dock/logs/__test__/pod.mock.ts
  src/renderer/components/dock/logs/__test__/to-bottom.test.tsx
  src/renderer/components/dock/logs/call-for-logs.injectable.ts
  src/renderer/components/dock/logs/controls.scss
  src/renderer/components/dock/logs/controls.tsx
  src/renderer/components/dock/logs/dock-tab.tsx
  src/renderer/components/dock/logs/get-log-tab-data.injectable.ts
  src/renderer/components/dock/logs/get-logs-without-timestamps.injectable.ts
  src/renderer/components/dock/logs/get-logs.injectable.ts
  src/renderer/components/dock/logs/get-timestamp-split-logs.injectable.ts
  src/renderer/components/dock/logs/list.scss
  src/renderer/components/dock/logs/list.tsx
  src/renderer/components/dock/logs/load-logs.injectable.ts
  src/renderer/components/dock/logs/logs-view-model.injectable.ts
  src/renderer/components/dock/logs/logs-view-model.ts
  src/renderer/components/dock/logs/logs-view-model/logs-view-model.injectable.ts
  src/renderer/components/dock/logs/logs-view-model/logs-view-model.ts
  src/renderer/components/dock/logs/reload-logs.injectable.ts
  src/renderer/components/dock/logs/resource-selector.scss
  src/renderer/components/dock/logs/resource-selector.tsx
  src/renderer/components/dock/logs/search.scss
  src/renderer/components/dock/logs/search.tsx
  src/renderer/components/dock/logs/set-log-tab-data.injectable.ts
  src/renderer/components/dock/logs/stop-loading-logs.injectable.ts
  src/renderer/components/dock/logs/store.injectable.ts
  src/renderer/components/dock/logs/store.ts
  src/renderer/components/dock/logs/tab-store.injectable.ts
  src/renderer/components/dock/logs/tab.store.ts
  src/renderer/components/dock/logs/to-bottom.tsx
  src/renderer/components/dock/logs/update-tab-name.injectable.ts
  src/renderer/search-store/search-store.injectable.ts
  src/renderer/search-store/search-store.test.ts
  src/renderer/search-store/search-store.ts
  src/renderer/utils/interval.ts
Labels: bug, blocker

#4749 Export missing k8s api types for extensions
  src/extensions/main-api/k8s-api.ts
  src/extensions/renderer-api/k8s-api.ts
Labels: bug, area/extension

#4761 Fix: remove catalog first column padding
  src/renderer/components/+catalog/catalog.module.scss
Labels: bug, area/ui

#4762 Fix: do not pass blurOnEnter to html element
  src/renderer/components/input/input.tsx
Labels: bug, area/ui

#4756 Fix multi-document support in monaco editor
  src/renderer/components/monaco-editor/monaco-validators.ts
Labels: bug

#4752 Allow users of KubeObjectListLayout to override all props of ItemListLayout
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
Labels: bug, area/extension

#4763 Ensure that CatalogEntity.getName() and CatalogEntity.getId() are always used
  src/common/__tests__/hotbar-store.test.ts
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog-entities/web-link.ts
  src/common/catalog/catalog-entity.ts
  src/common/hotbar-store.ts
  src/main/catalog/catalog-entity-registry.ts
  src/main/cluster-manager.ts
  src/migrations/hotbar-store/5.0.0-beta.5.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/components/+catalog/catalog-entity-item.tsx
  src/renderer/components/+entity-settings/entity-settings.tsx
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-icon-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-name-setting.tsx
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
  src/renderer/components/layout/sidebar-cluster.tsx
  src/renderer/initializers/catalog.tsx
Labels: bug, blocker

#4728 Replace StatusBarRegistry with reactive solution
  src/extensions/common-api/registrations.ts
  src/extensions/extension-loader/extension-loader.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/index.ts
  src/renderer/components/cluster-manager/bottom-bar-items.injectable.ts
  src/renderer/components/cluster-manager/bottom-bar.test.tsx
  src/renderer/components/cluster-manager/bottom-bar.tsx
  src/renderer/components/cluster-manager/status-bar-registration.d.ts
  src/renderer/initializers/registries.ts
Labels: chore

#4770 Fix item menus for several pages
  src/renderer/components/+user-management/+service-accounts/view.tsx
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-deployments/deployments.tsx
  src/renderer/components/+workloads-replicasets/replicasets.tsx
  src/renderer/components/+workloads-statefulsets/statefulsets.tsx
Labels: bug, area/ui, blocker

#4755 Upgrade to latest for all linting deps
  .eslintrc.js
  package.json
  src/common/ipc-channel/channel.ts
  src/common/item.store.ts
  src/common/k8s-api/kube-watch-event.ts
  src/common/utils/extended-map.ts
  src/extensions/extensions-store/extensions-store.ts
  src/main/menu/menu-registration.ts
  src/main/tray/tray-menu-registration.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+apps-helm-charts/helm-chart-details.tsx
  src/renderer/components/+catalog/catalog-add-button.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+extensions/attempt-install/install-request.ts
  src/renderer/components/+preferences/app-preferences/app-preference-registration.ts
  src/renderer/components/+preferences/kubeconfig-syncs.tsx
  src/renderer/components/+user-management/+cluster-role-bindings/dialog.tsx
  src/renderer/components/+user-management/+role-bindings/dialog.tsx
  src/renderer/components/+user-management/+service-accounts/details.tsx
  src/renderer/components/+welcome/welcome-banner-items/welcome-banner-registration.ts
  src/renderer/components/+welcome/welcome-menu-items/welcome-menu-registration.ts
  src/renderer/components/+workloads-pods/pod-details-secrets.tsx
  src/renderer/components/command-palette/registered-commands/commands.ts
  src/renderer/components/dialog/dialog.tsx
  src/renderer/components/dock/dock-store/dock.store.ts
  src/renderer/components/dock/install-chart.tsx
  src/renderer/components/dock/logs/list.tsx
  src/renderer/components/dock/upgrade-chart.tsx
  src/renderer/components/icon/icon.tsx
  src/renderer/components/input/search-input-url.tsx
  src/renderer/components/kube-object-details/kube-object-details.tsx
  src/renderer/components/layout/top-bar/top-bar-registration.ts
  src/renderer/components/monaco-editor/monaco-editor.tsx
  src/renderer/components/resizing-anchor/resizing-anchor.tsx
  yarn.lock
Labels: chore

#4775 Fix failing lint in master
  src/renderer/components/cluster-manager/status-bar-registration.ts
Labels: bug, area/ui

#4776 Fix: increase catalog entity name col width
  src/renderer/components/+catalog/catalog-tree.module.scss
  src/renderer/components/+catalog/catalog.module.scss
  src/renderer/components/table/table-head.scss
Labels: bug, area/ui

#4779 Fix build due to removal of old extended collections
  src/common/user-store/preferences-helpers.ts
  src/common/user-store/user-store.ts
  src/common/utils/collection-functions.ts
  src/common/utils/index.ts
  src/common/utils/toggle-set.ts
  src/renderer/components/+config-secrets/secret-details.tsx
  src/renderer/components/+namespaces/namespace-store/namespace.store.ts
  src/renderer/components/item-object-list/list-layout.tsx
Labels: bug

#4778 Disable native window open
  src/main/window-manager.ts
Labels: bug, area/extension, blocker
