Repository lensapp/lens, pull requests merged in 2022-02, with the labels that each got.

#4742 select all on helm releases now selects all or none (toggles)
  src/renderer/components/+apps-releases/releases.tsx
Labels: bug, area/ui

#4771 Update Node.getRoleLabels() to work with kube 1.16's defaults
  src/common/k8s-api/__tests__/nodes.test.ts
  src/common/k8s-api/endpoints/nodes.api.ts
Labels: bug

#4780 release v5.4.0-alpha.0
  package.json
Labels: skip-changelog

#4785 Fix bugs in helm releases
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-service.ts
  src/main/routes/helm-route.ts
  src/renderer/components/+apps-releases/update-release/update-release.injectable.ts
  src/renderer/components/dock/upgrade-chart/view.tsx
Labels: bug

#4789 Fix quota entries layout in Add Resource Quota dialog
  src/renderer/components/+config-resource-quotas/add-quota-dialog.scss
Labels: bug, area/ui

#4791 Fix dialog icons hover color
  src/renderer/components/+catalog/catalog.module.scss
  src/renderer/components/icon/icon.scss
Labels: bug, area/ui

#4792 Fix bugs in ItemListLayouts/KubeObjectListLayouts
  src/renderer/components/+apps-releases/release-details/release-details.injectable.ts
  src/renderer/components/+apps-releases/release-details/release-details.tsx
  src/renderer/components/+apps-releases/release-details/release-values.injectable.ts
  src/renderer/components/+apps-releases/release-details/release.injectable.ts
  src/renderer/components/+events/events.tsx
  src/renderer/components/item-object-list/content.tsx
  src/renderer/components/kube-detail-params/params.ts
Labels: bug

#4797 release v5.4.0-alpha.1
  package.json
Labels: skip-changelog

#4800 Use system-node-critical for the node shell pod
  src/main/shell-session/node-shell-session/node-shell-session.ts
Labels: bug

#4808 Fix ItemListLayouts scrolling to top involuntarely
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  src/renderer/components/kube-object-menu/kube-object-menu.tsx
  src/renderer/components/table/table.tsx
Labels: bug, blocker

#4807 Fix unresponsive kubectl download binaries switch
  src/renderer/components/+preferences/kubectl-binaries.tsx
  src/renderer/components/+preferences/terminal.tsx
Labels: bug, area/ui

#4783 Use electronegativity to identify misconfigurations and security issues
  .github/workflows/electronegativity.yml
Labels: area/security, area/ci

#4787 adding some rough notes to release guide to help with making changelogs
  RELEASE_GUIDE.md
Labels: area/documentation

#4809 Fix electronegativity workflow config
  .github/workflows/electronegativity.yml
Labels: area/ci

#4810 Fix 'mkdocs deploy master' workflow
  .github/workflows/main.yml
Labels: area/ci

#4812 release v5.4.0-beta.0
  package.json
Labels: skip-changelog

#4825 release v5.4.0-beta.1
  package.json
Labels: skip-changelog

#4828 Fix observation of asyncComputed when invalidated before ever observed
  package.json
  yarn.lock
Labels: bug

#4794 Fix not being able to install extensions sometimes
  src/renderer/components/+extensions/attempt-install/attempt-install.tsx
Labels: bug, area/extension

#4798 Only group delete visible items
  src/common/item.store.ts
  src/common/k8s-api/kube-object.store.ts
  src/renderer/components/+helm-releases/releases.tsx
  src/renderer/components/item-object-list/content.tsx
  src/renderer/components/item-object-list/list-layout.tsx
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  src/renderer/port-forward/port-forward-store/port-forward-store.ts
Labels: bug

#4826 Fix Cluster.refresh sometimes taking upwards of 20s
  src/common/cluster/authorization-review.injectable.ts
  src/common/cluster/cluster.ts
  src/common/cluster/list-namespaces.injectable.ts
  src/main/__test__/cluster.test.ts
  src/main/create-cluster/create-cluster.injectable.ts
  src/renderer/create-cluster/create-cluster.injectable.ts
Labels: bug

#4831 Fix custom-resource navigation
  src/renderer/components/+custom-resources/route-tabs.injectable.ts
  src/renderer/components/+custom-resources/route.tsx
Labels: bug, blocker

#4835 Fix extension sidebar items sometimes being expandable
  src/renderer/components/+config/sidebar-item.tsx
  src/renderer/components/+helm/sidebar-item.tsx
  src/renderer/components/+network/sidebar-item.tsx
  src/renderer/components/+storage/sidebar-item.tsx
  src/renderer/components/+user-management/sidebar-item.tsx
  src/renderer/components/+workloads/sidebar-item.tsx
  src/renderer/components/layout/sidebar-item.tsx
  src/renderer/components/layout/sidebar.tsx
  src/renderer/components/layout/tab-routes-sidebar-items.tsx
Labels: bug

#4839 Restrict title name to be only string
  src/renderer/components/+catalog/custom-category-columns.ts
Labels: bug, area/extension

#4836 Helm v3.7.2
  package.json
Labels: enhancement, area/helm

#4838 Fix StatusBar extension API
  src/extensions/common-api/registrations.ts
  src/extensions/lens-renderer-extension.ts
  src/renderer/components/cluster-manager/bottom-bar-items.injectable.ts
  src/renderer/components/cluster-manager/bottom-bar.module.scss
  src/renderer/components/cluster-manager/bottom-bar.tsx
  src/renderer/components/cluster-manager/cluster-manager.scss
  src/renderer/components/cluster-manager/cluster-manager.tsx
  src/renderer/components/cluster-manager/status-bar-registration.ts
  src/renderer/components/layout/main-layout.module.scss
  src/renderer/components/status-bar/registered-status-bar-items.injectable.tsx
  src/renderer/components/status-bar/status-bar-items.injectable.ts
  src/renderer/components/status-bar/status-bar-registration.ts
  src/renderer/components/status-bar/status-bar.module.scss
  src/renderer/components/status-bar/status-bar.test.tsx
  src/renderer/components/status-bar/status-bar.tsx
Labels: bug, area/extension

#4837 Bundle kubectl 1.23.3
  package.json
  src/main/kubectl/kubectl.ts
Labels: dependencies, area/kubernetes-next

#4805 Don't block other extensions from loading if one activation fails
  src/extensions/extension-loader/extension-loader.ts
  src/extensions/lens-extension.ts
Labels: bug

#4850 Consolidate way of passing items to ItemListLayout
  src/renderer/components/+helm-charts/helm-charts.tsx
  src/renderer/components/+helm-releases/releases.tsx
  src/renderer/components/+network-port-forwards/port-forwards.tsx
  src/renderer/components/item-object-list/list-layout.tsx
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
Labels: chore

#4854 Rename KubernetesCluster MenuItem from Delete to Remove
  integration/__tests__/cluster-pages.tests.ts
  src/renderer/initializers/catalog.tsx
Labels: area/ui, chore

#4725 Upgrade to webpack@5
  __mocks__/assetMock.ts
  extensions/kube-object-event-status/package-lock.json
  extensions/kube-object-event-status/package.json
  extensions/metrics-cluster-feature/package-lock.json
  extensions/metrics-cluster-feature/package.json
  extensions/node-menu/package-lock.json
  extensions/node-menu/package.json
  extensions/pod-menu/package-lock.json
  extensions/pod-menu/package.json
  package.json
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog/catalog-category-registry.ts
  src/common/getTSLoader.ts
  src/common/user-store/user-store.ts
  src/main/catalog/catalog-entity-registry.ts
  src/main/index.ts
  src/main/menu/menu.ts
  src/main/router.ts
  src/main/window-manager.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+catalog/catalog-entity-details.tsx
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/+catalog/catalog-menu.tsx
  src/renderer/components/+cluster/cluster-overview-store/cluster-overview-store.ts
  src/renderer/components/+helm-charts/helm-chart-details.tsx
  src/renderer/components/+helm-releases/release-rollback-dialog.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-jobs/job-details.tsx
  src/renderer/components/+workloads-pods/pod-details.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/dock/terminal/terminal.ts
  src/renderer/components/dock/upgrade-chart/view.tsx
  src/renderer/components/fonts.scss
  src/renderer/components/fonts/MaterialIcons-Regular.ttf
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
  src/renderer/components/icon/icon.tsx
  src/renderer/components/select/select.tsx
  src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
  types/mocks.d.ts
  webpack.dev-server.ts
  webpack.extensions.ts
  webpack.main.ts
  webpack.renderer.ts
  yarn.lock
Labels: area/ui, chore

#4874 Fix: closing terminal tab error
  src/renderer/api/websocket-api.ts
Labels: bug, area/terminal

#4872 Revert "Upgrade to webpack@5 (#4725)"
  __mocks__/imageMock.ts
  extensions/kube-object-event-status/package-lock.json
  extensions/kube-object-event-status/package.json
  extensions/metrics-cluster-feature/package-lock.json
  extensions/metrics-cluster-feature/package.json
  extensions/node-menu/package-lock.json
  extensions/node-menu/package.json
  extensions/pod-menu/package-lock.json
  extensions/pod-menu/package.json
  package.json
  src/common/catalog-entities/kubernetes-cluster.ts
  src/common/catalog/catalog-category-registry.ts
  src/common/getTSLoader.ts
  src/common/user-store/user-store.ts
  src/main/catalog/catalog-entity-registry.ts
  src/main/index.ts
  src/main/menu/menu.ts
  src/main/router.ts
  src/main/window-manager.ts
  src/renderer/api/catalog-entity-registry.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+catalog/catalog-entity-details.tsx
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/+catalog/catalog-menu.tsx
  src/renderer/components/+cluster/cluster-overview-store/cluster-overview-store.ts
  src/renderer/components/+helm-charts/helm-chart-details.tsx
  src/renderer/components/+helm-releases/release-rollback-dialog.tsx
  src/renderer/components/+namespaces/namespace-details.tsx
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+workloads-daemonsets/daemonset-details.tsx
  src/renderer/components/+workloads-deployments/deployment-details.tsx
  src/renderer/components/+workloads-jobs/job-details.tsx
  src/renderer/components/+workloads-pods/pod-details.tsx
  src/renderer/components/+workloads-replicasets/replicaset-details.tsx
  src/renderer/components/+workloads-statefulsets/statefulset-details.tsx
  src/renderer/components/dock/terminal/terminal.ts
  src/renderer/components/dock/upgrade-chart/view.tsx
  src/renderer/components/fonts.scss
  src/renderer/components/hotbar/hotbar-entity-icon.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
  src/renderer/components/icon/icon.tsx
  src/renderer/components/select/select.tsx
  src/renderer/fonts/MaterialIcons-Regular.ttf
  src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
  types/mocks.d.ts
  webpack.dev-server.ts
  webpack.extensions.ts
  webpack.main.ts
  webpack.renderer.ts
  yarn.lock
Labels: chore

#4891 nick-invision/retry package changed ownership
  .github/workflows/test.yml
Labels: chore

#4868 release v5.4.0-beta.2
  package.json
Labels: skip-changelog

#3292 Refine UserStore from/to usage
  src/common/user-store/user-store.ts
  src/common/utils/objects.ts
Labels: chore, p2

#4564 Cleanup HelmRepoManager and <HelmCharts>
  integration/__tests__/app-preferences.tests.ts
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-repo-manager.ts
  src/renderer/components/+preferences/add-helm-repo-dialog.tsx
  src/renderer/components/+preferences/helm-charts.tsx
Labels: chore

#3310 Remove ExtenedMap, ToggleSet, and observable versions
  src/common/catalog/catalog-category-registry.ts
  src/common/utils/collection-functions.ts
  src/common/utils/extended-map.ts
  src/common/utils/index.ts
  src/main/catalog-sources/kubeconfig-sync-manager/kubeconfig-sync-manager.ts
  src/main/proxy-functions/shell-api-request/shell-request-authenticator/shell-request-authenticator.ts
  src/migrations/helpers.ts
  src/renderer/components/+config-secrets/secret-details.tsx
  src/renderer/components/+preferences/kubeconfig-syncs.tsx
  src/renderer/initializers/catalog-category-registry.tsx
Labels: chore, p2

#4876 Introduce and use "openBrowser"
  src/common/utils/index.ts
  src/common/utils/openBrowser.ts
  src/common/utils/openExternal.ts
  src/extensions/common-api/utils.ts
  src/main/menu/menu.ts
  src/main/window-manager.ts
  src/renderer/port-forward/port-forward-utils.ts
Labels: bug, area/security

#4918 release v5.4.0-beta.3
  package.json
Labels: skip-changelog

#4919 Fix UnhandledPromiseRejectionWarning in KubeApi.watch
  src/common/k8s-api/kube-api.ts
Labels: bug

#4911 Fix catalog syncer long delay
  src/main/catalog-pusher.ts
  src/main/index.ts
Labels: bug

#4904 Revert accidental breaking change in Extension API
  src/common/k8s-api/kube-object.store.ts
  src/renderer/components/+namespaces/add-namespace-dialog.tsx
Labels: bug

#4925 Use official helm icon
  src/renderer/components/+helm/sidebar-item.tsx
  src/renderer/components/icon/helm.svg
Labels: enhancement, area/ui

#4905 Show helm details fetch errors in Notifications
  src/renderer/components/+helm-charts/helm-chart-details.tsx
Labels: bug, area/helm

#4930 release v5.4.0-beta.5
  package.json
Labels: skip-changelog

#4869 Updated typescript target to ES2019
  src/common/getTSLoader.ts
  tsconfig.json
Labels: chore

#4871 Bump concurrently version to fix windows 10 builds
  package.json
  yarn.lock
Labels: dependencies

#4935 Reduce cluster logging on quit
  src/common/cluster/cluster.ts
Labels: chore
