Repository lensapp/lens, pull requests merged in 2022-09, with the labels that each got.

#6152 reinstate integration tests on windows
  integration/__tests__/app-preferences.tests.ts
  integration/__tests__/command-palette.tests.ts
Labels: chore

#6143 Bump typescript, @typescript-eslint/eslint-plugin, and @typescript-eslint/parser
  package.json
  src/common/base-store.ts
  src/common/get-configuration-file-model/get-configuration-file-model.injectable.ts
  src/common/k8s-api/endpoints/metrics.api.ts
  src/common/protocol-handler/router.ts
  src/common/utils/readableStream.ts
  src/common/utils/singleton.ts
  src/extensions/as-legacy-globals-for-extension-api/as-legacy-global-object-for-extension-api-with-modifications.ts
  src/extensions/extension-store.ts
  src/main/routes/metrics/add-metrics-route.injectable.ts
  src/main/routes/metrics/metrics-query.ts
  src/renderer/api/helpers/watch-for-general-entity-navigation.injectable.ts
  src/renderer/navigation/index.ts
  src/renderer/navigation/match-route.injectable.ts
  src/renderer/utils/storageHelper.ts
  yarn.lock
Labels: dependencies

#6160 Update snapshots from other work
  src/behaviours/pod-logs/__snapshots__/download-logs.test.tsx.snap
  src/features/cluster/__snapshots__/workload-overview.test.tsx.snap
Labels: chore

#6158 Reset Prometheus metrics provider on disconnect
  src/main/context-handler/context-handler.ts
Labels: enhancement, area/metrics

#6157 Add Prometheus Helm 14.x metrics provider
  src/main/prometheus/helm-14.ts
  src/main/start-main-application/runnables/setup-prometheus-registry.injectable.ts
Labels: enhancement, area/metrics

#6161 Use extension version as projectVersion for exported ExtensionStore
  src/common/base-store.ts
  src/extensions/extension-store.ts
Labels: bug, area/extension

#5434 Fix envFrom.prefix not being applied in container's env view
  src/common/k8s-api/__tests__/pods.test.ts
  src/common/k8s-api/endpoints/index.ts
  src/common/k8s-api/endpoints/job.api.ts
  src/common/k8s-api/endpoints/pod.api.ts
  src/common/k8s-api/endpoints/types/capabilities.ts
  src/common/k8s-api/endpoints/types/container-port.ts
  src/common/k8s-api/endpoints/types/container.ts
  src/common/k8s-api/endpoints/types/env-from-source.ts
  src/common/k8s-api/endpoints/types/env-source.ts
  src/common/k8s-api/endpoints/types/env-var-key-selector.ts
  src/common/k8s-api/endpoints/types/env-var-source.ts
  src/common/k8s-api/endpoints/types/env-var.ts
  src/common/k8s-api/endpoints/types/exec-action.ts
  src/common/k8s-api/endpoints/types/handler.ts
  src/common/k8s-api/endpoints/types/http-get-action.ts
  src/common/k8s-api/endpoints/types/http-header.ts
  src/common/k8s-api/endpoints/types/index.ts
  src/common/k8s-api/endpoints/types/lifecycle.ts
  src/common/k8s-api/endpoints/types/object-field-selector.ts
  src/common/k8s-api/endpoints/types/pod-security-context.ts
  src/common/k8s-api/endpoints/types/probe.ts
  src/common/k8s-api/endpoints/types/resource-field-selector.ts
  src/common/k8s-api/endpoints/types/se-linux-options.ts
  src/common/k8s-api/endpoints/types/seccomp-profile.ts
  src/common/k8s-api/endpoints/types/security-context.ts
  src/common/k8s-api/endpoints/types/tcp-socket-action.ts
  src/common/k8s-api/endpoints/types/volume-device.ts
  src/common/k8s-api/endpoints/types/volume-mount.ts
  src/common/k8s-api/endpoints/types/windows-security-context-options.ts
  src/extensions/common-api/k8s-api.ts
  src/renderer/components/+workloads-deployments/scale/dialog.test.tsx
  src/renderer/components/+workloads-pods/pod-container-env.tsx
  src/renderer/components/+workloads-pods/pod-details-container.tsx
  src/renderer/components/+workloads-replicasets/scale-dialog/dialog.test.tsx
  src/renderer/components/__tests__/deployments.store.test.ts
  src/renderer/components/dock/logs/__test__/pod.mock.ts
  src/renderer/components/dock/logs/create-pod-logs-tab.injectable.ts
  src/renderer/components/dock/logs/resource-selector.tsx
Labels: bug, area/ui

#6167 Fix type error in download-logs test
  src/behaviours/pod-logs/download-logs.test.tsx
Labels: chore

#6180 Release 6.0.2-beta.0
  package.json
  src/behaviours/cluster/__snapshots__/order-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-core.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  src/behaviours/cluster/__snapshots__/visibility-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/extension-api/__snapshots__/disable-cluster-pages-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/extension-api/__snapshots__/disable-sidebar-items-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-details/extension-api/__snapshots__/disable-kube-object-detail-items-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-menu/extension-api/__snapshots__/disable-kube-object-menu-items-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-status-icon/__snapshots__/show-status-for-a-kube-object.test.tsx.snap
  src/behaviours/cluster/kube-object-status-icon/extension-api/__snapshots__/disable-kube-object-statuses-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/namespaces/__snapshots__/edit-namespace-from-new-tab.test.tsx.snap
  src/behaviours/cluster/namespaces/__snapshots__/edit-namespace-from-previously-opened-tab.test.tsx.snap
  src/behaviours/cluster/workloads/overview/extension-api/__snapshots__/disable-workloads-overview-details-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-new-tab.test.ts.snap
  src/behaviours/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-previously-opened-tab.test.ts.snap
  src/behaviours/helm-charts/installing-chart/__snapshots__/opening-dock-tab-for-installing-helm-chart.test.ts.snap
  src/behaviours/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  src/main/prometheus/operator.ts
  src/renderer/components/layout/main-layout.tsx
  src/renderer/components/layout/sidebar-item.scss
  src/renderer/components/layout/sidebar-item.tsx
  src/renderer/components/layout/sidebar-items.module.scss
  src/renderer/components/layout/sidebar.module.scss
  src/renderer/components/resource-metrics/resource-metrics-text.tsx
  src/renderer/frames/cluster-frame/__snapshots__/cluster-frame.test.tsx.snap
Labels: skip-changelog

#6188 Move pod-logs test to features folder
  src/features/pod-logs/__snapshots__/download-logs.test.tsx.snap
  src/features/pod-logs/download-logs.test.tsx
Labels: chore

#6176 Bump npm to 8.19.1
  extensions/kube-object-event-status/package.json
  extensions/metrics-cluster-feature/package.json
  extensions/node-menu/package.json
  extensions/pod-menu/package.json
  package.json
  src/extensions/extension-installer/extension-installer.ts
  src/extensions/npm/extensions/package-lock.json
  yarn.lock
Labels: dependencies

#6181 Initial telemetry whitelist
  src/features/telemetry/renderer/telemetry-white-list-for-functions.injectable.ts
  src/renderer/components/+extensions/install-from-input/install-from-input.injectable.ts
  src/renderer/routes/navigate-to-route.injectable.ts
Labels: enhancement, area/telemetry

#6183 Readd space between key and value in ENV display
  src/renderer/components/+workloads-pods/__tests__/__snapshots__/pod-container-env.test.tsx.snap
  src/renderer/components/+workloads-pods/__tests__/pod-container-env.test.tsx
  src/renderer/components/+workloads-pods/pod-container-env.tsx
Labels: bug, area/ui

#6178 Allow extensions to control status bar item visibility
  src/features/status-bar/status-bar-items-originating-from-extensions.test.tsx
  src/renderer/components/status-bar/status-bar-item-registrator.injectable.tsx
  src/renderer/components/status-bar/status-bar-registration.ts
Labels: enhancement, area/extension

#6195 Assume that bundled extensions are always compatible
  src/extensions/extension-discovery/extension-discovery.injectable.ts
  src/extensions/extension-discovery/extension-discovery.ts
  src/extensions/extension-discovery/is-compatible-bundled-extension/is-compatible-bundled-extension.injectable.ts
  src/extensions/extension-discovery/is-compatible-bundled-extension/is-compatible-bundled-extension.ts
Labels: chore, area/extension

#6088 Make opening of release details work properly when release has resources without namespace
  src/common/front-end-routing/routes/cluster/helm/releases/navigate-to-helm-releases.injectable.ts
  src/common/fs/exec-file.injectable.ts
  src/features/helm-charts/add-custom-helm-repository-in-preferences.test.ts
  src/features/helm-charts/add-helm-repository-from-list-in-preferences.test.ts
  src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-new-tab.test.ts.snap
  src/features/helm-charts/installing-chart/installing-helm-chart-from-new-tab.test.ts
  src/features/helm-charts/listing-active-helm-repositories-in-preferences.test.ts
  src/features/helm-charts/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts
  src/features/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  src/features/helm-releases/showing-details-for-helm-release.test.ts
  src/main/getDiForUnitTesting.ts
  src/main/helm/exec-helm/exec-helm.injectable.ts
  src/main/helm/get-helm-env/get-helm-env.injectable.ts
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-service/get-helm-release-resources/call-for-helm-manifest/call-for-helm-manifest.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/call-for-kube-resources-by-manifest.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/exec-file-with-input/exec-file-with-input.global-override-for-injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/exec-file-with-input/exec-file-with-input.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/exec-file-with-input/exec-file-with-input.test.ts
  src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/exec-file-with-input/non-promise-exec-file.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.test.ts
  src/main/helm/helm-service/get-helm-release.global-override-for-injectable.ts
  src/main/helm/helm-service/get-helm-release.injectable.ts
  src/main/helm/helm-service/update-helm-release.global-override-for-injectable.ts
  src/main/helm/helm-service/update-helm-release.injectable.ts
  src/main/helm/repositories/add-helm-repository/add-helm-repository.injectable.ts
  src/main/helm/repositories/get-active-helm-repositories/get-active-helm-repositories.injectable.ts
  src/main/helm/repositories/remove-helm-repository/remove-helm-repository.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-content.tsx
  src/renderer/components/+helm-releases/release-details/release-details-drawer-toolbar.tsx
  src/renderer/components/+helm-releases/release-details/release-details-drawer.tsx
  src/renderer/components/+helm-releases/release-details/release-details-model/call-for-helm-release/call-for-helm-release.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx
  src/renderer/components/+helm-releases/release-details/release-details.scss
  src/renderer/components/+helm-releases/release-details/release-details.tsx
  src/renderer/themes/active-type.injectable.ts
  src/renderer/themes/store.ts
Labels: bug

#6215 release v6.0.2
  package.json
Labels: skip-changelog

#6214 Install all extensions via package.json
  src/extensions/extension-discovery/extension-discovery.ts
  src/extensions/extension-installer/extension-installer.ts
Labels: bug, area/extension

#6221 Fix discovering extensions with with scopes
  src/extensions/extension-discovery/extension-discovery.ts
Labels: bug, area/extension

#6225 Updated README file
  README.md
Labels: chore

#6218 Leading topbar home button to welcome page
  src/features/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  src/features/__snapshots__/navigate-to-extension-page.test.tsx.snap
  src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/features/application-update/__snapshots__/force-user-to-update-when-too-long-time-since-update-was-downloaded.test.ts.snap
  src/features/application-update/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  src/features/application-update/__snapshots__/installing-update-using-tray.test.ts.snap
  src/features/application-update/__snapshots__/installing-update.test.ts.snap
  src/features/application-update/__snapshots__/periodical-checking-of-updates.test.ts.snap
  src/features/application-update/__snapshots__/selection-of-update-stability.test.ts.snap
  src/features/command-pallet/__snapshots__/keyboard-shortcuts.test.tsx.snap
  src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/features/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/features/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  src/features/status-bar/__snapshots__/status-bar-items-originating-from-extensions.test.tsx.snap
  src/features/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/renderer/components/layout/top-bar/top-bar.tsx
Labels: enhancement, area/ui

#6249 Bump version in package.json
  package.json
Labels: chore

#6182 Upgrade release making script to support skipping PRs
  scripts/create-release-pr.ts
Labels: chore

#6240 Update link to "add-cluster" docs page
  src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/renderer/components/+add-cluster/add-cluster.tsx
Labels: bug

#6258 Fix overflow on main layout not being scrolled
  src/renderer/components/cluster-manager/cluster-manager.scss
Labels: bug, area/ui, blocker

#6260 Revert KubeJsonApi removal from extension api
  src/extensions/common-api/k8s-api.ts
Labels: bug, area/extension

#6264 Fix typing issue with missing build.publish field
  package.json
  src/common/vars/application-information.injectable.ts
Labels: bug

#6268 Release 6.1.0-alpha.1
  package.json
Labels: skip-changelog

#6223 Download arm64 linux binaries
  build/download_binaries.ts
Labels: chore

#6276 Fix crash on clean startup
  src/common/__tests__/user-store.test.ts
  src/common/application-update/selected-update-channel/default-update-channel.injectable.ts
  src/common/error-reporting/initialize-sentry-reporting.injectable.ts
  src/common/user-store/file-name-migration.global-override-for-injectable.ts
  src/common/user-store/file-name-migration.injectable.ts
  src/common/user-store/user-store.injectable.ts
  src/common/user-store/user-store.ts
  src/common/vars/release-channel.injectable.ts
  src/main/application-update/check-for-updates/update-can-be-downgraded.injectable.ts
  src/main/getDiForUnitTesting.ts
  src/main/stores/init-user-store.injectable.ts
  src/main/vars/default-update-channel/init.injectable.ts
  src/main/vars/release-channel/init.injectable.ts
  src/renderer/bootstrap.tsx
  src/renderer/getDiForUnitTesting.tsx
  src/renderer/stores/init-user-store.injectable.ts
  src/renderer/vars/default-update-channel/init.injectable.ts
  src/renderer/vars/release-channel/init.injectable.ts
Labels: bug, blocker

#6275 Release 6.1.0
  package.json
Labels: skip-changelog

#6284 Remove telemetry from editing resources
  src/features/telemetry/renderer/telemetry-white-list-for-functions.injectable.ts
Labels: bug, p0, area/telemetry

#6285 Release 6.1.1
  package.json
  src/features/telemetry/renderer/telemetry-white-list-for-functions.injectable.ts
Labels: skip-changelog

#6291 Fix Singleton type in exports
  src/extensions/common-api/utils.ts
Labels: bug, area/extension

#6296 Remove get-logs telemetry event
  src/features/telemetry/renderer/telemetry-white-list-for-functions.injectable.ts
Labels: bug
