Repository lensapp/lens, pull requests merged in 2022-12, with the labels that each got.

#6681 Add milestone automatically to release PRs
  scripts/create-release-pr.ts
Labels: chore

#6680 Fix race conditrion preventing window from opening
  src/main/start-main-application/lens-window/application-window/create-lens-window.injectable.ts
Labels: bug, p1

#6689 Fix: remove excessive scrollbars from the TabLayout view
  src/features/cluster/__snapshots__/legacy-extension-adding-cluster-frame-components.test.tsx.snap
  src/features/cluster/__snapshots__/order-of-sidebar-items.test.tsx.snap
  src/features/cluster/__snapshots__/sidebar-and-tab-navigation-for-core.test.tsx.snap
  src/features/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  src/features/cluster/__snapshots__/visibility-of-sidebar-items.test.tsx.snap
  src/features/cluster/__snapshots__/workload-overview.test.tsx.snap
  src/features/cluster/extension-api/__snapshots__/disable-cluster-pages-when-cluster-is-not-relevant.test.tsx.snap
  src/features/cluster/extension-api/__snapshots__/disable-sidebar-items-when-cluster-is-not-relevant.test.tsx.snap
  src/features/cluster/namespaces/__snapshots__/edit-namespace-from-new-tab.test.tsx.snap
  src/features/cluster/namespaces/__snapshots__/edit-namespace-from-previously-opened-tab.test.tsx.snap
  src/features/cluster/workloads/overview/extension-api/__snapshots__/disable-workloads-overview-details-when-cluster-is-not-relevant.test.tsx.snap
  src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-new-tab.test.ts.snap
  src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-previously-opened-tab.test.ts.snap
  src/features/helm-charts/installing-chart/__snapshots__/opening-dock-tab-for-installing-helm-chart.test.ts.snap
  src/features/helm-charts/upgrade-chart/__snapshots__/upgrade-chart-new-tab.test.ts.snap
  src/features/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  src/features/pod-logs/__snapshots__/download-logs.test.tsx.snap
  src/renderer/components/+cluster/cluster-overview.tsx
  src/renderer/components/+workloads-overview/overview.tsx
  src/renderer/components/item-object-list/item-list-layout.scss
  src/renderer/components/layout/main-layout.module.scss
  src/renderer/components/layout/siblings-in-tab-layout.tsx
  src/renderer/components/layout/tab-layout-2.tsx
  src/renderer/components/layout/tab-layout.scss
  src/renderer/components/layout/tab-layout.tsx
  src/renderer/components/table/table.scss
  src/renderer/frames/cluster-frame/__snapshots__/cluster-frame.test.tsx.snap
Labels: bug, area/ui

#6691 Fix crash in PersistentVolumeDetails
  src/common/k8s-api/endpoints/persistent-volume.api.ts
  src/renderer/components/+storage-volumes/volume-details.tsx
Labels: bug

#6706 Fix top-bar .separator width
  src/renderer/components/layout/top-bar/top-bar.module.scss
Labels: bug, area/ui

#6707 Release 6.2.5
  package.json
  src/common/k8s-api/endpoints/persistent-volume.api.ts
  src/features/cluster/__snapshots__/legacy-extension-adding-cluster-frame-components.test.tsx.snap
  src/features/cluster/__snapshots__/order-of-sidebar-items.test.tsx.snap
  src/features/cluster/__snapshots__/sidebar-and-tab-navigation-for-core.test.tsx.snap
  src/features/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  src/features/cluster/__snapshots__/visibility-of-sidebar-items.test.tsx.snap
  src/features/cluster/__snapshots__/workload-overview.test.tsx.snap
  src/features/cluster/extension-api/__snapshots__/disable-cluster-pages-when-cluster-is-not-relevant.test.tsx.snap
  src/features/cluster/extension-api/__snapshots__/disable-sidebar-items-when-cluster-is-not-relevant.test.tsx.snap
  src/features/cluster/namespaces/__snapshots__/edit-namespace-from-new-tab.test.tsx.snap
  src/features/cluster/namespaces/__snapshots__/edit-namespace-from-previously-opened-tab.test.tsx.snap
  src/features/cluster/workloads/overview/extension-api/__snapshots__/disable-workloads-overview-details-when-cluster-is-not-relevant.test.tsx.snap
  src/features/helm-charts/child-features/preferences/renderer/adding-of-custom-helm-repository/adding-of-custom-helm-repository-dialog-content.tsx
  src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-new-tab.test.ts.snap
  src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-previously-opened-tab.test.ts.snap
  src/features/helm-charts/installing-chart/__snapshots__/opening-dock-tab-for-installing-helm-chart.test.ts.snap
  src/features/helm-charts/upgrade-chart/__snapshots__/upgrade-chart-new-tab.test.ts.snap
  src/features/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  src/features/pod-logs/__snapshots__/download-logs.test.tsx.snap
  src/main/start-main-application/lens-window/application-window/create-lens-window.injectable.ts
  src/renderer/components/+cluster/cluster-overview.tsx
  src/renderer/components/+storage-volumes/volume-details.tsx
  src/renderer/components/+workloads-overview/overview.tsx
  src/renderer/components/item-object-list/item-list-layout.scss
  src/renderer/components/layout/main-layout.module.scss
  src/renderer/components/layout/siblings-in-tab-layout.tsx
  src/renderer/components/layout/tab-layout-2.tsx
  src/renderer/components/layout/tab-layout.scss
  src/renderer/components/layout/tab-layout.tsx
  src/renderer/components/layout/top-bar/top-bar.module.scss
  src/renderer/components/table/table.scss
  src/renderer/frames/cluster-frame/__snapshots__/cluster-frame.test.tsx.snap
  src/test-utils/channel-fakes/override-messaging-from-window-to-main.ts
  src/test-utils/channel-fakes/override-requesting-from-window-to-main.ts
  yarn.lock
Labels: skip-changelog, release

#6723 Remove named exports from CSS module typings
  tsconfig.json
Labels: chore

#6734 Remove blue borders in light themed tables
  src/renderer/components/table/table-head.scss
  src/renderer/themes/lens-dark.ts
  src/renderer/themes/lens-light.ts
  src/renderer/themes/theme-vars.css
Labels: bug, area/ui

#6717 Unify build fs layout
  Makefile
  build/generate-tray-icons.ts
  package.json
  src/common/app-paths/app-path-names.ts
  src/common/app-paths/app-paths.test.ts
  src/common/vars/static-files-directory.global-override-for-injectable.ts
  src/common/vars/static-files-directory.injectable.ts
  src/extensions/extension-discovery/extension-discovery.injectable.ts
  src/extensions/extension-discovery/extension-discovery.ts
  src/features/application-update/installing-update.test.ts
  src/features/quitting-and-restarting-the-app/opening-application-window-using-tray.test.ts
  src/main/app-paths/get-electron-app-path/get-electron-app-path.ts
  src/main/tray/menu-icon/get-tray-icon-path.injectable.ts
  src/renderer/components/dock/create-resource/lens-templates.injectable.ts
Labels: chore

#6715 Include bundled extensions in package.json
  Makefile
  extensions/kube-object-event-status/package.json
  extensions/metrics-cluster-feature/package.json
  extensions/node-menu/package.json
  extensions/pod-menu/package.json
  package.json
  src/common/vars/application-information.global-override-for-injectable.ts
  src/extensions/extension-discovery/extension-discovery.injectable.ts
  src/extensions/extension-discovery/extension-discovery.ts
  src/extensions/extension-installer/extension-installer.ts
  src/extensions/extension-installer/install-extensions/install-extensions.injectable.ts
  yarn.lock
Labels: enhancement, area/security

#6669 Simplify Error.cause logging
  src/main/logger/console-format.ts
Labels: chore

#6758 Fix publishing @k8slens/extension package to NPM
  .github/workflows/publish-release-npm.yml
  .github/workflows/release.yml
Labels: area/ci

#6761 Always publish NPM package from workflow
  .github/workflows/publish-release-npm.yml
Labels: area/ci

#6763 Fix always releasing master as NPM package
  .github/workflows/publish-release-npm.yml
  .github/workflows/release.yml
Labels: area/ci

#6764 Fix typing of ExtensionStore.createInstance static
  src/extensions/extension-store.ts
Labels: bug, area/extension

#6770 Fix loosing osx dock and tray icons on window reopen
  src/main/electron-app/runnables/setup-runnables-after-window-is-opened.injectable.ts
Labels: bug, area/windows, area/macos

#6679 Fix queries for operator provider metrics
  src/main/prometheus/operator-provider.injectable.ts.ts
Labels: bug, area/metrics

#6772 Fix release workflow file
  .github/workflows/release.yml
Labels: area/ci

#6774 Make apiBase not an InjectionToken and make openNodeShellSession not special
  src/common/k8s-api/api-base-configs.ts
  src/common/k8s-api/api-base.injectable.ts
  src/common/k8s-api/api-base.ts
  src/common/k8s-api/create-kube-api-for-cluster.injectable.ts
  src/common/k8s-api/create-kube-json-api-for-cluster.injectable.ts
  src/common/k8s-api/endpoints/helm-charts.api/request-charts.injectable.ts
  src/common/k8s-api/endpoints/helm-charts.api/request-readme.injectable.ts
  src/common/k8s-api/endpoints/helm-charts.api/request-values.injectable.ts
  src/common/k8s-api/endpoints/helm-charts.api/request-versions.injectable.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-configuration.injectable.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-create.injectable.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-delete.injectable.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-details.injectable.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-history.injectable.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-releases.injectable.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-rollback.injectable.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-update.injectable.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-values.injectable.ts
  src/common/k8s-api/endpoints/metrics.api/request-metrics.injectable.ts
  src/common/k8s-api/endpoints/metrics.api/request-providers.injectable.ts
  src/common/k8s-api/endpoints/resource-applier.api/request-patch.injectable.ts
  src/common/k8s-api/endpoints/resource-applier.api/request-update.injectable.ts
  src/main/k8s/api-base-host-header.injectable.ts
  src/main/k8s/api-base-server-address.injectable.ts
  src/main/k8s/api-base.injectable.ts
  src/main/shell-session/create-shell-session.injectable.ts
  src/main/shell-session/node-shell-session/open.injectable.ts
  src/renderer/components/kubeconfig-dialog/open-service-account-kube-config-dialog.injectable.ts
  src/renderer/k8s/api-base-host-header.injectable.ts
  src/renderer/k8s/api-base-server-address.injectable.ts
  src/renderer/k8s/api-base.injectable.ts
  src/renderer/port-forward/port-forward-store/port-forward-store.injectable.ts
  src/renderer/port-forward/port-forward-store/request-active-port-forward.injectable.ts
Labels: chore

#6781 Fix helm chart readme load app crash
  src/common/k8s-api/endpoints/helm-charts.api/request-readme.injectable.ts
  src/features/helm-charts/installing-chart/__snapshots__/opening-dock-tab-for-installing-helm-chart.test.ts.snap
  src/features/helm-charts/installing-chart/installing-helm-chart-from-new-tab.test.ts
  src/features/helm-charts/installing-chart/opening-dock-tab-for-installing-helm-chart.test.ts
  src/renderer/components/+helm-charts/details/readme-of-selected-helm-chart.injectable.ts
Labels: bug, area/ui, p0

#6782 Fix app crash opening Install Chart dock tab
  src/common/k8s-api/endpoints/helm-charts.api/request-values.injectable.ts
  src/features/helm-charts/installing-chart/installing-helm-chart-from-new-tab.test.ts
  src/features/helm-charts/installing-chart/installing-helm-chart-from-previously-opened-tab.test.ts
  src/renderer/components/dock/install-chart/install-chart-model.injectable.tsx
Labels: bug, area/ui

#6784 Fix resize anchor z-index
  src/renderer/components/resizing-anchor/resizing-anchor.scss
Labels: bug, area/ui

#6775 Remove in-tree extensions to help facilitate a more secure and faster booting lens
  .eslintrc.js
  .github/workflows/test.yml
  .gitignore
  .idea/lens.iml
  Makefile
  extensions/.eslintrc.js
  extensions/.gitignore
  extensions/kube-object-event-status/Makefile
  extensions/kube-object-event-status/package.json
  extensions/kube-object-event-status/renderer.tsx
  extensions/kube-object-event-status/src/resolver.tsx
  extensions/kube-object-event-status/tsconfig.json
  extensions/kube-object-event-status/webpack.config.js
  extensions/metrics-cluster-feature/package.json
  extensions/metrics-cluster-feature/renderer.tsx
  extensions/metrics-cluster-feature/resources/01-namespace.yml.hb
  extensions/metrics-cluster-feature/resources/02-configmap.yml.hb
  extensions/metrics-cluster-feature/resources/02-service-account.yml
  extensions/metrics-cluster-feature/resources/03-service.yml.hb
  extensions/metrics-cluster-feature/resources/03-statefulset.yml.hb
  extensions/metrics-cluster-feature/resources/04-rules.yml
  extensions/metrics-cluster-feature/resources/05-clusterrole.yml
  extensions/metrics-cluster-feature/resources/06-clusterrole-binding.yml
  extensions/metrics-cluster-feature/resources/10-node-exporter-ds.yml.hb
  extensions/metrics-cluster-feature/resources/11-node-exporter-svc.yml
  extensions/metrics-cluster-feature/resources/12-kube-state-metrics-clusterrole.yml
  extensions/metrics-cluster-feature/resources/12.kube-state-metrics-sa.yml
  extensions/metrics-cluster-feature/resources/13-kube-state-metrics-clusterrole-binding.yml
  extensions/metrics-cluster-feature/resources/14-kube-state-metrics-deployment.yml.hb
  extensions/metrics-cluster-feature/resources/14-kube-state-metrics-svc.yml
  extensions/metrics-cluster-feature/src/metrics-feature.ts
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
  extensions/metrics-cluster-feature/tsconfig.json
  extensions/metrics-cluster-feature/webpack.config.js
  extensions/node-menu/package.json
  extensions/node-menu/renderer.tsx
  extensions/node-menu/src/node-menu.tsx
  extensions/node-menu/tsconfig.json
  extensions/node-menu/webpack.config.js
  extensions/pod-menu/package.json
  extensions/pod-menu/renderer.tsx
  extensions/pod-menu/src/attach-menu.tsx
  extensions/pod-menu/src/logs-menu.tsx
  extensions/pod-menu/src/shell-menu.tsx
  extensions/pod-menu/tsconfig.json
  extensions/pod-menu/webpack.config.js
  integration/__tests__/cluster-pages.tests.ts
  package.json
Labels: chore

#6668 Prevent shell sync commands from polluting history
  src/features/shell-sync/main/compute-unix-shell-environment.injectable.ts
  src/features/shell-sync/main/compute-unix-shell-environment.test.ts
Labels: bug

#6794 Fix: load pods from all namespaces in node details
  src/renderer/components/+nodes/details.tsx
  src/renderer/components/+workloads-pods/load-pods-from-all-namespaces.injectable.ts
Labels: bug, area/ui

#6797 Navigation logging injectable
  src/renderer/navigation/observable-history.injectable.ts
  src/renderer/navigation/setup-logging-for-navigation.injectable.ts
Labels: chore

#6771 Split out use of httpsProxy preference
  src/common/fetch/download-json.injectable.ts
  src/common/fetch/download-json/impl.ts
  src/common/fetch/download-json/normal.injectable.ts
  src/common/fetch/download-json/proxy.injectable.ts
  src/common/fetch/fetch-module.injectable.ts
  src/common/fetch/fetch.injectable.ts
  src/common/fetch/proxy-fetch.injectable.ts
  src/features/extensions/navigation-using-application-menu.test.ts
  src/features/helm-charts/child-features/preferences/renderer/adding-of-public-helm-repository/public-helm-repositories/request-public-helm-repositories.injectable.ts
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/+extensions/attempt-install-by-info.injectable.tsx
Labels: bug

#6803 Fix broken import after PR merge
  src/renderer/navigation/setup-logging-for-navigation.injectable.ts
Labels: chore

#6802 Make request-api-resources flatter in implementation
  src/common/cluster/cluster.ts
  src/common/cluster/request-api-resources.injectable.ts
  src/common/utils/iter.ts
  src/common/utils/with-concurrency-limit.ts
  src/main/catalog-sources/kubeconfig-sync/manager.ts
  src/main/cluster/request-api-resources.injectable.ts
  src/main/cluster/request-api-versions.ts
  src/main/cluster/request-core-api-versions.injectable.ts
  src/main/cluster/request-kube-api-resources-for.injectable.ts
  src/main/cluster/request-non-core-api-versions.injectable.ts
  src/main/create-cluster/create-cluster.injectable.ts
  src/main/k8s-request.injectable.ts
  src/renderer/components/+config-secrets/add-secret-dialog.tsx
  src/renderer/components/command-palette/command-dialog.tsx
  src/renderer/utils/cssNames.ts
Labels: chore

#6787 Massively simplify bundled extension loading
  package.json
  src/extensions/extension-discovery/bundled-extension-token.ts
  src/extensions/extension-discovery/extension-discovery.injectable.ts
  src/extensions/extension-discovery/extension-discovery.ts
  src/extensions/extension-loader/entry-point-name.ts
  src/extensions/extension-loader/extension-loader.injectable.ts
  src/extensions/extension-loader/extension-loader.ts
  src/main/extension-loader/entry-point-name.injectable.ts
  src/renderer/extension-loader/entry-point-name.injectable.ts
Labels: chore, area/extension

#6804 Release 6.3.0
  package.json
Labels: skip-changelog, release

#6821 Revert #6733 to avoid breaking changes for extensions
  src/features/application-update/child-features/application-update-using-top-bar/renderer/update-application-top-bar-item/update-button/styles.module.scss
  src/renderer/components/+namespaces/namespace-select-filter.scss
  src/renderer/components/+welcome/welcome.scss
  src/renderer/components/add-remove-buttons/add-remove-buttons.scss
  src/renderer/components/app.scss
  src/renderer/components/cluster-manager/cluster-manager.scss
  src/renderer/components/cluster-manager/cluster-status.module.scss
  src/renderer/components/dialog/dialog.scss
  src/renderer/components/dock/dock-tabs.module.scss
  src/renderer/components/dock/dock.scss
  src/renderer/components/drawer/drawer.scss
  src/renderer/components/editable-list/editable-list.scss
  src/renderer/components/hotbar/hotbar-menu.scss
  src/renderer/components/hotbar/hotbar-selector.module.scss
  src/renderer/components/kube-object-details/kube-object-details.scss
  src/renderer/components/layout/main-layout.module.scss
  src/renderer/components/layout/setting-layout.scss
  src/renderer/components/layout/top-bar/top-bar.module.scss
  src/renderer/components/markdown-viewer/markdown-viewer.scss
  src/renderer/components/menu/menu.scss
  src/renderer/components/notifications/notifications.scss
  src/renderer/components/resizing-anchor/resizing-anchor.scss
  src/renderer/components/select/select.scss
  src/renderer/components/table/table-head.scss
  src/renderer/components/tooltip/tooltip.scss
  src/renderer/components/vars.scss
Labels: bug, area/extension

#6822 Fix terminal window paddings
  src/renderer/components/dock/dock.scss
  src/renderer/components/dock/terminal/terminal-window.scss
Labels: bug, area/ui, area/terminal

#6826 Add Restart Button to DaemonSet Menu
  src/common/k8s-api/endpoints/daemon-set.api.ts
  src/renderer/components/+workloads-daemonsets/daemonset-menu.tsx
  src/renderer/components/kube-object-menu/kube-object-menu-items/daemonset-menu.injectable.ts
Labels: enhancement

#6831 Remove error overlay in dev mode
  webpack/renderer.ts
Labels: chore

#6835 Allow main send messages to cluster frames
  src/main/utils/channel/message-to-channel.injectable.ts
  src/main/utils/channel/message-to-channel.test.ts
Labels: enhancement

#6837 Fix kubeconfig sync not saving data
  src/features/preferences/renderer/preference-items/kubernetes/kubeconfig-sync/kubeconfig-sync.tsx
Labels: bug, area/kubeconfig-sync

#6838 Clarify readme
  .github/screenshot.png
  README.md
Labels: chore

#6843 Fix small TabLayout jump when switching pages
  src/renderer/components/layout/tab-layout.scss
Labels: bug, area/ui

#6830 Use Monaco editor in ConfigMap details
  src/renderer/components/+config-maps/config-map-details.tsx
  src/renderer/components/monaco-editor/get-editor-height-from-lines-number.injectable.ts
  src/renderer/components/monaco-editor/get-editor-height-from-lines-number.test.ts
  src/renderer/components/monaco-editor/monaco-editor.tsx
Labels: enhancement, area/ui

#6844 Page refresh is broken in development mode
  src/main/routes/files/development.injectable.ts
Labels: chore

#6847 Fix minor typo/grammar in extension install message
  src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/renderer/components/+extensions/install.tsx
  src/renderer/components/+extensions/installed-extensions.tsx
Labels: bug
