Repository lensapp/lens, pull requests merged in 2022-10, with the labels that each got.

#6302 Adding asc provider
  build/notarize.js
Labels: enhancement, area/macos, area/build

#6301 Delete old extensions when app is updated on Windows
  build/installer.nsh
Labels: bug

#6290 Add missing space in "Remove x items"
  src/renderer/components/item-object-list/content.tsx
Labels: bug

#6043 Remove mac-ca usage since it was only in tests
  integration/__tests__/app-preferences.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/utils.ts
  package.json
  src/common/__tests__/system-ca.test.ts
  src/common/certificate-authorities/inject-system-cas.injectable.ts
  src/common/certificate-authorities/request-system-cas-token.ts
  src/common/certificate-authorities/request-system-cas.injectable.darwin.ts
  src/common/certificate-authorities/request-system-cas.injectable.linux.ts
  src/common/certificate-authorities/request-system-cas.injectable.testing-env.ts
  src/common/certificate-authorities/request-system-cas.injectable.win32.ts
  src/common/fs/exec-file.injectable.ts
  src/common/system-ca.ts
  src/common/utils/__tests__/paths.test.ts
  src/jest.setup.ts
  src/main/getDi.ts
  src/main/start-main-application/runnables/setup-system-ca.injectable.ts
  src/renderer/frames/root-frame/setup-system-ca.injectable.ts
  src/renderer/getDi.tsx
  src/test-utils/skippers.ts
  types/from-webpack.d.ts
  types/mocks.d.ts
  webpack/main.ts
  webpack/renderer.ts
  yarn.lock
Labels: chore, area/security

#6308 Bump typedoc-plugin-markdown to 3.13.6 to fix documentation creation
  package.json
  yarn.lock
Labels: area/documentation

#4515 Validate ClusterModel before trying to update or create a Cluster
  src/common/cluster-types.ts
  src/common/cluster/cluster.ts
Labels: chore

#6149 Refactoring dock tab download logs tests
  src/features/pod-logs/__snapshots__/download-logs.test.tsx.snap
  src/features/pod-logs/download-logs.test.tsx
  src/renderer/components/dock/logs/controls.tsx
  src/renderer/components/dock/logs/download-all-logs.injectable.ts
  src/renderer/components/dock/logs/download-logs-dropdown.tsx
Labels: chore

#6315 Release 6.1.2
  build/installer.nsh
  package.json
  src/features/telemetry/renderer/telemetry-white-list-for-functions.injectable.ts
  src/renderer/components/item-object-list/content.tsx
Labels: skip-changelog

#6299 ignore prerelease tag for kubectl version to download
  src/main/kubectl/kubectl.ts
Labels: bug

#6310 Split integration tests into seperate jobs from unit tests for faster CI
  .github/workflows/test.yml
  integration/__tests__/app-preferences.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/__tests__/command-palette.tests.ts
  integration/helpers/utils.ts
Labels: area/ci

#6319 Revert "Remove mac-ca usage since it was only in tests (#6043)"
  integration/__tests__/app-preferences.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/utils.ts
  package.json
  src/common/__tests__/system-ca.test.ts
  src/common/certificate-authorities/inject-system-cas.injectable.ts
  src/common/certificate-authorities/request-system-cas-token.ts
  src/common/certificate-authorities/request-system-cas.injectable.darwin.ts
  src/common/certificate-authorities/request-system-cas.injectable.linux.ts
  src/common/certificate-authorities/request-system-cas.injectable.testing-env.ts
  src/common/certificate-authorities/request-system-cas.injectable.win32.ts
  src/common/fs/exec-file.injectable.ts
  src/common/system-ca.ts
  src/common/utils/__tests__/paths.test.ts
  src/jest.setup.ts
  src/main/getDi.ts
  src/main/start-main-application/runnables/setup-system-ca.injectable.ts
  src/renderer/frames/root-frame/setup-system-ca.injectable.ts
  src/renderer/getDi.tsx
  src/test-utils/skippers.ts
  types/from-webpack.d.ts
  types/mocks.d.ts
  webpack/main.ts
  webpack/renderer.ts
  yarn.lock
Labels: bug

#6336 Remove logging env in integration tests
  integration/helpers/utils.ts
Labels: chore

#6339 Don't run linux integration tests on the unit matrix entry
  .github/workflows/test.yml
Labels: area/ci

#6338 Upgrade all injectable libraries to v11
  package.json
  src/main/lens-proxy/lens-proxy.ts
  src/main/router/router.injectable.ts
  src/main/start-main-application/runnables/setup-lens-proxy.injectable.ts
  yarn.lock
Labels: dependencies

#6345 Remove sentry logger-transport
  src/common/logger-transports/index.ts
  src/common/logger-transports/sentry.ts
Labels: chore

#6166 Add distribution and version columns for KubernetesClusters
  src/extensions/extension-loader/extension-registrator-injection-token.ts
  src/renderer/components/+catalog/__tests__/custom-columns.test.ts
  src/renderer/components/+catalog/columns/custom-token.ts
  src/renderer/components/+catalog/columns/extensions-registrator.injectable.ts
  src/renderer/components/+catalog/columns/get.injectable.ts
  src/renderer/components/+catalog/columns/kubernetes-api-version.injectable.tsx
  src/renderer/components/+catalog/columns/kubernetes-distribution.injectable.tsx
  src/renderer/components/+catalog/custom-category-columns.injectable.tsx
  src/renderer/components/item-object-list/content.tsx
Labels: enhancement, area/catalog

#6318 Fix loading helm release details
  src/common/utils/objects.ts
  src/features/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  src/main/helm/helm-service/get-helm-release-resources/call-for-helm-manifest/call-for-helm-manifest.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.test.ts
  src/main/helm/helm-service/get-helm-release.injectable.ts
  src/main/router/create-handler-for-route.injectable.ts
  src/main/router/router.injectable.ts
  src/main/router/router.ts
  src/renderer/components/+helm-releases/release-details/release-details-content.tsx
  src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx
  src/renderer/components/+helm-releases/release-details/release-details-model/request-detailed-helm-release.injectable.ts
Labels: bug, area/helm

#6351 Improve shellEnv
  package.json
  src/main/shell-session/shell-session.ts
  src/main/utils/shell-env.ts
  yarn.lock
Labels: enhancement

#6354 Release 6.1.3
  .bundled-extensions.json
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  integration/__tests__/app-preferences.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/__tests__/command-palette.tests.ts
  integration/helpers/utils.ts
  package.json
  scripts/create-release-pr.ts
  scripts/tag-release.sh
  src/common/utils/objects.ts
  src/features/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  src/main/helm/helm-service/get-helm-release-resources/call-for-helm-manifest/call-for-helm-manifest.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.test.ts
  src/main/helm/helm-service/get-helm-release.injectable.ts
  src/main/kubectl/kubectl.ts
  src/main/router/create-handler-for-route.injectable.ts
  src/main/router/router.injectable.ts
  src/main/router/router.ts
  src/main/shell-session/shell-session.ts
  src/main/utils/shell-env.ts
  src/renderer/components/+helm-releases/release-details/release-details-content.tsx
  src/renderer/components/+helm-releases/release-details/release-details-model/call-for-helm-release/call-for-helm-release.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx
  yarn.lock
Labels: skip-changelog, release

#6356 Release 6.1.4
  .github/workflows/release.yml
  package.json
Labels: skip-changelog, release

#6357 Attempt 2 to fix the targetting of release workflow
  .github/workflows/release.yml
Labels: area/ci

#6359 Release 6.1.5
  .github/workflows/release.yml
  package.json
Labels: skip-changelog, release

#6360 Filter release workflow via if instead of on
  .github/workflows/release.yml
Labels: area/ci

#6361 Release 6.1.6
  .github/workflows/release.yml
  package.json
Labels: skip-changelog, release

#6362 Testing pull_request:closed workflow
  .github/workflows/release.yml
Labels: chore

#6363 Different testing code
  .github/workflows/release.yml
Labels: chore

#6364 Add complete debug to release workflow for testing
  .github/workflows/release.yml
Labels: chore

#6365 Release 6.1.7
  .github/workflows/release.yml
  package.json
Labels: skip-changelog, release

#6366 More debugging to understand why targetting isn't working
  .github/workflows/release.yml
Labels: area/ci

#6369 Check if operator in release PR is correct
  .github/workflows/release.yml
Labels: area/ci

#6370 Fix filtering on the release workflow
  .github/workflows/release.yml
Labels: area/ci

#6371 Release 6.1.9
  .github/workflows/release.yml
  package.json
Labels: skip-changelog, release

#6372 Fix release action step in release workflow
  .github/workflows/release.yml
Labels: area/ci

#6373 Release 6.1.10
  .github/workflows/release.yml
  package.json
Labels: skip-changelog, release

#6374 Add release guide
  RELEASE_GUIDE.md
Labels: area/documentation

#6376 Fix crash when opening pod details
  src/renderer/components/menu/menu.tsx
Labels: bug, area/ui

#6352 Clickable links in pods details for ServiceAccount, PriorityClass and RuntimeClass
  src/renderer/components/+workloads-pods/pod-details.tsx
Labels: enhancement, area/ui

#6378 Leases view
  src/common/front-end-routing/routes/cluster/config/leases/leases-route.injectable.ts
  src/common/front-end-routing/routes/cluster/config/leases/navigate-to-leases.injectable.ts
  src/common/k8s-api/endpoints/index.ts
  src/common/k8s-api/endpoints/lease.api.injectable.ts
  src/common/k8s-api/endpoints/lease.api.ts
  src/common/rbac.ts
  src/renderer/components/+config-leases/index.ts
  src/renderer/components/+config-leases/lease-details.scss
  src/renderer/components/+config-leases/lease-details.tsx
  src/renderer/components/+config-leases/leases-route-component.injectable.ts
  src/renderer/components/+config-leases/leases-sidebar-items.injectable.tsx
  src/renderer/components/+config-leases/leases.scss
  src/renderer/components/+config-leases/leases.tsx
  src/renderer/components/+config-leases/store.injectable.ts
  src/renderer/components/+config-leases/store.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/lease-detail-item.injectable.ts
  src/renderer/utils/rbac.ts
Labels: enhancement, area/kubernetes-next

#6375 Fix ReactiveDuration to update as frequently as necessary
  src/renderer/components/duration/reactive-duration.tsx
  src/renderer/components/kube-object-meta/kube-object-meta.tsx
Labels: bug, area/ui

#6397 Release 6.1.11
  RELEASE_GUIDE.md
  package.json
  src/renderer/components/duration/reactive-duration.tsx
  src/renderer/components/kube-object-meta/kube-object-meta.tsx
  src/renderer/components/menu/menu.tsx
Labels: skip-changelog, release

#6408 Release 6.1.12
  build/notarize.js
  package.json
  src/common/user-store/resolved-shell.injectable.ts
  src/main/__test__/shell-session.test.ts
  src/main/lens-proxy/proxy-functions/shell-api-request/shell-api-request.ts
  src/main/shell-session/create-shell-session.injectable.ts
  src/main/shell-session/local-shell-session/local-shell-session.injectable.ts
  src/main/shell-session/local-shell-session/local-shell-session.ts
  src/main/shell-session/local-shell-session/techincal.test.ts
  src/main/shell-session/node-shell-session/node-shell-session.injectable.ts
  src/main/shell-session/node-shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/main/shell-session/spawn-pty.global-override-for-injectable.ts
  src/main/shell-session/spawn-pty.injectable.ts
  src/main/start-main-application/runnables/setup-shell.injectable.ts
  src/main/utils/clear-kube-env-vars.ts
  src/main/utils/shell-env.ts
  src/main/utils/shell-env/compute-shell-environment.injectable.ts
  src/main/utils/shell-env/compute-unix-shell-environment.global-override-for-injectable.ts
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
Labels: skip-changelog, release

#6400 Add data-origin to status bar items for better observability
  src/features/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  src/features/__snapshots__/navigate-to-extension-page.test.tsx.snap
  src/features/__snapshots__/navigating-between-routes.test.tsx.snap
  src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/features/application-update/__snapshots__/force-user-to-update-when-too-long-time-since-update-was-downloaded.test.ts.snap
  src/features/application-update/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  src/features/application-update/__snapshots__/installing-update-using-tray.test.ts.snap
  src/features/application-update/__snapshots__/installing-update.test.ts.snap
  src/features/application-update/__snapshots__/periodical-checking-of-updates.test.ts.snap
  src/features/application-update/__snapshots__/selection-of-update-stability.test.ts.snap
  src/features/cluster/delete-dialog/__snapshots__/delete-cluster-dialog.test.tsx.snap
  src/features/command-pallet/__snapshots__/keyboard-shortcuts.test.tsx.snap
  src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/features/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  src/features/helm-charts/__snapshots__/add-helm-repository-from-list-in-preferences.test.ts.snap
  src/features/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
  src/features/helm-charts/__snapshots__/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts.snap
  src/features/preferences/__snapshots__/closing-preferences.test.tsx.snap
  src/features/preferences/__snapshots__/extension-adding-preference-tabs.test.tsx.snap
  src/features/preferences/__snapshots__/navigation-to-application-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/features/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-to-telemetry-preferences.test.tsx.snap
  src/features/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/features/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  src/features/status-bar/__snapshots__/status-bar-items-originating-from-extensions.test.tsx.snap
  src/features/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/renderer/components/status-bar/status-bar-item-injection-token.ts
  src/renderer/components/status-bar/status-bar-item-registrator.injectable.tsx
  src/renderer/components/status-bar/status-bar-items.injectable.tsx
  src/renderer/components/status-bar/status-bar.test.tsx
  src/renderer/components/status-bar/status-bar.tsx
Labels: enhancement, area/ui, area/extension

#6410 Clickable StorageClass
  src/renderer/components/+storage-volume-claims/volume-claim-details.tsx
  src/renderer/components/+storage-volumes/volume-details.tsx
Labels: enhancement, area/ui

#6411 Fix scss compilation warning by removing flex.box dependency
  package.json
  src/renderer/components/app.scss
  src/renderer/components/flexbox.scss
  yarn.lock
Labels: chore

#6428 Update version on master to 6.2.0-alpha.0
  package.json
Labels: chore

#6429 Add automatic workflow for bumping version on master
  .github/workflows/bump-master-version.yaml
Labels: area/ci

#6431 Require milestones on PRs before merging
  .github/workflows/require-milestone.yml
Labels: area/ci

#6438 Export node-pty spawn from main to extensions
  src/main/index.ts
Labels: enhancement, area/extension

#6444 Fix AppImage windows not showing the application icon
  src/common/vars/application-information.global-override-for-injectable.ts
  src/common/vars/application-information.injectable.ts
  src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts
Labels: bug, area/linux

#6441 Fix links in Readme
  README.md
Labels: area/documentation

#6442 Update all links within application
  .github/workflows/mkdocs-manual.yml
  CONTRIBUTING.md
  docs/extensions/get-started/your-first-extension.md
  docs/extensions/guides/generator.md
  docs/extensions/guides/renderer-extension.md
  src/common/vars.ts
  src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/migrations/weblinks-store/currentVersion.ts
Labels: bug

#6458 Increase log file maxsize from 16KB to 1MB
  src/common/logger.ts
Labels: enhancement

#6461 Bump lens-k8s-proxy to v0.3.0
  package.json
Labels: dependencies

#6453 Fix syncing shell env on TCSH and CSH
  src/main/crypto/random-uuid.global-override-for-injectable.ts
  src/main/crypto/random-uuid.injectable.ts
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
Labels: bug, p0

#6462 Change log level to file always be debug
  src/common/logger.ts
Labels: chore

#6481 Bump ogre-tools and adapt to breaking changes
  package.json
  src/features/helm-charts/child-features/preferences/renderer/active-helm-repositories.injectable.ts
  src/features/helm-charts/child-features/preferences/renderer/adding-of-public-helm-repository/public-helm-repositories/public-helm-repositories.injectable.ts
  src/renderer/components/+helm-charts/details/readme-of-selected-helm-chart.injectable.ts
  src/renderer/components/+helm-charts/details/versions-of-selected-helm-chart.injectable.ts
  src/renderer/components/+helm-charts/helm-charts/helm-charts.injectable.ts
  src/renderer/components/+helm-charts/helm-charts/versions.injectable.ts
  src/renderer/components/+helm-releases/releases.injectable.ts
  src/renderer/components/dock/upgrade-chart/upgrade-chart-model.injectable.ts
  src/renderer/extension-loader/extension-should-be-enabled-for-cluster-frame.injectable.ts
  src/renderer/getDiForUnitTesting.tsx
  yarn.lock
Labels: chore

#6483 Release 6.1.14
  package.json
  src/features/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  src/features/__snapshots__/navigate-to-extension-page.test.tsx.snap
  src/features/__snapshots__/navigating-between-routes.test.tsx.snap
  src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/features/application-update/__snapshots__/force-user-to-update-when-too-long-time-since-update-was-downloaded.test.ts.snap
  src/features/application-update/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  src/features/application-update/__snapshots__/installing-update-using-tray.test.ts.snap
  src/features/application-update/__snapshots__/installing-update.test.ts.snap
  src/features/application-update/__snapshots__/periodical-checking-of-updates.test.ts.snap
  src/features/application-update/__snapshots__/selection-of-update-stability.test.ts.snap
  src/features/command-pallet/__snapshots__/keyboard-shortcuts.test.tsx.snap
  src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/features/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  src/features/helm-charts/__snapshots__/add-helm-repository-from-list-in-preferences.test.ts.snap
  src/features/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
  src/features/helm-charts/__snapshots__/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts.snap
  src/features/preferences/__snapshots__/closing-preferences.test.tsx.snap
  src/features/preferences/__snapshots__/extension-adding-preference-tabs.test.tsx.snap
  src/features/preferences/__snapshots__/navigation-to-application-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/features/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-to-telemetry-preferences.test.tsx.snap
  src/features/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  src/features/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/features/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  src/features/status-bar/__snapshots__/status-bar-items-originating-from-extensions.test.tsx.snap
  src/features/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/renderer/components/status-bar/status-bar-item-injection-token.ts
  src/renderer/components/status-bar/status-bar-item-registrator.injectable.tsx
  src/renderer/components/status-bar/status-bar-items.injectable.tsx
  src/renderer/components/status-bar/status-bar.test.tsx
  src/renderer/components/status-bar/status-bar.tsx
Labels: skip-changelog, release

#6096 Remove global version of appEventBus
  src/common/__tests__/event-bus.test.ts
  src/common/app-event-bus/app-event-bus.global-override-for-injectable.ts
  src/common/app-event-bus/app-event-bus.injectable.ts
  src/common/app-event-bus/emit-event.injectable.ts
  src/common/app-event-bus/event-bus.ts
  src/common/cluster-store/cluster-store.injectable.ts
  src/common/cluster-store/cluster-store.ts
  src/common/event-emitter.ts
  src/common/fs/exec-file.injectable.ts
  src/common/helm/add-helm-repository-channel.ts
  src/common/helm/remove-helm-repository-channel.ts
  src/common/k8s/resource-stack.ts
  src/common/user-store/user-store.injectable.ts
  src/common/user-store/user-store.ts
  src/common/utils/async-result.ts
  src/extensions/common-api/event-bus.ts
  src/extensions/npm/extensions/package.json
  src/features/application-update/main/emit-current-version-to-analytics.injectable.ts
  src/features/application-update/main/process-checking-for-updates.injectable.ts
  src/features/application-update/main/quit-and-install-update.injectable.ts
  src/features/cluster/delete-dialog/delete-cluster-dialog.test.tsx
  src/features/cluster/delete-dialog/main/delete-channel-listener.injectable.ts
  src/features/helm-charts/add-custom-helm-repository-in-preferences.test.ts
  src/features/helm-charts/add-helm-repository-from-list-in-preferences.test.ts
  src/features/helm-charts/listing-active-helm-repositories-in-preferences.test.ts
  src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.injectable.ts
  src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.ts
  src/main/getDiForUnitTesting.ts
  src/main/helm/exec-helm/exec-helm.injectable.ts
  src/main/helm/get-helm-env/get-helm-env.injectable.ts
  src/main/helm/helm-service/get-helm-release-resources/call-for-helm-manifest/call-for-helm-manifest.injectable.ts
  src/main/helm/repositories/add-helm-repository/add-helm-repository.injectable.ts
  src/main/helm/repositories/get-active-helm-repositories/get-active-helm-repositories.injectable.ts
  src/main/helm/repositories/remove-helm-repository/remove-helm-repository.injectable.ts
  src/main/lens-proxy/lens-proxy.injectable.ts
  src/main/lens-proxy/lens-proxy.ts
  src/main/resource-applier/create-resource-applier.injectable.ts
  src/main/resource-applier/resource-applier.ts
  src/main/router/router.test.ts
  src/main/routes/resource-applier/create-resource-route.injectable.ts
  src/main/routes/resource-applier/patch-resource-route.injectable.ts
  src/main/shell-session/local-shell-session/open.injectable.ts
  src/main/shell-session/node-shell-session/open.injectable.ts
  src/main/shell-session/shell-session.ts
  src/main/start-main-application/lens-window/application-window/create-application-window.injectable.ts
  src/main/start-main-application/runnables/emit-close-to-event-bus.injectable.ts
  src/main/start-main-application/runnables/emit-service-start-to-event-bus.injectable.ts
  src/main/stop-services-and-exit-app.injectable.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/+catalog/catalog.test.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.injectable.ts
  src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
Labels: chore

#6490 React on any KubeObjectStore eventsBuffer change, not just length
  src/common/k8s-api/kube-object.store.ts
Labels: bug
