Repository lensapp/lens, pull requests merged in 2022-07, with the labels that each got.

#5764 Fix stuff happening based on timers not being run correctly in unit tests
  src/behaviours/application-update/analytics-for-installing-update.test.ts
  src/behaviours/application-update/installing-update-using-topbar-button.test.tsx
  src/behaviours/application-update/installing-update.test.ts
  src/behaviours/application-update/periodical-checking-of-updates.test.ts
  src/behaviours/cluster/sidebar-and-tab-navigation-for-core.test.tsx
  src/behaviours/cluster/sidebar-and-tab-navigation-for-extensions.test.tsx
  src/behaviours/quitting-and-restarting-the-app/quitting-the-app-using-application-menu.test.ts
  src/common/test-utils/use-fake-time.ts
  src/common/utils/reactive-now/reactive-now.test.tsx
  src/common/utils/reactive-now/reactive-now.ts
  src/renderer/components/duration/reactive-duration.tsx
  src/renderer/components/status-bar/auto-update-component.tsx
  src/renderer/components/update-button/update-warning-level.injectable.ts
Labels: bug

#5667 Fix crash in HelmChartDetails
  src/common/k8s-api/endpoints/helm-charts.api.ts
  src/renderer/components/+helm-charts/__snapshots__/helm-chart-details.test.tsx.snap
  src/renderer/components/+helm-charts/get-char-details.injectable.ts
  src/renderer/components/+helm-charts/helm-chart-details.scss
  src/renderer/components/+helm-charts/helm-chart-details.test.tsx
  src/renderer/components/+helm-charts/helm-chart-details.tsx
  src/renderer/components/+helm-charts/helm-charts.scss
  src/renderer/components/+helm-charts/helm-charts.tsx
  src/renderer/components/+helm-charts/helm-placeholder.svg
  src/renderer/components/+helm-charts/icon.tsx
  src/renderer/components/dock/install-chart/create-install-chart-tab.injectable.ts
  src/renderer/components/notifications/notifications.store.tsx
  src/renderer/components/notifications/notifications.tsx
  src/renderer/components/notifications/show-checked-error.injectable.ts
  src/renderer/components/notifications/show-error-notification.injectable.ts
  src/renderer/components/notifications/show-info-notification.injectable.ts
  src/renderer/components/notifications/show-short-info.injectable.ts
  src/renderer/components/notifications/show-success-notification.injectable.ts
  src/renderer/themes/lens-dark.ts
  src/renderer/themes/lens-light.ts
  src/renderer/themes/theme-vars.css
Labels: bug

#5704 Fix type errors using raw InputValidator
  src/renderer/components/input/__tests__/input_validators.test.ts
  src/renderer/components/input/input.tsx
  src/renderer/components/input/input_validators.ts
Labels: bug, area/extension

#5788 Remove unused ask-boolean injectable
  src/common/ask-boolean/ask-boolean-answer-channel.injectable.ts
  src/common/ask-boolean/ask-boolean-question-channel.injectable.ts
  src/renderer/ask-boolean/ask-boolean-question-channel-listener.injectable.tsx
Labels: chore

#5769 Replace status bar item application update with different tray icon based on status of the update
  build/generate-tray-icons.ts
  build/tray/trayIconCheckingForUpdates.png
  build/tray/trayIconCheckingForUpdates@2x.png
  build/tray/trayIconCheckingForUpdates@3x.png
  build/tray/trayIconCheckingForUpdates@4x.png
  build/tray/trayIconCheckingForUpdatesTemplate.png
  build/tray/trayIconCheckingForUpdatesTemplate@2x.png
  build/tray/trayIconCheckingForUpdatesTemplate@3x.png
  build/tray/trayIconCheckingForUpdatesTemplate@4x.png
  src/behaviours/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  src/behaviours/__snapshots__/navigate-to-extension-page.test.tsx.snap
  src/behaviours/__snapshots__/navigating-between-routes.test.tsx.snap
  src/behaviours/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/behaviours/application-update/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  src/behaviours/application-update/__snapshots__/installing-update-using-tray.test.ts.snap
  src/behaviours/application-update/__snapshots__/installing-update.test.ts.snap
  src/behaviours/application-update/__snapshots__/periodical-checking-of-updates.test.ts.snap
  src/behaviours/application-update/__snapshots__/selection-of-update-stability.test.ts.snap
  src/behaviours/application-update/installing-update-using-tray.test.ts
  src/behaviours/application-update/installing-update.test.ts
  src/behaviours/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/add-helm-repository-from-list-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/closing-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-application-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-telemetry-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  src/behaviours/status-bar/__snapshots__/status-bar-items-originating-from-extensions.test.tsx.snap
  src/behaviours/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/main/application-update/install-application-update-tray-item.injectable.ts
  src/main/application-update/tray-icons/checking-for-updates-tray-icon.injectable.ts
  src/main/application-update/tray-icons/update-is-ready-to-be-installed-tray-icon.injectable.ts
  src/main/application-update/update-is-ready-to-be-installed.injectable.ts
  src/main/tray/electron-tray/electron-tray.injectable.ts
  src/main/tray/menu-icon/get-tray-icon-path.injectable.ts
  src/main/tray/menu-icon/normal-tray-icon.injectable.ts
  src/main/tray/menu-icon/reactive.injectable.ts
  src/main/tray/menu-icon/tray-icon-injection-token.ts
  src/main/tray/menu-icon/tray-icon.injectable.ts
  src/main/tray/tray-icon-path.injectable.ts
  src/renderer/components/icon/arrow-spinner.svg
  src/renderer/components/status-bar/auto-update-component.tsx
  src/renderer/components/status-bar/auto-update-status-bar-item.injectable.ts
  src/renderer/components/test-utils/get-application-builder.tsx
Labels: enhancement

#5782 Make application window appear even when its hidden underneath other apps
  src/behaviours/quitting-and-restarting-the-app/opening-application-window-using-tray.test.ts
  src/main/electron-app/features/focus-application.injectable.ts
  src/main/getDiForUnitTesting.ts
  src/main/start-main-application/lens-window/show-application-window.injectable.ts
Labels: bug

#5781 Prevent re-downloading update that is already downloaded
  src/behaviours/application-update/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  src/behaviours/application-update/analytics-for-installing-update.test.ts
  src/behaviours/application-update/installing-update-using-topbar-button.test.tsx
  src/behaviours/application-update/installing-update.test.ts
  src/main/application-update/check-for-updates/process-checking-for-updates.injectable.ts
Labels: chore

#5789 Expose a way to reactively control visibility of preference tabs and tray menu items through Extension API
  src/behaviours/cluster/__snapshots__/order-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-core.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  src/behaviours/cluster/__snapshots__/visibility-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/sidebar-and-tab-navigation-for-extensions.test.tsx
  src/behaviours/helm-charts/__snapshots__/navigation-to-helm-charts.test.ts.snap
  src/behaviours/preferences/__snapshots__/extension-adding-preference-tabs.test.tsx.snap
  src/behaviours/preferences/extension-adding-preference-tabs.test.tsx
  src/behaviours/tray/extension-adding-tray-items.test.tsx
  src/extensions/registries/page-menu-registry.ts
  src/main/tray/tray-menu-item/tray-menu-item-registrator.injectable.ts
  src/main/tray/tray-menu-registration.ts
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+extensions/installed-extensions.tsx
  src/renderer/components/+helm-releases/release-menu.tsx
  src/renderer/components/+network-port-forwards/port-forward-menu.tsx
  src/renderer/components/+preferences/app-preference-tab/app-preference-tab-registration.ts
  src/renderer/components/+preferences/preferences-navigation/extension-tab-preferences-navigation-item.injectable.ts
  src/renderer/components/cluster-settings/components/cluster-icon-settings.tsx
  src/renderer/components/dock/dock.tsx
  src/renderer/components/item-object-list/content.tsx
  src/renderer/components/kube-object-menu/__snapshots__/kube-object-menu.test.tsx.snap
  src/renderer/components/kube-object-menu/kube-object-menu.tsx
  src/renderer/components/layout/extension-sidebar-item-registrator.injectable.tsx
  src/renderer/components/menu/menu-actions.tsx
  src/renderer/components/test-utils/get-application-builder.tsx
  src/renderer/components/test-utils/get-extension-fake.ts
  src/renderer/components/test-utils/get-renderer-extension-fake.ts
  src/renderer/frames/cluster-frame/__snapshots__/cluster-frame.test.tsx.snap
Labels: enhancement

#5776 Force update after thirty days since update was downloaded
  src/behaviours/application-update/__snapshots__/force-user-to-update-when-too-long-time-since-update-was-downloaded.test.ts.snap
  src/behaviours/application-update/force-user-to-update-when-too-long-time-since-update-was-downloaded.test.ts
  src/renderer/application-update/force-update-modal/force-update-modal-root-frame-component.injectable.ts
  src/renderer/application-update/force-update-modal/force-update-modal.module.scss
  src/renderer/application-update/force-update-modal/force-update-modal.tsx
  src/renderer/application-update/force-update-modal/install-update-countdown.injectable.ts
  src/renderer/application-update/force-update-modal/seconds-after-install-starts.injectable.ts
  src/renderer/application-update/force-update-modal/time-after-update-must-be-installed.injectable.ts
  src/renderer/application-update/force-update-modal/time-since-update-was-downloaded.injectable.ts
  src/renderer/components/countdown/countdown-state.injectable.ts
  src/renderer/components/countdown/countdown.test.tsx
  src/renderer/components/countdown/countdown.tsx
Labels: enhancement

#5793 Export TrayMenuRegistration type
  src/extensions/common-api/registrations.ts
Labels: bug, area/extension

#5795 release 5.6.0-alpha.6
  package.json
Labels: skip-changelog

#5798 Use extension's app preference tab name when available
  src/behaviours/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/renderer/components/+preferences/extension-preference-model.injectable.ts
Labels: bug, area/extension

#5691 Fix check on NamespaceSelectFilter not updating
  src/common/utils/index.ts
  src/common/utils/noop.ts
  src/common/utils/observable-crate/impl.ts
  src/common/utils/observable-crate/observable-crate.test.ts
  src/renderer/components/+namespaces/__snapshots__/namespace-select-filter.test.tsx.snap
  src/renderer/components/+namespaces/namespace-select-filter-model/is-selection-key.injectable.ts
  src/renderer/components/+namespaces/namespace-select-filter-model/namespace-select-filter-model.injectable.ts
  src/renderer/components/+namespaces/namespace-select-filter-model/namespace-select-filter-model.tsx
  src/renderer/components/+namespaces/namespace-select-filter.scss
  src/renderer/components/+namespaces/namespace-select-filter.test.tsx
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/select/select.tsx
  src/renderer/frames/cluster-frame/__snapshots__/cluster-frame.test.tsx.snap
Labels: bug, blocker

#5815 Update snapshots after merging something
  src/behaviours/cluster/__snapshots__/order-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-core.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  src/behaviours/cluster/__snapshots__/visibility-of-sidebar-items.test.tsx.snap
Labels: chore

#5803 Introduce kludge to make "isEnabledForCluster" work again for kube object menu items PART 4
  src/behaviours/cluster/kube-object-menu/extension-api/__snapshots__/disable-kube-object-menu-items-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-menu/extension-api/disable-kube-object-menu-items-when-cluster-is-not-relevant.test.tsx
  src/renderer/components/kube-object-menu/dependencies/kube-object-menu-items/get-kube-object-menu-items.ts
  src/renderer/components/kube-object-menu/dependencies/kube-object-menu-items/kube-object-menu-items.injectable.ts
  src/renderer/components/kube-object-menu/dependencies/static-kube-object-menu-items.ts
  src/renderer/components/kube-object-menu/kube-object-menu-item-injection-token.ts
  src/renderer/components/kube-object-menu/kube-object-menu-item-registrator.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items/cron-job-menu.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items/deployment-menu.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items/replica-set-menu.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items/service-account-menu.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu.test.tsx
  src/renderer/components/kube-object-menu/kube-object-menu.tsx
Labels: bug

#5802 Introduce kludge to make "isEnabledForCluster" work again for kube object status texts PART 3
  src/behaviours/cluster/kube-object-menu/extension-api/__snapshots__/disable-kube-object-menu-items-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-menu/extension-api/disable-kube-object-menu-items-when-cluster-is-not-relevant.test.tsx
  src/behaviours/cluster/kube-object-status-icon/extension-api/__snapshots__/disable-kube-object-statuses-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-status-icon/extension-api/disable-kube-object-statuses-when-cluster-is-not-relevant.test.tsx
  src/renderer/components/kube-object-menu/dependencies/kube-object-menu-items/get-kube-object-menu-items.ts
  src/renderer/components/kube-object-menu/dependencies/kube-object-menu-items/kube-object-menu-items.injectable.ts
  src/renderer/components/kube-object-menu/dependencies/static-kube-object-menu-items.ts
  src/renderer/components/kube-object-menu/kube-object-menu-item-injection-token.ts
  src/renderer/components/kube-object-menu/kube-object-menu-item-registrator.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items/cron-job-menu.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items/deployment-menu.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items/replica-set-menu.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu-items/service-account-menu.injectable.ts
  src/renderer/components/kube-object-menu/kube-object-menu.test.tsx
  src/renderer/components/kube-object-menu/kube-object-menu.tsx
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.test.tsx
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.tsx
  src/renderer/components/kube-object-status-icon/kube-object-status-text-injection-token.ts
  src/renderer/components/kube-object-status-icon/kube-object-status-text-registrator.injectable.ts
  src/renderer/components/kube-object-status-icon/kube-object-status-texts-for-object.injectable.ts
  src/renderer/components/kube-object-status-icon/kube-object-status-texts.injectable.ts
  src/renderer/components/kube-object-status-icon/status-registrations.injectable.ts
  src/renderer/components/kube-object-status-icon/statuses-for-kube-object.injectable.ts
Labels: bug

#5805 Introduce kludge to make "isEnabledForCluster" work again for kube object details PART 6
  src/behaviours/cluster/kube-object-details/extension-api/__snapshots__/disable-kube-object-detail-items-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-details/extension-api/disable-kube-object-detail-items-when-cluster-is-not-relevant.test.tsx
  src/extensions/common-api/registrations.ts
  src/extensions/extension-loader/extension-loader.injectable.ts
  src/extensions/extension-loader/extension-loader.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/index.ts
  src/extensions/registries/kube-object-detail-registry.ts
  src/renderer/api/kube-object-detail-registry.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+workloads-pods/details/volumes/variants/flex-volume.tsx
  src/renderer/components/kube-object-details/current-kube-object-in-details.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/cluster-role-binding-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/cluster-role-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/config-map-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/cron-job-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/custom-resource-definitions-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/daemon-set-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/deployment-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/endpoints-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/events-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/horizontal-pod-autoscaler-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/ingress-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/job-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/kube-event-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/limit-range-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/namespaces-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/network-policy-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/node-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/persistent-volume-claim-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/persistent-volume-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/pod-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/pod-disruption-budget-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/pod-security-policy-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/replica-set-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/resource-quota-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/role-binding-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/role-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/secrets-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/service-account-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/service-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/stateful-set-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/storage-class-detail-item.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/kube-object-detail-item-injection-token.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/kube-object-detail-item-registrator.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/kube-object-detail-items.injectable.ts
  src/renderer/components/kube-object-details/kube-object-detail-items/kube-object-matches-to-kind-and-api-version.ts
  src/renderer/components/kube-object-details/kube-object-detail-registration.ts
  src/renderer/components/kube-object-details/kube-object-details.tsx
  src/renderer/initializers/index.ts
  src/renderer/initializers/kube-object-detail-registry.tsx
  src/renderer/initializers/registries.ts
Labels: bug

#5832 release v5.6.0-alpha.7
  package.json
Labels: skip-changelog

#5818 Fix open CommandDialog
  src/behaviours/command-pallet/__snapshots__/keyboard-shortcuts.test.tsx.snap
  src/behaviours/command-pallet/keyboard-shortcuts.test.tsx
  src/extensions/registries/entity-setting-registry.ts
  src/renderer/components/command-palette/command-container-cluster-frame-child-component.injectable.ts
  src/renderer/components/command-palette/command-container-root-frame-child-component.injectable.ts
  src/renderer/components/command-palette/command-container.module.scss
  src/renderer/components/command-palette/command-container.tsx
  src/renderer/components/command-palette/command-overlay.injectable.ts
  src/renderer/components/command-palette/registered-commands/get-entity-setting-commands.injectable.ts
  src/renderer/components/command-palette/registered-commands/internal-commands.injectable.tsx
  src/renderer/getDiForUnitTesting.tsx
  src/renderer/utils/on-keyboard-shortcut.ts
  src/renderer/window/event-listener.injectable.ts
Labels: bug, area/windows, area/linux

#5811 Fix terminal fit errors
  src/common/utils/disposer.ts
  src/renderer/components/dock/terminal/terminal.ts
Labels: bug, area/terminal

#5840 Do not show Version on welcome screen
  src/behaviours/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  src/behaviours/__snapshots__/navigate-to-extension-page.test.tsx.snap
  src/behaviours/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/behaviours/application-update/__snapshots__/force-user-to-update-when-too-long-time-since-update-was-downloaded.test.ts.snap
  src/behaviours/application-update/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  src/behaviours/application-update/__snapshots__/installing-update-using-tray.test.ts.snap
  src/behaviours/application-update/__snapshots__/installing-update.test.ts.snap
  src/behaviours/application-update/__snapshots__/periodical-checking-of-updates.test.ts.snap
  src/behaviours/application-update/__snapshots__/selection-of-update-stability.test.ts.snap
  src/behaviours/command-pallet/__snapshots__/keyboard-shortcuts.test.tsx.snap
  src/behaviours/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  src/behaviours/status-bar/__snapshots__/status-bar-items-originating-from-extensions.test.tsx.snap
  src/behaviours/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/renderer/components/+welcome/welcome.tsx
Labels: chore

#5816 feat: New view for PriorityClasses under Config menu
  extensions/metrics-cluster-feature/resources/12-kube-state-metrics-clusterrole.yml
  src/common/front-end-routing/routes/cluster/config/priority-classes/navigate-to-priority-classes.injectable.ts
  src/common/front-end-routing/routes/cluster/config/priority-classes/priority-classes-route.injectable.ts
  src/common/k8s-api/endpoints/index.ts
  src/common/k8s-api/endpoints/priority-class.api.injectable.ts
  src/common/k8s-api/endpoints/priority-class.api.ts
  src/common/k8s-api/endpoints/types/preemption-policy.ts
  src/common/rbac.ts
  src/extensions/common-api/k8s-api.ts
  src/extensions/renderer-api/k8s-api.ts
  src/renderer/components/+config-priority-classes/index.ts
  src/renderer/components/+config-priority-classes/priority-classes-details.scss
  src/renderer/components/+config-priority-classes/priority-classes-details.tsx
  src/renderer/components/+config-priority-classes/priority-classes-items.injectable.tsx
  src/renderer/components/+config-priority-classes/priority-classes-route-component.injectable.ts
  src/renderer/components/+config-priority-classes/priority-classes.scss
  src/renderer/components/+config-priority-classes/priority-classes.tsx
  src/renderer/components/+config-priority-classes/store.injectable.ts
  src/renderer/components/+config-priority-classes/store.ts
  src/renderer/components/command-palette/registered-commands/internal-commands.injectable.tsx
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/priority-class-detail-item.injectable.ts
  src/renderer/utils/rbac.ts
  templates/create-resource/ClusterRole.yaml
  templates/create-resource/PriorityClass.yaml
Labels: enhancement

#5833 Remove old workaround to append clusterUrl in resolveAuthProxyUrl()
  src/main/context-handler/context-handler.ts
Labels: bug

#5845 Add guards to prevent activation errors slipping through
  src/common/cluster/cluster.ts
  src/common/logger.ts
  src/main/kube-auth-proxy/kube-auth-proxy.ts
  src/main/kubectl/kubectl.ts
  src/main/routes/metrics/add-metrics-route.injectable.ts
  src/main/routes/port-forward/functionality/port-forward.ts
  src/main/utils/get-port.ts
  src/renderer/themes/store.ts
Labels: bug

#5878 Fix edit kube resource tab not respecting changes to current draft
  src/renderer/components/dock/edit-resource/view.tsx
Labels: bug, area/dock

#5882 Revert "Bump type-fest from 2.14.0 to 2.17.0 (#5864)"
  package.json
  yarn.lock
Labels: dependencies

#5880 use intended(?) node-pty version
  package.json
  yarn.lock
Labels: bug

#5870 Fix terminal freezing self and whole app when internet is disconnected
  src/renderer/api/__tests__/websocket-api.test.ts
  src/renderer/api/websocket-api.ts
Labels: bug, area/terminal

#5874 Fix styles for topbar window buttons on linux
  src/renderer/components/layout/top-bar/top-bar.module.scss
Labels: bug, area/linux, area/ui

#5886 release 6.0.0-alpha.0
  package.json
  scripts/create-release-pr.mjs
Labels: skip-changelog

#5881 Fix trying to connect to cluster whose entity doesn't exist
  src/renderer/components/cluster-manager/cluster-view.tsx
Labels: bug, blocker

#5850 Fix opening of release details
  src/behaviours/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-new-tab.test.ts.snap
  src/behaviours/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  src/behaviours/helm-releases/showing-details-for-helm-release.test.ts
  src/common/k8s-api/endpoints/helm-releases.api.ts
  src/common/test-utils/get-global-override.ts
  src/main/getDiForUnitTesting.ts
  src/main/helm/helm-release-manager.ts
  src/renderer/components/+helm-releases/call-for-helm-releases/call-for-helm-releases.global-override-for-injectable.ts
  src/renderer/components/+helm-releases/call-for-helm-releases/call-for-helm-releases.injectable.ts
  src/renderer/components/+helm-releases/create-release/call-for-create-helm-release.injectable.ts
  src/renderer/components/+helm-releases/create-release/create-release.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-cluster-frame-child-component.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-content.tsx
  src/renderer/components/+helm-releases/release-details/release-details-model/call-for-helm-release-configuration/call-for-helm-release-configuration.global-override-for-injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/call-for-helm-release-configuration/call-for-helm-release-configuration.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/call-for-helm-release/call-for-helm-release-details/call-for-helm-release-details.global-override-for-injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/call-for-helm-release/call-for-helm-release-details/call-for-helm-release-details.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/call-for-helm-release/call-for-helm-release.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/get-resource-details-url.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx
  src/renderer/components/+helm-releases/release-details/release-details.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details.tsx
  src/renderer/components/+helm-releases/release-details/release-values.injectable.ts
  src/renderer/components/+helm-releases/release-details/target-helm-release.injectable.ts
  src/renderer/components/+helm-releases/release-details/user-supplied-values-are-shown.injectable.ts
  src/renderer/components/+helm-releases/releases.injectable.ts
  src/renderer/components/+helm-releases/releases.tsx
  src/renderer/components/+helm-releases/update-release/call-for-helm-release-update/call-for-helm-release-update.global-override-for-injectable.ts
  src/renderer/components/+helm-releases/update-release/call-for-helm-release-update/call-for-helm-release-update.injectable.ts
  src/renderer/components/+helm-releases/update-release/update-release.injectable.ts
  src/renderer/components/dock/upgrade-chart/create-upgrade-chart-tab.injectable.ts
  src/renderer/components/dock/upgrade-chart/get-random-upgrade-chart-tab-id.injectable.ts
  src/renderer/components/dock/upgrade-chart/view.tsx
  src/renderer/components/drawer/drawer.tsx
  src/renderer/components/item-object-list/content.tsx
  src/renderer/components/item-object-list/list-layout.tsx
  src/renderer/getDiForUnitTesting.tsx
Labels: bug, blocker

#5889 Remove global shared state to fix unit tests
  src/behaviours/application-update/analytics-for-installing-update.test.ts
  src/behaviours/application-update/downgrading-version-update.test.ts
  src/behaviours/application-update/selection-of-update-stability.test.ts
  src/common/__tests__/base-store.test.ts
  src/common/__tests__/cluster-store.test.ts
  src/common/__tests__/hotbar-store.test.ts
  src/common/__tests__/user-store.test.ts
  src/common/application-update/selected-update-channel/default-update-channel.injectable.ts
  src/common/base-store.ts
  src/common/vars.ts
  src/common/vars/app-semantic-version.injectable.ts
  src/common/vars/app-version.injectable.ts
  src/extensions/extension-discovery/extension-discovery.test.ts
  src/extensions/extension-discovery/is-compatible-bundled-extension/is-compatible-bundled-extension.injectable.ts
  src/extensions/extension-discovery/is-compatible-extension/is-compatible-extension.injectable.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/application-update/check-for-updates/update-can-be-downgraded.injectable.ts
  src/main/application-update/emit-current-version-to-analytics.injectable.ts
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/getDiForUnitTesting.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/renderer/components/+catalog/catalog.test.tsx
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/dock/__test__/dock-tabs.test.tsx
  src/renderer/components/dock/logs/__test__/log-resource-selector.test.tsx
  src/renderer/components/hotbar/__tests__/hotbar-remove-command.test.tsx
  src/renderer/components/select/select.test.tsx
  src/renderer/getDiForUnitTesting.tsx
Labels: chore

#5875 Resolve kube object status texts again on re-render to make it look like it's reactive
  src/behaviours/cluster/kube-object-status-icon/__snapshots__/show-status-for-a-kube-object.test.tsx.snap
  src/behaviours/cluster/kube-object-status-icon/extension-api/__snapshots__/disable-kube-object-statuses-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-status-icon/show-status-for-a-kube-object.test.tsx
  src/renderer/components/kube-object-status-icon/__snapshots__/kube-object-status-icon.test.tsx.snap
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.test.tsx
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.tsx
  src/renderer/components/kube-object-status-icon/kube-object-status-text-injection-token.ts
  src/renderer/components/kube-object-status-icon/kube-object-status-texts-for-object.injectable.ts
Labels: bug, p1

#5908 Set focus on port field when port-forward-dialog opens
  src/renderer/port-forward/port-forward-dialog.tsx
Labels: enhancement, area/ui

#5901 Remove "preferences" from extension preference page title
  src/behaviours/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/behaviours/preferences/navigation-to-extension-specific-preferences.test.tsx
  src/renderer/components/+preferences/extension-preference-model.injectable.ts
  src/renderer/components/+preferences/extensions.tsx
Labels: enhancement, area/extension

#5913 Increase timeout for macos build pipeline
  .azure-pipelines.yml
Labels: area/ci

#5916 revert node-pty to stable version
  package.json
  yarn.lock
Labels: bug, blocker

#5933 release 6.0.0-alpha.1
  package.json
Labels: skip-changelog

#5935 release 6.0.0
  package.json
Labels: skip-changelog

#5911 Fix Badge.props.expandable's default being switched to false
  src/renderer/components/badge/badge.tsx
Labels: bug

#5921 Fine-tune styles of Extensions page
  src/behaviours/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/renderer/components/+extensions/extensions.module.scss
  src/renderer/components/+extensions/extensions.scss
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+extensions/install.module.scss
  src/renderer/components/+extensions/install.tsx
Labels: bug, area/ui

#5948 Open application only if new update is available when using tray to check for updates
  src/behaviours/application-update/installing-update-using-topbar-button.test.tsx
  src/behaviours/application-update/installing-update-using-tray.test.ts
  src/behaviours/application-update/installing-update.test.ts
  src/behaviours/application-update/periodical-checking-of-updates.test.ts
  src/behaviours/application-update/selection-of-update-stability.test.ts
  src/main/application-update/check-for-updates-tray-item.injectable.ts
  src/main/application-update/check-for-updates/process-checking-for-updates.injectable.ts
  src/renderer/utils/sync-box/provide-initial-values-for-sync-boxes.injectable.ts
Labels: bug
