Repository lensapp/lens, pull requests merged in 2022-08, with the labels that each got.

#5943 Remove duplicate 'Controlled by' section on Jobs' details
  src/renderer/components/+workloads-jobs/job-details.tsx
Labels: bug

#5954 Fix KubeObjectDetails drawer not working for Cluster scoped resources
  src/common/k8s-api/kube-object.store.ts
  src/renderer/components/kube-object-details/kube-object-details.tsx
Labels: bug

#5949 Fix ingress list line heights
  src/renderer/components/+network-ingresses/ingresses.scss
  src/renderer/components/+network-ingresses/ingresses.tsx
  src/renderer/components/virtual-list/virtual-list.tsx
Labels: bug, area/ui

#5430 Fix not being able to switch metrics if none are available
  src/renderer/components/+cluster/cluster-metric-switchers.tsx
  src/renderer/components/+cluster/cluster-metrics.module.scss
  src/renderer/components/radio/radio.scss
  src/renderer/components/radio/radio.tsx
Labels: bug, area/ui

#5962 Replace individual mocks for withTooltip with global mock
  src/behaviours/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/behaviours/add-cluster/navigation-using-application-menu.test.tsx
  src/behaviours/cluster/__snapshots__/order-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-core.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  src/behaviours/cluster/__snapshots__/visibility-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/extension-api/__snapshots__/disable-cluster-pages-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/extension-api/__snapshots__/disable-sidebar-items-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-details/extension-api/__snapshots__/disable-kube-object-detail-items-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-menu/extension-api/__snapshots__/disable-kube-object-menu-items-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-status-icon/__snapshots__/show-status-for-a-kube-object.test.tsx.snap
  src/behaviours/cluster/kube-object-status-icon/extension-api/__snapshots__/disable-kube-object-statuses-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/cluster/kube-object-status-icon/show-status-for-a-kube-object.test.tsx
  src/behaviours/cluster/namespaces/__snapshots__/edit-namespace-from-new-tab.test.tsx.snap
  src/behaviours/cluster/namespaces/__snapshots__/edit-namespace-from-previously-opened-tab.test.tsx.snap
  src/behaviours/cluster/namespaces/edit-namespace-from-new-tab.test.tsx
  src/behaviours/cluster/namespaces/edit-namespace-from-previously-opened-tab.test.tsx
  src/behaviours/cluster/sidebar-and-tab-navigation-for-extensions.test.tsx
  src/behaviours/cluster/workloads/overview/extension-api/__snapshots__/disable-workloads-overview-details-when-cluster-is-not-relevant.test.tsx.snap
  src/behaviours/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/add-helm-repository-from-list-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts.snap
  src/behaviours/helm-charts/add-custom-helm-repository-in-preferences.test.ts
  src/behaviours/helm-charts/add-helm-repository-from-list-in-preferences.test.ts
  src/behaviours/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-new-tab.test.ts.snap
  src/behaviours/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-previously-opened-tab.test.ts.snap
  src/behaviours/helm-charts/installing-chart/__snapshots__/opening-dock-tab-for-installing-helm-chart.test.ts.snap
  src/behaviours/helm-charts/installing-chart/installing-helm-chart-from-new-tab.test.ts
  src/behaviours/helm-charts/installing-chart/installing-helm-chart-from-previously-opened-tab.test.ts
  src/behaviours/helm-charts/installing-chart/opening-dock-tab-for-installing-helm-chart.test.ts
  src/behaviours/helm-charts/listing-active-helm-repositories-in-preferences.test.ts
  src/behaviours/helm-charts/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts
  src/behaviours/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  src/behaviours/helm-releases/showing-details-for-helm-release.test.ts
  src/jest.setup.ts
  src/renderer/components/tooltip/__mocks__/withTooltip.tsx
  src/renderer/frames/cluster-frame/__snapshots__/cluster-frame.test.tsx.snap
Labels: chore

#5642 Fix CPU spike when opening PodDetails from MonacoEditor
  src/renderer/components/drawer/__snapshots__/drawer-param-toggler.test.tsx.snap
  src/renderer/components/drawer/drawer-param-toggler.test.tsx
  src/renderer/components/drawer/drawer-param-toggler.tsx
Labels: bug

#5175 Fix Pod Container sorting not correlating to visuals
  src/common/utils/tuple.ts
  src/renderer/components/+workloads-pods/pods.tsx
  src/renderer/components/table/__tests__/getSorted.test.ts
  src/renderer/components/table/sorting.ts
Labels: bug

#5956 Fix HorizontalPodAutoscaler metrics not displaying current values
  src/common/k8s-api/endpoints/horizontal-pod-autoscaler.api.ts
  src/renderer/components/+config-autoscalers/hpa-details.tsx
Labels: bug, area/ui

#5982 Tweak timing of starting and stopping kubeconfig sync
  src/main/start-main-application/runnables/kube-config-sync/start-kube-config-sync.injectable.ts
  src/main/start-main-application/runnables/kube-config-sync/stop-kube-config-sync.injectable.ts
Labels: chore

#5986 Correctly handle HorizontalPodAutoscaler metrics with 0 usage
  src/common/k8s-api/endpoints/horizontal-pod-autoscaler.api.ts
Labels: bug

#5981 Tweak timing of starting and stopping periodical checking for updates
  src/main/application-update/periodical-check-for-updates/start-checking-for-updates.injectable.ts
  src/main/application-update/periodical-check-for-updates/stop-checking-for-updates.injectable.ts
Labels: chore

#5909 Fix ResourceQuotaDetails quotas display bugs
  src/common/utils/convertCpu.ts
  src/renderer/components/+config-resource-quotas/resource-quota-details.tsx
  src/renderer/components/+workloads-pods/store.ts
Labels: bug

#5964 fix(ci): make appBundleId configurable.
  build/notarize.js
Labels: chore

#6002 Fix incorrect links in workload overview page
  src/renderer/components/+workloads-overview/workloads/implementations/cron-jobs-workload.injectable.ts
  src/renderer/components/+workloads-overview/workloads/implementations/replicasets-workload.injectable.ts
  src/renderer/components/+workloads-overview/workloads/implementations/statefulsets-workload.injectable.ts
Labels: bug

#5995 Fix focus not switching to new cluster frame
  src/renderer/components/cluster-manager/cluster-frame-handler.ts
Labels: bug

#5451 Fix completely overriding PATH in shellSync
  src/common/utils/__tests__/union-env-path.test.ts
  src/common/utils/union-env-path.ts
  src/main/shell-sync.ts
  src/main/utils/shell-env.ts
Labels: bug

#6006 release 6.0.1-beta.0
  package.json
Labels: skip-changelog

#5996 Remove usage of deprecated xtermjs's registerLinkMatcher API
  package.json
  src/common/utils/index.ts
  src/common/utils/open-link-in-browser.global-override-for-injectable.ts
  src/common/utils/open-link-in-browser.injectable.ts
  src/common/utils/openBrowser.ts
  src/extensions/common-api/utils.ts
  src/main/menu/application-menu-items.injectable.ts
  src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts
  src/renderer/components/+network-port-forwards/port-forward-menu.tsx
  src/renderer/components/+network-services/service-port-component.tsx
  src/renderer/components/+workloads-pods/pod-container-port.tsx
  src/renderer/components/dock/terminal/create-terminal.injectable.ts
  src/renderer/components/dock/terminal/terminal.ts
  src/renderer/port-forward/open-port-forward.injectable.ts
  src/renderer/port-forward/port-forward-dialog.tsx
  src/renderer/port-forward/port-forward-utils.ts
  yarn.lock
Labels: chore

#5712 Start doing Architectural Decision Records (ADRs)
  .adr.json
  docs/architecture/decisions/README.md
  package.json
  yarn.lock
Labels: area/documentation

#5987 Fix Badges being too small when scrollable and not expandable
  src/renderer/components/badge/badge.module.scss
Labels: bug, area/ui

#6016 release v6.0.1
  package.json
Labels: skip-changelog

#6011 Update injectable for improved performance
  package.json
  yarn.lock
Labels: chore

#6020 Remove Tabs hover line width transition
  src/renderer/components/tabs/tabs.scss
Labels: bug, area/ui

#6013 Optimize getting injectable paths only once for all test suites
  src/common/test-utils/get-global-override.ts
  src/jest.setup.ts
  src/main/getDiForUnitTesting.ts
  src/renderer/getDiForUnitTesting.tsx
Labels: chore

#6023 Fix distribution detector erroneously depending on previous metadata
  src/main/cluster-detectors/distribution-detector.ts
Labels: bug

#6036 Allow reactive tray item labels for extensions
  src/behaviours/tray/clicking-tray-menu-item-originating-from-extension.test.ts
  src/behaviours/tray/extension-adding-tray-items.test.tsx
  src/main/tray/tray-menu-item/tray-menu-item-registrator.injectable.ts
  src/main/tray/tray-menu-registration.ts
Labels: enhancement

#6038 Show extension api version
  src/main/menu/build-version.global-override-for-injectable.ts
  src/main/menu/build-version.injectable.ts
  src/main/menu/menu.ts
  src/main/menu/show-about.injectable.ts
Labels: enhancement, area/extension

#6034 Make injectables in new "features"-directory auto register
  src/jest.setup.ts
  src/main/getDi.ts
  src/renderer/getDi.tsx
Labels: chore

#6039 Don't error out if we can't find resources from helm in our cluster, and handle "blank" output from kubectl gracefully.
  src/main/helm/helm-release-manager.ts
Labels: bug, area/helm

#6049 Use official node-fetch 2.x
  package.json
  yarn.lock
Labels: bug, area/security

#6050 Add Service Account in pods details
  src/common/k8s-api/endpoints/pod.api.ts
  src/renderer/components/+workloads-pods/pod-details.tsx
Labels: enhancement, area/ui

#6052 Fix UI for scaling ReplicaSets
  src/renderer/components/+workloads-replicasets/scale-dialog/dialog.tsx
Labels: bug, area/ui

#6074 Fix iframes white background
  src/renderer/components/app.scss
Labels: bug, area/ui

#6077 Use abort-controller package to fix typing issues
  package.json
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/utils/abort-controller.ts
  src/common/utils/delay.ts
  src/common/utils/reject-promise.ts
  src/renderer/kube-watch-api/kube-watch-api.ts
  yarn.lock
Labels: chore, area/extension

#6025 Add node name column to pods list
  src/renderer/components/+workloads-pods/pod-details-list.scss
  src/renderer/components/+workloads-pods/pod-details-list.tsx
Labels: enhancement, area/ui

#6081 Use default export to fix issue with package lying with types
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/utils/abort-controller.ts
  src/renderer/kube-watch-api/kube-watch-api.ts
Labels: chore

#6014 Replace some mocks with overrides
  src/common/cluster/cluster.ts
  src/common/fs/stat/stat.global-override-for-injectable.ts
  src/common/fs/stat/stat.injectable.ts
  src/common/fs/validate-directory.injectable.ts
  src/common/fs/watch/watch.global-override-for-injectable.ts
  src/common/fs/watch/watch.injectable.ts
  src/common/ipc/broadcast-message.injectable.ts
  src/common/ipc/ipc.ts
  src/common/protocol-handler/router.ts
  src/extensions/__tests__/extension-loader.test.ts
  src/extensions/extension-discovery/extension-discovery.injectable.ts
  src/extensions/extension-discovery/extension-discovery.test.ts
  src/extensions/extension-discovery/extension-discovery.ts
  src/extensions/extension-loader/extension-loader.ts
  src/main/__test__/cluster.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/create-cluster/create-cluster.injectable.ts
  src/main/getDiForUnitTesting.ts
  src/main/helm/__mocks__/helm-chart-manager.ts
  src/main/helm/__tests__/helm-service.test.ts
  src/main/helm/helm-chart-manager-cache.injectable.ts
  src/main/helm/helm-chart-manager.injectable.ts
  src/main/helm/helm-chart-manager.ts
  src/main/helm/helm-service/get-helm-chart-values.injectable.ts
  src/main/helm/helm-service/get-helm-chart.injectable.ts
  src/main/helm/helm-service/list-helm-charts.injectable.ts
  src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts
  src/main/kube-auth-proxy/kube-auth-proxy.ts
  src/main/kube-auth-proxy/wait-until-port-is-used/wait-until-port-is-used.global-override-for-injectable.ts
  src/main/kube-auth-proxy/wait-until-port-is-used/wait-until-port-is-used.injectable.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/main/protocol-handler/lens-protocol-router-main/lens-protocol-router-main.injectable.ts
  src/main/protocol-handler/lens-protocol-router-main/lens-protocol-router-main.ts
  src/main/start-main-application/start-main-application.injectable.ts
  src/main/utils/channel/ipc-main/ipc-main.global-override-for-injectable.ts
  src/renderer/api/catalog/entity/registry.injectable.ts
  src/renderer/api/catalog/entity/registry.ts
  src/renderer/components/+catalog/catalog.test.tsx
  src/renderer/components/+config-secrets/__tests__/secret-details.test.tsx
  src/renderer/components/+network-policies/__tests__/network-policy-details.test.tsx
  src/renderer/components/cluster-settings/components/__tests__/cluster-local-terminal-settings.test.tsx
  src/renderer/components/cluster-settings/components/cluster-local-terminal-settings.tsx
  src/renderer/components/kube-object-menu/__snapshots__/kube-object-menu.test.tsx.snap
  src/renderer/components/kube-object-menu/kube-object-menu.test.tsx
  src/renderer/create-cluster/create-cluster.injectable.ts
  src/renderer/getDiForUnitTesting.tsx
  src/renderer/ipc/index.ts
  src/renderer/protocol-handler/lens-protocol-router-renderer/lens-protocol-router-renderer.injectable.ts
  src/renderer/protocol-handler/lens-protocol-router-renderer/lens-protocol-router-renderer.tsx
  src/renderer/utils/channel/ipc-renderer.global-override-for-injectable.ts
Labels: chore

#6078 Switch ubuntu CI to ubuntu-20.04
  .github/workflows/test.yml
Labels: area/ci

#6085 Fix <Select/> text overflow below baseline
  src/renderer/components/+namespaces/namespace-select-filter.scss
  src/renderer/components/cluster-settings/components/cluster-local-terminal-settings.tsx
  src/renderer/components/select/select.scss
Labels: bug, area/ui

#6104 Prevent massed remounting of dock tabs when dock height changes
  package.json
  src/renderer/components/dock/create-resource/view.tsx
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/edit-resource/view.tsx
  src/renderer/components/dock/install-chart/view.tsx
  yarn.lock
Labels: bug

#6092 Fix node conditions column text-align
  src/renderer/components/+nodes/nodes.scss
Labels: bug, area/ui

#6076 Fix light or dark flash while connecting to cluster
  src/renderer/components/app.scss
Labels: bug, area/ui

#6060 Replace deprecated <FormSwitcher/> in metrics-cluster-feature extension
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
  src/renderer/components/switch/form-switcher.tsx
  src/renderer/components/switch/switcher.tsx
Labels: area/ui, chore

#6080 Disable fail-fast on the testing CI jobs
  .github/workflows/test.yml
Labels: area/ci

#6116 Release/v6.0.2 alpha.0
  .github/workflows/test.yml
  Makefile
  package.json
  scripts/.gitignore
  scripts/.swcrc
  scripts/create-release-pr.ts
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/utils/abort-controller.ts
  src/common/utils/delay.ts
  src/main/cluster-detectors/distribution-detector.ts
  src/main/helm/helm-release-manager.ts
  src/renderer/components/+namespaces/namespace-select-filter.scss
  src/renderer/components/+nodes/nodes.scss
  src/renderer/components/+workloads-replicasets/scale-dialog/dialog.tsx
  src/renderer/components/app.scss
  src/renderer/components/badge/badge.module.scss
  src/renderer/components/badge/badge.tsx
  src/renderer/components/cluster-settings/components/cluster-local-terminal-settings.tsx
  src/renderer/components/dock/create-resource/view.tsx
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/edit-resource/view.tsx
  src/renderer/components/dock/install-chart/view.tsx
  src/renderer/components/select/select.scss
  src/renderer/components/tabs/tabs.scss
  src/renderer/kube-watch-api/kube-watch-api.ts
  yarn.lock
Labels: skip-changelog

#6120 Cherry-pick improvements to creation of release PRs script
  package.json
  scripts/.gitignore
  scripts/.swcrc
  scripts/create-release-pr.ts
  yarn.lock
Labels: chore, skip-changelog

#6121 Remove old create-release-script
  scripts/create-release-pr.mjs
Labels: skip-changelog

#6130 Revert eslint-plugin-react to 7.30.1 to fix linting
  package.json
  yarn.lock
Labels: area/ci

#6132 Fix issues when using newer @types/semver
  src/common/utils/sort-compare.ts
  src/extensions/extension-discovery/is-compatible-extension/is-compatible-extension.ts
  src/main/kubectl/kubectl.ts
  src/renderer/components/+extensions/attempt-install-by-info.injectable.tsx
  src/renderer/components/+helm-charts/helm-chart.store.ts
Labels: chore

#5727 Fix doughnut graphs on workload overview sometimes not showing
  src/common/cluster-store/allowed-resources-injection-token.ts
  src/extensions/renderer-api/theming.ts
  src/features/cluster/__snapshots__/order-of-sidebar-items.test.tsx.snap
  src/features/cluster/__snapshots__/sidebar-and-tab-navigation-for-core.test.tsx.snap
  src/features/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  src/features/cluster/__snapshots__/visibility-of-sidebar-items.test.tsx.snap
  src/features/cluster/__snapshots__/workload-overview.test.tsx.snap
  src/features/cluster/extension-api/__snapshots__/disable-cluster-pages-when-cluster-is-not-relevant.test.tsx.snap
  src/features/cluster/extension-api/__snapshots__/disable-sidebar-items-when-cluster-is-not-relevant.test.tsx.snap
  src/features/cluster/namespaces/__snapshots__/edit-namespace-from-previously-opened-tab.test.tsx.snap
  src/features/cluster/workload-overview.test.tsx
  src/features/cluster/workloads/overview/extension-api/__snapshots__/disable-workloads-overview-details-when-cluster-is-not-relevant.test.tsx.snap
  src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-previously-opened-tab.test.ts.snap
  src/renderer/components/+cluster/cluster-issues.tsx
  src/renderer/components/+cluster/cluster-pie-charts.tsx
  src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx
  src/renderer/components/+nodes/node-charts.tsx
  src/renderer/components/+storage-volume-claims/volume-claim-disk-chart.tsx
  src/renderer/components/+workloads-overview/overview-statuses.tsx
  src/renderer/components/+workloads-overview/overview-workload-status.tsx
  src/renderer/components/+workloads-overview/overview.tsx
  src/renderer/components/+workloads-overview/workloads/workload-injection-token.ts
  src/renderer/components/+workloads-pods/container-charts.tsx
  src/renderer/components/chart/bar-chart.tsx
  src/renderer/components/chart/chart.tsx
  src/renderer/components/chart/pie-chart.tsx
  src/renderer/components/dock/terminal/view.tsx
  src/renderer/components/item-object-list/content.tsx
  src/renderer/components/monaco-editor/monaco-editor.tsx
  src/renderer/components/select/select.tsx
  src/renderer/components/test-utils/get-application-builder.tsx
  src/renderer/frames/cluster-frame/__snapshots__/cluster-frame.test.tsx.snap
  src/renderer/themes/active.injectable.ts
  src/renderer/themes/lens-dark.ts
  src/renderer/themes/lens-light.ts
  src/renderer/themes/store.ts
Labels: bug

#5914 Fix IPv6 missing brackets in httpProxy.ServerOptions
  src/main/context-handler/context-handler.ts
Labels: bug

#6040 Add data-warning prop on button for better snapshot testing
  src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/features/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  src/features/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  src/renderer/components/button/button.tsx
  src/renderer/components/kube-object-menu/__snapshots__/kube-object-menu.test.tsx.snap
Labels: chore

#5970 Add option to download all logs from the container
  integration/__tests__/cluster-pages.tests.ts
  src/behaviours/pod-logs/__snapshots__/download-logs.test.tsx.snap
  src/behaviours/pod-logs/download-logs.test.tsx
  src/renderer/components/dock/logs/__test__/log-resource-selector.test.tsx
  src/renderer/components/dock/logs/__test__/log-search.test.tsx
  src/renderer/components/dock/logs/controls.module.scss
  src/renderer/components/dock/logs/controls.scss
  src/renderer/components/dock/logs/controls.tsx
  src/renderer/components/dock/logs/create-logs-tab.injectable.ts
  src/renderer/components/dock/logs/download-all-logs.injectable.ts
  src/renderer/components/dock/logs/download-logs-dropdown.module.scss
  src/renderer/components/dock/logs/download-logs-dropdown.tsx
  src/renderer/components/dock/logs/download-logs.injectable.ts
  src/renderer/components/dock/logs/get-random-id-for-pod-logs-tab.injectable.ts
  src/renderer/components/dock/logs/logs-view-model.injectable.ts
  src/renderer/components/dock/logs/logs-view-model.ts
  src/renderer/components/dropdown/dropdown.tsx
Labels: enhancement, area/ui, area/logs

#6139 Update metric queries used for Helm installed Prometheus
  src/main/prometheus/helm.ts
Labels: enhancement, area/metrics

#6140 Update failing tests after merge
  src/behaviours/pod-logs/__snapshots__/download-logs.test.tsx.snap
  src/behaviours/pod-logs/download-logs.test.tsx
  src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-new-tab.test.ts.snap
Labels: chore

#6142 release v6.0.2-alpha.1
  package.json
  src/behaviours/tray/clicking-tray-menu-item-originating-from-extension.test.ts
  src/behaviours/tray/extension-adding-tray-items.test.tsx
  src/main/context-handler/context-handler.ts
  src/main/tray/tray-menu-item/tray-menu-item-registrator.injectable.ts
  src/main/tray/tray-menu-registration.ts
Labels: skip-changelog

#6117 Remove release building pipelines
  .azure-pipelines-k8s-matrix.yml
  .azure-pipelines.yml
Labels: area/ci

#6150 Fix Promethes operator metrics provider detection
  src/main/prometheus/operator.ts
Labels: bug, area/metrics

#6128 Remove requests/limits text data for workload metrics
  src/renderer/components/resource-metrics/resource-metrics-text.tsx
Labels: bug, area/ui, area/metrics
