Repository lensapp/lens, pull requests merged in 2022-04, with the labels that each got.

#5164 Revert breaking change by making id for select optional
  src/renderer/components/select/select.tsx
Labels: bug

#5166 Fix LensRendererExtension.navigate() when extension is adding routes …
  src/extensions/extension-loader/extension-loader.ts
Labels: bug

#5155 Bump all @sentry related packages
  package.json
  src/common/sentry.ts
  src/main/index.ts
  src/renderer/bootstrap.tsx
  yarn.lock
Labels: dependencies

#5194 Release/v5.4.5
  package.json
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/k8s-api/kube-watch-event.ts
  src/renderer/components/+catalog/internal-category-columns.tsx
  src/renderer/components/avatar/avatar.tsx
  src/renderer/components/cluster-manager/cluster-status.tsx
  src/renderer/components/dock/dock.scss
  src/renderer/components/dock/edit-resource/view.tsx
  src/renderer/components/hotbar/hotbar-icon.module.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/layout/sidebar-cluster.tsx
Labels: skip-changelog

#5182 Fix broken hotbar switcher
  src/renderer/components/hotbar/hotbar-selector.tsx
Labels: bug, area/ui

#5156 Add optional badge to Catalog Category label
  src/common/__tests__/catalog-entity.test.tsx
  src/common/catalog/catalog-entity.ts
  src/renderer/components/+catalog/__tests__/catalog-category-label.test.tsx
  src/renderer/components/+catalog/catalog-category-label.tsx
  src/renderer/components/+catalog/catalog-menu.tsx
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
  src/renderer/themes/theme-vars.css
Labels: enhancement, area/extension, area/catalog

#5170 Add B to bytesToUnits to make clear that they are bytes
  src/common/utils/__tests__/convert-memory.test.ts
  src/common/utils/convertMemory.ts
  src/common/utils/iter.ts
  src/renderer/components/+cluster/cluster-metrics.tsx
  src/renderer/components/+nodes/route.tsx
  src/renderer/components/+workloads-pods/pod-details-list.tsx
  src/renderer/components/chart/bar-chart.tsx
Labels: bug, area/ui

#5204 Add identity-obj-proxy dependency
  __mocks__/styleMock.ts
  package.json
  yarn.lock
Labels: chore

#5108 Fix slackLink in catalog becoming out of date
  src/common/vars.ts
  src/common/weblink-store.ts
  src/migrations/helpers.ts
  src/migrations/weblinks-store/5.1.4.ts
  src/migrations/weblinks-store/5.4.5-beta.1.ts
  src/migrations/weblinks-store/currentVersion.ts
  src/migrations/weblinks-store/index.ts
Labels: bug

#5223 Fix PieChart tooltips
  src/renderer/components/+cluster/cluster-pie-charts.tsx
  src/renderer/components/+workloads-overview/overview-workload-status.scss
  src/renderer/components/+workloads-overview/overview-workload-status.tsx
  src/renderer/components/chart/pie-chart.tsx
Labels: bug, area/ui

#5229 Export ReactDOM globally, and ensure in-tree extension to use the same instance
  extensions/kube-object-event-status/webpack.config.js
  extensions/metrics-cluster-feature/webpack.config.js
  extensions/node-menu/webpack.config.js
  extensions/pod-menu/webpack.config.js
  src/renderer/bootstrap.tsx
Labels: bug, area/extension

#5201 Fix returning to specific catalog tab and removing a hotbar item
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/hotbar/hotbar-menu.tsx
Labels: bug

#5085 Behavioural unit tests for navigation and reference
  src/behaviours/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  src/behaviours/__snapshots__/navigate-to-extension-page.test.tsx.snap
  src/behaviours/__snapshots__/navigating-between-routes.test.tsx.snap
  src/behaviours/add-cluster/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/add-cluster/navigation-using-application-menu.test.ts
  src/behaviours/cluster/__snapshots__/order-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-core.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  src/behaviours/cluster/__snapshots__/visibility-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/order-of-sidebar-items.test.tsx
  src/behaviours/cluster/sidebar-and-tab-navigation-for-core.test.tsx
  src/behaviours/cluster/sidebar-and-tab-navigation-for-extensions.test.tsx
  src/behaviours/cluster/visibility-of-sidebar-items.test.tsx
  src/behaviours/extension-special-characters-in-page-registrations.test.tsx
  src/behaviours/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/extensions/navigation-using-application-menu.test.ts
  src/behaviours/navigate-to-extension-page.test.tsx
  src/behaviours/navigating-between-routes.test.tsx
  src/behaviours/preferences/__snapshots__/closing-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-application-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-telemetry-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/preferences/closing-preferences.test.tsx
  src/behaviours/preferences/navigation-to-application-preferences.test.ts
  src/behaviours/preferences/navigation-to-editor-preferences.test.ts
  src/behaviours/preferences/navigation-to-extension-specific-preferences.test.tsx
  src/behaviours/preferences/navigation-to-kubernetes-preferences.test.ts
  src/behaviours/preferences/navigation-to-proxy-preferences.test.ts
  src/behaviours/preferences/navigation-to-telemetry-preferences.test.tsx
  src/behaviours/preferences/navigation-to-terminal-preferences.test.ts
  src/behaviours/preferences/navigation-using-application-menu.test.ts
  src/behaviours/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/welcome/navigation-using-application-menu.test.ts
Labels: area/tests

#5235 Fix snapshots/code-style after merging stuff to master
  src/behaviours/add-cluster/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/add-cluster/navigation-using-application-menu.test.ts
  src/behaviours/cluster/__snapshots__/order-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-core.test.tsx.snap
  src/behaviours/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  src/behaviours/cluster/__snapshots__/visibility-of-sidebar-items.test.tsx.snap
  src/behaviours/cluster/order-of-sidebar-items.test.tsx
  src/behaviours/cluster/sidebar-and-tab-navigation-for-core.test.tsx
  src/behaviours/cluster/sidebar-and-tab-navigation-for-extensions.test.tsx
  src/behaviours/cluster/visibility-of-sidebar-items.test.tsx
  src/behaviours/extension-special-characters-in-page-registrations.test.tsx
  src/behaviours/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/extensions/navigation-using-application-menu.test.ts
  src/behaviours/navigate-to-extension-page.test.tsx
  src/behaviours/navigating-between-routes.test.tsx
  src/behaviours/preferences/__snapshots__/closing-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-application-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-telemetry-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/preferences/closing-preferences.test.tsx
  src/behaviours/preferences/navigation-to-application-preferences.test.ts
  src/behaviours/preferences/navigation-to-editor-preferences.test.ts
  src/behaviours/preferences/navigation-to-extension-specific-preferences.test.tsx
  src/behaviours/preferences/navigation-to-kubernetes-preferences.test.ts
  src/behaviours/preferences/navigation-to-proxy-preferences.test.ts
  src/behaviours/preferences/navigation-to-telemetry-preferences.test.tsx
  src/behaviours/preferences/navigation-to-terminal-preferences.test.ts
  src/behaviours/preferences/navigation-using-application-menu.test.ts
  src/behaviours/welcome/navigation-using-application-menu.test.ts
Labels: area/tests

#5230 Add optional destination property to app event
  src/common/app-event-bus/event-bus.ts
Labels: enhancement, area/extension

#4992 Remove webpack.*.ts importing values from src/
  package.json
  src/common/utils/defineGlobal.ts
  src/common/utils/index.ts
  src/common/vars.ts
  src/common/vars/context-dir.injectable.ts
  src/extensions/extension-discovery/extension-discovery.ts
  src/main/index.ts
  src/main/router/router.ts
  src/main/routes/static-file-route.injectable.ts
  src/main/tray/tray.ts
  src/renderer/components/dock/create-resource/lens-templates.injectable.ts
  tsconfig.json
  types/mocks.d.ts
  webpack.dev-server.ts
  webpack/dev-server.ts
  webpack/extensions.ts
  webpack/get-typescript-loader.ts
  webpack/main.ts
  webpack/renderer.ts
  webpack/tsconfig.json
  webpack/vars.ts
Labels: chore

#5249 Fix: do not use paddings for empty top bar items
  src/renderer/components/layout/top-bar/top-bar.module.scss
Labels: bug, area/ui, area/extension

#5247 Upgrade electron-builder to 23.0.3
  package.json
  yarn.lock
Labels: chore

#5265 Release/v5.4.6
  package.json
  src/common/utils/__tests__/convert-memory.test.ts
  src/common/utils/convertMemory.ts
  src/common/utils/iter.ts
  src/common/vars.ts
  src/common/weblink-store.ts
  src/migrations/helpers.ts
  src/migrations/weblinks-store/5.1.4.ts
  src/migrations/weblinks-store/5.4.5-beta.1.ts
  src/migrations/weblinks-store/currentVersion.ts
  src/migrations/weblinks-store/index.ts
  src/renderer/components/+cluster/cluster-metrics.tsx
  src/renderer/components/+cluster/cluster-pie-charts.tsx
  src/renderer/components/+nodes/route.tsx
  src/renderer/components/+workloads-overview/overview-workload-status.scss
  src/renderer/components/+workloads-overview/overview-workload-status.tsx
  src/renderer/components/+workloads-pods/pod-details-list.tsx
  src/renderer/components/animate/animate.tsx
  src/renderer/components/chart/bar-chart.tsx
  src/renderer/components/chart/pie-chart.tsx
  src/renderer/components/kube-object-menu/__snapshots__/kube-object-menu.test.tsx.snap
  src/renderer/components/layout/top-bar/top-bar.module.scss
  src/renderer/components/menu/menu.tsx
  src/renderer/components/tooltip/tooltip.tsx
Labels: skip-changelog

#5264 Expose Lens Monaco Editor component to extensions-api
  integration/__tests__/cluster-pages.tests.ts
  src/extensions/renderer-api/components.ts
  src/renderer/components/monaco-editor/monaco-editor.tsx
Labels: enhancement, area/extension

#5256 Fix crash in CRD display
  package.json
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/utils/__tests__/jsonPath.test.tsx
  src/renderer/utils/jsonPath.ts
  yarn.lock
Labels: bug

#5282 Fix make dev on master
  .github/workflows/test.yml
  Makefile
  package.json
  yarn.lock
Labels: dependencies

#5277 Upgrade ReactSelect to latest version
  package.json
  src/behaviours/preferences/__snapshots__/closing-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-application-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-telemetry-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/renderer/components/+namespaces/namespace-select-filter.tsx
  src/renderer/components/+preferences/kubectl-binaries.tsx
  src/renderer/components/select/select.tsx
  yarn.lock
Labels: bug, area/extension

#5240 Fix misleading no metrics message
  integration/__tests__/cluster-pages.tests.ts
  src/renderer/components/+cluster/cluster-no-metrics.module.scss
  src/renderer/components/+cluster/cluster-no-metrics.tsx
  src/renderer/components/+cluster/cluster-pie-charts.module.scss
  src/renderer/components/+cluster/cluster-pie-charts.tsx
Labels: bug, area/ui

#5273 adding https_proxy to execHelm env
  src/main/helm/exec.ts
Labels: bug
