Repository lensapp/lens, pull requests merged in 2022-11, with the labels that each got.

#6385 Expose a way to add cluster frame components in Extension API
  src/extensions/lens-renderer-extension.ts
  src/features/cluster/__snapshots__/legacy-extension-adding-cluster-frame-components.test.tsx.snap
  src/features/cluster/legacy-extension-adding-cluster-frame-components.test.tsx
  src/renderer/frames/cluster-frame/cluster-frame-component-registrator.injectable.ts
  src/renderer/frames/cluster-frame/cluster-frame.tsx
Labels: enhancement, area/extension

#6516 Fix compute unix shell environment timeout
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
Labels: bug, blocker

#6502 Fix syncing shell environment when using fish
  package.json
  src/main/start-main-application/runnables/setup-shell.injectable.ts
  src/main/utils/shell-env/compute-shell-environment.injectable.ts
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
  src/main/utils/shell-env/compute-unix-shell-environment.test.ts
  src/main/utils/shell-env/env.injectable.ts
  src/main/utils/shell-env/execPath.injectable.ts
  yarn.lock
Labels: bug, blocker

#6509 Replace deprecated github actions ::set-output
  .github/workflows/add-to-project-board.yaml
  .github/workflows/bump-master-version.yaml
  .github/workflows/check-docs.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/electronegativity.yml
  .github/workflows/license-header.yml
  .github/workflows/linter.yml
  .github/workflows/main.yml
  .github/workflows/mkdocs-delete-version.yml
  .github/workflows/mkdocs-manual.yml
  .github/workflows/mkdocs-set-default-version.yml
  .github/workflows/publish-master-npm.yml
  .github/workflows/publish-release-npm.yml
  .github/workflows/release.yml
  .github/workflows/require-milestone.yml
  .github/workflows/test.yml
Labels: area/ci

#6517 Release 6.1.15
  .github/workflows/add-to-project-board.yaml
  .github/workflows/check-docs.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/electronegativity.yml
  .github/workflows/license-header.yml
  .github/workflows/linter.yml
  .github/workflows/main.yml
  .github/workflows/mkdocs-delete-version.yml
  .github/workflows/mkdocs-manual.yml
  .github/workflows/mkdocs-set-default-version.yml
  .github/workflows/publish-master-npm.yml
  .github/workflows/publish-release-npm.yml
  .github/workflows/release.yml
  .github/workflows/require-milestone.yml
  .github/workflows/test.yml
  package.json
  src/common/k8s-api/kube-object.store.ts
  src/main/start-main-application/runnables/setup-shell.injectable.ts
  src/main/utils/shell-env/compute-shell-environment.injectable.ts
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
  src/main/utils/shell-env/compute-unix-shell-environment.test.ts
  src/main/utils/shell-env/env.injectable.ts
  src/main/utils/shell-env/execPath.injectable.ts
  yarn.lock
Labels: skip-changelog, release

#6526 Fix for Menu component memory leak
  src/renderer/components/menu/menu.tsx
Labels: bug, area/ui

#6529 Release 6.1.16
  package.json
  src/renderer/components/menu/menu.tsx
Labels: skip-changelog, release

#6528 Refactor runnables
  src/common/runnable/run-many-for.test.ts
  src/common/runnable/run-many-for.ts
  src/common/runnable/run-many-sync-for.test.ts
  src/common/runnable/run-many-sync-for.ts
  src/common/runnable/throw-with-incorrect-hierarchy-for.ts
  src/common/utils/get-startable-stoppable.test.ts
  src/common/utils/get-startable-stoppable.ts
  src/features/application-menu/main/application-menu-reactivity.injectable.ts
  src/features/application-menu/main/stop-application-menu.injectable.ts
  src/features/application-update/child-features/periodical-checking-of-updates/main/periodical-check-for-updates.injectable.ts
  src/features/application-update/child-features/periodical-checking-of-updates/main/stop-checking-for-updates.injectable.ts
  src/features/application-update/main/watch-if-update-should-happen-on-quit/stop-watching-if-update-should-happen-on-quit.injectable.ts
  src/main/app-paths/setup-app-paths.injectable.ts
  src/main/catalog-sync-to-renderer/catalog-sync-to-renderer.injectable.ts
  src/main/catalog-sync-to-renderer/stop-catalog-sync.injectable.ts
  src/main/electron-app/features/sync-theme-from-operating-system.injectable.ts
  src/main/electron-app/runnables/clean-up-deep-linking.injectable.ts
  src/main/electron-app/runnables/dock-visibility/hide-dock-for-last-closed-window.injectable.ts
  src/main/electron-app/runnables/enforce-single-application-instance.injectable.ts
  src/main/electron-app/runnables/setup-application-name.injectable.ts
  src/main/electron-app/runnables/setup-runnables-after-window-is-opened.injectable.ts
  src/main/electron-app/runnables/setup-runnables-before-closing-of-application.injectable.ts
  src/main/start-main-application/runnable-tokens/before-electron-is-ready-injection-token.ts
  src/main/start-main-application/runnable-tokens/before-quit-of-back-end-injection-token.ts
  src/main/start-main-application/runnable-tokens/before-quit-of-front-end-injection-token.ts
  src/main/start-main-application/runnables/clean-up-shell-sessions.injectable.ts
  src/main/start-main-application/runnables/emit-close-to-event-bus.injectable.ts
  src/main/start-main-application/runnables/flag-renderer/flag-renderer-as-not-loaded.injectable.ts
  src/main/start-main-application/runnables/kube-config-sync/stop-kube-config-sync.injectable.ts
  src/main/start-main-application/runnables/sentry/setup.injectable.ts
  src/main/start-main-application/runnables/setup-hardware-acceleration.injectable.ts
  src/main/start-main-application/runnables/setup-immer.injectable.ts
  src/main/start-main-application/runnables/setup-mobx.injectable.ts
  src/main/start-main-application/runnables/setup-proxy-env.injectable.ts
  src/main/start-main-application/runnables/stop-cluster-manager.injectable.ts
  src/main/theme/broadcast-theme-change/stop-broadcasting-theme-change.injectable.ts
  src/main/theme/sync-theme-from-os/stop-syncing-theme-from-operating-system.injectable.ts
  src/main/tray/electron-tray/stop-tray.injectable.ts
  src/main/tray/menu-icon/stop-reactivity.injectable.ts
  src/main/tray/reactive-tray-menu-items/reactive-tray-menu-items.injectable.ts
  src/main/tray/reactive-tray-menu-items/stop-reactive-tray-menu-items.injectable.ts
  src/main/utils/channel/channel-listeners/start-listening-on-channels.injectable.ts
Labels: bug

#6531 Improve unix shell env sync error logging
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
Labels: chore

#6532 Fix computeUnixShellEnv tests
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
  src/main/utils/shell-env/compute-unix-shell-environment.test.ts
Labels: chore

#6530 Fix jsonPath functions
  src/renderer/components/+custom-resources/__tests__/__snapshots__/custom-resource-details.test.tsx.snap
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/utils/__tests__/jsonPath.test.ts
  src/renderer/utils/jsonPath.ts
Labels: bug

#6537 Fix installing extension dependencies
  src/extensions/extension-installer/extension-installer.ts
Labels: bug, area/extension, blocker

#6538 Release 6.1.17
  package.json
  src/extensions/extension-installer/extension-installer.ts
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
  src/main/utils/shell-env/compute-unix-shell-environment.test.ts
  src/renderer/components/+custom-resources/__tests__/__snapshots__/custom-resource-details.test.tsx.snap
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/utils/__tests__/jsonPath.test.ts
  src/renderer/utils/jsonPath.ts
Labels: skip-changelog, release

#6501 Preserve preference URLs
  src/features/preferences/__snapshots__/urls-of-legacy-extensions.test.tsx.snap
  src/features/preferences/common/preferences-route-for-legacy-extensions.injectable.ts
  src/features/preferences/renderer/preference-items/current-preference-tab-id.injectable.ts
  src/features/preferences/renderer/preference-items/preferences-composite.injectable.ts
  src/features/preferences/renderer/preferences-route-component-for-legacy-extensions.injectable.ts
  src/features/preferences/urls-of-legacy-extensions.test.tsx
Labels: bug

#6543 Fix non-bundled extensions not working
  src/extensions/extension-installer/extension-installer.ts
Labels: bug, area/extension, blocker

#6544 Release 6.1.18
  package.json
  src/extensions/extension-installer/extension-installer.ts
Labels: skip-changelog, release

#6551 Detach shell process in computeUnixShellEnvironmentInjectable
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
Labels: bug, blocker

#6542 Fix cron jobs not being viewable on newer kube
  src/common/k8s-api/endpoints/cron-job.api.injectable.ts
  src/common/k8s-api/endpoints/cron-job.api.ts
  src/common/k8s-api/kube-object.store.ts
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-cronjobs/legacy-store.ts
Labels: bug, area/kubernetes-next

#6552 Release 6.1.19
  package.json
  src/common/k8s-api/endpoints/cron-job.api.injectable.ts
  src/common/k8s-api/endpoints/cron-job.api.ts
  src/common/k8s-api/kube-object.store.ts
  src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts
  src/renderer/components/+workloads-cronjobs/cronjobs.tsx
  src/renderer/components/+workloads-cronjobs/legacy-store.ts
  yarn.lock
Labels: skip-changelog, release

#6046 Upgrade to latest node-fetch
  .eslintrc.js
  .gitignore
  Makefile
  build/download_binaries.ts
  package.json
  src/common/fetch/download-json.injectable.ts
  src/common/fetch/fetch.global-override-for-injectable.ts
  src/common/fetch/fetch.injectable.ts
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/utils/abort-controller.ts
  src/common/vars/lens-resources-dir.injectable.ts
  src/main/__test__/static-file-route.test.ts
  src/main/routes/files/development.injectable.ts
  src/main/routes/files/production.injectable.ts
  src/main/routes/files/static-file-route.injectable.ts
  src/main/routes/static-file-route.injectable.ts
  webpack/node-fetch.ts
  yarn.lock
Labels: dependencies

#6573 Fix auto finding logic of preferred versions
  src/common/k8s-api/__tests__/kube-api-version-detection.test.ts
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/endpoints/cron-job.api.injectable.ts
  src/common/k8s-api/endpoints/job.api.injectable.ts
  src/common/k8s-api/kube-api-parse.ts
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
Labels: bug

#6581 Fix CronJob trigger menu missing
  extensions/kube-object-event-status/package.json
  extensions/kube-object-event-status/renderer.tsx
  src/renderer/components/kube-object-menu/kube-object-menu-items/cron-job-menu.injectable.ts
Labels: bug

#6577 Do not mark terminating namespaces as disabled
  src/renderer/components/+namespaces/route.tsx
Labels: bug

#6576 Add winston formatting support for error causes
  package.json
  src/common/app-paths/directory-for-logs.injectable.ts
  src/common/ipc/__tests__/type-enforced-ipc.test.ts
  src/common/ipc/index.ts
  src/common/ipc/type-enforced-ipc.ts
  src/common/logger.injectable.ts
  src/common/logger.ts
  src/common/logger/transports.ts
  src/main/app-paths/setup-app-paths.injectable.ts
  src/main/context-handler/context-handler.ts
  src/main/index.ts
  src/main/logger/console-format.ts
  src/main/logger/console-transport.injectable.ts
  src/main/logger/file-transport.injectable.ts
  src/main/logger/level.global-override-for-injectable.ts
  src/main/logger/level.injectable.ts
  src/main/routes/metrics/add-metrics-route.injectable.ts
  src/main/start-main-application/runnable-tokens/phases.ts
  src/main/start-main-application/runnables/show-initial-window.injectable.ts
  src/main/start-main-application/runnables/show-loading.injectable.ts
  src/main/start-main-application/start-main-application.injectable.ts
  src/renderer/components/test-utils/get-application-builder.tsx
  src/renderer/ipc/register-listeners.tsx
  src/renderer/kube-watch-api/kube-watch-api.ts
  src/renderer/logger/browser-transport.injectable.ts
  src/renderer/protocol-handler/lens-protocol-router-renderer/lens-protocol-router-renderer.tsx
  webpack/dev-server.ts
  yarn.lock
Labels: chore

#6597 Fix not being able to install Lens metrics
  src/main/resource-applier/resource-applier.ts
Labels: bug, area/metrics, blocker

#6589 Fix not using the users configured shell for sync
  src/common/os/home-directory-path.injectable.ts
  src/common/user-store/resolved-shell.injectable.ts
  src/common/user-store/shell-setting.injectable.ts
  src/common/user-store/user-info.global-override-for-injectable.ts
  src/common/user-store/user-info.injectable.ts
  src/common/user-store/user-store.ts
  src/main/shell-session/local-shell-session/open.injectable.ts
  src/main/shell-session/node-shell-session/open.injectable.ts
  src/main/shell-session/shell-session.ts
  src/main/start-main-application/runnables/setup-shell.injectable.ts
Labels: bug

#6598 Allow computed tray menu for extensions
  src/extensions/extension-loader/extension-registrator-injection-token.ts
  src/extensions/extension-loader/extension/extension.injectable.ts
  src/extensions/lens-main-extension.ts
  src/features/tray/extension-adding-tray-items.test.tsx
  src/main/tray/reactive-tray-menu-items/start-reactive-tray-menu-items.injectable.ts
  src/main/tray/tray-menu-item/tray-menu-item-registrator.injectable.ts
Labels: enhancement, area/extension

#6602 Release 6.2.0
  package.json
Labels: skip-changelog, release

#6580 Remove spdy support
  package.json
  src/main/lens-proxy/lens-proxy.ts
  yarn.lock
Labels: dependencies

#6612 Update Button, keep left
  src/features/application-update/__snapshots__/installing-update.test.ts.snap
  src/features/application-update/child-features/application-update-using-top-bar/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  src/features/application-update/child-features/application-update-using-top-bar/renderer/update-application-top-bar-item/update-application-top-bar-item.injectable.ts
  src/features/application-update/child-features/application-update-using-tray/__snapshots__/installing-update-using-tray.test.ts.snap
  src/features/application-update/child-features/force-user-to-update-when-too-long-time-since-update-was-downloaded/__snapshots__/force-user-to-update-when-too-long-time-since-update-was-downloaded.test.ts.snap
Labels: bug

#6590 Make ClusterFrameManager fully injectable
  src/common/cluster/visibility-channel.ts
  src/common/ipc/cluster.ts
  src/main/cluster/manager.injectable.ts
  src/main/cluster/manager.ts
  src/main/cluster/visibility-handler.injectable.ts
  src/main/cluster/visible-cluster.injectable.ts
  src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.injectable.ts
  src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.ts
  src/renderer/components/cluster-manager/cluster-frame-handler.injectable.ts
  src/renderer/components/cluster-manager/cluster-frame-handler.ts
  src/renderer/components/cluster-manager/emit-cluster-visibility.injectable.ts
Labels: chore

#6321 Remove mac-ca usage since it was only in tests (#6043)
  integration/__tests__/app-preferences.tests.ts
  integration/__tests__/cluster-pages.tests.ts
  integration/helpers/utils.ts
  package.json
  src/common/__tests__/system-ca.test.ts
  src/common/certificate-authorities/inject-system-cas.injectable.ts
  src/common/certificate-authorities/request-system-cas-token.ts
  src/common/certificate-authorities/request-system-cas.injectable.darwin.ts
  src/common/certificate-authorities/request-system-cas.injectable.linux.ts
  src/common/certificate-authorities/request-system-cas.injectable.testing-env.ts
  src/common/certificate-authorities/request-system-cas.injectable.win32.ts
  src/common/fs/exec-file.injectable.ts
  src/common/system-ca.ts
  src/jest.setup.ts
  src/main/getDi.ts
  src/main/start-main-application/runnables/setup-system-ca.injectable.ts
  src/renderer/frames/root-frame/setup-system-ca.injectable.ts
  src/renderer/getDi.tsx
  src/test-utils/skippers.ts
  types/from-webpack.d.ts
  types/mocks.d.ts
  webpack/main.ts
  webpack/renderer.ts
  yarn.lock
Labels: chore, area/security

#6631 Add missing gutter between sections in cluster settings
  src/renderer/components/cluster-settings/components/cluster-local-terminal-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx
Labels: bug, area/ui

#6632 Adding spacing between Metrics Settings sections
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
Labels: bug, area/ui

#6626 Fix crash when upgrading release
  src/common/k8s-api/endpoints/helm-releases.api/request-update.injectable.ts
  src/features/helm-charts/add-custom-helm-repository-in-preferences.test.ts
  src/features/helm-charts/add-helm-repository-from-list-in-preferences.test.ts
  src/features/helm-charts/listing-active-helm-repositories-in-preferences.test.ts
  src/features/helm-charts/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts
  src/features/helm-releases/showing-details-for-helm-release.test.ts
  src/main/helm/exec-helm/exec-env.global-override-for-injectable.ts
  src/main/helm/exec-helm/exec-env.injectable.ts
  src/main/helm/exec-helm/exec-helm.injectable.ts
  src/main/helm/helm-service/update-helm-release.injectable.ts
  src/main/routes/helm/releases/update-release-route.injectable.ts
  src/renderer/components/+helm-charts/helm-charts/versions.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx
  src/renderer/components/+helm-releases/update-release/update-release.injectable.ts
  src/renderer/components/dock/upgrade-chart/upgrade-chart-model.injectable.ts
  src/renderer/components/dock/upgrade-chart/view.tsx
Labels: bug, area/helm

#6634 Fix: adjust padding after cluster settings avatar
  src/renderer/components/+entity-settings/entity-settings.module.scss
  src/renderer/components/+entity-settings/entity-settings.tsx
Labels: bug, area/ui

#6640 Fix KubeApi watch retry on timeout
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/kube-api.ts
Labels: bug, blocker

#6639 Add eslint support for package.json exports
  .eslintrc.js
  package.json
  yarn.lock
Labels: chore

#6591 Make ResourceStack fully injectable
  src/common/ipc/cluster.ts
  src/common/k8s/create-resource-stack.injectable.ts
  src/common/k8s/resource-stack.ts
  src/common/kube-helpers/channels.ts
  src/extensions/common-api/k8s-api.ts
  src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.injectable.ts
  src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.ts
  src/main/kubectl/apply-all-handler.injectable.ts
  src/main/kubectl/delete-all-handler.injectable.ts
  src/main/kubectl/kubectl-apply-all.injectable.ts
  src/main/kubectl/kubectl-delete-all.injectable.ts
  src/main/resource-applier/resource-applier.ts
  src/renderer/ipc/index.ts
  src/renderer/kubectl/apply-all.injectable.ts
  src/renderer/kubectl/delete-all.injectable.ts
Labels: chore

#6642 Release 6.2.2
  extensions/metrics-cluster-feature/src/metrics-settings.tsx
  integration/__tests__/cluster-pages.tests.ts
  package.json
  src/common/cluster-types.ts
  src/common/cluster/authorization-namespace-review.injectable.ts
  src/common/cluster/authorization-review.injectable.ts
  src/common/cluster/cluster.ts
  src/common/cluster/list-api-resources.injectable.ts
  src/common/ipc/cluster.ts
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/k8s-api/endpoints/helm-releases.api/request-update.injectable.ts
  src/common/k8s-api/kube-api.ts
  src/features/helm-charts/add-custom-helm-repository-in-preferences.test.ts
  src/features/helm-charts/add-helm-repository-from-list-in-preferences.test.ts
  src/features/helm-charts/listing-active-helm-repositories-in-preferences.test.ts
  src/features/helm-charts/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts
  src/features/helm-releases/showing-details-for-helm-release.test.ts
  src/main/__test__/cluster.test.ts
  src/main/create-cluster/create-cluster.injectable.ts
  src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.ts
  src/main/helm/exec-helm/exec-env.global-override-for-injectable.ts
  src/main/helm/exec-helm/exec-env.injectable.ts
  src/main/helm/exec-helm/exec-helm.injectable.ts
  src/main/helm/helm-service/update-helm-release.injectable.ts
  src/main/routes/helm/releases/update-release-route.injectable.ts
  src/renderer/components/+entity-settings/entity-settings.module.scss
  src/renderer/components/+entity-settings/entity-settings.tsx
  src/renderer/components/+helm-charts/helm-charts/versions.injectable.ts
  src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx
  src/renderer/components/+helm-releases/update-release/update-release.injectable.ts
  src/renderer/components/cluster-settings/components/cluster-local-terminal-settings.tsx
  src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx
  src/renderer/components/dock/upgrade-chart/upgrade-chart-model.injectable.ts
  src/renderer/components/dock/upgrade-chart/view.tsx
  src/renderer/create-cluster/create-cluster.injectable.ts
  yarn.lock
Labels: skip-changelog, release

#6628 Handle globalAgent having a single non-array CA
  src/common/certificate-authorities/inject-system-cas.injectable.ts
Labels: bug

#6644 Improve UX for shell env sync failure
  src/common/utils/channel/message-to-channel-injection-token.ts
  src/features/shell-sync/common/failure-channel.ts
  src/features/shell-sync/main/compute-shell-environment.injectable.ts
  src/features/shell-sync/main/compute-unix-shell-environment.global-override-for-injectable.ts
  src/features/shell-sync/main/compute-unix-shell-environment.injectable.ts
  src/features/shell-sync/main/compute-unix-shell-environment.test.ts
  src/features/shell-sync/main/emit-failure.injectable.ts
  src/features/shell-sync/main/env.injectable.ts
  src/features/shell-sync/main/execPath.injectable.ts
  src/features/shell-sync/main/setup-shell.injectable.ts
  src/features/shell-sync/renderer/failure-listener.injectable.ts
  src/main/getDiForUnitTesting.ts
  src/main/shell-session/local-shell-session/open.injectable.ts
  src/main/shell-session/node-shell-session/open.injectable.ts
  src/main/shell-session/shell-session.ts
Labels: enhancement

#6649 Release/v6.2.3
  integration/__tests__/cluster-pages.tests.ts
  package.json
  src/common/cluster-types.ts
  src/common/cluster/authorization-namespace-review.injectable.ts
  src/common/cluster/authorization-review.injectable.ts
  src/common/cluster/cluster.ts
  src/common/cluster/list-api-resources.injectable.ts
  src/common/ipc/cluster.ts
  src/main/__test__/cluster.test.ts
  src/main/create-cluster/create-cluster.injectable.ts
  src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.ts
  src/renderer/components/cluster-manager/cluster-frame-handler.ts
  src/renderer/create-cluster/create-cluster.injectable.ts
Labels: skip-changelog, release

#6604 Make EntitySettingRegistry fully injectable
  src/common/utils/composable-responsibilities/orderable/orderable.ts
  src/extensions/extension-loader/extension-loader.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/entity-setting-registry.ts
  src/extensions/registries/index.ts
  src/features/entity-settings/__snapshots__/showing-settings-for-correct-entity.test.tsx.snap
  src/features/entity-settings/showing-settings-for-correct-entity.test.tsx
  src/features/preferences/renderer/preference-navigation/navigate-to-preference-tab/navigate-to-preference-tab.injectable.ts
  src/features/preferences/renderer/preference-navigation/preferences-navigation-tab.tsx
  src/features/preferences/renderer/preference-navigation/preferences-navigation.tsx
  src/renderer/bootstrap.tsx
  src/renderer/components/+catalog/columns/extensions-registrator.injectable.ts
  src/renderer/components/+entity-settings/active-tabs.injectable.ts
  src/renderer/components/+entity-settings/current-entity.injectable.ts
  src/renderer/components/+entity-settings/entity-settings.tsx
  src/renderer/components/+entity-settings/extension-registrator.injectable.ts
  src/renderer/components/+entity-settings/has-settings.injectable.ts
  src/renderer/components/+entity-settings/index.ts
  src/renderer/components/+entity-settings/internal-kubernetes-cluster/general-settings.injectable.tsx
  src/renderer/components/+entity-settings/internal-kubernetes-cluster/metrics-settings.injectable.tsx
  src/renderer/components/+entity-settings/internal-kubernetes-cluster/namespace-settings.injectable.tsx
  src/renderer/components/+entity-settings/internal-kubernetes-cluster/node-shell-settings.injectable.tsx
  src/renderer/components/+entity-settings/internal-kubernetes-cluster/proxy-settings.injectable.tsx
  src/renderer/components/+entity-settings/internal-kubernetes-cluster/terminal-settings.injectable.tsx
  src/renderer/components/+entity-settings/route-component.injectable.ts
  src/renderer/components/+entity-settings/route-parameters.injectable.ts
  src/renderer/components/+entity-settings/settings.injectable.ts
  src/renderer/components/+entity-settings/token.ts
  src/renderer/components/cluster-settings/__tests__/cluster-local-terminal-settings.test.tsx
  src/renderer/components/cluster-settings/accessible-namespaces.tsx
  src/renderer/components/cluster-settings/cluster-settings.tsx
  src/renderer/components/cluster-settings/components/index.ts
  src/renderer/components/cluster-settings/icon-settings.tsx
  src/renderer/components/cluster-settings/index.ts
  src/renderer/components/cluster-settings/kubeconfig.tsx
  src/renderer/components/cluster-settings/local-terminal-settings.tsx
  src/renderer/components/cluster-settings/metrics-setting.tsx
  src/renderer/components/cluster-settings/name-setting.tsx
  src/renderer/components/cluster-settings/node-shell-setting.tsx
  src/renderer/components/cluster-settings/prometheus-setting.tsx
  src/renderer/components/cluster-settings/proxy-setting.tsx
  src/renderer/components/cluster-settings/show-metrics.tsx
  src/renderer/components/command-palette/registered-commands/get-entity-setting-commands.injectable.ts
  src/renderer/components/command-palette/registered-commands/internal-commands.injectable.tsx
  src/renderer/components/layout/tab-layout-2.tsx
  src/renderer/components/layout/tab-layout.tsx
  src/renderer/components/tabs/tabs.tsx
  src/renderer/getDiForUnitTesting.tsx
  src/renderer/initializers/entity-settings-registry.ts
  src/renderer/initializers/index.ts
  src/renderer/initializers/registries.ts
Labels: chore

#6660 Remove uses of legacy global logger from injectables
  src/main/routes/metrics/add-metrics-route.injectable.ts
  src/main/routes/port-forward/start-port-forward-route.injectable.ts
  src/main/routes/port-forward/stop-current-port-forward-route.injectable.ts
  src/renderer/components/+extensions/attempt-install/create-temp-files-and-validate.injectable.tsx
Labels: chore

#6666 Fix extensions using "application" as magic string for preference tab
  src/features/preferences/__snapshots__/navigation-to-application-preferences.test.tsx.snap
  src/features/preferences/navigation-to-application-preferences.test.tsx
  src/features/preferences/renderer/compliance-for-legacy-extension-api/registrator-for-preference-items.injectable.tsx
Labels: bug

#6674 Make preferences from extensions using tabs "application" and "telemetry" appear as last
  src/features/preferences/__snapshots__/navigation-to-application-preferences.test.tsx.snap
  src/features/preferences/navigation-to-application-preferences.test.tsx
  src/features/preferences/renderer/compliance-for-legacy-extension-api/registrator-for-preference-items.injectable.tsx
Labels: bug

#6670 Fix back navigation in entity settings
  src/renderer/components/+entity-settings/active-tabs.injectable.ts
Labels: bug

#6671 Fix not displaying any pie charts when missing only some data
  src/renderer/components/+cluster/cluster-pie-charts.tsx
Labels: bug, area/ui, area/metrics

#6676 Release 6.2.4
  package.json
  src/features/preferences/__snapshots__/navigation-to-application-preferences.test.tsx.snap
  src/features/preferences/navigation-to-application-preferences.test.tsx
  src/features/preferences/renderer/compliance-for-legacy-extension-api/registrator-for-preference-items.injectable.tsx
  yarn.lock
Labels: skip-changelog, release
