Repository lensapp/lens, pull requests merged in 2022-05, with the labels that each got.

#5306 Cancel in progress npm master publishes if multuple in flight
  .github/workflows/publish-master-npm.yml
Labels: area/ci

#5309 Fix last item not being removed on initial loadAll
  src/common/k8s-api/__tests__/kube-object.store.test.ts
  src/common/k8s-api/kube-object.store.ts
Labels: bug, blocker

#5318 Fix check for making sure dependency upgrades don't break dev mode
  .github/workflows/test.yml
Labels: dependencies

#5107 Add ability to hide KubeObjectMenu Edit and Remove buttons in extensions
  src/common/catalog/catalog-entity.ts
  src/common/utils/index.ts
  src/common/utils/readonly.ts
  src/extensions/common-api/registrations.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/renderer-api/components.ts
  src/renderer/catalog/normalize-menu-item.injectable.ts
  src/renderer/components/+catalog/catalog-entity-drawer-menu.tsx
  src/renderer/components/+catalog/catalog.tsx
  src/renderer/components/+extensions/attempt-install-by-info.injectable.tsx
  src/renderer/components/+extensions/attempt-install-by-info/attempt-install-by-info.injectable.ts
  src/renderer/components/+extensions/attempt-install-by-info/attempt-install-by-info.tsx
  src/renderer/components/+extensions/confirm-uninstall-extension.injectable.tsx
  src/renderer/components/+extensions/confirm-uninstall-extension/confirm-uninstall-extension.injectable.ts
  src/renderer/components/+extensions/confirm-uninstall-extension/confirm-uninstall-extension.tsx
  src/renderer/components/+extensions/extensions.tsx
  src/renderer/components/+extensions/install-from-input/install-from-input.injectable.ts
  src/renderer/components/+extensions/install-from-input/install-from-input.tsx
  src/renderer/components/+user-management/+cluster-role-bindings/details.tsx
  src/renderer/components/+user-management/+role-bindings/details.tsx
  src/renderer/components/+workloads-cronjobs/cron-job-menu.tsx
  src/renderer/components/+workloads-deployments/deployment-menu.tsx
  src/renderer/components/+workloads-statefulsets/stateful-set-menu.tsx
  src/renderer/components/animate/animate.tsx
  src/renderer/components/confirm-dialog/confirm-dialog.tsx
  src/renderer/components/confirm-dialog/confirm.injectable.ts
  src/renderer/components/confirm-dialog/open.injectable.ts
  src/renderer/components/confirm-dialog/state.injectable.ts
  src/renderer/components/confirm-dialog/with-confirm.injectable.ts
  src/renderer/components/drawer/drawer.tsx
  src/renderer/components/hotbar/hotbar-icon.tsx
  src/renderer/components/hotbar/hotbar-remove-command.tsx
  src/renderer/components/icon/icon.tsx
  src/renderer/components/item-object-list/content.tsx
  src/renderer/components/kube-object-menu/__snapshots__/kube-object-menu.test.tsx.snap
  src/renderer/components/kube-object-menu/dependencies/kube-object-menu-items/get-kube-object-menu-items.ts
  src/renderer/components/kube-object-menu/dependencies/static-kube-object-menu-items.ts
  src/renderer/components/kube-object-menu/kube-object-menu-registration.ts
  src/renderer/components/kube-object-menu/kube-object-menu.test.tsx
  src/renderer/components/kube-object-menu/kube-object-menu.tsx
  src/renderer/components/kube-object-menu/on-context-menu-open.injectable.ts
  src/renderer/components/layout/sidebar-cluster.tsx
  src/renderer/components/menu/menu-actions.tsx
  src/renderer/components/menu/menu.tsx
  src/renderer/kube-object/handler.ts
  src/renderer/kube-object/handlers.injectable.ts
  src/renderer/kube-object/static-handlers.ts
  src/renderer/navigation/helpers.ts
  src/renderer/navigation/navigate.injectable.ts
  src/renderer/protocol-handler/bind-protocol-add-route-handlers/bind-protocol-add-route-handlers.injectable.ts
  src/renderer/protocol-handler/bind-protocol-add-route-handlers/bind-protocol-add-route-handlers.tsx
Labels: enhancement, area/extension

#5307 Fix subclasses of BaseStore<T> not be able to overrride cwd()
  src/common/base-store.ts
  src/common/get-configuration-file-model/get-configuration-file-model.injectable.ts
Labels: bug, area/extension

#5326 release v5.5.0-beta.0
  package.json
Labels: skip-changelog

#5288 Add some debug logging to help debug LED issue
  src/main/cluster-manager.ts
Labels: chore

#5352 Revert upgrade to react 18
  package.json
  src/renderer/bootstrap.tsx
  yarn.lock
Labels: bug, area/extension, blocker

#5346 Stop using sharp at runtime
  .gitignore
  Makefile
  build/generate-tray-icons.ts
  package.json
  src/main/index.ts
  src/main/tray/tray.ts
  yarn.lock
Labels: bug, blocker

#5356 Remove unused code in the telemetry preference.
  src/common/user-store/preferences-helpers.ts
  src/common/user-store/user-store.ts
Labels: chore, area/telemetry

#5362 Bundle tray icons in repo
  .gitignore
  Makefile
  build/generate-tray-icons.ts
  build/tray/trayIconDarkTemplate.png
  build/tray/trayIconDarkTemplate@2x.png
  build/tray/trayIconTemplate.png
  build/tray/trayIconTemplate@2x.png
  package.json
Labels: chore

#5367 Fix crash with NamespaceSelectFilter
  src/renderer/components/+namespaces/namespace-select-filter-model/namespace-select-filter-model.ts
Labels: bug

#5349 Fix CustomResourceDetails merging arrays of values
  src/renderer/components/+custom-resources/crd-resource-details.tsx
Labels: bug

#5297 Add defensive code around Cluster.broadcastConnectUpdate
  src/common/cluster/cluster.ts
  src/common/utils/type-narrowing.ts
  src/renderer/components/cluster-manager/cluster-status.tsx
Labels: bug

#5290 Change engines.lens signature to only respect minimums
  integration/__tests__/cluster-pages.tests.ts
  src/extensions/__tests__/extension-compatibility.test.ts
  src/extensions/__tests__/is-compatible-extension.test.ts
  src/extensions/__tests__/lens-extension.test.ts
  src/extensions/extension-compatibility.ts
  src/extensions/extension-discovery/extension-discovery.test.ts
  src/extensions/extension-discovery/is-compatible-extension/is-compatible-extension.ts
  src/extensions/lens-extension.ts
  src/main/menu/electron-menu-items.test.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/main/tray/tray-menu-items.test.ts
  src/renderer/components/+extensions/__tests__/extensions.test.tsx
  src/renderer/components/+welcome/__test__/welcome.test.tsx
  src/renderer/components/kube-object-menu/kube-object-menu.test.tsx
  src/renderer/components/kube-object-status-icon/kube-object-status-icon.test.tsx
  src/renderer/components/status-bar/status-bar.test.tsx
  src/renderer/components/test-utils/get-renderer-extension-fake.ts
Labels: enhancement, area/extension

#5384 Remove outdated @types/react-select
  package.json
  yarn.lock
Labels: dependencies

#5386 Remove @types/react-select from npm/extensions/package.json
  src/extensions/npm/extensions/package.json
Labels: dependencies

#5390 Change update default to update on quit
  src/main/app-updater.ts
Labels: enhancement, area/auto-update

#5382 Release 5.5.0-beta.1
  extensions/kube-object-event-status/package-lock.json
  extensions/metrics-cluster-feature/package-lock.json
  extensions/node-menu/package-lock.json
  extensions/pod-menu/package-lock.json
  package.json
  src/extensions/npm/extensions/package-lock.json
  src/extensions/npm/extensions/package.json
  yarn.lock
Labels: skip-changelog

#5389 Refactoring extension-app compatibility checks
  src/extensions/__tests__/is-compatible-extension.test.ts
Labels: area/extension, area/tests

#5404 Increase version to v5.6.0-alpha.0 for master
  package.json
Labels: skip-changelog

#5376 TopBar Update button
  src/renderer/components/layout/top-bar/top-bar.tsx
  src/renderer/components/update-button/__tests__/__snapshots__/update-button.test.tsx.snap
  src/renderer/components/update-button/__tests__/update-button.test.tsx
  src/renderer/components/update-button/index.ts
  src/renderer/components/update-button/styles.module.scss
  src/renderer/components/update-button/update-button.tsx
Labels: enhancement, area/ui, area/auto-update

#5408 Switch to always using latest minikube in CI
  .github/workflows/test.yml
Labels: area/ci

#5415 Fix Kubectl.checkBinary() to be compatible with kubectl@1.24
  src/main/kubectl/kubectl.ts
Labels: bug, blocker, area/kubernetes-next

#5413 Fix downloading cluster specific kubectl
  src/common/__tests__/cluster-store.test.ts
  src/common/app-paths/directory-for-bundled-binaries/directory-for-bundled-binaries.injectable.ts
  src/common/vars.ts
  src/common/vars/base-bundled-binaries-dir.injectable.ts
  src/common/vars/bundled-binaries-normalized-arch.injectable.ts
  src/common/vars/bundled-resources-dir.injectable.ts
  src/common/vars/is-production.injectable.ts
  src/common/vars/normalized-platform.injectable.ts
  src/main/__test__/cluster.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/getDiForUnitTesting.ts
  src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts
  src/main/kubectl/binary-name.injectable.ts
  src/main/kubectl/bundled-binary-path.injectable.ts
  src/main/kubectl/create-kubectl.injectable.ts
  src/main/kubectl/kubectl.ts
  src/main/kubectl/normalized-arch.injectable.ts
  src/main/router/router.test.ts
  src/main/shell-session/local-shell-session/local-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/renderer/components/delete-cluster-dialog/__tests__/delete-cluster-dialog.test.tsx
Labels: bug, blocker

#5418 Fix splash window having window control buttons
  src/main/start-main-application/lens-window/application-window/application-window-state.injectable.ts
  src/main/start-main-application/lens-window/application-window/application-window.injectable.ts
  src/main/start-main-application/lens-window/application-window/create-electron-window-for.injectable.ts
  src/main/start-main-application/lens-window/application-window/create-lens-window.injectable.ts
Labels: bug, area/macos

#5426 Fix error in legacyRegisterApi on main
  src/common/k8s-api/kube-api.ts
Labels: bug

#5432 Fix cluster connection failing after execHelm
  src/main/helm/exec.ts
Labels: bug, blocker

#5428 Release 5.5.0-beta.2
  package.json
Labels: skip-changelog

#5438 Allow bundled extensions to use codesign
  .azure-pipelines.yml
Labels: enhancement, area/macos, blocker, area/release-process

#5427 Fix Catalog displaying wrong number of items per category
  src/renderer/components/+catalog/__tests__/catalog-entity-store.test.ts
  src/renderer/components/+catalog/catalog-entity-store/catalog-entity.store.tsx
Labels: bug, area/catalog

#5429 Cherry Pick bug fixes from v5.5.0-beta.2
  src/common/k8s-api/__tests__/node.test.ts
  src/common/k8s-api/endpoints/node.api.ts
  src/main/helm/exec.ts
  src/main/kubectl/kubectl.ts
  src/renderer/components/+nodes/store.ts
Labels: skip-changelog

#5441 Release 5.5.0
  package.json
Labels: skip-changelog

#5450 Fix crash when using an inline svg Icon
  src/renderer/components/icon/icon.tsx
  types/mocks.d.ts
  webpack/renderer.ts
Labels: bug, blocker

#5466 Release 5.5.1
  package.json
Labels: skip-changelog

#5479 Fix: app-crash with multiple usages of active MonacoEditor component
  src/renderer/components/monaco-editor/monaco-editor.tsx
Labels: bug, area/ui, blocker

#5474 Remove deprecated nodeSelectorTerms from cluster metrics manifests
  extensions/metrics-cluster-feature/resources/03-statefulset.yml.hb
  extensions/metrics-cluster-feature/resources/10-node-exporter-ds.yml.hb
  extensions/metrics-cluster-feature/resources/14-kube-state-metrics-deployment.yml.hb
Labels: bug, area/metrics

#5484 Fix error in EditResource
  src/renderer/components/dock/edit-resource/view.tsx
Labels: bug

#5488 Ensure the cluster dashboard start url is valid
  src/renderer/frames/cluster-frame/start-url.injectable.ts
Labels: bug

#5467 Fix crash in ProjectedVolume component
  src/common/k8s-api/endpoints/pod.api.ts
  src/renderer/components/+workloads-pods/details/volumes/variants/__snapshots__/projected.test.tsx.snap
  src/renderer/components/+workloads-pods/details/volumes/variants/projected.test.tsx
  src/renderer/components/+workloads-pods/details/volumes/variants/projected.tsx
  src/renderer/utils/display-mode.ts
  src/renderer/utils/index.ts
Labels: bug

#5501 Fix crash in <CephFs />
  package.json
  src/common/k8s-api/endpoints/pod.api.ts
  src/jest-after-env.setup.ts
  src/renderer/components/+workloads-pods/details/volumes/variants/__tests__/__snapshots__/ceph-fs.test.tsx.snap
  src/renderer/components/+workloads-pods/details/volumes/variants/__tests__/ceph-fs.test.tsx
  src/renderer/components/+workloads-pods/details/volumes/variants/ceph-fs.tsx
Labels: bug

#5449 Make terminal tab icon the same as the menu item icon
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/terminal/dock-tab.tsx
Labels: bug, area/ui

#5504 release v5.5.2
  extensions/metrics-cluster-feature/resources/03-statefulset.yml.hb
  extensions/metrics-cluster-feature/resources/10-node-exporter-ds.yml.hb
  extensions/metrics-cluster-feature/resources/14-kube-state-metrics-deployment.yml.hb
  package.json
  src/common/k8s-api/endpoints/pods.api.ts
  src/common/k8s-api/kube-json-api.ts
  src/jest-after-env.setup.ts
  src/renderer/components/+workloads-pods/details/volumes/variants/__snapshots__/projected.test.tsx.snap
  src/renderer/components/+workloads-pods/details/volumes/variants/__tests__/__snapshots__/ceph-fs.test.tsx.snap
  src/renderer/components/+workloads-pods/details/volumes/variants/__tests__/ceph-fs.test.tsx
  src/renderer/components/+workloads-pods/details/volumes/variants/ceph-fs.tsx
  src/renderer/components/+workloads-pods/details/volumes/variants/projected.test.tsx
  src/renderer/components/+workloads-pods/details/volumes/variants/projected.tsx
  src/renderer/components/monaco-editor/monaco-editor.tsx
  src/renderer/utils/display-mode.ts
  src/renderer/utils/index.ts
Labels: skip-changelog

#5515 Update slack invite link
  README.md
Labels: area/documentation
