Repository lensapp/lens, pull requests merged in 2022-03, with the labels that each got.

#4938 Fix Editor's Font Family preference not being editable
  src/renderer/components/+preferences/editor.tsx
Labels: bug, merge/release

#4945 Cherry Pick from master to release/v5.4
  src/common/cluster/cluster.ts
  src/common/utils/__tests__/formatDuration.test.ts
  src/renderer/components/+preferences/editor.tsx
Labels: skip-changelog

#4947 Release v5.4.0
  package.json
Labels: skip-changelog

#4946 Bump lens-k8s-proxy to v0.1.5
  package.json
  src/main/context-handler/context-handler.ts
  src/main/kube-auth-proxy/kube-auth-proxy.ts
Labels: dependencies

#4959 Fix api-manager kubeobject types
  src/common/k8s-api/api-manager.ts
Labels: bug, area/extension

#4817 Replace WorkloadsOverviewDetailRegistry with reactive solution
  src/extensions/extension-loader/extension-loader.ts
  src/extensions/lens-renderer-extension.ts
  src/extensions/registries/index.ts
  src/extensions/registries/workloads-overview-detail-registry.ts
  src/renderer/bootstrap.tsx
  src/renderer/components/+workloads-overview/detail-components.injectable.ts
  src/renderer/components/+workloads-overview/overview.tsx
  src/renderer/components/+workloads-overview/workloads-overview-detail-registration.ts
  src/renderer/initializers/index.ts
  src/renderer/initializers/registries.ts
  src/renderer/initializers/workloads-overview-detail-registry.tsx
Labels: chore

#4961 Fix unselect. Add unit tests
  src/renderer/components/select/select.test.tsx
  src/renderer/components/select/select.tsx
Labels: bug, area/ui

#4964 quick fix for logs not showing in tabs after first tab
  src/renderer/components/dock/logs/view.tsx
Labels: bug

#4969 Release/v5.4.1
  package.json
  src/common/k8s-api/api-manager.ts
  src/renderer/components/dock/logs/view.tsx
  src/renderer/components/select/select.test.tsx
  src/renderer/components/select/select.tsx
Labels: skip-changelog

#4976 Fix annotation for cronjob when is manually triggered
  src/renderer/components/+workloads-cronjobs/cronjob-trigger-dialog.tsx
Labels: bug

#4980 Webpack quality of life improvements for dev mode
  Makefile
  extensions/kube-object-event-status/package-lock.json
  extensions/kube-object-event-status/package.json
  extensions/metrics-cluster-feature/package-lock.json
  extensions/metrics-cluster-feature/package.json
  extensions/node-menu/package-lock.json
  extensions/node-menu/package.json
  extensions/pod-menu/package-lock.json
  extensions/pod-menu/package.json
  package.json
  src/main/index.ts
  src/main/lens-proxy.ts
  src/main/router.ts
  src/main/router/router.injectable.ts
  webpack.dev-server.ts
  webpack.main.ts
  webpack.renderer.ts
Labels: chore

#4973 Add 'Sync with computer' theme option
  src/common/ipc/native-theme.ts
  src/extensions/registries/__tests__/page-registry.test.ts
  src/main/index.ts
  src/main/initializers/init-ipc-main-handlers/init-ipc-main-handlers.ts
  src/main/native-theme.ts
  src/renderer/components/+catalog/catalog.test.tsx
  src/renderer/components/+preferences/application.tsx
  src/renderer/components/dock/__test__/dock-tabs.test.tsx
  src/renderer/components/dock/logs/__test__/log-resource-selector.test.tsx
  src/renderer/components/hotbar/__tests__/hotbar-remove-command.test.tsx
  src/renderer/components/select/select.test.tsx
  src/renderer/theme.store.ts
Labels: enhancement, area/ui

#4942 Consolidate downloading binaries into one script
  Makefile
  build/download_binaries.ts
  build/download_helm.ts
  build/download_k8s_proxy.ts
  build/download_kubectl.ts
  package.json
  src/common/app-paths/directory-for-bundled-binaries/directory-for-bundled-binaries.injectable.ts
  src/common/utils/lazy-initialized.ts
  src/common/vars.ts
  src/main/helm/exec.ts
  src/main/helm/helm-chart-manager.ts
  src/main/helm/helm-cli.ts
  src/main/helm/helm-release-manager.ts
  src/main/helm/helm-repo-manager.ts
  src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts
  src/main/kube-auth-proxy/kube-auth-proxy.ts
  src/main/kubectl/kubectl.ts
  src/main/lens-binary.ts
  src/main/shell-session/local-shell-session/local-shell-session.ts
  src/renderer/components/+preferences/kubectl-binaries.tsx
  webpack.main.ts
  webpack.renderer.ts
  yarn.lock
Labels: dependencies

#4920 Fix HelmChart validator requiring digest field
  src/common/k8s-api/__tests__/helm-charts.api.test.ts
  src/common/k8s-api/endpoints/helm-charts.api.ts
Labels: bug, area/helm

#4970 Remove listener for online event
  src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
Labels: bug, area/windows, area/ui

#4987 Fix "logs from" date
  src/renderer/components/dock/logs/controls.tsx
Labels: bug, area/ui

#4859 Make routes in back-end comply to Open Closed Principle
  package.json
  src/common/k8s-api/endpoints/metrics.api.ts
  src/main/__test__/router.test.ts
  src/main/__test__/static-file-route.test.ts
  src/main/getDiForUnitTesting.ts
  src/main/helm/helm-release-manager.ts
  src/main/lens-proxy.ts
  src/main/router.ts
  src/main/router/parse-request.injectable.ts
  src/main/router/router-content-types.ts
  src/main/router/router.injectable.ts
  src/main/router/router.test.ts
  src/main/router/router.ts
  src/main/routes/helm-route.ts
  src/main/routes/helm/charts/get-chart-route.injectable.ts
  src/main/routes/helm/charts/get-chart-values-route.injectable.ts
  src/main/routes/helm/charts/list-charts-route.injectable.ts
  src/main/routes/helm/releases/delete-release-route.injectable.ts
  src/main/routes/helm/releases/get-release-history-route.injectable.ts
  src/main/routes/helm/releases/get-release-route.injectable.ts
  src/main/routes/helm/releases/get-release-values-route.injectable.ts
  src/main/routes/helm/releases/install-chart-route.injectable.ts
  src/main/routes/helm/releases/list-releases-route.injectable.ts
  src/main/routes/helm/releases/rollback-release-route.injectable.ts
  src/main/routes/helm/releases/update-release-route.injectable.ts
  src/main/routes/index.ts
  src/main/routes/kubeconfig-route.ts
  src/main/routes/kubeconfig-route/get-service-account-route.injectable.ts
  src/main/routes/metrics-route.ts
  src/main/routes/metrics/add-metrics-route.injectable.ts
  src/main/routes/metrics/get-metric-providers-route.injectable.ts
  src/main/routes/metrics/metrics-query.ts
  src/main/routes/port-forward-route.ts
  src/main/routes/port-forward/functionality/create-port-forward.injectable.ts
  src/main/routes/port-forward/functionality/port-forward.ts
  src/main/routes/port-forward/get-current-port-forward-route.injectable.ts
  src/main/routes/port-forward/route-port-forward/route-port-forward.injectable.ts
  src/main/routes/port-forward/route-port-forward/route-port-forward.ts
  src/main/routes/port-forward/start-port-forward-route.injectable.ts
  src/main/routes/port-forward/stop-current-port-forward-route.injectable.ts
  src/main/routes/resource-applier-route.ts
  src/main/routes/resource-applier/apply-resource-route.injectable.ts
  src/main/routes/resource-applier/patch-resource-route.injectable.ts
  src/main/routes/static-file-route.injectable.ts
  src/main/routes/version-route.ts
  src/main/routes/versions/get-version-route.injectable.ts
  yarn.lock
Labels: chore

#4991 Fix spacing and layout of registered TopBar items
  src/renderer/components/layout/top-bar/top-bar.module.scss
  src/renderer/components/layout/top-bar/top-bar.tsx
Labels: bug, area/ui

#5005 Release/v5.4.2
  package.json
  src/common/k8s-api/__tests__/helm-charts.api.test.ts
  src/common/k8s-api/endpoints/helm-charts.api.ts
  src/renderer/components/+workloads-cronjobs/cronjob-trigger-dialog.tsx
  src/renderer/components/dock/logs/controls.tsx
  src/renderer/components/item-object-list/content.tsx
  src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
Labels: skip-changelog

#5029 Fix: overlapped pod logs
  src/renderer/components/dock/logs/store.ts
Labels: bug, area/ui, area/logs

#5010 Bump injectable to 5.1.2
  package.json
  src/common/app-paths/directory-for-bundled-binaries/directory-for-bundled-binaries.injectable.ts
  src/common/vars/context-dir.injectable.ts
  src/common/vars/is-development.injectable.ts
  src/extensions/as-legacy-globals-for-extension-api/as-legacy-global-function-for-extension-api.ts
  src/extensions/as-legacy-globals-for-extension-api/as-legacy-global-object-for-extension-api-with-modifications.test.ts
  src/extensions/as-legacy-globals-for-extension-api/as-legacy-global-object-for-extension-api-with-modifications.ts
  src/extensions/as-legacy-globals-for-extension-api/as-legacy-global-object-for-extension-api.ts
  src/extensions/renderer-api/components.ts
  src/main/shell-session/shell-env-modifier/terminal-shell-env-modify.injectable.ts
  src/renderer/components/+workloads-overview/detail-components.injectable.ts
  src/renderer/components/kube-object-status-icon/status-registrations.injectable.ts
  src/renderer/components/status-bar/registered-status-bar-items.injectable.tsx
  src/renderer/components/status-bar/status-bar-items.injectable.ts
  yarn.lock
Labels: chore

#4754 Improve dock tabs UX
  src/renderer/components/dock/__test__/dock-store.test.ts
  src/renderer/components/dock/__test__/dock-tabs.test.tsx
  src/renderer/components/dock/dock-tab.module.scss
  src/renderer/components/dock/dock-tab.scss
  src/renderer/components/dock/dock-tab.tsx
  src/renderer/components/dock/dock-tabs.module.scss
  src/renderer/components/dock/dock-tabs.tsx
  src/renderer/components/dock/dock.scss
  src/renderer/components/dock/dock.tsx
  src/renderer/components/dock/dock/store.ts
  src/renderer/components/dock/terminal/dock-tab.tsx
  src/renderer/components/fonts.scss
  src/renderer/components/fonts/MaterialIcons-Regular.ttf
  src/renderer/components/fonts/MaterialIcons-Regular.woff2
  src/renderer/components/tabs/tabs.tsx
  src/renderer/hooks/index.ts
  src/renderer/hooks/useResizeObserver.ts
  src/renderer/themes/lens-dark.json
  src/renderer/themes/lens-light.json
Labels: enhancement, area/ui

#5071 Emit AppEvent when opening Catalog and changing Catalog Category
  src/common/__tests__/catalog-entity.test.ts
  src/common/catalog/catalog-entity.ts
  src/renderer/components/+catalog/catalog.test.tsx
  src/renderer/components/+catalog/catalog.tsx
Labels: enhancement, area/catalog

#5070 Fix winston logger missing splat format
  src/common/logger.ts
  src/main/__test__/cluster.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/app-updater.ts
Labels: bug, area/extension

#5086 Deprecate some undesirables
  src/common/vars.ts
  src/extensions/as-legacy-globals-for-extension-api/as-legacy-global-object-for-extension-api-with-modifications.ts
Labels: chore

#5083 Bump package version to 5.5.0-alpha.0
  package.json
Labels: skip-changelog

#5034 Fix KubeJsonApi.forCluster throwing on renderer
  src/common/k8s-api/api-base.ts
  src/common/k8s-api/api-kube.ts
  src/common/k8s-api/index.ts
  src/common/k8s-api/kube-json-api.ts
Labels: bug

#5099 Release/v5.4.4
  package.json
  src/common/__tests__/catalog-entity.test.ts
  src/common/catalog/catalog-entity.ts
  src/common/k8s-api/api-base.ts
  src/common/k8s-api/api-kube.ts
  src/common/k8s-api/index.ts
  src/common/k8s-api/kube-json-api.ts
  src/common/logger.ts
  src/main/__test__/cluster.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/app-updater.ts
  src/renderer/components/+catalog/catalog.test.tsx
  src/renderer/components/+catalog/catalog.tsx
Labels: skip-changelog

#5081 TLS cert per cluster for lens-k8s-proxy
  package.json
  src/common/__tests__/cluster-store.test.ts
  src/main/__test__/context-handler.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/context-handler/context-handler.ts
  src/main/context-handler/create-context-handler.injectable.ts
  src/main/kube-auth-proxy/create-kube-auth-proxy-cert-files.injectable.ts
  src/main/kube-auth-proxy/create-kube-auth-proxy-cert-files.ts
  src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts
  src/main/kube-auth-proxy/get-kube-auth-proxy-certificate.ts
  src/main/kube-auth-proxy/kube-auth-proxy-ca.injectable.ts
  src/main/kube-auth-proxy/kube-auth-proxy.ts
  src/renderer/components/dock/logs/view.tsx
  src/renderer/components/tabs/tabs.tsx
  types/dom.d.ts
Labels: bug

#5087 Yarn scripts for quality of life in development
  package.json
Labels: chore

#5115 Fix: make dock tab close button smaller
  src/renderer/components/dock/dock-tab.module.scss
Labels: bug, area/ui

#5130 Fix mobx error after closing Edit Resource tab
  src/renderer/components/dock/edit-resource/view.tsx
Labels: bug, area/ui

#5131 Fix use transparent bg if Avatar contains <img/> inside
  src/renderer/components/avatar/avatar.tsx
  src/renderer/components/layout/sidebar-cluster.tsx
Labels: bug, area/ui

#5120 Fix exception in KubeStore.watch event buffer handling
  src/common/k8s-api/kube-api.ts
  src/common/k8s-api/kube-object.store.ts
  src/common/k8s-api/kube-watch-event.ts
Labels: bug

#5142 Fix: remove HotbarIcon rounded corner artifacts
  src/renderer/components/avatar/avatar.tsx
  src/renderer/components/hotbar/hotbar-icon.module.scss
  src/renderer/components/hotbar/hotbar-icon.tsx
Labels: bug, area/ui

#5143 Set dock tab contrast bg color
  src/renderer/components/dock/dock.scss
Labels: bug, area/ui

#5147 Fix CatalogEntity.status sorting in Catalog
  src/renderer/components/+catalog/internal-category-columns.tsx
Labels: bug

#4630 Add links for ingresses
  src/common/k8s-api/__tests__/ingress.api.ts
  src/common/k8s-api/endpoints/ingress.api.ts
  src/common/k8s-api/kube-object.ts
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+network-ingresses/ingresses.scss
  src/renderer/components/+network-ingresses/ingresses.tsx
Labels: enhancement, area/ui

#5158 fix license-header workflow
  .github/workflows/license-header.yml
Labels: chore
