Repository lensapp/lens, pull requests merged in 2022-06, with the labels that each got.

#5540 Fix type error in kube-object-menu.test.tsx
  src/renderer/components/kube-object-menu/kube-object-menu.test.tsx
Labels: chore

#5483 Remove legacy renderBooleans prop
  src/common/k8s-api/endpoints/custom-resource-definition.api.ts
  src/common/k8s-api/endpoints/types/external-documentation.ts
  src/common/k8s-api/endpoints/types/json-schema-props.ts
  src/renderer/components/+custom-resources/__tests__/__snapshots__/custom-resource-details.test.tsx.snap
  src/renderer/components/+custom-resources/__tests__/custom-resource-details.test.tsx
  src/renderer/components/+custom-resources/crd-resource-details.tsx
  src/renderer/components/drawer/drawer-item.tsx
  src/renderer/components/table/table-cell.tsx
  src/renderer/utils/__tests__/display-booleans.test.tsx
  src/renderer/utils/display-booleans.ts
  src/renderer/utils/index.ts
Labels: chore

#5532 Fix *.modules.scss that don't get correctly typed
  src/renderer/components/+add-cluster/add-cluster.module.scss
  src/renderer/components/kubeconfig-dialog/kubeconfig-dialog.module.scss
  src/renderer/components/switch/switch.module.scss
Labels: chore

#5546 Release v5.5.3-beta.0
  package.json
Labels: skip-changelog

#5549 Release v5.5.3
  package.json
Labels: skip-changelog

#5399 Fix downloading cluster specific kubectl
  src/common/__tests__/cluster-store.test.ts
  src/common/app-paths/directory-for-bundled-binaries/directory-for-bundled-binaries.injectable.ts
  src/common/vars.ts
  src/common/vars/base-bundled-binaries-dir.injectable.ts
  src/common/vars/bundled-binaries-normalized-arch.injectable.ts
  src/common/vars/bundled-resources-dir.injectable.ts
  src/common/vars/normalized-platform.injectable.ts
  src/main/__test__/cluster.test.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  src/main/getDiForUnitTesting.ts
  src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts
  src/main/kubectl/binary-name.injectable.ts
  src/main/kubectl/bundled-binary-path.injectable.ts
  src/main/kubectl/create-kubectl.injectable.ts
  src/main/kubectl/kubectl.ts
  src/main/kubectl/normalized-arch.injectable.ts
  src/main/router/router.test.ts
  src/main/shell-session/local-shell-session/local-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/renderer/components/delete-cluster-dialog/__tests__/delete-cluster-dialog.test.tsx
Labels: skip-changelog

#5519 Fix Tooltip not showing when switching hotbars
  src/renderer/components/tooltip/__snapshots__/tooltip.test.tsx.snap
  src/renderer/components/tooltip/tooltip.test.tsx
  src/renderer/components/tooltip/tooltip.tsx
Labels: bug, area/ui, area/hotbar

#5548 Remove all manual uses of v8 serialization
  src/common/terminal/channels.ts
  src/main/helm/helm-chart-manager.ts
  src/main/shell-session/node-shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/renderer/api/terminal-api.ts
  src/renderer/api/websocket-api.ts
  src/renderer/components/dock/terminal/send-command.injectable.ts
  src/renderer/components/dock/terminal/terminal.ts
Labels: bug, area/terminal

#5564 Allow using custom https.Agent instance
  src/common/k8s-api/kube-api.ts
Labels: enhancement, area/catalog

#5550 Fix cluster server path being duplicated by proxy
  src/main/context-handler/context-handler.ts
Labels: bug

#5562 Electron v15.5.7
  .azure-pipelines.yml
  .github/workflows/check-docs.yml
  .github/workflows/electronegativity.yml
  .github/workflows/linter.yml
  .github/workflows/main.yml
  .github/workflows/mkdocs-manual.yml
  .github/workflows/publish-master-npm.yml
  .github/workflows/publish-release-npm.yml
  .github/workflows/test.yml
  .yarnrc
  package.json
  src/main/helm/exec.ts
  src/renderer/components/test-utils/get-application-builder.tsx
  yarn.lock
Labels: enhancement, area/security

#5567 Add reactive tray icon for when update is available
  Makefile
  build/generate-tray-icons.ts
  build/tray/trayIcon.png
  build/tray/trayIcon@2x.png
  build/tray/trayIcon@3x.png
  build/tray/trayIcon@4x.png
  build/tray/trayIconTemplate@3x.png
  build/tray/trayIconTemplate@4x.png
  build/tray/trayIconUpdateAvailable.png
  build/tray/trayIconUpdateAvailable@2x.png
  build/tray/trayIconUpdateAvailable@3x.png
  build/tray/trayIconUpdateAvailable@4x.png
  build/tray/trayIconUpdateAvailableTemplate.png
  build/tray/trayIconUpdateAvailableTemplate@2x.png
  build/tray/trayIconUpdateAvailableTemplate@3x.png
  build/tray/trayIconUpdateAvailableTemplate@4x.png
  src/behaviours/application-update/__snapshots__/installing-update-using-tray.test.ts.snap
  src/behaviours/application-update/installing-update-using-tray.test.ts
  src/common/application-update/update-channels.ts
  src/common/utils/sync-box/sync-box-injection-token.ts
  src/main/tray/electron-tray/electron-tray.injectable.ts
  src/main/tray/menu-icon/reactive.injectable.ts
  src/main/tray/menu-icon/start-reactivity.injectable.ts
  src/main/tray/menu-icon/stop-reactivity.injectable.ts
  src/main/tray/reactive-tray-menu-items/converters.ts
  src/main/tray/reactive-tray-menu-items/reactive-tray-menu-items.injectable.ts
  src/main/tray/tray-icon-path.injectable.ts
  src/main/tray/tray-menu-items.injectable.ts
  src/main/tray/tray.ts
  src/renderer/components/icon/icon.tsx
  src/renderer/components/icon/notice.svg
  src/renderer/components/test-utils/get-application-builder.tsx
Labels: enhancement, area/auto-update

#5573 Revert breaking the types of DrawerTitle
  src/renderer/components/drawer/drawer-title.tsx
Labels: bug, area/extension

#5581 Enable csp on lens proxy
  package.json
  src/common/vars.ts
  src/main/lens-proxy/lens-proxy.ts
Labels: enhancement, area/security

#5587 Bump injectable for faster unit tests
  package.json
  yarn.lock
Labels: chore

#5593 Fix cluster.k8s.io/v1alpha1/clusters CRD not being marked as Namespaced
  src/common/k8s-api/endpoints/cluster.api.ts
Labels: bug

#5599 Fix: allow to load images with data:base64 urls
  package.json
Labels: bug

#5403 Fix changes to InputValidator to resolve accidental breaking changes
  src/common/utils/type-narrowing.ts
  src/renderer/components/+extensions/install-from-input/install-from-input.tsx
  src/renderer/components/+extensions/install.tsx
  src/renderer/components/input/__tests__/input_validators.test.ts
  src/renderer/components/input/input.tsx
  src/renderer/components/input/input_validators.ts
Labels: bug, area/extension

#5589 Release v5.5.4
  package.json
  src/common/k8s-api/endpoints/cluster.api.ts
  src/common/terminal/channels.ts
  src/main/context-handler/context-handler.ts
  src/main/helm/helm-chart-manager.ts
  src/main/shell-session/node-shell-session/node-shell-session.ts
  src/main/shell-session/shell-session.ts
  src/renderer/api/terminal-api.ts
  src/renderer/api/websocket-api.ts
  src/renderer/components/dock/terminal/send-command.injectable.ts
  src/renderer/components/dock/terminal/terminal.ts
  src/renderer/components/drawer/drawer-title.tsx
  src/renderer/components/tooltip/__snapshots__/tooltip.test.tsx.snap
  src/renderer/components/tooltip/tooltip.test.tsx
  src/renderer/components/tooltip/tooltip.tsx
Labels: skip-changelog

#5606 Fix merge conflict with async validators
  src/renderer/components/input/validators/is-path.injectable.ts
Labels: chore

#5597 Fix memory leak in unit tests
  .swcrc
  package.json
  src/behaviours/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/navigation-to-helm-charts.test.ts.snap
  src/behaviours/helm-charts/add-custom-helm-repository-in-preferences.test.ts
  src/behaviours/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  src/common/k8s-api/__tests__/kube-api.test.ts
  src/common/protocol-handler/router.ts
  src/common/test-utils/flush-promises.ts
  src/extensions/__tests__/extension-loader.test.ts
  src/extensions/extension-discovery/extension-discovery.test.ts
  src/extensions/extensions-store/extensions-store.ts
  src/jest-28-resolver.js
  src/jest.setup.ts
  src/main/__test__/kube-auth-proxy.test.ts
  src/main/protocol-handler/__test__/router.test.ts
  src/main/protocol-handler/lens-protocol-router-main/lens-protocol-router-main.ts
  src/renderer/components/+add-cluster/add-cluster.tsx
  src/renderer/components/badge/has-text-selected.injectable.ts
  src/renderer/components/layout/top-bar/close-window.injectable.ts
  src/renderer/components/layout/top-bar/go-back.injectable.ts
  src/renderer/components/layout/top-bar/go-forward.injectable.ts
  src/renderer/components/layout/top-bar/maximize-window.injectable.ts
  src/renderer/components/layout/top-bar/next-enabled.injectable.ts
  src/renderer/components/layout/top-bar/open-app-context-menu.injectable.ts
  src/renderer/components/layout/top-bar/prev-enabled.injectable.ts
  src/renderer/components/layout/top-bar/start-state-sync.injectable.ts
  src/renderer/components/layout/top-bar/state.injectable.ts
  src/renderer/components/layout/top-bar/toggle-maximize-window.injectable.ts
  src/renderer/components/layout/top-bar/top-bar-win-linux.test.tsx
  src/renderer/components/layout/top-bar/top-bar.test.tsx
  src/renderer/components/layout/top-bar/top-bar.tsx
  src/renderer/components/tooltip/__snapshots__/tooltip.test.tsx.snap
  src/renderer/components/tooltip/tooltip.test.tsx
  src/renderer/components/tooltip/tooltip.tsx
  src/renderer/getDiForUnitTesting.tsx
  yarn.lock
Labels: chore

#5574 Add @types/hapi__call and @types/hapi__subtext
  package.json
  src/main/router/parse-request.injectable.ts
  src/main/router/router.test.ts
  src/main/router/router.ts
  types/mocks.d.ts
  yarn.lock
Labels: dependencies

#5617 Update release creation script
  scripts/create-release-pr.mjs
Labels: chore

#5624 Update copyright to 2022
  LICENSE
  package.json
  src/extensions/npm/extensions/package.json
Labels: chore

#5618 release 5.6.0-alpha.1
  package.json
Labels: skip-changelog

#5629 Fix not starting with sentryDSN configured
  src/main/index.ts
  src/main/start-main-application/runnables/setup-sentry.injectable.ts
  src/main/start-main-application/start-main-application.injectable.ts
Labels: bug, blocker

#5630 modify app test rendering to include status bar
  src/behaviours/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  src/behaviours/__snapshots__/navigate-to-extension-page.test.tsx.snap
  src/behaviours/__snapshots__/navigating-between-routes.test.tsx.snap
  src/behaviours/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/behaviours/application-update/__snapshots__/installing-update-using-tray.test.ts.snap
  src/behaviours/application-update/__snapshots__/installing-update.test.ts.snap
  src/behaviours/application-update/__snapshots__/periodical-checking-of-updates.test.ts.snap
  src/behaviours/application-update/__snapshots__/selection-of-update-stability.test.ts.snap
  src/behaviours/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/add-helm-repository-from-list-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/closing-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-application-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-to-telemetry-preferences.test.tsx.snap
  src/behaviours/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/behaviours/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  src/behaviours/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/main/ask-boolean/__snapshots__/ask-boolean.test.ts.snap
  src/renderer/components/test-utils/get-application-builder.tsx
Labels: chore

#5640 release 5.6.0-alpha.2
  package.json
Labels: skip-changelog

#5533 Prevent duplicate app windows
  src/behaviours/extensions/navigation-using-application-menu.test.ts
  src/behaviours/preferences/navigation-using-application-menu.test.ts
  src/behaviours/quitting-and-restarting-the-app/opening-application-window-using-tray.test.ts
  src/behaviours/quitting-and-restarting-the-app/quitting-the-app-using-application-menu.test.ts
  src/behaviours/welcome/navigation-using-application-menu.test.ts
  src/common/utils/channel/channel.test.ts
  src/main/electron-app/runnables/dock-visibility/hide-dock-for-last-closed-window.injectable.ts
  src/main/getDiForUnitTesting.ts
  src/main/start-main-application/lens-window/application-window/application-window.injectable.ts
  src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts
  src/main/start-main-application/lens-window/application-window/create-lens-window.injectable.ts
  src/main/start-main-application/lens-window/application-window/lens-window-injection-token.ts
  src/main/start-main-application/lens-window/application-window/wait-until-bundled-extensions-are-loaded.injectable.ts
  src/main/start-main-application/lens-window/get-visible-windows.injectable.ts
  src/main/start-main-application/lens-window/show-application-window.injectable.ts
  src/main/start-main-application/start-main-application.injectable.ts
  src/main/utils/channel/message-to-channel.injectable.ts
  src/main/utils/channel/message-to-channel.test.ts
  src/renderer/components/test-utils/get-application-builder.tsx
Labels: bug

#5634 Make jest not crash totally when encountering non handled exception
  src/jest.setup.ts
Labels: chore

#5641 Fix html font size and adjust usage of rem units
  src/behaviours/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/add-helm-repository-from-list-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
  src/behaviours/helm-charts/__snapshots__/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts.snap
  src/renderer/components/+catalog/catalog-menu.module.scss
  src/renderer/components/+extensions/notice.module.scss
  src/renderer/components/+namespaces/namespace-select-filter.scss
  src/renderer/components/+preferences/kubernetes/helm-charts/helm-charts.module.scss
  src/renderer/components/+preferences/kubernetes/helm-charts/helm-repositories.tsx
  src/renderer/components/+preferences/removable-item.module.scss
  src/renderer/components/app.scss
  src/renderer/components/delete-cluster-dialog/view.module.scss
  src/renderer/components/delete-cluster-dialog/view.tsx
  src/renderer/components/dock/dock-tab.module.scss
  src/renderer/components/dock/logs/to-bottom.tsx
  src/renderer/components/layout/sidebar-cluster.module.scss
  src/renderer/components/layout/top-bar/top-bar.module.scss
  src/renderer/components/switch/switch.module.scss
Labels: bug, area/ui

#5607 Improved metrics for updating application
  src/behaviours/application-update/analytics-for-installing-update.test.ts
  src/behaviours/application-update/downgrading-version-update.test.ts
  src/behaviours/application-update/installing-update.test.ts
  src/behaviours/application-update/selection-of-update-stability.test.ts
  src/common/app-event-bus/emit-event.injectable.ts
  src/common/utils/date/get-current-date-time.ts
  src/main/application-update/check-for-updates-tray-item.injectable.ts
  src/main/application-update/check-for-updates/process-checking-for-updates.injectable.ts
  src/main/application-update/emit-current-version-to-analytics.injectable.ts
  src/main/application-update/install-application-update-tray-item.injectable.ts
  src/main/application-update/periodical-check-for-updates/periodical-check-for-updates.injectable.ts
  src/main/application-update/quit-and-install-update.injectable.ts
  src/main/electron-app/features/electron-quit-and-install-update.injectable.ts
  src/main/getDiForUnitTesting.ts
  src/main/menu/application-menu-items.injectable.ts
Labels: enhancement

#5661 Fix flaky unit test
  src/behaviours/quitting-and-restarting-the-app/opening-application-window-using-tray.test.ts
Labels: chore

#5603 Fix issue where releases are not reloaded when new release is added e…
  src/renderer/components/+helm-releases/release-secrets.injectable.ts
  src/renderer/components/+helm-releases/releases.injectable.ts
Labels: bug

#5609 Add behaviour for tray menu items originating from extensions
  src/behaviours/cluster/sidebar-and-tab-navigation-for-extensions.test.tsx
  src/behaviours/extension-special-characters-in-page-registrations.test.tsx
  src/behaviours/navigate-to-extension-page.test.tsx
  src/behaviours/preferences/navigation-to-extension-specific-preferences.test.tsx
  src/behaviours/preferences/navigation-to-telemetry-preferences.test.tsx
  src/behaviours/tray/clicking-tray-menu-item-originating-from-extension.test.ts
  src/main/tray/tray-menu-item/tray-menu-item-registrator.injectable.ts
  src/main/tray/tray-menu-items.injectable.ts
  src/main/tray/tray-menu-items.test.ts
  src/renderer/components/test-utils/get-application-builder.tsx
Labels: chore

#5666 Fix tray bugs
  src/behaviours/tray/multiple-separators-originating-from-extension.test.ts
  src/main/tray/tray-menu-item/tray-menu-item-registrator.injectable.ts
  src/renderer/components/test-utils/get-application-builder.tsx
Labels: bug

#5662 Simplify logic for injecting many instances which can reactively change e.g. based on extension being enabled or disabled
  package.json
  src/behaviours/cluster/sidebar-and-tab-navigation-for-extensions.test.tsx
  src/behaviours/extension-special-characters-in-page-registrations.test.tsx
  src/behaviours/navigate-to-extension-page.test.tsx
  src/behaviours/navigating-between-routes.test.tsx
  src/behaviours/preferences/navigation-to-extension-specific-preferences.test.tsx
  src/behaviours/tray/clicking-tray-menu-item-originating-from-extension.test.ts
  src/behaviours/tray/multiple-separators-originating-from-extension.test.ts
  src/extensions/extension-loader/extension-loader.injectable.ts
  src/extensions/extension-loader/extension-loader.ts
  src/extensions/extension-loader/extension-registrator-injection-token.ts
  src/extensions/extension-loader/extension/extension.injectable.ts
  src/main/getDi.ts
  src/main/getDiForUnitTesting.ts
  src/main/tray/tray-menu-item/tray-menu-item-injection-token.ts
  src/main/tray/tray-menu-item/tray-menu-item-registrator.injectable.ts
  src/main/tray/tray-menu-item/tray-menu-items.injectable.ts
  src/renderer/components/+custom-resources/sidebar-items-for-definition-groups.injectable.ts
  src/renderer/components/+preferences/extension-preference-item-registrator.injectable.ts
  src/renderer/components/+preferences/extension-preference-items.injectable.ts
  src/renderer/components/+preferences/extension-telemetry-preference-item-registrator.injectable.ts
  src/renderer/components/+preferences/telemetry-preference-items.injectable.ts
  src/renderer/components/+preferences/telemetry.tsx
  src/renderer/components/layout/extension-sidebar-item-registrator.injectable.tsx
  src/renderer/components/layout/sidebar-items.injectable.ts
  src/renderer/components/test-utils/get-application-builder.tsx
  src/renderer/getDi.tsx
  src/renderer/getDiForUnitTesting.tsx
  src/renderer/routes/all-routes.injectable.ts
  src/renderer/routes/current-path-parameters.injectable.ts
  src/renderer/routes/current-route-component.injectable.ts
  src/renderer/routes/extension-route-registrator.injectable.tsx
  src/renderer/routes/route-is-active.injectable.ts
  src/renderer/routes/routes.injectable.ts
  yarn.lock
Labels: chore

#5675 Update README.md
  README.md
Labels: area/documentation

#5679 Trivial tweaks accidentally left from other PR
  src/extensions/extension-loader/extension-installation-counter.injectable.ts
  src/extensions/extension-loader/extension-loader.injectable.ts
  src/extensions/extension-loader/extension-loader.ts
  src/extensions/extension-loader/extension/extension.injectable.ts
  src/renderer/components/test-utils/get-application-builder.tsx
Labels: chore

#5284 Show extension preferences in separate page
  package.json
  src/behaviours/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  src/behaviours/preferences/closing-preferences.test.tsx
  src/behaviours/preferences/navigation-to-extension-specific-preferences.test.tsx
  src/common/front-end-routing/routes/preferences/extension/extension-preferences-route.injectable.ts
  src/common/front-end-routing/routes/preferences/extension/navigate-to-extension-preferences.injectable.ts
  src/common/runnable/run-many-for.test.ts
  src/common/runnable/run-many-sync-for.test.ts
  src/extensions/as-legacy-globals-for-extension-api/as-legacy-global-object-for-extension-api-with-modifications.test.ts
  src/extensions/lens-renderer-extension.ts
  src/main/getDi.ts
  src/main/getDiForUnitTesting.ts
  src/renderer/components/+preferences/app-preference-tab/app-preference-tab-registration.ts
  src/renderer/components/+preferences/extension-preference-item-registrator.injectable.ts
  src/renderer/components/+preferences/extension-preference-items-injection-token.ts
  src/renderer/components/+preferences/extension-preference-model.injectable.ts
  src/renderer/components/+preferences/extensions.tsx
  src/renderer/components/+preferences/get-extension-preference-items.ts
  src/renderer/components/+preferences/preferences-navigation/__tests__/preferences-navigation.test.tsx
  src/renderer/components/+preferences/preferences-navigation/application-preferences-navigation-item.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/editor-preferences-navigation-item.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/extension-tab-preferences-navigation-item.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/extensions-nav-group.tsx
  src/renderer/components/+preferences/preferences-navigation/extensions-preferences-navigation-item-registrator.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/extensions-preferences-navigation-item.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/general-nav-group.tsx
  src/renderer/components/+preferences/preferences-navigation/kubernetes-preferences-navigation-item.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/preference-navigation-items-for-group.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/preference-navigation-items.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/preference-navigation-tab.tsx
  src/renderer/components/+preferences/preferences-navigation/preferences-navigation.tsx
  src/renderer/components/+preferences/preferences-navigation/proxy-preferences-navigation-item.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/telemetry-preferences-navigation-item.injectable.ts
  src/renderer/components/+preferences/preferences-navigation/terminal-preferences-navigation-item.injectable.ts
  src/renderer/components/layout/setting-layout.scss
  src/renderer/components/test-utils/get-application-builder.tsx
  src/renderer/getDi.tsx
  src/renderer/getDiForUnitTesting.tsx
  yarn.lock
Labels: enhancement, area/ui, area/extension

#5665 Do not crash if ingress is missing status.loadbalancer.ingress property
  src/common/k8s-api/__tests__/ingress.api.test.ts
  src/common/k8s-api/endpoints/ingress.api.ts
Labels: bug

#5697 Fix download percentages not updating in tray
  src/behaviours/application-update/installing-update-using-tray.test.ts
  src/main/tray/electron-tray/electron-tray.injectable.ts
  src/main/tray/reactive-tray-menu-items/converters.ts
  src/main/tray/reactive-tray-menu-items/reactive-tray-menu-items.injectable.ts
  src/renderer/components/test-utils/get-application-builder.tsx
Labels: bug

#5690 Helper to resolve proxy from URL in any environment, or using extension-API
  src/behaviours/resolve-system-proxy/resolve-system-proxy.test.ts
  src/common/log-error.injectable.ts
  src/common/utils/resolve-system-proxy/resolve-system-proxy-channel.injectable.ts
  src/common/utils/resolve-system-proxy/resolve-system-proxy-injection-token.ts
  src/common/utils/with-error-logging/with-error-logging.injectable.ts
  src/common/utils/with-error-logging/with-error-logging.test.ts
  src/extensions/common-api/index.ts
  src/extensions/common-api/proxy.ts
  src/main/getDiForUnitTesting.ts
  src/main/utils/resolve-system-proxy/electron.injectable.ts
  src/main/utils/resolve-system-proxy/resolve-system-proxy-channel-responder.injectable.ts
  src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.injectable.ts
  src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.test.ts
  src/main/utils/resolve-system-proxy/resolve-system-proxy.injectable.ts
  src/renderer/utils/resolve-proxy/resolve-system-proxy.injectable.ts
Labels: enhancement, area/extension

#5703 Revert accidental breaking change
  src/extensions/renderer-api/components.ts
  src/renderer/components/notifications/index.ts
  src/renderer/port-forward/port-forward-notify.tsx
Labels: bug

#5701 release 5.6.0-alpha.4
  package.json
Labels: skip-changelog

#5715 Re-export types for notifications store to revert accidental breaking…
  src/renderer/components/notifications/index.ts
Labels: bug

#5741 Fix: do not affect browsing history while navigating to extension preferences
  src/common/front-end-routing/routes/preferences/extension/navigate-to-extension-preferences.injectable.ts
Labels: bug, area/ui

#5431 Reenable generating of .js files for extension api package
  package.json
  tsconfig.extension-api.json
Labels: chore, area/extension

#5750 Remove 'Update Now' notification
  src/behaviours/application-update/__snapshots__/installing-update-using-tray.test.ts.snap
  src/behaviours/application-update/__snapshots__/installing-update.test.ts.snap
  src/behaviours/application-update/installing-update.test.ts
  src/behaviours/application-update/selection-of-update-stability.test.ts
  src/main/application-update/check-for-updates/process-checking-for-updates.injectable.ts
  src/main/ask-boolean/__snapshots__/ask-boolean.test.ts.snap
  src/main/ask-boolean/ask-boolean-answer-channel-listener.injectable.ts
  src/main/ask-boolean/ask-boolean-promise.injectable.ts
  src/main/ask-boolean/ask-boolean.injectable.ts
  src/main/ask-boolean/ask-boolean.test.ts
Labels: bug, area/ui

#5754 release 5.6.0-alpha.5
  package.json
Labels: skip-changelog

#5728 Fix selecting items always scrolling to top
  src/renderer/components/virtual-list/__snapshots__/virtual-list.test.tsx.snap
  src/renderer/components/virtual-list/virtual-list.test.tsx
  src/renderer/components/virtual-list/virtual-list.tsx
Labels: bug

#5735 Stop trying to restart catalog sync and updating of application when reloading window
  src/main/application-update/periodical-check-for-updates/start-checking-for-updates.injectable.ts
  src/main/catalog-sync-to-renderer/start-catalog-sync.injectable.ts
  src/main/getDiForUnitTesting.ts
  src/main/start-main-application/runnables/setup-runnables-for-after-root-frame-is-ready.injectable.ts
Labels: bug

#5755 Align hotbar selector elements with status bar items
  src/renderer/components/hotbar/hotbar-selector.module.scss
  src/renderer/components/hotbar/hotbar-selector.tsx
  src/renderer/components/status-bar/status-bar.module.scss
Labels: bug, area/ui

#5705 Add react-select as a dependency for @k8slens/extensions
  src/extensions/npm/extensions/package-lock.json
  src/extensions/npm/extensions/package.json
Labels: bug, area/extension

#5760 More padding between status bar items
  src/renderer/components/status-bar/status-bar.module.scss
Labels: enhancement, area/ui

#5585 Fix parsing memory metrics expecting wrong unit suffix
  src/common/utils/__tests__/convert-memory.test.ts
  src/common/utils/convertMemory.ts
Labels: bug
