Repository lensapp/lens, pull requests merged in 2023-01, with the labels that each got.

#6856 Update slack links to a static redirect url
  README.md
  src/common/vars.ts
  src/features/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  src/features/__snapshots__/navigate-to-extension-page.test.tsx.snap
  src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  src/features/application-update/__snapshots__/installing-update.test.ts.snap
  src/features/application-update/child-features/application-update-using-top-bar/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  src/features/application-update/child-features/application-update-using-tray/__snapshots__/installing-update-using-tray.test.ts.snap
  src/features/application-update/child-features/force-user-to-update-when-too-long-time-since-update-was-downloaded/__snapshots__/force-user-to-update-when-too-long-time-since-update-was-downloaded.test.ts.snap
  src/features/application-update/child-features/periodical-checking-of-updates/__snapshots__/periodical-checking-of-updates.test.ts.snap
  src/features/application-update/child-features/selection-of-update-stability/__snapshots__/selection-of-update-stability.test.ts.snap
  src/features/catalog/__snapshots__/opening-entity-details.test.tsx.snap
  src/features/command-pallet/__snapshots__/keyboard-shortcuts.test.tsx.snap
  src/features/entity-settings/__snapshots__/showing-settings-for-correct-entity.test.tsx.snap
  src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/features/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  src/features/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  src/features/status-bar/__snapshots__/status-bar-items-originating-from-extensions.test.tsx.snap
  src/features/top-bar/extension-api/__snapshots__/extendability-using-extension-api.test.tsx.snap
  src/features/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
Labels: chore

#6864 Update yarn lock
  yarn.lock
Labels: chore

#6868 Add Restart Button to StatefulSet Menu
  src/common/k8s-api/endpoints/stateful-set.api.ts
  src/renderer/components/+workloads-statefulsets/statefulset-menu.tsx
  src/renderer/components/kube-object-menu/kube-object-menu-items/statefulset-menu.injectable.ts
Labels: enhancement

#6863 Fix removePath functionality to also include directories
  src/common/fs/remove.injectable.ts
Labels: bug

#6851 Lens proxy with TLS
  integration/helpers/utils.ts
  package.json
  src/common/certificate/lens-proxy-certificate-channel.ts
  src/common/certificate/lens-proxy-certificate.global-override-for-injectable.ts
  src/common/certificate/lens-proxy-certificate.injectable.ts
  src/common/k8s-api/create-json-api.injectable.ts
  src/common/k8s-api/create-kube-api-for-cluster.injectable.ts
  src/common/k8s-api/create-kube-json-api.injectable.ts
  src/common/k8s-api/kube-api-parse.ts
  src/common/utils/__tests__/cluster-id-url-parsing.test.ts
  src/common/utils/app-version.ts
  src/common/utils/channel/get-request-channel.ts
  src/common/utils/cluster-id-url-parsing.ts
  src/common/utils/index.ts
  src/features/quitting-and-restarting-the-app/opening-application-window-using-tray.test.ts
  src/main/__test__/kubeconfig-manager.test.ts
  src/main/electron-app/electron-app.global-override-for-injectable.ts
  src/main/k8s-request.injectable.ts
  src/main/k8s/api-base-server-address.injectable.ts
  src/main/kubeconfig-manager/create-kubeconfig-manager.injectable.ts
  src/main/kubeconfig-manager/kubeconfig-manager.ts
  src/main/lens-proxy/lens-proxy-certificate-request-handler.injectable.ts
  src/main/lens-proxy/lens-proxy.injectable.ts
  src/main/lens-proxy/lens-proxy.ts
  src/main/routes/files/development.injectable.ts
  src/main/start-main-application/lens-window/application-window/create-application-window.injectable.ts
  src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts
  src/main/start-main-application/runnables/setup-hostnames.injectable.ts
  src/main/start-main-application/runnables/setup-lens-proxy-certificate.injectable.ts
  src/main/start-main-application/runnables/setup-lens-proxy.injectable.ts
  src/renderer/before-frame-starts/runnables/setup-lens-proxy-certificate.injectable.ts
  src/renderer/certificate/request-lens-proxy-certificate.injectable.ts
  src/renderer/components/+namespaces/namespace-select-filter.test.tsx
  src/renderer/k8s/api-base-server-address.injectable.ts
  src/renderer/k8s/api-kube.injectable.ts
Labels: enhancement, area/security

#6881 Add build-impl make target to skip install node_modules again
  Makefile
Labels: chore

#6882 Remove need to download node_modules twice in build-impl
  Makefile
Labels: chore

#6883 Allow adding additional webpack externals at build time
  webpack/main.ts
  webpack/renderer.ts
  webpack/vars.ts
Labels: chore

#6884 Cleanup compile:node-fetch script decl
  package.json
Labels: chore

#6893 Fix app crash when sometimes using MonacoEditor
  src/renderer/components/monaco-editor/monaco-editor.tsx
Labels: bug

#6904 Computed appMenus option
  src/extensions/common-api/registrations.ts
  src/extensions/lens-main-extension.ts
  src/features/application-menu/main/application-menu-item-registrator.injectable.ts
  src/features/application-menu/main/menu-registration.ts
Labels: enhancement, area/extension

#6906 Bump Horizontal Pod Autoscaler apiBase version
  src/common/k8s-api/endpoints/horizontal-pod-autoscaler.api.ts
Labels: enhancement, area/kubernetes-next

#6900 Fix shouldShowResource when not a cluster admin
  src/common/front-end-routing/routes/cluster/config/config-maps/config-maps-route.injectable.ts
  src/common/front-end-routing/routes/cluster/config/limit-ranges/limit-ranges-route.injectable.ts
  src/common/front-end-routing/routes/cluster/config/resource-quotas/resource-quotas-route.injectable.ts
  src/common/front-end-routing/routes/cluster/config/secrets/secrets-route.injectable.ts
  src/common/front-end-routing/routes/cluster/events/events-route.injectable.ts
  src/common/front-end-routing/routes/cluster/namespaces/namespaces-route.injectable.ts
  src/common/front-end-routing/routes/cluster/network/endpoints/endpoints-route.injectable.ts
  src/common/front-end-routing/routes/cluster/network/services/services-route.injectable.ts
  src/common/front-end-routing/routes/cluster/nodes/nodes-route.injectable.ts
  src/common/front-end-routing/routes/cluster/overview/cluster-overview-route.injectable.ts
  src/common/front-end-routing/routes/cluster/storage/persistent-volume-claims/persistent-volume-claims-route.injectable.ts
  src/common/front-end-routing/routes/cluster/storage/persistent-volumes/persistent-volumes-route.injectable.ts
  src/common/front-end-routing/routes/cluster/user-management/service-accounts/service-accounts-route.injectable.ts
  src/common/front-end-routing/routes/cluster/workloads/pods/pods-route.injectable.ts
  src/common/rbac.ts
  src/features/cluster/namespaces/edit-namespace-from-new-tab.test.tsx
  src/features/cluster/namespaces/edit-namespace-from-previously-opened-tab.test.tsx
  src/features/cluster/visibility-of-sidebar-items.test.tsx
  src/features/cluster/workload-overview.test.tsx
  src/main/cluster/request-core-api-versions.injectable.ts
  src/renderer/components/+workloads-overview/workloads/implementations/pods-workload.injectable.ts
  src/renderer/frames/cluster-frame/cluster-frame.test.tsx
  src/renderer/initializers/workload-events.tsx
Labels: bug

#6867 Remove kludge from KubeApi
  src/common/k8s-api/__tests__/kube-api-version-detection.test.ts
  src/common/k8s-api/api-manager/api-manager.ts
  src/common/k8s-api/api-manager/kube-object-store-token.ts
  src/common/k8s-api/api-manager/manager.injectable.ts
  src/common/k8s-api/kube-api.ts
  src/common/utils/__tests__/iter.test.ts
  src/common/utils/iter.ts
  src/extensions/common-api/k8s-api.ts
  src/features/cluster/kube-object-details/extension-api/reactively-hide-kube-object-detail-item.test.tsx
  src/renderer/components/+cluster/cluster-overview-store/cluster-overview-store.injectable.ts
  src/renderer/components/+config-autoscalers/store.injectable.ts
  src/renderer/components/+config-leases/store.injectable.ts
  src/renderer/components/+config-limit-ranges/store.injectable.ts
  src/renderer/components/+config-maps/store.injectable.ts
  src/renderer/components/+config-pod-disruption-budgets/store.injectable.ts
  src/renderer/components/+config-priority-classes/store.injectable.ts
  src/renderer/components/+config-resource-quotas/store.injectable.ts
  src/renderer/components/+config-runtime-classes/store.injectable.ts
  src/renderer/components/+config-secrets/store.injectable.ts
  src/renderer/components/+custom-resources/definition.store.injectable.ts
  src/renderer/components/+events/store.injectable.ts
  src/renderer/components/+namespaces/store.injectable.ts
  src/renderer/components/+network-endpoints/store.injectable.ts
  src/renderer/components/+network-ingresses/ingress-class-store.injectable.ts
  src/renderer/components/+network-ingresses/ingress-store.injectable.ts
  src/renderer/components/+network-policies/store.injectable.ts
  src/renderer/components/+network-services/store.injectable.ts
  src/renderer/components/+nodes/store.injectable.ts
  src/renderer/components/+pod-security-policies/store.injectable.ts
  src/renderer/components/+storage-classes/store.injectable.ts
  src/renderer/components/+storage-volume-claims/store.injectable.ts
  src/renderer/components/+storage-volumes/store.injectable.ts
  src/renderer/components/+user-management/+cluster-role-bindings/store.injectable.ts
  src/renderer/components/+user-management/+cluster-roles/store.injectable.ts
  src/renderer/components/+user-management/+role-bindings/store.injectable.ts
  src/renderer/components/+user-management/+roles/store.injectable.ts
  src/renderer/components/+user-management/+service-accounts/store.injectable.ts
  src/renderer/components/+workloads-cronjobs/store.injectable.ts
  src/renderer/components/+workloads-daemonsets/store.injectable.ts
  src/renderer/components/+workloads-deployments/store.injectable.ts
  src/renderer/components/+workloads-jobs/store.injectable.ts
  src/renderer/components/+workloads-pods/store.injectable.ts
  src/renderer/components/+workloads-replicasets/store.injectable.ts
  src/renderer/components/+workloads-statefulsets/store.injectable.ts
Labels: chore

#6909 Release 6.4.0-alpha.1
  package.json
Labels: skip-changelog, release

#6915 Fix publish-npm workflow invocations
  Makefile
Labels: area/ci

#6916 Fix bump-master-version worklow
  .github/workflows/bump-master-version.yaml
Labels: area/ci

#6918 Release 6.4.0-alpha.2
  package.json
Labels: skip-changelog, release

#6919 Fix the output when skipping creating PR
  .github/workflows/bump-master-version.yaml
Labels: area/ci

#6921 Change some ClusterManager logs debug->silly
  src/main/cluster/manager.ts
Labels: chore

#6927 Fix workflows
  .github/workflows/bump-master-version.yaml
  .github/workflows/release.yml
Labels: area/ci

#6926 Allow specifying ResourceName in KubeObjectListLayout
  src/renderer/components/kube-object-list-layout/__snapshots__/kube-object-list-layout.test.tsx.snap
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.test.tsx
  src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
Labels: enhancement

#6913 Better handling loading terminal fonts
  src/features/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  src/features/preferences/renderer/preference-items/terminal/terminal-font-family/terminal-font-family.tsx
  src/renderer/components/app.scss
  src/renderer/components/dock/terminal/create-terminal.injectable.ts
  src/renderer/components/dock/terminal/terminal-fonts.global-override-for-injectable.ts
  src/renderer/components/dock/terminal/terminal-fonts.injectable.ts
  src/renderer/components/fonts.scss
  src/renderer/template.html
Labels: bug

#6935 Release 6.4.0-alpha.3
  package.json
Labels: skip-changelog, release

#6946 Fix Notifications extension API
  src/extensions/renderer-api/components.ts
Labels: bug, area/extension

#6938 Fix not being able to add new Kubeconfig syncs
  src/renderer/before-frame-starts/runnables/setup-kubernetes-cluster-catalog-add-menu.injectable.ts
  src/renderer/initializers/add-sync-entries.injectable.tsx
Labels: bug, p0, area/kubeconfig-sync

#6947 Fix extension API
  src/extensions/common-api/k8s-api.ts
Labels: bug, area/extension

#6950 Introduce ipcMainInjectionToken
  src/common/ipc/ipc-main-injection-token.ts
  src/common/ipc/ipc.ts
  src/main/catalog-sync-to-renderer/catalog-sync-to-renderer.injectable.ts
  src/main/start-main-application/lens-window/application-window/wait-until-bundled-extensions-are-loaded.injectable.ts
  src/main/utils/channel/channel-listeners/enlist-message-channel-listener.injectable.ts
  src/main/utils/channel/channel-listeners/enlist-request-channel-listener.injectable.ts
  src/main/utils/channel/ipc-main/ipc-main.injectable.ts
Labels: chore

#6937 Cleanup loading terminal fonts
  src/features/preferences/renderer/preference-items/terminal/terminal-font-family/terminal-font-family.tsx
  src/features/preferences/renderer/preference-items/terminal/terminal-font-family/terminal-font-options.injectable.tsx
  src/features/terminal/renderer/fonts/AnonymousPro-Regular.ttf
  src/features/terminal/renderer/fonts/IBMPlexMono-Regular.ttf
  src/features/terminal/renderer/fonts/JetBrainsMono-Regular.ttf
  src/features/terminal/renderer/fonts/RedHatMono-Regular.ttf
  src/features/terminal/renderer/fonts/Roboto-Mono.ttf
  src/features/terminal/renderer/fonts/SourceCodePro-Regular.ttf
  src/features/terminal/renderer/fonts/SpaceMono-Regular.ttf
  src/features/terminal/renderer/fonts/UbuntuMono-Regular.ttf
  src/features/terminal/renderer/fonts/anonymous-pro.injectable.ts
  src/features/terminal/renderer/fonts/fonts.injectable.ts
  src/features/terminal/renderer/fonts/ibm-plex-mono.injectable.ts
  src/features/terminal/renderer/fonts/jetbrains-mono.injectable.ts
  src/features/terminal/renderer/fonts/load-font.global-override-for-injectable.ts
  src/features/terminal/renderer/fonts/load-font.injectable.ts
  src/features/terminal/renderer/fonts/preload-fonts.injectable.ts
  src/features/terminal/renderer/fonts/red-hat-mono.injectable.ts
  src/features/terminal/renderer/fonts/roboto-mono.injectable.ts
  src/features/terminal/renderer/fonts/source-code-pro.injectable.ts
  src/features/terminal/renderer/fonts/space-mono.injectable.ts
  src/features/terminal/renderer/fonts/token.ts
  src/features/terminal/renderer/fonts/ubuntu-mono.injectable.ts
  src/renderer/components/dock/terminal/terminal-fonts.injectable.ts
  types/mocks.d.ts
Labels: chore, area/terminal

#6952 Delay removing iframe to fix renderer crash
  src/renderer/components/cluster-manager/cluster-frame-handler.ts
Labels: bug, blocker

#6965 Update lockfile
  package.json
  yarn.lock
Labels: dependencies

#6963 Publish to the correct channels instead of always latest
  .github/workflows/release.yml
  Makefile
  scripts/publish-extensions-npm.sh
  scripts/publish-library-npm.sh
Labels: chore

#6973 Fix KubeJsonApi.forCluster as part of extension API
  src/extensions/common-api/k8s-api.ts
Labels: bug, area/extension

#6972 Finish using NamespaceSelectBadge in all places
  src/renderer/components/+config-autoscalers/hpa.tsx
  src/renderer/components/+config-limit-ranges/limit-ranges.tsx
  src/renderer/components/+custom-resources/crd-resources.scss
  src/renderer/components/+custom-resources/crd-resources.tsx
  src/renderer/components/+events/events.tsx
  src/renderer/components/+storage-volume-claims/volume-claims.tsx
Labels: enhancement

#6978 Add KubeEventDetails empty placeholder
  src/features/cluster/kube-object-details/extension-api/__snapshots__/disable-kube-object-detail-items-when-cluster-is-not-relevant.test.tsx.snap
  src/features/cluster/kube-object-details/extension-api/__snapshots__/reactively-hide-kube-object-detail-item.test.tsx.snap
  src/renderer/components/+events/kube-event-details.module.scss
  src/renderer/components/+events/kube-event-details.tsx
Labels: enhancement, area/ui

#6981 Fix KubeObjectDetails light theme table view
  src/renderer/components/+events/event-details.tsx
  src/renderer/components/+network-ingresses/ingress-details.tsx
  src/renderer/components/+network-services/service-details-endpoint.tsx
  src/renderer/components/+nodes/details-resources.tsx
  src/renderer/components/+workloads-deployments/deployment-replicasets.tsx
  src/renderer/components/+workloads-pods/pod-details-list.tsx
  src/renderer/components/drawer/drawer.scss
  src/renderer/components/table/table-head.scss
  src/renderer/components/table/table-head.tsx
Labels: bug, area/ui

#6974 Fix extension API version being specified by library user
  src/common/vars/extension-api-version.global-override-for-injectable.ts
  src/common/vars/extension-api-version.injectable.ts
Labels: bug, area/extension, blocker

#6975 Release 6.4.0-alpha.4
  package.json
Labels: skip-changelog, release

#6964 Broadcast error messages within Cluster.getConnectionStatus
  src/common/cluster/cluster.ts
Labels: chore

#6976 Upgrade to codeql@v2
  .github/workflows/codeql-analysis.yml
Labels: area/ci

#6910 Improve the injectability of cluster metadata detection
  src/common/cluster/cluster.ts
  src/common/utils/type-narrowing.ts
  src/main/cluster-detectors/base-cluster-detector.ts
  src/main/cluster-detectors/cluster-distribution-detector.injectable.ts
  src/main/cluster-detectors/cluster-id-detector.injectable.ts
  src/main/cluster-detectors/cluster-id-detector.ts
  src/main/cluster-detectors/cluster-last-seen-detector.injectable.ts
  src/main/cluster-detectors/cluster-nodes-count-detector.injectable.ts
  src/main/cluster-detectors/cluster-version-detector.injectable.ts
  src/main/cluster-detectors/create-version-detector.injectable.ts
  src/main/cluster-detectors/detect-cluster-metadata.injectable.ts
  src/main/cluster-detectors/detector-registry.injectable.ts
  src/main/cluster-detectors/detector-registry.ts
  src/main/cluster-detectors/distribution-detector.ts
  src/main/cluster-detectors/last-seen-detector.ts
  src/main/cluster-detectors/nodes-count-detector.ts
  src/main/cluster-detectors/request-cluster-version.injectable.ts
  src/main/cluster-detectors/token.ts
  src/main/cluster-detectors/version-detector.ts
  src/main/create-cluster/create-cluster.injectable.ts
  src/main/start-main-application/runnables/setup-detector-registry.injectable.ts
  src/renderer/cluster/create-cluster.injectable.ts
Labels: chore

#6984 Do not show Created on DetailsPane when there's no timestamp.
  src/features/cluster/kube-object-details/extension-api/__snapshots__/disable-kube-object-detail-items-when-cluster-is-not-relevant.test.tsx.snap
  src/features/cluster/kube-object-details/extension-api/__snapshots__/reactively-hide-kube-object-detail-item.test.tsx.snap
  src/renderer/components/kube-object-meta/kube-object-meta.tsx
Labels: bug

#6990 Export type-space versions of constructors to fix extension API
  src/extensions/common-api/k8s-api.ts
Labels: bug, area/extension

#6971 Parse HPA metrics from different versions
  src/common/k8s-api/endpoints/horizontal-pod-autoscaler.api.ts
  src/renderer/components/+config-autoscalers/get-hpa-metric-name.ts
  src/renderer/components/+config-autoscalers/get-hpa-metrics.injectable.ts
  src/renderer/components/+config-autoscalers/horizontal-pod-autoscaler-metrics.test.ts
  src/renderer/components/+config-autoscalers/hpa-details.scss
  src/renderer/components/+config-autoscalers/hpa-details.tsx
  src/renderer/components/+config-autoscalers/hpa-v1-metric-parser.ts
  src/renderer/components/+config-autoscalers/hpa-v2-metric-parser.ts
  src/renderer/components/+config-autoscalers/hpa.tsx
  src/renderer/components/kube-object-details/kube-object-detail-items/implementations/horizontal-pod-autoscaler-detail-item.injectable.ts
Labels: bug

#7003 Change renderer attempting to load CAs to go through main
  src/features/certificate-authorities/common/channel.ts
  src/features/certificate-authorities/common/inject-system-cas.injectable.ts
  src/features/certificate-authorities/common/request-system-cas-token.ts
  src/features/certificate-authorities/main/channel-handler.global-override-for-injectable.ts
  src/features/certificate-authorities/main/channel-handler.injectable.ts
  src/features/certificate-authorities/main/request-system-cas.injectable.darwin.ts
  src/features/certificate-authorities/main/request-system-cas.injectable.linux.ts
  src/features/certificate-authorities/main/request-system-cas.injectable.testing-env.ts
  src/features/certificate-authorities/main/request-system-cas.injectable.win32.ts
  src/features/certificate-authorities/renderer/request-system-cas.injectable.ts
  src/main/start-main-application/runnables/setup-system-ca.injectable.ts
  src/renderer/frames/root-frame/setup-system-ca.injectable.ts
Labels: bug

#7005 Remove deleted make target invocation
  .github/workflows/test.yml
  Makefile
Labels: chore

#7010 Add --skip-nx-cache to lerna run dev command
  package.json
Labels: chore

#7007 Fix core package name and version
  lerna.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/extension-api/src/extension-api.ts
  packages/extension-api/webpack/extensions.ts
  packages/open-lens/package.json
  packages/open-lens/src/common/application-information.injectable.ts
  packages/open-lens/src/main/index.ts
  packages/open-lens/src/renderer/index.ts
  packages/open-lens/webpack/vars.ts
  packages/release-tool/package.json
Labels: chore

#6908 Add ability for KubeApi to filter server versions
  packages/core/src/common/k8s-api/__tests__/kube-api-version-detection.test.ts
  packages/core/src/common/k8s-api/endpoints/horizontal-pod-autoscaler.api.ts
  packages/core/src/common/k8s-api/kube-api.ts
Labels: enhancement

#6988 Bump bundled helm to v3.11.0
  packages/core/package.json
Labels: bug, area/helm

#7009 Move node-fetch to separate package
  nx.json
  packages/core/build/download_binaries.ts
  packages/core/package.json
  packages/core/src/common/fetch/download-binary.injectable.ts
  packages/core/src/common/fetch/download-json/impl.ts
  packages/core/src/common/fetch/fetch-module.injectable.ts
  packages/core/src/common/fetch/fetch.injectable.ts
  packages/core/src/common/fetch/lens-fetch.injectable.ts
  packages/core/src/common/k8s-api/create-json-api.injectable.ts
  packages/core/src/common/k8s-api/create-kube-api-for-remote-cluster.injectable.ts
  packages/core/src/common/k8s-api/create-kube-json-api.injectable.ts
  packages/core/src/common/k8s-api/json-api.ts
  packages/core/src/common/k8s-api/kube-api.ts
  packages/core/src/common/k8s-api/kube-json-api.ts
  packages/core/src/common/k8s-api/kube-object.store.ts
  packages/core/src/extensions/common-api/k8s-api.ts
  packages/core/src/main/get-metrics.injectable.ts
  packages/core/src/test-utils/mock-responses.ts
  packages/core/webpack/renderer.ts
  packages/core/yarn.lock
  packages/node-fetch/.gitignore
  packages/node-fetch/package.json
  packages/node-fetch/src/index.ts
  packages/node-fetch/tsconfig.json
  packages/node-fetch/webpack.ts
  packages/node-fetch/yarn.lock
  packages/open-lens/build/download_binaries.ts
  packages/open-lens/package.json
  packages/open-lens/webpack/renderer.ts
  packages/open-lens/yarn.lock
Labels: chore

#6995 Add more resiliancy to listing kube API resource kinds
  packages/core/src/common/cluster-types.ts
  packages/core/src/common/cluster/cluster.ts
  packages/core/src/common/utils/backoff-caller.ts
  packages/core/src/main/__test__/kube-auth-proxy.test.ts
  packages/core/src/main/cluster/request-api-resources.injectable.ts
  packages/core/src/main/cluster/request-api-versions.ts
  packages/core/src/main/cluster/request-core-api-versions.injectable.ts
  packages/core/src/main/cluster/request-kube-api-resources-for.injectable.ts
  packages/core/src/main/cluster/request-non-core-api-versions.injectable.ts
  packages/core/src/main/kube-auth-proxy/kube-auth-proxy.ts
  packages/core/src/renderer/components/cluster-manager/cluster-status.tsx
Labels: bug

#7000 Fix monaco editor scroll block in config map details
  packages/core/src/renderer/components/+config-maps/config-map-details.tsx
Labels: bug, area/ui

#7013 Fix building docs and verify:docs workflow
  .github/workflows/check-docs.yml
  nx.json
  packages/core/src/common/base-store/base-store.ts
  packages/core/src/common/catalog-entities/general.ts
  packages/core/src/common/catalog/catalog-entity.ts
  packages/core/src/common/event-emitter.ts
  packages/core/src/extensions/common-api/app.ts
  packages/core/src/extensions/common-api/catalog.ts
  packages/core/src/extensions/common-api/event-bus.ts
  packages/core/src/extensions/common-api/index.ts
  packages/core/src/extensions/common-api/stores.ts
  packages/core/src/extensions/common-api/user-preferences.ts
  packages/core/src/extensions/common-api/utils.ts
  packages/core/src/extensions/lens-extension.ts
  packages/core/src/main/extension-api.ts
  packages/core/src/main/library.ts
  packages/core/src/renderer/extension-api.ts
  packages/extension-api/package.json
  packages/extension-api/src/extension-api.ts
  packages/extension-api/typedoc.json
Labels: area/documentation

#7014 Release 6.4.0-beta.0
  lerna.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: skip-changelog, release

#7018 Specify custom root to @k8slens/core package directory
  .github/workflows/release.yml
Labels: area/ci

#7019 Release 6.4.0-beta.1
  lerna.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
Labels: skip-changelog, release

#7020 Revert remove GITHUB_TOKEN from release workflow
  .github/workflows/release.yml
Labels: area/ci

#7022 Make sure auth token for NPM registry is set
  .github/workflows/publish-master-npm.yml
  .github/workflows/publish-release-npm.yml
Labels: area/ci

#7023 Release 6.4.0-beta.3
  lerna.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
Labels: skip-changelog, release

#7024 Fix publishing @k8slens/node-fetch
  .yarnrc
  packages/node-fetch/README.md
Labels: area/ci

#7025 Release 6.4.0-beta.4
  lerna.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
Labels: skip-changelog, release

#7026 Mark all packages as public
  packages/core/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
Labels: area/ci

#7027 Release 6.4.0-beta.5
  lerna.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
Labels: skip-changelog, release

#7028 Fix dist tags being wrong
  .github/workflows/publish-release-npm.yml
  packages/semver/.gitignore
  packages/semver/package.json
  packages/semver/src/index.ts
  packages/semver/tsconfig.json
  packages/semver/yarn.lock
  scripts/publish-extensions-npm.sh
  scripts/publish-library-npm.sh
Labels: area/ci

#7031 Release 6.4.0-beta.6
  lerna.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
Labels: skip-changelog, release

#7033 Move downloading binaries to new package
  packages/core/build/download_binaries.ts
  packages/core/package.json
  packages/core/yarn.lock
  packages/download-binaries/.gitignore
  packages/download-binaries/package.json
  packages/download-binaries/src/index.ts
  packages/download-binaries/tsconfig.json
  packages/download-binaries/yarn.lock
  packages/open-lens/package.json
  packages/open-lens/yarn.lock
  packages/semver/package.json
  tsconfig.json
Labels: chore

#7037 Fix missing core styles in dev mode
  packages/core/webpack/dev-server.ts
  packages/core/webpack/renderer.ts
Labels: chore

#7038 Release 6.4.0-beta.7
  lerna.json
  packages/core/package.json
  packages/download-binaries/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
Labels: skip-changelog, release

#7039 Mark @k8slens/download-binaries as public access
  packages/download-binaries/package.json
Labels: area/ci

#7040 Release 6.4.0-beta.8
  lerna.json
  packages/core/package.json
  packages/download-binaries/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
Labels: skip-changelog, release

#7041 Rename package due to https://github.com/npm/cli/issues/2248
  packages/ensure-binaries/.gitignore
  packages/ensure-binaries/package.json
  packages/ensure-binaries/src/index.ts
  packages/ensure-binaries/tsconfig.json
  packages/ensure-binaries/yarn.lock
  packages/open-lens/package.json
Labels: chore

#7042 Release 6.4.0-beta.9
  lerna.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
Labels: skip-changelog, release

#7045 Release 6.4.0-beta.10
  lerna.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
Labels: skip-changelog, release

#7053 Allow computed catalog source from extension
  packages/core/src/extensions/lens-main-extension.ts
Labels: enhancement, area/extension

#7054 Fix dev not working due to ensure-binaries
  packages/ensure-binaries/package.json
Labels: chore

#7058 Fix @k8slens/extensions being broken after monorepo
  packages/core/src/common/front-end-routing/routes/welcome/welcome-route-config.injectable.ts
  packages/core/src/common/library.ts
  packages/core/src/common/vars/application-copyright.injectable.ts
  packages/core/src/common/vars/application-description.injectable.ts
  packages/core/src/common/vars/application-information-injectable.ts
  packages/core/src/common/vars/application-information-token.ts
  packages/core/src/common/vars/bundled-kubectl-version.injectable.ts
  packages/core/src/common/vars/content-security-policy.injectable.ts
  packages/core/src/common/vars/product-name.injectable.ts
  packages/core/src/common/vars/sentry-dsn-url.injectable.ts
  packages/core/src/common/vars/store-migration-version.injectable.ts
  packages/core/src/extensions/main-api/index.ts
  packages/core/src/features/application-update/main/updating-is-enabled/publish-is-configured/publish-is-configured.injectable.ts
  packages/core/src/main/cluster/store-migrations/snap.injectable.ts
  packages/core/src/main/extension-api.ts
  packages/core/src/main/index.ts
  packages/core/src/main/library.ts
  packages/core/src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts
  packages/core/src/main/weblinks-store/migrations/currentVersion.injectable.ts
  packages/core/src/renderer/extension-api.ts
  packages/core/src/renderer/index.ts
  packages/core/src/renderer/library.ts
  packages/core/yarn.lock
  packages/extension-api/package.json
  packages/extension-api/src/extension-api.ts
  packages/open-lens/src/main/index.ts
  packages/open-lens/src/renderer/index.ts
  packages/open-lens/yarn.lock
Labels: bug, area/extension

#7066 Rename extension api parts as 'extensionApi'
  packages/core/src/common/library.ts
  packages/core/src/main/library.ts
  packages/core/src/renderer/library.ts
  packages/extension-api/src/extension-api.ts
  packages/open-lens/src/main/index.ts
  packages/open-lens/src/renderer/index.ts
Labels: chore, area/extension

#7069 Set cwd when spawning kube auth proxy
  packages/core/src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts
  packages/core/src/main/kube-auth-proxy/kube-auth-proxy.ts
Labels: enhancement
