Repository lensapp/lens, pull requests merged in 2023-03, with the labels that each got.

#7248 Make builds of TS-declarations more deterministic in multi-export packages
  package-lock.json
  packages/infrastructure/webpack/package.json
  packages/infrastructure/webpack/src/__snapshots__/get-multi-export-config.test.js.snap
  packages/infrastructure/webpack/src/get-multi-export-config.js
  packages/infrastructure/webpack/src/get-multi-export-config.test.js
  packages/infrastructure/webpack/src/get-node-config.js
  packages/infrastructure/webpack/src/get-react-config.js
  packages/infrastructure/webpack/src/node-config.js
  packages/infrastructure/webpack/src/react-config.js
Labels: chore

#7247 Fix extension install
  packages/core/src/common/fs/fs.injectable.ts
  packages/core/src/extensions/extension-discovery/extension-discovery.injectable.ts
  packages/core/src/extensions/extension-discovery/extension-discovery.test.ts
  packages/core/src/extensions/extension-installer/extension-installer.injectable.ts
  packages/core/src/extensions/extension-installer/extension-installer.ts
  packages/core/src/extensions/extension-installer/install-extension/install-extension.injectable.ts
  packages/core/src/extensions/install-extension/extension-package-root-directory.injectable.ts
  packages/core/src/extensions/install-extension/install-extension.injectable.ts
Labels: bug

#7250 Release 6.4.0
  lerna.json
  packages/core/package.json
  packages/core/src/common/__tests__/create-resource-stack.test.ts
  packages/core/src/common/fs/fs.injectable.ts
  packages/core/src/common/k8s/resource-stack.ts
  packages/core/src/common/logger.injectable.ts
  packages/core/src/common/vars/store-migration-version.injectable.ts
  packages/core/src/common/winston-logger.injectable.ts
  packages/core/src/extensions/extension-discovery/extension-discovery.injectable.ts
  packages/core/src/extensions/extension-discovery/extension-discovery.test.ts
  packages/core/src/extensions/extension-installer/extension-installer.injectable.ts
  packages/core/src/extensions/extension-installer/extension-installer.ts
  packages/core/src/extensions/extension-installer/install-extension/install-extension.injectable.ts
  packages/core/src/extensions/install-extension/extension-package-root-directory.injectable.ts
  packages/core/src/extensions/install-extension/install-extension.injectable.ts
  packages/core/src/renderer/bootstrap.tsx
  packages/core/src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.injectable.ts
  packages/core/src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
  packages/core/src/renderer/frames/root-frame/init-root-frame.injectable.ts
  packages/core/src/renderer/logger/close-renderer-log-file.injectable.ts
  packages/core/src/renderer/logger/file-transport.injectable.ts
  packages/extension-api/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: skip-changelog, release

#7251 Cleanup getDi and registering injectables
  packages/core/src/common/catalog-entities/web-link.ts
  packages/core/src/common/create-app.ts
  packages/core/src/common/vars/application-information-fake.injectable.testing-env.ts
  packages/core/src/common/vars/node-env.injectable.testing-env.ts
  packages/core/src/extensions/as-legacy-globals-for-extension-api/as-legacy-global-object-for-extension-api-with-modifications.test.ts
  packages/core/src/extensions/as-legacy-globals-for-extension-api/legacy-global-di-for-extension-api.ts
  packages/core/src/extensions/main-api/navigation.ts
  packages/core/src/main/create-app.ts
  packages/core/src/main/getDi.ts
  packages/core/src/main/getDiForUnitTesting.ts
  packages/core/src/main/library.ts
  packages/core/src/main/register-injectables.ts
  packages/core/src/renderer/create-app.ts
  packages/core/src/renderer/getDi.tsx
  packages/core/src/renderer/getDiForUnitTesting.tsx
  packages/core/src/renderer/library.ts
  packages/core/src/renderer/register-injectables.ts
  packages/open-lens/src/main/index.ts
  packages/open-lens/src/renderer/index.ts
Labels: chore, area/extension

#7254 For unit test workflow to only start on linux
  .github/workflows/test.yml
Labels: area/ci

#7255 Fix cluster metadata detectors
  packages/core/src/main/cluster-detectors/detect-cluster-metadata.injectable.ts
  packages/core/src/main/cluster-detectors/detect-cluster-metadata.test.ts
Labels: bug

#7257 Add displaying @k8slens/* versions in about when not latest
  packages/core/src/common/vars/application-information-fake.injectable.testing-env.ts
  packages/core/src/features/application-menu/main/menu-items/special-menu-for-mac-application/show-about-application/about-bundled-extensions.injectable.ts
  packages/core/src/features/application-menu/main/menu-items/special-menu-for-mac-application/show-about-application/show-about.injectable.ts
  packages/core/src/main/electron-app/features/show-message-popup.injectable.ts
  packages/open-lens/src/common/application-information.injectable.ts
  packages/technical-features/application/src/application-information-token.ts
Labels: enhancement

#7253 Bump versions to 6.5.0-alpha.0
  lerna.json
  package-lock.json
  packages/bump-version-for-cron/package.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/infrastructure/jest/package.json
  packages/infrastructure/typescript/package.json
  packages/infrastructure/webpack/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
  packages/technical-features/application/package.json
  packages/technical-features/feature-core/package.json
Labels: chore

#7274 UI should show resource if cluster is missing allowedResources data
  packages/core/src/common/cluster/cluster.ts
Labels: bug, blocker

#7263 Fix extension API not having all the correct types
  package-lock.json
  packages/extension-api/package.json
Labels: bug, area/extension

#7276 Update release guide and fix release script
  RELEASE_GUIDE.md
  packages/release-tool/src/index.ts
Labels: chore

#7259 Extract agnostic and electron-main ways of starting application to separate packages
  package-lock.json
  packages/core/package.json
  packages/open-lens/package.json
  packages/technical-features/application/README.md
  packages/technical-features/application/agnostic/README.md
  packages/technical-features/application/agnostic/index.ts
  packages/technical-features/application/agnostic/jest.config.js
  packages/technical-features/application/agnostic/package.json
  packages/technical-features/application/agnostic/src/application-information-token.ts
  packages/technical-features/application/agnostic/src/feature.ts
  packages/technical-features/application/agnostic/src/start-application/start-application.injectable.ts
  packages/technical-features/application/agnostic/src/start-application/starting-of-application.test.ts
  packages/technical-features/application/agnostic/src/start-application/timeslots/after-application-is-loaded-injection-token.ts
  packages/technical-features/application/agnostic/src/start-application/timeslots/before-application-is-loading-injection-token.ts
  packages/technical-features/application/agnostic/src/start-application/timeslots/on-load-of-application-injection-token.ts
  packages/technical-features/application/agnostic/tsconfig.json
  packages/technical-features/application/agnostic/webpack.config.js
  packages/technical-features/application/electron-main/README.md
  packages/technical-features/application/electron-main/index.ts
  packages/technical-features/application/electron-main/jest.config.js
  packages/technical-features/application/electron-main/package.json
  packages/technical-features/application/electron-main/src/electron/electron-app.injectable.ts
  packages/technical-features/application/electron-main/src/electron/electron-app.test.ts
  packages/technical-features/application/electron-main/src/feature.ts
  packages/technical-features/application/electron-main/src/override-side-effects-with-fakes.ts
  packages/technical-features/application/electron-main/src/start-application/start-electron-application.injectable.ts
  packages/technical-features/application/electron-main/src/start-application/timeslots/before-anything-injection-token.ts
  packages/technical-features/application/electron-main/src/start-application/timeslots/before-electron-is-ready-injection-token.ts
  packages/technical-features/application/electron-main/src/start-application/when-app-is-ready.injectable.ts
  packages/technical-features/application/electron-main/src/start-application/when-app-is-ready/when-app-is-ready.test.ts
  packages/technical-features/application/electron-main/src/starting-of-electron-main-application.test.ts
  packages/technical-features/application/electron-main/tsconfig.json
  packages/technical-features/application/electron-main/webpack.config.js
  packages/technical-features/application/index.ts
  packages/technical-features/application/jest.config.js
Labels: chore

#7282 Fix request namespace list permissions check if a list rule is not the first match
  packages/core/src/common/cluster/request-namespace-list-permissions.injectable.ts
  packages/core/src/common/cluster/request-namespace-list-permissions.test.ts
Labels: bug, blocker, area/rbac

#7286 Release 6.4.2
  RELEASE_GUIDE.md
  lerna.json
  packages/core/package.json
  packages/core/src/main/cluster-detectors/detect-cluster-metadata.injectable.ts
  packages/core/src/main/cluster-detectors/detect-cluster-metadata.test.ts
  packages/extension-api/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: skip-changelog, release

#7287 Fix failing unit tests about overriding too late
  packages/core/src/features/telemetry/renderer/telemetry-decorator.injectable.ts
Labels: chore

#7288 Update package lock
  package-lock.json
Labels: chore

#7289 Port #7282 to master
  packages/core/src/common/cluster/request-namespace-list-permissions.injectable.ts
  packages/core/src/common/cluster/request-namespace-list-permissions.test.ts
Labels: bug

#7291 Add support for using release branch targetted PRs
  packages/release-tool/src/index.ts
Labels: chore

#7279 Fix namespaces not respecting accessible namespace config
  packages/core/src/common/cluster/cluster.ts
  packages/core/src/common/k8s-api/selected-filter-namespaces.injectable.ts
  packages/core/src/features/helm-charts/installing-chart/installing-helm-chart-from-new-tab.test.ts
  packages/core/src/features/helm-releases/showing-details-for-helm-release.test.ts
  packages/core/src/features/namespace-filtering/renderer/storage.injectable.ts
  packages/core/src/renderer/cluster-frame-context/for-namespaced-resources.injectable.ts
  packages/core/src/renderer/components/+helm-releases/releases.injectable.ts
  packages/core/src/renderer/components/+namespaces/__snapshots__/namespace-select-filter.test.tsx.snap
  packages/core/src/renderer/components/+namespaces/namespace-select-filter-model/namespace-select-filter-model.injectable.ts
  packages/core/src/renderer/components/+namespaces/namespace-select-filter-model/namespace-select-filter-model.tsx
  packages/core/src/renderer/components/+namespaces/namespace-select.tsx
  packages/core/src/renderer/components/+namespaces/store.injectable.ts
  packages/core/src/renderer/components/+namespaces/store.ts
  packages/core/src/renderer/components/+workloads-pods/load-pods-from-all-namespaces.injectable.ts
  packages/core/src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  packages/core/src/renderer/components/test-utils/get-application-builder.tsx
  packages/core/src/renderer/kube-watch-api/kube-watch-api.ts
Labels: bug, area/rbac

#7292 Release 6.4.3
  lerna.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
Labels: skip-changelog, release

#6939 Allow CatalogEntityDetails to be opened anywhere
  packages/core/src/common/catalog/category-registry.ts
  packages/core/src/extensions/renderer-api/navigation.ts
  packages/core/src/features/catalog/__snapshots__/entity-running.test.tsx.snap
  packages/core/src/features/catalog/__snapshots__/opening-entity-details.test.tsx.snap
  packages/core/src/features/catalog/entity-running.test.tsx
  packages/core/src/features/catalog/opening-entity-details.test.tsx
  packages/core/src/renderer/api/catalog/entity/get-by-id.injectable.ts
  packages/core/src/renderer/api/catalog/entity/registry.ts
  packages/core/src/renderer/components/+catalog/__tests__/catalog-entity-store.test.ts
  packages/core/src/renderer/components/+catalog/catalog-entity-store.injectable.ts
  packages/core/src/renderer/components/+catalog/catalog-entity-store/catalog-entity-store.injectable.ts
  packages/core/src/renderer/components/+catalog/catalog-entity-store/catalog-entity.store.tsx
  packages/core/src/renderer/components/+catalog/catalog.test.tsx
  packages/core/src/renderer/components/+catalog/catalog.tsx
  packages/core/src/renderer/components/+catalog/entity-details/component.injectable.tsx
  packages/core/src/renderer/components/+catalog/entity-details/hide.injectable.ts
  packages/core/src/renderer/components/+catalog/entity-details/on-catalog-click.injectable.ts
  packages/core/src/renderer/components/+catalog/entity-details/selected-entity.injectable.ts
  packages/core/src/renderer/components/+catalog/entity-details/selected-uid.injectable.ts
  packages/core/src/renderer/components/+catalog/entity-details/show.injectable.ts
Labels: enhancement

#7303 Fix not showing some non-core kinds
  packages/core/src/main/cluster/request-api-versions.ts
  packages/core/src/main/cluster/request-non-core-api-versions.injectable.ts
  packages/core/src/main/cluster/request-non-core-api-versions.test.ts
  packages/core/src/main/k8s-request.injectable.ts
Labels: bug

#7308 Release 6.4.4
  lerna.json
  packages/core/package.json
  packages/core/src/common/catalog-entities/kubernetes-cluster.ts
  packages/core/src/renderer/components/cluster-manager/cluster-view.tsx
  packages/extension-api/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release

#7309 Cherry pick PRs from 6.4.4 and 6.4.3
  packages/core/src/common/cluster/cluster.ts
  packages/core/src/common/k8s-api/selected-filter-namespaces.injectable.ts
  packages/core/src/features/helm-charts/installing-chart/installing-helm-chart-from-new-tab.test.ts
  packages/core/src/features/helm-releases/showing-details-for-helm-release.test.ts
  packages/core/src/features/namespace-filtering/renderer/storage.injectable.ts
  packages/core/src/main/cluster/request-api-versions.ts
  packages/core/src/main/cluster/request-non-core-api-versions.injectable.ts
  packages/core/src/main/cluster/request-non-core-api-versions.test.ts
  packages/core/src/main/k8s-request.injectable.ts
  packages/core/src/renderer/cluster-frame-context/for-namespaced-resources.injectable.ts
  packages/core/src/renderer/components/+helm-releases/releases.injectable.ts
  packages/core/src/renderer/components/+namespaces/__snapshots__/namespace-select-filter.test.tsx.snap
  packages/core/src/renderer/components/+namespaces/namespace-select-filter-model/namespace-select-filter-model.injectable.ts
  packages/core/src/renderer/components/+namespaces/namespace-select-filter-model/namespace-select-filter-model.tsx
  packages/core/src/renderer/components/+namespaces/namespace-select.tsx
  packages/core/src/renderer/components/+namespaces/store.injectable.ts
  packages/core/src/renderer/components/+namespaces/store.ts
  packages/core/src/renderer/components/+workloads-pods/load-pods-from-all-namespaces.injectable.ts
  packages/core/src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  packages/core/src/renderer/components/test-utils/get-application-builder.tsx
  packages/core/src/renderer/kube-watch-api/kube-watch-api.ts
  packages/release-tool/src/index.ts
Labels: skip-changelog

#7312 Fix requestNonCoreApiVersions after cherry-pick
  packages/core/src/main/cluster/request-non-core-api-versions.test.ts
Labels: chore

#7318 Fix typo in name of environment
  packages/open-lens/src/renderer/index.ts
Labels: chore

#7319 Release 6.4.5
  lerna.json
  packages/core/package.json
  packages/core/src/common/log-error.injectable.ts
  packages/core/src/common/logger.injectable.ts
  packages/core/src/features/telemetry/emit-telemetry-from-specific-function-calls.test.ts
  packages/core/src/features/telemetry/renderer/emit-telemetry.injectable.ts
  packages/core/src/features/telemetry/renderer/telemetry-decorator.injectable.ts
  packages/core/src/features/telemetry/renderer/telemetry-white-list-for-functions.injectable.ts
  packages/core/src/main/logger/console-transport.injectable.ts
  packages/core/src/main/logger/file-transport.injectable.ts
  packages/core/src/renderer/logger/browser-transport.injectable.ts
  packages/extension-api/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release

#7314 Update link in README
  README.md
Labels: chore

#7316 Copy detected metadata from cluster to catalog cluster
  packages/core/src/common/utils/enum.ts
  packages/core/src/main/cluster/manager.injectable.ts
  packages/core/src/main/cluster/manager.ts
  packages/core/src/main/cluster/update-entity-metadata.injectable.ts
  packages/core/src/main/cluster/update-entity-metadata.test.ts
  packages/core/src/main/cluster/update-entity-spec.injectable.ts
  packages/core/src/main/cluster/update-entity-spec.test.ts
Labels: bug

#7327 Release 6.4.6
  lerna.json
  packages/core/package.json
  packages/core/src/common/utils/enum.ts
  packages/core/src/main/cluster/manager.injectable.ts
  packages/core/src/main/cluster/manager.ts
  packages/core/src/main/cluster/update-entity-metadata.injectable.ts
  packages/core/src/main/cluster/update-entity-metadata.test.ts
  packages/core/src/main/cluster/update-entity-spec.injectable.ts
  packages/core/src/main/cluster/update-entity-spec.test.ts
  packages/extension-api/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release

#7326 Exporting ResourceMetrics and PodCharts to extension API
  packages/core/src/extensions/renderer-api/components.ts
Labels: chore, area/extension

#7306 Introduce eslint and prettier for features and start using it
  package-lock.json
  packages/infrastructure/eslint-config/README.md
  packages/infrastructure/eslint-config/bin/lint
  packages/infrastructure/eslint-config/eslint-config.js
  packages/infrastructure/eslint-config/package.json
  packages/infrastructure/eslint-config/prettier-config.json
  packages/technical-features/application/agnostic/.eslintrc.js
  packages/technical-features/application/agnostic/.prettierrc
  packages/technical-features/application/agnostic/jest.config.js
  packages/technical-features/application/agnostic/package.json
  packages/technical-features/application/agnostic/src/application-information-token.ts
  packages/technical-features/application/agnostic/src/feature.ts
  packages/technical-features/application/agnostic/src/start-application/starting-of-application.test.ts
  packages/technical-features/application/agnostic/tsconfig.json
  packages/technical-features/application/electron-main/.eslintrc.js
  packages/technical-features/application/electron-main/.prettierrc
  packages/technical-features/application/electron-main/index.ts
  packages/technical-features/application/electron-main/jest.config.js
  packages/technical-features/application/electron-main/package.json
  packages/technical-features/application/electron-main/src/electron/electron-app.test.ts
  packages/technical-features/application/electron-main/src/feature.ts
  packages/technical-features/application/electron-main/src/override-side-effects-with-fakes.ts
  packages/technical-features/application/electron-main/src/start-application/when-app-is-ready.test.ts
  packages/technical-features/application/electron-main/src/starting-of-electron-main-application.test.ts
  packages/technical-features/application/electron-main/tsconfig.json
  packages/technical-features/feature-core/.eslintrc.js
  packages/technical-features/feature-core/.prettierrc
  packages/technical-features/feature-core/jest.config.js
  packages/technical-features/feature-core/package.json
  packages/technical-features/feature-core/src/deregister-feature.ts
  packages/technical-features/feature-core/src/feature-context-map-injectable.ts
  packages/technical-features/feature-core/src/feature-dependencies.test.ts
  packages/technical-features/feature-core/src/feature.ts
  packages/technical-features/feature-core/src/register-feature.ts
  packages/technical-features/feature-core/src/registration-of-feature.test.ts
  packages/technical-features/feature-core/tsconfig.json
Labels: chore

#7336 Fix update button being visible when download for update fails
  packages/core/src/features/application-update/__snapshots__/installing-update.test.ts.snap
  packages/core/src/features/application-update/child-features/application-update-using-tray/__snapshots__/installing-update-using-tray.test.ts.snap
  packages/core/src/features/application-update/installing-update.test.ts
  packages/core/src/features/application-update/main/download-update/download-update.injectable.ts
Labels: bug

#7331 Better displaying container's info for Pods
  packages/core/src/common/k8s-api/endpoints/pod.api.ts
  packages/core/src/renderer/components/+workloads-pods/pods.tsx
  packages/core/src/renderer/components/tooltip/tooltip.scss
Labels: enhancement

#7338 Update repository in statefulset template from k8s.gcr.io to registry.k8s
  packages/open-lens/templates/create-resource/StatefulSet.yaml
Labels: bug, area/kubernetes-next

#7224 Keep up-to-date resource in the details view (Drawer)
  packages/core/src/features/cluster/kube-object-details/extension-api/disable-kube-object-detail-items-when-cluster-is-not-relevant.test.tsx
  packages/core/src/features/cluster/kube-object-details/extension-api/reactively-hide-kube-object-detail-item.test.tsx
  packages/core/src/renderer/components/kube-object-details/current-kube-object-in-details.injectable.ts
Labels: bug

#7349 Fix cluster view broken scrolling
  packages/core/src/renderer/components/cluster-manager/cluster-manager.scss
Labels: bug, area/ui

#7351 Fine-tune light theme hotbar colors
  packages/core/src/renderer/components/hotbar/hotbar-icon.module.scss
  packages/core/src/renderer/themes/lens-dark.injectable.ts
  packages/core/src/renderer/themes/lens-light.injectable.ts
Labels: enhancement, area/ui

#7352 Fix cluster disconnect not working
  packages/core/src/main/cluster/cluster-connection.injectable.ts
Labels: bug

#7345 Release 6.5.0-alpha.1
  lerna.json
  package-lock.json
  packages/bump-version-for-cron/package.json
  packages/core/package.json
  packages/core/src/renderer/components/tooltip/__snapshots__/tooltip.test.tsx.snap
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/infrastructure/eslint-config/package.json
  packages/infrastructure/jest/package.json
  packages/infrastructure/typescript/package.json
  packages/infrastructure/webpack/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
  packages/technical-features/application/agnostic/package.json
  packages/technical-features/application/electron-main/package.json
  packages/technical-features/feature-core/package.json
  packages/utility-features/run-many/package.json
  packages/utility-features/test-utils/package.json
  packages/utility-features/utilities/package.json
Labels: skip-changelog, release

#7358 Release 6.5.0-alpha.2
  package-lock.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
Labels: skip-changelog, release

#7341 Adding cluster settings icon menu items using injection token
  packages/core/src/renderer/components/cluster-settings/__tests__/__snapshots__/icon-settings.test.tsx.snap
  packages/core/src/renderer/components/cluster-settings/__tests__/icon-settings.test.tsx
  packages/core/src/renderer/components/cluster-settings/cluster-settings-menu-clear-item.injectable.ts
  packages/core/src/renderer/components/cluster-settings/cluster-settings-menu-injection-token.ts
  packages/core/src/renderer/components/cluster-settings/icon-settings.tsx
Labels: enhancement

#7356 Move deactivating a cluster into injectable IPC
  packages/core/src/common/catalog-entities/kubernetes-cluster.ts
  packages/core/src/common/cluster-frames.injectable.ts
  packages/core/src/common/cluster-frames.ts
  packages/core/src/common/ipc/cluster.ts
  packages/core/src/common/ipc/ipc.ts
  packages/core/src/features/cluster/activation/common/channels.ts
  packages/core/src/features/cluster/activation/common/request-token.ts
  packages/core/src/features/cluster/activation/main/deactivate-listener.injectable.ts
  packages/core/src/features/cluster/activation/main/request-deactivation.injectable.ts
  packages/core/src/features/cluster/activation/renderer/request-deactivation.injectable.ts
  packages/core/src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.injectable.ts
  packages/core/src/main/electron-app/runnables/setup-ipc-main-handlers/setup-ipc-main-handlers.ts
  packages/core/src/main/getDiForUnitTesting.ts
  packages/core/src/main/start-main-application/lens-window/application-window/create-lens-window.injectable.ts
  packages/core/src/main/utils/channel/message-to-channel.test.ts
  packages/core/src/renderer/ipc/index.ts
Labels: chore, PR: needs rebase

#7359 Fix bundled extensions not being loaded
  package-lock.json
  packages/core/package.json
  packages/core/src/common/library.ts
  packages/core/src/extensions/__tests__/is-compatible-extension.test.ts
  packages/core/src/extensions/common-api/index.ts
  packages/core/src/extensions/extension-discovery/bundled-extension-token.ts
  packages/core/src/extensions/extension-discovery/extension-discovery.ts
  packages/core/src/extensions/extension-discovery/is-compatible-extension/is-compatible-extension.ts
  packages/core/src/extensions/extension-loader/create-extension-instance.token.ts
  packages/core/src/extensions/extension-loader/extension-instances.injectable.ts
  packages/core/src/extensions/extension-loader/extension-loader.injectable.ts
  packages/core/src/extensions/extension-loader/extension-loader.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/file-system-provisioner-store.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/registered-extensions.injectable.ts
  packages/core/src/extensions/extensions-store/extensions-store.ts
  packages/core/src/extensions/lens-extension.ts
  packages/core/src/features/application-menu/main/menu-items/special-menu-for-mac-application/show-about-application/about-bundled-extensions.injectable.ts
  packages/core/src/main/protocol-handler/__test__/router.test.ts
  packages/core/src/main/start-main-application/runnables/initialize-extensions.injectable.ts
  packages/core/src/renderer/components/+extensions/attempt-install/attempt-install.injectable.tsx
  packages/core/src/renderer/components/+extensions/attempt-install/create-temp-files-and-validate.injectable.tsx
  packages/core/src/renderer/components/+extensions/attempt-install/validate-package.tsx
  packages/core/src/renderer/components/+extensions/confirm-uninstall-extension.injectable.tsx
  packages/core/src/renderer/components/+extensions/disable-extension/disable-extension.ts
  packages/core/src/renderer/components/+extensions/enable-extension/enable-extension.ts
  packages/core/src/renderer/components/+extensions/extensions.tsx
  packages/core/src/renderer/components/+extensions/installed-extensions.tsx
  packages/core/src/renderer/components/+extensions/uninstall-extension.injectable.tsx
  packages/core/src/renderer/ipc/index.ts
  packages/core/webpack/common.ts
  packages/core/webpack/library-bundle.ts
  packages/legacy-extension-example/.eslintrc.json
  packages/legacy-extension-example/jest.config.js
  packages/legacy-extension-example/main.ts
  packages/legacy-extension-example/package.json
  packages/legacy-extension-example/renderer.tsx
  packages/legacy-extension-example/tsconfig.json
  packages/legacy-extension-example/webpack.ts
  packages/open-lens/package.json
  packages/open-lens/src/common/example-bundled-extension.injectable.ts
  packages/technical-features/application/agnostic/.eslintrc.js
  packages/technical-features/application/agnostic/.eslintrc.json
  packages/technical-features/application/legacy-extensions/.eslintrc.json
  packages/technical-features/application/legacy-extensions/README.md
  packages/technical-features/application/legacy-extensions/index.ts
  packages/technical-features/application/legacy-extensions/jest.config.js
  packages/technical-features/application/legacy-extensions/package.json
  packages/technical-features/application/legacy-extensions/src/bundled-extension.ts
  packages/technical-features/application/legacy-extensions/src/lens-extension.ts
  packages/technical-features/application/legacy-extensions/tsconfig.json
  packages/technical-features/application/legacy-extensions/webpack.config.js
Labels: bug, area/extension, blocker

#7361 Release 6.5.0-alpha.3
  package-lock.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/legacy-extension-example/package.json
  packages/open-lens/package.json
  packages/technical-features/application/agnostic/package.json
  packages/technical-features/application/legacy-extensions/package.json
Labels: skip-changelog, release

#7365 Respect cluster avatars entity background color
  packages/core/src/main/cluster/update-entity-spec.injectable.ts
  packages/core/src/main/cluster/update-entity-spec.test.ts
  packages/core/src/renderer/components/+catalog/catalog.tsx
  packages/core/src/renderer/components/+entity-settings/entity-settings.tsx
  packages/core/src/renderer/components/cluster-settings/icon-settings.tsx
  packages/core/src/renderer/components/layout/sidebar-cluster.tsx
Labels: enhancement, area/ui

#7374 Fix findClosestVersionTagLessThanVersion in release tool
  packages/release-tool/src/index.ts
Labels: chore

#7373 Release 6.4.7
  lerna.json
  packages/core/package.json
  packages/core/src/extensions/renderer-api/components.ts
  packages/core/src/features/application-update/__snapshots__/installing-update.test.ts.snap
  packages/core/src/features/application-update/child-features/application-update-using-tray/__snapshots__/installing-update-using-tray.test.ts.snap
  packages/core/src/features/application-update/installing-update.test.ts
  packages/core/src/features/application-update/main/download-update/download-update.injectable.ts
  packages/core/src/renderer/components/cluster-manager/cluster-manager.scss
  packages/extension-api/package.json
  packages/open-lens/package.json
  packages/open-lens/templates/create-resource/StatefulSet.yaml
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: skip-changelog, release

#7371 Fix catalog & workloads table view
  packages/core/src/features/catalog/__snapshots__/entity-running.test.tsx.snap
  packages/core/src/features/catalog/__snapshots__/opening-entity-details.test.tsx.snap
  packages/core/src/renderer/components/+catalog/catalog.module.scss
  packages/core/src/renderer/components/+catalog/catalog.tsx
  packages/core/src/renderer/components/+network-ingresses/ingresses.scss
  packages/core/src/renderer/components/+workloads-pods/pods.tsx
  packages/core/src/renderer/components/badge/badge.module.scss
  packages/core/src/renderer/components/line-progress/line-progress.scss
  packages/core/src/renderer/components/table/table-cell.scss
  packages/core/src/renderer/components/table/table-head.scss
Labels: bug, area/ui

#7366 Remove direct dependency on 'abort-controller' package
  package-lock.json
  packages/core/package.json
  packages/core/src/common/fetch/timeout-controller.ts
  packages/core/src/common/k8s-api/__tests__/kube-api.test.ts
  packages/core/src/common/k8s-api/kube-api.ts
  packages/core/src/common/k8s-api/kube-object.store.ts
  packages/core/src/main/k8s-request.injectable.ts
  packages/core/src/renderer/kube-watch-api/kube-watch-api.ts
  packages/open-lens/package.json
  packages/utility-features/utilities/src/abort-controller.ts
  packages/utility-features/utilities/src/delay.ts
  packages/utility-features/utilities/src/reject-promise.ts
Labels: dependencies

#7375 Fix resolve system proxy error when no windows available
  packages/core/src/main/getDiForUnitTesting.ts
  packages/core/src/main/utils/resolve-system-proxy/electron-browser-window.global-override-for-injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/electron-browser-window.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/electron.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.test.ts
Labels: bug

#7379 Fix resolveSystemProxyFromElectron causing a crash on quit
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.test.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.global-override-for-injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts
Labels: bug

#7380 Fix problems when using 'npm link'
  package-lock.json
  package.json
  packages/core/package.json
  packages/utility-features/run-many/package.json
  packages/utility-features/test-utils/package.json
  packages/utility-features/utilities/package.json
Labels: dependencies

#7389 Electron 22.3.3
  package-lock.json
  packages/core/package.json
  packages/core/src/common/app-paths/app-path-names.ts
  packages/core/src/common/app-paths/app-paths.test.ts
  packages/core/src/common/error-reporting/initialize-sentry-reporting.injectable.ts
  packages/core/src/main/app-paths/setup-app-paths.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts
  packages/open-lens/package.json
  packages/technical-features/application/electron-main/package.json
  packages/technical-features/messaging/electron/main/package.json
  packages/technical-features/messaging/electron/renderer/package.json
Labels: dependencies, area/security

#7392 Fix type error in new @k8slens/messaging
  packages/technical-features/messaging/agnostic/src/features/actual/message/message-channel-listener-injection-token.ts
  packages/technical-features/messaging/electron/renderer/src/listening-of-messages/enlist-message-channel-listener.injectable.ts
Labels: bug

#7300 Renderer file logging through IPC
  packages/core/src/common/logger.injectable.ts
  packages/core/src/common/logger/ipc-file-logger-channel.ts
  packages/core/src/common/winston-logger.global-override-for-injectable.ts
  packages/core/src/common/winston-logger.injectable.ts
  packages/core/src/main/logger/close-ipc-logging-listener.injectable.ts
  packages/core/src/main/logger/create-ipc-file-transport.global-override-for-injectable.ts
  packages/core/src/main/logger/create-ipc-file-transport.injectable.ts
  packages/core/src/main/logger/file-transport.injectable.ts
  packages/core/src/main/logger/ipc-file-logger.injectable.ts
  packages/core/src/main/logger/ipc-file-logger.test.ts
  packages/core/src/main/logger/ipc-logging-listener.injectable.ts
  packages/core/src/main/logger/ipc-logging-listener.test.ts
  packages/core/src/main/logger/stop-ipc-logging.injectable.ts
  packages/core/src/renderer/before-frame-starts/runnables/listen-unload.injectable.ts
  packages/core/src/renderer/bootstrap.tsx
  packages/core/src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
  packages/core/src/renderer/frames/root-frame/init-root-frame.injectable.ts
  packages/core/src/renderer/logger/close-renderer-log-file-id.test.ts
  packages/core/src/renderer/logger/close-renderer-log-file.injectable.ts
  packages/core/src/renderer/logger/ipc-transport.injectable.ts
  packages/core/src/renderer/logger/ipc-transport.test.ts
  packages/core/src/renderer/logger/ipc-transport.ts
  packages/core/src/renderer/logger/renderer-log-file-id.injectable.ts
  packages/core/src/renderer/logger/renderer-log-file-id.test.ts
Labels: enhancement, area/logs

#7393 Revert "Renderer file logging through IPC"
  packages/core/src/common/logger.injectable.ts
  packages/core/src/common/logger/ipc-file-logger-channel.ts
  packages/core/src/common/winston-logger.global-override-for-injectable.ts
  packages/core/src/common/winston-logger.injectable.ts
  packages/core/src/main/logger/close-ipc-logging-listener.injectable.ts
  packages/core/src/main/logger/create-ipc-file-transport.global-override-for-injectable.ts
  packages/core/src/main/logger/create-ipc-file-transport.injectable.ts
  packages/core/src/main/logger/file-transport.injectable.ts
  packages/core/src/main/logger/ipc-file-logger.injectable.ts
  packages/core/src/main/logger/ipc-file-logger.test.ts
  packages/core/src/main/logger/ipc-logging-listener.injectable.ts
  packages/core/src/main/logger/ipc-logging-listener.test.ts
  packages/core/src/main/logger/stop-ipc-logging.injectable.ts
  packages/core/src/renderer/before-frame-starts/runnables/listen-unload.injectable.ts
  packages/core/src/renderer/bootstrap.tsx
  packages/core/src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
  packages/core/src/renderer/frames/root-frame/init-root-frame.injectable.ts
  packages/core/src/renderer/logger/close-renderer-log-file-id.test.ts
  packages/core/src/renderer/logger/close-renderer-log-file.injectable.ts
  packages/core/src/renderer/logger/ipc-transport.injectable.ts
  packages/core/src/renderer/logger/ipc-transport.test.ts
  packages/core/src/renderer/logger/ipc-transport.ts
  packages/core/src/renderer/logger/renderer-log-file-id.injectable.ts
  packages/core/src/renderer/logger/renderer-log-file-id.test.ts
Labels: bug

#7280 Add behavioural tests for Cluster Menu K8s Resources in Sidebar menu not being shown
  packages/core/src/common/cluster/authorization-review.injectable.ts
  packages/core/src/common/cluster/create-authorization-api.injectable.ts
  packages/core/src/common/cluster/create-can-i.injectable.ts
  packages/core/src/common/cluster/create-core-api.injectable.ts
  packages/core/src/common/cluster/create-request-namespace-list-permissions.injectable.ts
  packages/core/src/common/cluster/list-namespaces.injectable.ts
  packages/core/src/common/cluster/request-namespace-list-permissions.injectable.ts
  packages/core/src/common/cluster/request-namespace-list-permissions.test.ts
  packages/core/src/common/fs/copy.global-override-for-injectable.ts
  packages/core/src/common/fs/lstat.global-override-for-injectable.ts
  packages/core/src/common/fs/read-directory.global-override-for-injectable.ts
  packages/core/src/common/fs/remove.global-override-for-injectable.ts
  packages/core/src/common/fs/write-file.global-override-for-injectable.ts
  packages/core/src/features/cluster/refresh-accessibility-technical.test.ts
  packages/core/src/main/__test__/cluster.test.ts
  packages/core/src/main/__test__/context-handler.test.ts
  packages/core/src/main/__test__/kube-auth-proxy.test.ts
  packages/core/src/main/__test__/prometheus-handler.test.ts
  packages/core/src/main/cluster/api-versions-requester.ts
  packages/core/src/main/cluster/cluster-connection.injectable.ts
  packages/core/src/main/cluster/kube-auth-proxy-server.injectable.ts
  packages/core/src/main/cluster/request-api-resources.injectable.ts
  packages/core/src/main/cluster/request-core-api-versions.injectable.ts
  packages/core/src/main/cluster/request-kube-api-resources-for.injectable.ts
  packages/core/src/main/cluster/request-non-core-api-versions.injectable.ts
  packages/core/src/main/cluster/request-non-core-api-versions.test.ts
  packages/core/src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts
  packages/core/src/main/kube-auth-proxy/kube-auth-proxy.ts
  packages/core/src/main/kubeconfig-manager/kubeconfig-manager.ts
  packages/core/src/test-utils/cast.ts
  packages/core/src/test-utils/mock-interface.ts
  packages/utility-features/test-utils/src/flush-promises.ts
Labels: bug, area/rbac

#7397 Release 6.4.8
  lerna.json
  packages/core/package.json
  packages/core/src/main/getDiForUnitTesting.ts
  packages/core/src/main/utils/resolve-system-proxy/electron.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.test.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.global-override-for-injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts
  packages/extension-api/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release

#7384 Fix behaviour of auto generated CRD KubeApis and KubeObjectStores
  packages/core/src/common/k8s-api/__tests__/api-manager.test.ts
  packages/core/src/common/k8s-api/api-manager/api-manager.ts
  packages/core/src/common/k8s-api/api-manager/auto-registration-emitter.injectable.ts
  packages/core/src/common/k8s-api/api-manager/crd-api-token.ts
  packages/core/src/common/k8s-api/api-manager/create-custom-resource-store.injectable.ts
  packages/core/src/common/k8s-api/api-manager/manager.injectable.ts
  packages/core/src/common/k8s-api/kube-object.store.ts
  packages/core/src/common/utils/registrator-helper.ts
  packages/core/src/extensions/extension-loader/extension/extension.injectable.ts
  packages/core/src/features/extension-special-characters-in-page-registrations.test.tsx
  packages/core/src/renderer/before-frame-starts/runnables/setup-auto-crd-api-creations.injectable.ts
  packages/core/src/renderer/before-frame-starts/runnables/setup-auto-registration.injectable.ts
  packages/core/src/renderer/components/+config-horizontal-pod-autoscalers/hpa-details.test.tsx
  packages/core/src/renderer/components/+custom-resources/definition.store.injectable.ts
  packages/core/src/renderer/components/+custom-resources/definition.store.ts
  packages/core/src/renderer/components/test-utils/get-application-builder.tsx
  packages/core/src/renderer/components/test-utils/get-extension-fake.ts
Labels: bug

#7399 Fix import of getGlobalOverride
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.global-override-for-injectable.ts
Labels: chore

#7400 Release 6.4.9
  lerna.json
  packages/core/package.json
  packages/core/src/common/k8s-api/__tests__/api-manager.test.ts
  packages/core/src/common/k8s-api/api-manager/api-manager.ts
  packages/core/src/common/k8s-api/api-manager/auto-registration-emitter.injectable.ts
  packages/core/src/common/k8s-api/api-manager/crd-api-token.ts
  packages/core/src/common/k8s-api/api-manager/create-custom-resource-store.injectable.ts
  packages/core/src/common/k8s-api/api-manager/manager.injectable.ts
  packages/core/src/common/k8s-api/kube-object.store.ts
  packages/core/src/common/utils/registrator-helper.ts
  packages/core/src/extensions/extension-loader/extension/extension.injectable.ts
  packages/core/src/features/extension-special-characters-in-page-registrations.test.tsx
  packages/core/src/renderer/before-frame-starts/runnables/setup-auto-crd-api-creations.injectable.ts
  packages/core/src/renderer/before-frame-starts/runnables/setup-auto-registration.injectable.ts
  packages/core/src/renderer/components/+config-horizontal-pod-autoscalers/hpa-details.test.tsx
  packages/core/src/renderer/components/+custom-resources/definition.store.injectable.ts
  packages/core/src/renderer/components/+custom-resources/definition.store.ts
  packages/core/src/renderer/components/test-utils/get-application-builder.tsx
  packages/core/src/renderer/components/test-utils/get-extension-fake.ts
  packages/extension-api/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release

#7401 Fix build issues for patch release
  packages/core/src/renderer/before-frame-starts/runnables/setup-auto-crd-api-creations.injectable.ts
  packages/core/src/renderer/components/+config-horizontal-pod-autoscalers/hpa-details.test.tsx
Labels: chore

#7402 Release 6.4.10
  lerna.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release

#7396 Fix Check for updates menu item title capitalisation
  packages/core/src/features/application-update/child-features/application-update-using-application-menu/main/check-for-updates-menu-item.injectable.ts
  packages/core/src/features/application-update/child-features/application-update-using-tray/installing-update-using-tray.test.ts
  packages/core/src/features/application-update/child-features/application-update-using-tray/main/tray-items/check-for-updates-tray-item.injectable.ts
Labels: enhancement, area/ui

#7398 Fix formatting in release guide
  RELEASE_GUIDE.md
Labels: area/documentation

#7407 Fix app crash on quit
  packages/core/src/main/electron-app/runnables/setup-runnables-before-closing-of-application.injectable.ts
  packages/core/src/main/start-main-application/lens-window/application-window/create-lens-window.injectable.ts
  packages/core/src/main/start-main-application/runnable-tokens/before-quit-of-back-end-injection-token.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts
Labels: bug

#7225 Export `getPodsByOwnerId` to extension API
  packages/core/src/extensions/common-api/k8s-api.ts
  packages/core/src/renderer/components/+workloads-daemonsets/store.ts
  packages/core/src/renderer/components/+workloads-jobs/store.ts
  packages/core/src/renderer/components/+workloads-replicasets/store.ts
  packages/core/src/renderer/components/+workloads-statefulsets/store.ts
Labels: enhancement, area/extension

#7409 Release 6.4.11
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release

#7413 Fix download all logs for pod with few containers
  packages/core/src/features/pod-logs/download-logs.test.tsx
  packages/core/src/renderer/components/dock/logs/download-all-logs.injectable.ts
  packages/core/src/renderer/components/dock/logs/logs-view-model.ts
Labels: bug, area/logs

#7415 Update webstorm configs
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jsLinters/eslint.xml
  .idea/lens.iml
Labels: chore

#7185 Refactor electron window setCertificateVerifyProc
  packages/core/src/main/start-main-application/lens-window/application-window/__test__/session-certificate-verifier.test.ts
  packages/core/src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts
  packages/core/src/main/start-main-application/lens-window/application-window/session-certificate-verifier.injectable.ts
Labels: chore

#7419 Block renderering non http(s):// links via <HelmChartIcon>
  packages/core/src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-new-tab.test.ts.snap
  packages/core/src/features/helm-charts/installing-chart/__snapshots__/opening-dock-tab-for-installing-helm-chart.test.ts.snap
  packages/core/src/renderer/components/+helm-charts/__tests__/icon.test.tsx
  packages/core/src/renderer/components/+helm-charts/helm-chart-details.scss
  packages/core/src/renderer/components/+helm-charts/helm-chart-details.tsx
  packages/core/src/renderer/components/+helm-charts/helm-charts.tsx
  packages/core/src/renderer/components/+helm-charts/icon.module.css
  packages/core/src/renderer/components/+helm-charts/icon.tsx
Labels: bug, area/ui, area/security

#7424 Remove auto adding tickets to project board
  .github/actions/add-card-to-project/Dockerfile
  .github/actions/add-card-to-project/action.yml
  .github/actions/add-card-to-project/entrypoint.sh
  .github/workflows/add-to-project-board.yaml
Labels: chore

#7427 Restore disk metrics to PersistentVolumeClaim details page
  packages/core/src/common/cluster-types.ts
Labels: bug

#7431 Add scenarios for namespace selector
  scenarios/namespace-selector.md
Labels: area/documentation

#7426 Remove requirement for JSON of messages
  packages/technical-features/messaging/computed-channel/index.ts
  packages/technical-features/messaging/computed-channel/src/computed-channel/computed-channel-administration-channel.injectable.ts
  packages/technical-features/messaging/computed-channel/src/computed-channel/computed-channel.injectable.ts
  packages/technical-features/messaging/computed-channel/src/computed-channel/computed-channel.test.tsx
Labels: chore

#7441 Extract React Application as a Feature
  package-lock.json
  packages/core/package.json
  packages/core/src/features/preferences/extension-adding-preference-tabs.test.tsx
  packages/core/src/features/preferences/hiding-of-empty-branches.test.tsx
  packages/core/src/features/preferences/navigation-to-application-preferences.test.tsx
  packages/core/src/features/preferences/navigation-to-editor-preferences.test.ts
  packages/core/src/features/preferences/navigation-to-extension-specific-preferences.test.tsx
  packages/core/src/features/preferences/navigation-to-kubernetes-preferences.test.ts
  packages/core/src/features/preferences/navigation-to-proxy-preferences.test.ts
  packages/core/src/features/preferences/navigation-to-telemetry-preferences.test.tsx
  packages/core/src/features/preferences/navigation-to-terminal-preferences.test.ts
  packages/core/src/features/preferences/navigation-using-application-menu.test.ts
  packages/core/src/features/preferences/navigation-using-tray.test.ts
  packages/core/src/features/preferences/urls-of-legacy-extensions.test.tsx
  packages/core/src/renderer/bootstrap.injectable.ts
  packages/core/src/renderer/bootstrap.tsx
  packages/core/src/renderer/components/test-utils/discovery-of-html-elements.ts
  packages/core/src/renderer/components/test-utils/get-application-builder.tsx
  packages/core/src/renderer/frames/frame-application-root.injectable.ts
  packages/core/src/renderer/frames/routing-react-application-hoc.injectable.tsx
  packages/core/src/renderer/frames/theme-provider-react-application-hoc.injectable.tsx
  packages/core/src/renderer/mui-base-theme.tsx
  packages/core/src/renderer/start-frame/start-frame.injectable.ts
  packages/infrastructure/webpack/src/react-config.js
  packages/open-lens/package.json
  packages/open-lens/src/renderer/index.ts
  packages/technical-features/react-application/.eslintrc.json
  packages/technical-features/react-application/.prettierrc
  packages/technical-features/react-application/README.md
  packages/technical-features/react-application/index.ts
  packages/technical-features/react-application/jest.config.js
  packages/technical-features/react-application/package.json
  packages/technical-features/react-application/src/__snapshots__/react-application.test.tsx.snap
  packages/technical-features/react-application/src/feature.ts
  packages/technical-features/react-application/src/react-application.test.tsx
  packages/technical-features/react-application/src/react-application/react-application-children-injection-token.ts
  packages/technical-features/react-application/src/react-application/react-application-content.tsx
  packages/technical-features/react-application/src/react-application/react-application-higher-order-component-injection-token.ts
  packages/technical-features/react-application/src/react-application/react-application.tsx
  packages/technical-features/react-application/src/render-application/render-application-when-application-is-ready.injectable.tsx
  packages/technical-features/react-application/src/render-application/render.injectable.tsx
  packages/technical-features/react-application/tsconfig.json
  packages/technical-features/react-application/webpack.config.js
  packages/utility-features/react-testing-library-discovery/.eslintrc.json
  packages/utility-features/react-testing-library-discovery/.prettierrc
  packages/utility-features/react-testing-library-discovery/index.ts
  packages/utility-features/react-testing-library-discovery/package.json
  packages/utility-features/react-testing-library-discovery/src/discovery-of-html-elements.ts
  packages/utility-features/react-testing-library-discovery/tsconfig.json
  packages/utility-features/react-testing-library-discovery/webpack.config.js
Labels: chore

#7443 Wait app to be ready before creating a BrowserWindow for system proxy resolver
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.test.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.global-override-for-injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts
Labels: bug

#7446 Release 6.4.12
  lerna.json
  packages/core/package.json
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.test.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.global-override-for-injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts
  packages/extension-api/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release

#7433 Make ServiceAccount kubeconfig context name differ from cluster context name
  packages/core/src/main/routes/kubeconfig-route/get-service-account-route.injectable.ts
Labels: enhancement

#7450 Stop all extensions before quitting app
  packages/core/src/features/extensions/stopping/main/stop-all.injectable.ts
  packages/core/src/main/stop-services-and-exit-app.injectable.ts
Labels: bug

#7451 Correct dependencies of open-lens
  package-lock.json
  packages/open-lens/package.json
Labels: dependencies

#7452 Fix app crash on quit (#7407)
  packages/core/src/main/electron-app/runnables/setup-runnables-before-closing-of-application.injectable.ts
  packages/core/src/main/start-main-application/lens-window/application-window/create-lens-window.injectable.ts
  packages/core/src/main/start-main-application/runnable-tokens/phases.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts
Labels: skip-changelog

#7453 Close Lens Proxy on quit of backend
  packages/core/src/main/lens-proxy/close-on-quit.injectable.ts
  packages/core/src/main/lens-proxy/lens-proxy.ts
  packages/core/src/main/shell-session/local-shell-session/open.injectable.ts
  packages/core/src/main/shell-session/node-shell-session/open.injectable.ts
  packages/core/src/main/shell-session/processes.injectable.ts
  packages/core/src/main/shell-session/shell-envs.injectable.ts
  packages/core/src/main/shell-session/shell-session.ts
  packages/core/src/main/start-main-application/runnables/clean-up-shell-sessions.injectable.ts
Labels: bug

#7448 Fix crash due to non base64 encoded secrets
  packages/core/src/renderer/components/+workloads-pods/__snapshots__/secret-key.test.tsx.snap
  packages/core/src/renderer/components/+workloads-pods/__tests__/__snapshots__/pod-container-env.test.tsx.snap
  packages/core/src/renderer/components/+workloads-pods/pod-container-env.tsx
  packages/core/src/renderer/components/+workloads-pods/secret-key.test.tsx
  packages/core/src/renderer/components/+workloads-pods/secret-key.tsx
Labels: bug

#7454 Add temporal dependency to initializeExtensions
  packages/core/src/main/start-main-application/runnables/initialize-extensions.injectable.ts
Labels: bug, area/extension

#7354 Move Cluster.apiUrl to seperate injectable
  package-lock.json
  packages/core/package.json
  packages/core/src/common/cluster-types.ts
  packages/core/src/common/cluster/cluster.ts
  packages/core/src/common/k8s-api/__tests__/api-manager.test.ts
  packages/core/src/common/k8s-api/__tests__/kube-api-version-detection.test.ts
  packages/core/src/common/k8s-api/__tests__/kube-api.test.ts
  packages/core/src/common/kube-helpers.ts
  packages/core/src/common/kube-helpers/load-validated-config-from-file.injectable.ts
  packages/core/src/features/cluster/connections/main/api-url.injectable.ts
  packages/core/src/features/cluster/delete-dialog/delete-cluster-dialog.test.tsx
  packages/core/src/features/cluster/storage/cluster-storage.test.ts
  packages/core/src/features/cluster/storage/common/add.injectable.ts
  packages/core/src/features/cluster/storage/common/read-cluster-config.injectable.ts
  packages/core/src/features/cluster/storage/common/storage.injectable.ts
  packages/core/src/main/__test__/cluster.test.ts
  packages/core/src/main/__test__/kube-auth-proxy.test.ts
  packages/core/src/main/__test__/kubeconfig-manager.test.ts
  packages/core/src/main/__test__/prometheus-handler.test.ts
  packages/core/src/main/catalog-sources/__test__/kubeconfig-sync.test.ts
  packages/core/src/main/catalog-sources/kubeconfig-sync/compute-diff.injectable.ts
  packages/core/src/main/catalog-sources/kubeconfig-sync/config-to-models.injectable.ts
  packages/core/src/main/cluster-detectors/cluster-distribution-detector.injectable.ts
  packages/core/src/main/cluster-detectors/cluster-id-detector.injectable.ts
  packages/core/src/main/cluster-detectors/detect-cluster-metadata.test.ts
  packages/core/src/main/cluster/kube-auth-proxy-server.injectable.ts
  packages/core/src/main/cluster/manager.ts
  packages/core/src/main/cluster/update-entity-metadata.test.ts
  packages/core/src/main/cluster/update-entity-spec.test.ts
  packages/core/src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts
  packages/core/src/main/kube-auth-proxy/kube-auth-proxy.ts
  packages/core/src/main/lens-proxy/proxy-functions/kube-api-upgrade-request.injectable.ts
  packages/core/src/main/routes/kubeconfig-route/get-service-account-route.injectable.ts
  packages/core/src/main/shell-session/local-shell-session/techincal.test.ts
  packages/core/src/renderer/components/+config-horizontal-pod-autoscalers/hpa-details.test.tsx
  packages/core/src/renderer/components/+config-secrets/__tests__/secret-details.test.tsx
  packages/core/src/renderer/components/+namespaces/namespace-select-filter.test.tsx
  packages/core/src/renderer/components/+namespaces/namespace-store.test.ts
  packages/core/src/renderer/components/+user-management/+cluster-role-bindings/__tests__/dialog.test.tsx
  packages/core/src/renderer/components/+user-management/+role-bindings/__tests__/dialog.test.tsx
  packages/core/src/renderer/components/__tests__/cronjob.store.test.ts
  packages/core/src/renderer/components/__tests__/daemonset.store.test.ts
  packages/core/src/renderer/components/__tests__/deployments.store.test.ts
  packages/core/src/renderer/components/__tests__/job.store.test.ts
  packages/core/src/renderer/components/__tests__/pods.store.test.ts
  packages/core/src/renderer/components/__tests__/replicaset.store.test.ts
  packages/core/src/renderer/components/__tests__/statefulset.store.test.ts
  packages/core/src/renderer/components/cluster-settings/__tests__/cluster-local-terminal-settings.test.tsx
  packages/core/src/renderer/components/cluster-settings/__tests__/icon-settings.test.tsx
  packages/core/src/renderer/components/kube-object-list-layout/kube-object-list-layout.test.tsx
  packages/core/src/renderer/components/test-utils/get-application-builder.tsx
  packages/core/src/renderer/frames/cluster-frame/cluster-frame.test.tsx
  packages/utility-features/utilities/src/collection-functions.ts
Labels: chore

#7447 Get dev mode fixed
  .nxignore
  package-lock.json
  package.json
  packages/bump-version-for-cron/package.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/generate-tray-icons/package.json
  packages/legacy-extension-example/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/technical-features/application/agnostic/package.json
  packages/technical-features/application/electron-main/package.json
  packages/technical-features/application/legacy-extensions/package.json
  packages/technical-features/feature-core/package.json
  packages/technical-features/messaging/agnostic/package.json
  packages/technical-features/messaging/computed-channel/package.json
  packages/technical-features/messaging/electron/main/package.json
  packages/technical-features/messaging/electron/renderer/package.json
  packages/technical-features/messaging/message-bridge-fake/package.json
  packages/technical-features/react-application/package.json
  packages/utility-features/react-testing-library-discovery/package.json
  packages/utility-features/run-many/package.json
  packages/utility-features/startable-stoppable/package.json
  packages/utility-features/test-utils/package.json
  packages/utility-features/utilities/package.json
Labels: chore

#7455 Release 6.4.13
  lerna.json
  packages/core/package.json
  packages/core/src/features/extensions/stopping/main/stop-all.injectable.ts
  packages/core/src/main/lens-proxy/close-on-quit.injectable.ts
  packages/core/src/main/lens-proxy/lens-proxy.ts
  packages/core/src/main/shell-session/local-shell-session/open.injectable.ts
  packages/core/src/main/shell-session/node-shell-session/open.injectable.ts
  packages/core/src/main/shell-session/processes.injectable.ts
  packages/core/src/main/shell-session/shell-envs.injectable.ts
  packages/core/src/main/shell-session/shell-session.ts
  packages/core/src/main/start-main-application/runnables/clean-up-shell-sessions.injectable.ts
  packages/core/src/main/start-main-application/runnables/initialize-extensions.injectable.ts
  packages/core/src/main/stop-services-and-exit-app.injectable.ts
  packages/core/src/renderer/components/+workloads-pods/__snapshots__/secret-key.test.tsx.snap
  packages/core/src/renderer/components/+workloads-pods/__tests__/__snapshots__/pod-container-env.test.tsx.snap
  packages/core/src/renderer/components/+workloads-pods/pod-container-env.tsx
  packages/core/src/renderer/components/+workloads-pods/secret-key.test.tsx
  packages/core/src/renderer/components/+workloads-pods/secret-key.tsx
  packages/extension-api/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release
