Repository lensapp/lens, pull requests merged in 2023-06, with the labels that each got.

#7814 Bump ogre-tools for linkable improvements
  open-lens/package.json
  package-lock.json
  package.json
  packages/business-features/keyboard-shortcuts/package.json
  packages/cluster-settings/package.json
  packages/cluster-sidebar/package.json
  packages/core/package.json
  packages/infrastructure/webpack/package.json
  packages/kube-object/package.json
  packages/kubectl-versions/package.json
  packages/legacy-global-di/package.json
  packages/list-layout/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/routing/package.json
  packages/technical-features/application/agnostic/package.json
  packages/technical-features/application/electron-main/package.json
  packages/technical-features/application/legacy-extensions/package.json
  packages/technical-features/feature-core/package.json
  packages/technical-features/messaging/agnostic/package.json
  packages/technical-features/messaging/computed-channel/package.json
  packages/technical-features/messaging/electron/main/package.json
  packages/technical-features/messaging/electron/renderer/package.json
  packages/technical-features/messaging/message-bridge-fake/package.json
  packages/technical-features/react-application/package.json
  packages/ui-components/animate/package.json
  packages/ui-components/error-boundary/package.json
  packages/ui-components/icon/package.json
  packages/ui-components/resizing-anchor/package.json
  packages/utility-features/kube-api-specifics/package.json
  packages/utility-features/kube-api/package.json
  packages/utility-features/run-many/package.json
  packages/utility-features/test-utils/package.json
Labels: chore

#7813 Update @electron/notarize
  open-lens/build/notarize.js
  open-lens/package.json
  package-lock.json
Labels: dependencies

#7786 Chore: extract prometheus from core
  open-lens/package.json
  open-lens/src/main/index.ts
  package-lock.json
  packages/core/package.json
  packages/core/src/main/__test__/prometheus-handler.test.ts
  packages/core/src/main/cluster/prometheus-handler/prometheus-handler.ts
  packages/core/src/main/prometheus/get-by-kind.injectable.ts
  packages/core/src/main/prometheus/providers.injectable.ts
  packages/technical-features/prometheus/.eslintrc.js
  packages/technical-features/prometheus/.prettierrc
  packages/technical-features/prometheus/CHANGELOG.md
  packages/technical-features/prometheus/index.ts
  packages/technical-features/prometheus/jest.config.js
  packages/technical-features/prometheus/package.json
  packages/technical-features/prometheus/src/feature.ts
  packages/technical-features/prometheus/src/helm-14-provider.injectable.ts
  packages/technical-features/prometheus/src/helm-provider.injectable.ts
  packages/technical-features/prometheus/src/lens-provider.injectable.ts
  packages/technical-features/prometheus/src/operator-provider.injectable.ts.ts
  packages/technical-features/prometheus/src/provider.ts
  packages/technical-features/prometheus/src/stacklight-provider.injectable.ts
  packages/technical-features/prometheus/tsconfig.json
  packages/technical-features/prometheus/webpack.config.js
Labels: chore, area/metrics

#7832 Extract @k8slens/spinner
  open-lens/src/renderer/index.ts
  package-lock.json
  packages/core/package.json
  packages/core/src/extensions/renderer-api/components.ts
  packages/core/src/features/helm-charts/child-features/preferences/renderer/helm-repositories.tsx
  packages/core/src/features/preferences/renderer/preference-items/kubernetes/kubeconfig-sync/kubeconfig-sync.tsx
  packages/core/src/renderer/components/cluster-manager/cluster-status.tsx
  packages/core/src/renderer/components/cluster-settings/local-terminal-settings.tsx
  packages/core/src/renderer/components/cluster-settings/prometheus-setting.tsx
  packages/core/src/renderer/components/cluster/cluster-issues.tsx
  packages/core/src/renderer/components/cluster/cluster-metrics.tsx
  packages/core/src/renderer/components/cluster/cluster-overview.tsx
  packages/core/src/renderer/components/cluster/cluster-pie-charts.tsx
  packages/core/src/renderer/components/dock/create-resource/view.tsx
  packages/core/src/renderer/components/dock/edit-resource/view.tsx
  packages/core/src/renderer/components/dock/info-panel.tsx
  packages/core/src/renderer/components/dock/install-chart/view.tsx
  packages/core/src/renderer/components/dock/logs/list.tsx
  packages/core/src/renderer/components/dock/upgrade-chart/view.tsx
  packages/core/src/renderer/components/extensions/installed-extensions.tsx
  packages/core/src/renderer/components/file-picker/file-picker.tsx
  packages/core/src/renderer/components/helm-charts/helm-chart-details.tsx
  packages/core/src/renderer/components/helm-releases/release-details/release-details-content.tsx
  packages/core/src/renderer/components/item-object-list/content.tsx
  packages/core/src/renderer/components/kube-object-details/kube-object-details.tsx
  packages/core/src/renderer/components/namespaces/namespace-details.tsx
  packages/core/src/renderer/components/network-services/service-port-component.tsx
  packages/core/src/renderer/components/resource-metrics/resource-metrics.tsx
  packages/core/src/renderer/components/storage-volumes/volume-details-list.tsx
  packages/core/src/renderer/components/user-management/service-accounts/details.tsx
  packages/core/src/renderer/components/wizard/wizard.tsx
  packages/core/src/renderer/components/workloads-deployments/deployment-replicasets.tsx
  packages/core/src/renderer/components/workloads-pods/pod-container-port.tsx
  packages/core/src/renderer/components/workloads-pods/pod-details-list.tsx
  packages/ui-components/animate/README.md
  packages/ui-components/spinner/.eslintrc.json
  packages/ui-components/spinner/.prettierrc
  packages/ui-components/spinner/CHANGELOG.md
  packages/ui-components/spinner/README.md
  packages/ui-components/spinner/index.ts
  packages/ui-components/spinner/jest.config.js
  packages/ui-components/spinner/package.json
  packages/ui-components/spinner/src/spinner.scss
  packages/ui-components/spinner/src/spinner.tsx
  packages/ui-components/spinner/tailwind.config.js
  packages/ui-components/spinner/tsconfig.json
  packages/ui-components/spinner/webpack.config.js
Labels: chore
