Repository lensapp/lens, pull requests merged in 2023-04, with the labels that each got.

#7462 conf v10.2.0
  package-lock.json
  packages/core/package.json
Labels: dependencies

#7465 Fix metrics visibility logic
  packages/core/src/renderer/api/catalog/entity/__tests__/metrics-enabled.test.ts
  packages/core/src/renderer/api/catalog/entity/metrics-details-component-enabled.injectable.ts
  packages/core/src/renderer/api/catalog/entity/metrics-enabled.injectable.ts
  packages/core/src/renderer/components/+cluster/cluster-overview.tsx
  packages/core/src/renderer/components/+workloads-pods/pod-details-container.tsx
Labels: bug, area/metrics

#7463 Kludge fix for application crash when quitting
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.injectable.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-from-electron.test.ts
  packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts
Labels: bug

#7478 fix: Add check in release-tool for no relevant PRs
  packages/release-tool/src/index.ts
Labels: bug

#7476 Release 6.4.14
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/common/cluster-types.ts
  packages/extension-api/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: skip-changelog, release

#7492 chore: Add notes about picking PRs in release guide
  RELEASE_GUIDE.md
Labels: area/documentation

#7390 Show Message Box when no update is available after manually checking for updates
  packages/core/src/features/application-update/child-features/application-update-using-application-menu/__snapshots__/application-update-using-application-menu.test.ts.snap
  packages/core/src/features/application-update/child-features/application-update-using-application-menu/application-update-using-application-menu.test.ts
  packages/core/src/features/application-update/child-features/application-update-using-application-menu/main/check-for-updates-menu-item.injectable.ts
  packages/core/src/features/application-update/child-features/application-update-using-tray/installing-update-using-tray.test.ts
  packages/core/src/features/application-update/child-features/application-update-using-tray/main/tray-items/check-for-updates-tray-item.injectable.ts
Labels: enhancement

#7423 Typescript and webpack config fixes
  packages/infrastructure/typescript/config/base.json
  packages/infrastructure/webpack/package.json
  packages/infrastructure/webpack/src/__snapshots__/get-multi-export-config.test.js.snap
  packages/infrastructure/webpack/src/get-react-config.js
Labels: chore

#7464 Add workload 'kind' param to 'show-details' event
  packages/core/src/features/telemetry/renderer/telemetry-white-list-for-functions.injectable.ts
Labels: enhancement, area/telemetry

#7494 Auto cancel stale workflows
  .github/workflows/electronegativity.yml
  .github/workflows/linter.yml
  .github/workflows/publish-docs.yml
  .github/workflows/test.yml
Labels: area/ci

#7495 feat: Allow built versions to specify an environment
  package.json
  packages/core/src/extensions/common-api/app.ts
  packages/open-lens/src/common/build-environment.injectable.ts
  packages/technical-features/application/agnostic/index.ts
  packages/technical-features/application/agnostic/src/environment-token.test.ts
  packages/technical-features/application/agnostic/src/environment-token.ts
Labels: enhancement, area/extension

#7468 fix: Referencing apiManager should not throw
  packages/core/src/common/k8s-api/__tests__/api-manager.test.ts
  packages/core/src/common/k8s-api/api-manager/api-manager.ts
  packages/core/src/common/k8s-api/api-manager/manager.injectable.ts
Labels: bug

#7164 Introduce clearer boundry between extensions
  packages/core/src/common/protocol-handler/router.ts
  packages/core/src/extensions/__tests__/extension-loader.test.ts
  packages/core/src/extensions/extension-discovery/extension-discovery.ts
  packages/core/src/extensions/extension-loader/create-extension-instance.token.ts
  packages/core/src/extensions/extension-loader/extension-loader.ts
  packages/core/src/extensions/lens-extension.ts
  packages/core/src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/features/extensions/enabled/common/is-enabled.injectable.ts
  packages/core/src/main/extension-loader/create-extension-instance.injectable.ts
  packages/core/src/main/protocol-handler/__test__/router.test.ts
  packages/core/src/main/protocol-handler/lens-protocol-router-main/lens-protocol-router-main.ts
  packages/core/src/main/start-main-application/runnables/flag-renderer/flag-renderer-as-loaded.injectable.ts
  packages/core/src/main/start-main-application/runnables/flag-renderer/flag-renderer-as-not-loaded.injectable.ts
  packages/core/src/renderer/components/+extensions/attempt-install/attempt-install.injectable.tsx
  packages/core/src/renderer/components/+extensions/attempt-install/unpack-extension.injectable.tsx
  packages/core/src/renderer/components/+extensions/disable-extension.injectable.ts
  packages/core/src/renderer/components/+extensions/disable-extension/disable-extension.injectable.ts
  packages/core/src/renderer/components/+extensions/disable-extension/disable-extension.ts
  packages/core/src/renderer/components/+extensions/enable-extension.injectable.ts
  packages/core/src/renderer/components/+extensions/enable-extension/enable-extension.injectable.ts
  packages/core/src/renderer/components/+extensions/enable-extension/enable-extension.ts
  packages/core/src/renderer/components/+extensions/extensions.tsx
  packages/core/src/renderer/components/+extensions/install.tsx
  packages/core/src/renderer/components/+extensions/installed-extensions.tsx
  packages/core/src/renderer/components/+extensions/uninstall-extension.injectable.tsx
  packages/core/src/renderer/components/+extensions/user-extensions/user-extensions.injectable.ts
  packages/core/src/renderer/extension-loader/create-extension-instance.injectable.ts
  packages/technical-features/application/legacy-extensions/src/bundled-extension.ts
  packages/technical-features/application/legacy-extensions/src/lens-extension.ts
Labels: chore, area/extension

#7509 Cherry-pick #7504 to master
  packages/core/src/extensions/extension-discovery/extension-discovery.ts
  packages/core/src/extensions/extension-discovery/stop-watching-extensions-on-quit.injectable.ts
  packages/core/src/main/catalog-sources/kubeconfig-sync/manager.ts
Labels: skip-changelog

#7511 Fix cherry-pick of #7504
  packages/core/src/extensions/extension-discovery/stop-watching-extensions-on-quit.injectable.ts
Labels: skip-changelog

#7529 Set status item `padding-inline` to 0 if there is no children elements
  packages/core/src/renderer/components/status-bar/status-bar.module.scss
Labels: area/ui, chore

#7507 Add metrics Feature
  package-lock.json
  packages/core/package.json
  packages/core/src/features/metrics/metrics-feature.ts
  packages/core/src/renderer/components/+cluster/cluster-overview.tsx
  packages/core/src/renderer/components/+namespaces/metrics-details-component.tsx
  packages/core/src/renderer/components/+network-ingresses/metrics-details-component.tsx
  packages/core/src/renderer/components/+nodes/metrics-details-component.tsx
  packages/core/src/renderer/components/+storage-volume-claims/metrics-details-component.tsx
  packages/core/src/renderer/components/+workloads-daemonsets/metrics-details-component.tsx
  packages/core/src/renderer/components/+workloads-deployments/metrics-details-component.tsx
  packages/core/src/renderer/components/+workloads-jobs/metrics-details-component.tsx
  packages/core/src/renderer/components/+workloads-pods/details/containers/pod-details-containers.tsx
  packages/core/src/renderer/components/+workloads-pods/details/containers/pod-details-init-containers.tsx
  packages/core/src/renderer/components/+workloads-pods/pod-details-container-metrics.tsx
  packages/core/src/renderer/components/+workloads-pods/pod-details-container.tsx
  packages/core/src/renderer/components/+workloads-pods/pod-details.tsx
  packages/core/src/renderer/components/+workloads-pods/pod-metrics-details-component.tsx
  packages/core/src/renderer/components/+workloads-replicasets/metrics-details-component.tsx
  packages/core/src/renderer/components/+workloads-statefulsets/metrics-details-component.tsx
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/daemon-set-details-metrics.injectable.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/deployment-details-metrics.injectable.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/details-metrics-container.tsx
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/get-metrics-kube-object-detail-item.injectable.tsx
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/ingress-details-metrics.injectable.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/job-details-metrics.injectable.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/namespace-details-metrics.injectable.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/node-details-metrics.injectable.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/persistent-volume-claim-metrics.injectable.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/pod-details-pod-metrics.injectable.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/replica-set-details-metrics.injectable.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/metrics/stateful-set-details-metrics.injectable.ts
  packages/core/src/renderer/library.ts
  packages/metrics/.eslintrc.js
  packages/metrics/.prettierrc
  packages/metrics/index.ts
  packages/metrics/jest.config.js
  packages/metrics/package.json
  packages/metrics/tsconfig.json
  packages/metrics/webpack.config.js
  packages/open-lens/src/renderer/index.ts
Labels: enhancement, area/metrics

#7535 Release 6.5.0-alpha.4
  package-lock.json
  packages/bump-version-for-cron/package.json
  packages/business-features/keyboard-shortcuts/package.json
  packages/cluster-settings/package.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/infrastructure/eslint-config/package.json
  packages/infrastructure/jest/package.json
  packages/infrastructure/typescript/package.json
  packages/infrastructure/webpack/package.json
  packages/legacy-extension-example/package.json
  packages/metrics/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
  packages/technical-features/application/agnostic/package.json
  packages/technical-features/application/electron-main/package.json
  packages/technical-features/application/legacy-extensions/package.json
  packages/technical-features/feature-core/package.json
  packages/technical-features/messaging/agnostic/package.json
  packages/technical-features/messaging/computed-channel/package.json
  packages/technical-features/messaging/electron/main/package.json
  packages/technical-features/messaging/electron/renderer/package.json
  packages/technical-features/messaging/message-bridge-fake/package.json
  packages/technical-features/react-application/package.json
  packages/utility-features/react-testing-library-discovery/package.json
  packages/utility-features/run-many/package.json
  packages/utility-features/startable-stoppable/package.json
  packages/utility-features/test-utils/package.json
  packages/utility-features/utilities/package.json
Labels: skip-changelog, release

#7540 Release 6.5.0-alpha.5
  package-lock.json
  packages/business-features/keyboard-shortcuts/package.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/legacy-extension-example/package.json
  packages/open-lens/package.json
  packages/utility-features/react-testing-library-discovery/package.json
Labels: skip-changelog, release

#7541 Release 6.5.0-alpha.6
  package-lock.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/legacy-extension-example/package.json
  packages/open-lens/package.json
Labels: skip-changelog, release

#7542 fix: Fix when github releases are marked as prereleases
  .github/workflows/release.yml
Labels: area/ci

#7550 fix: Make importing styles not break the builds
  packages/infrastructure/webpack/src/plugins/protect-from-importing-non-dependencies.js
Labels: bug

#7562 chore: Fix cron test workflow failing due to wrong reasons
  .github/workflows/cron-test.yaml
Labels: area/ci

#7563 Fixing creating Pod integration tests
  packages/open-lens/integration/__tests__/cluster-pages.tests.ts
Labels: chore

#7572 chore: Revert only running one cluster page e2e test
  packages/open-lens/integration/__tests__/cluster-pages.tests.ts
Labels: chore

#7579 Use strict dependency for extension-api -> core
  packages/extension-api/package.json
Labels: bug

#7584 chore: Fix unit tests by increasing coverage of tooltip to 100%
  package-lock.json
  packages/ui-components/tooltip/jest.config.js
  packages/ui-components/tooltip/package.json
  packages/ui-components/tooltip/src/__snapshots__/tooltip.test.tsx.snap
  packages/ui-components/tooltip/src/__snapshots__/withTooltip.test.tsx.snap
  packages/ui-components/tooltip/src/helpers.ts
  packages/ui-components/tooltip/src/tooltip.test.tsx
  packages/ui-components/tooltip/src/tooltip.tsx
  packages/ui-components/tooltip/src/withTooltip.test.tsx
  packages/ui-components/tooltip/src/withTooltip.tsx
Labels: area/ci

#7580 docs: Add documentation for cluster connection flow
  scenarios/cluster-connection.md
Labels: area/documentation

#7595 chore: Expand withTooltip unit tests
  packages/ui-components/tooltip/src/__snapshots__/withTooltip.test.tsx.snap
  packages/ui-components/tooltip/src/withTooltip.test.tsx
Labels: chore

#7544 List layout column injection token package
  package-lock.json
  packages/core/package.json
  packages/core/src/common/item.store.ts
  packages/core/src/common/k8s-api/endpoints/helm-releases.api.ts
  packages/core/src/common/k8s-api/kube-object.ts
  packages/core/src/features/cluster/workloads/__snapshots__/pods.test.tsx.snap
  packages/core/src/features/cluster/workloads/pods.test.tsx
  packages/core/src/renderer/components/+cluster/cluster-issues.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-age-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-containers-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-name-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-namespace-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-node-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-owners-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-qos-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-restarts-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-status-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/columns/pods-status-icon-column.injectable.tsx
  packages/core/src/renderer/components/+workloads-pods/pods.tsx
  packages/core/src/renderer/components/item-object-list/content.tsx
  packages/core/src/renderer/components/item-object-list/header.tsx
  packages/core/src/renderer/components/item-object-list/list-layout.tsx
  packages/core/src/renderer/components/kube-object-list-layout/__snapshots__/kube-object-list-layout.test.tsx.snap
  packages/core/src/renderer/components/kube-object-list-layout/kube-object-list-layout.test.tsx
  packages/core/src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  packages/core/src/renderer/components/table/table.tsx
  packages/core/src/renderer/port-forward/port-forward-item.ts
  packages/list-layout/.eslintrc.js
  packages/list-layout/.prettierrc
  packages/list-layout/index.ts
  packages/list-layout/jest.config.js
  packages/list-layout/kube-object-list-layout-column-injection-token.tsx
  packages/list-layout/package.json
  packages/list-layout/tsconfig.json
  packages/list-layout/webpack.config.js
Labels: enhancement, area/extension

#7611 ci: Fix test of 'Cron Test' workflow
  .github/workflows/cron-test.yaml
Labels: area/ci

#7621 Adjust container status colors to be distinguable with red/green filter
  packages/core/src/renderer/components/+workloads-pods/pods.scss
Labels: enhancement, area/accessibility

#7632 chore: extract @k8slens/resizing-anchor
  package-lock.json
  packages/core/package.json
  packages/core/src/renderer/components/dock/dock.tsx
  packages/core/src/renderer/components/drawer/drawer.tsx
  packages/core/src/renderer/components/layout/main-layout.tsx
  packages/ui-components/resizing-anchor/.eslintrc.json
  packages/ui-components/resizing-anchor/README.md
  packages/ui-components/resizing-anchor/index.ts
  packages/ui-components/resizing-anchor/jest.config.js
  packages/ui-components/resizing-anchor/package.json
  packages/ui-components/resizing-anchor/src/resizing-anchor.scss
  packages/ui-components/resizing-anchor/src/resizing-anchor.tsx
  packages/ui-components/resizing-anchor/tailwind.config.js
  packages/ui-components/resizing-anchor/tsconfig.json
  packages/ui-components/resizing-anchor/webpack.config.js
Labels: chore
