Repository lensapp/lens, pull requests merged in 2023-05, with the labels that each got.

#7648 chore(ci): Fix Daily Alpha workflow
  .github/workflows/daily-alpha.yml
Labels: area/ci

#7649 chore: Add git fetch to daily alpha to fix error
  .github/workflows/daily-alpha.yml
Labels: area/ci

#7658 Chore: extract event-emitter from core
  package-lock.json
  packages/core/package.json
  packages/core/src/common/app-event-bus/app-event-bus.injectable.ts
  packages/core/src/common/k8s-api/json-api.ts
  packages/core/src/extensions/common-api/event-bus.ts
  packages/core/src/extensions/extension-loader/extension-loader.ts
  packages/open-lens/package.json
  packages/utility-features/event-emitter/.eslintrc.js
  packages/utility-features/event-emitter/.prettierrc
  packages/utility-features/event-emitter/index.ts
  packages/utility-features/event-emitter/jest.config.js
  packages/utility-features/event-emitter/package.json
  packages/utility-features/event-emitter/src/event-emitter.test.ts
  packages/utility-features/event-emitter/src/event-emitter.ts
  packages/utility-features/event-emitter/tsconfig.json
  packages/utility-features/event-emitter/webpack.config.js
Labels: chore

#7675 Chore: extract json-api from core
  package-lock.json
  packages/core/src/common/fetch/fetch.injectable.ts
  packages/core/src/common/k8s-api/create-json-api.injectable.ts
  packages/core/src/common/k8s-api/create-kube-json-api.injectable.ts
  packages/core/src/common/k8s-api/kube-json-api.ts
  packages/core/src/common/utils/get-error-message.ts
  packages/core/src/extensions/common-api/k8s-api.ts
  packages/core/src/features/cluster/namespaces/edit-namespace-from-new-tab.test.tsx
  packages/core/src/renderer/components/notifications/notifications.store.ts
  packages/core/src/renderer/components/notifications/notifications.tsx
  packages/core/src/renderer/components/notifications/show-checked-error.injectable.ts
  packages/core/src/renderer/port-forward/port-forward-store/port-forward-store.ts
  packages/utility-features/json-api/.eslintrc.js
  packages/utility-features/json-api/.prettierrc
  packages/utility-features/json-api/index.ts
  packages/utility-features/json-api/jest.config.js
  packages/utility-features/json-api/package.json
  packages/utility-features/json-api/src/json-api.ts
  packages/utility-features/json-api/tsconfig.json
  packages/utility-features/json-api/webpack.config.js
Labels: chore

#7678 Remove some unused dependencies
  packages/logger/package.json
Labels: chore

#7681 chore: Fix daily alpha to generate release PR
  .github/workflows/daily-alpha.yml
  packages/release-tool/src/index.ts
Labels: area/ci

#7686 chore: Fix daily alpha workflow not having enough commits
  .github/workflows/daily-alpha.yml
Labels: area/ci

#7685 Make StatefulSet dialog consistent with ReplicaSet
  packages/core/src/renderer/components/workloads-deployments/scale/dialog.tsx
  packages/core/src/renderer/components/workloads-statefulsets/scale/dialog.tsx
Labels: bug

#7696 Change welcome icon to home
  packages/core/src/common/catalog-entities/general-catalog-entities/implementations/welcome-catalog-entity.injectable.ts
Labels: enhancement, area/catalog

#7699 chore: Don't fail daily alpha workflow when there is nothing to release
  .github/workflows/daily-alpha.yml
  packages/release-tool/src/index.ts
Labels: area/ci

#7705 chore: Fix build failing on non-windows platforms
  packages/generate-tray-icons/src/index.ts
Labels: bug, area/linux, area/macos

#7714 Fix open-lens package address in prestart-dev
  package-lock.json
  package.json
Labels: chore

#7715 fix: Kludge cluster settings not opening when extension introduces ne…
  packages/core/src/renderer/components/entity-settings/extension-registrator.injectable.ts
Labels: bug

#7702 Add missing styles to fix terminal resizing
  open-lens/package.json
  open-lens/src/renderer/index.ts
  package-lock.json
Labels: bug

#7717 Add welcome page to hotbar
  packages/core/src/common/vars/store-migration-version.injectable.ts
  packages/core/src/features/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  packages/core/src/features/__snapshots__/navigate-to-extension-page.test.tsx.snap
  packages/core/src/features/__snapshots__/navigating-between-routes.test.tsx.snap
  packages/core/src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  packages/core/src/features/application-update/__snapshots__/hiding-preference-when-disabled.test.ts.snap
  packages/core/src/features/application-update/__snapshots__/installing-update.test.ts.snap
  packages/core/src/features/application-update/child-features/application-update-using-application-menu/__snapshots__/application-update-using-application-menu.test.ts.snap
  packages/core/src/features/application-update/child-features/application-update-using-top-bar/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  packages/core/src/features/application-update/child-features/application-update-using-tray/__snapshots__/installing-update-using-tray.test.ts.snap
  packages/core/src/features/application-update/child-features/force-update/__snapshots__/force-update.test.ts.snap
  packages/core/src/features/application-update/child-features/periodical-checking-of-updates/__snapshots__/periodical-checking-of-updates.test.ts.snap
  packages/core/src/features/application-update/child-features/selection-of-update-stability/__snapshots__/selection-of-update-stability.test.ts.snap
  packages/core/src/features/catalog/__snapshots__/custom-columns.test.tsx.snap
  packages/core/src/features/catalog/__snapshots__/entity-running.test.tsx.snap
  packages/core/src/features/catalog/__snapshots__/opening-entity-details.test.tsx.snap
  packages/core/src/features/cluster/delete-dialog/__snapshots__/delete-cluster-dialog.test.tsx.snap
  packages/core/src/features/command-pallet/__snapshots__/keyboard-shortcuts.test.tsx.snap
  packages/core/src/features/entity-settings/__snapshots__/showing-settings-for-correct-entity.test.tsx.snap
  packages/core/src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/features/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  packages/core/src/features/helm-charts/__snapshots__/add-helm-repository-from-list-in-preferences.test.ts.snap
  packages/core/src/features/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
  packages/core/src/features/helm-charts/__snapshots__/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts.snap
  packages/core/src/features/hotbar/storage/main/welcome-page-migration.injectable.ts
  packages/core/src/features/hotbar/storage/main/welcome-page-migration.test.ts
  packages/core/src/features/hotbar/storage/storage-technical.test.ts
  packages/core/src/features/preferences/__snapshots__/closing-preferences.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/extension-adding-preference-tabs.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/hiding-of-empty-branches.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-application-preferences.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-telemetry-preferences.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/urls-of-legacy-extensions.test.tsx.snap
  packages/core/src/features/status-bar/__snapshots__/status-bar-items-originating-from-extensions.test.tsx.snap
  packages/core/src/features/top-bar/extension-api/__snapshots__/extendability-using-extension-api.test.tsx.snap
  packages/core/src/features/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/renderer/components/status-bar/__snapshots__/status-bar.test.tsx.snap
Labels: enhancement, area/hotbar

#7661 Bump bundled helm version to 3.11.0
  open-lens/package.json
Labels: bug, area/helm

#7726 chore: Fix dev mode of open-lens running is circles
  .nxignore
  nx.json
  open-lens/package.json
  package.json
  packages/core/package.json
Labels: chore

#7728 chore: Support and switch to using ^9.6.5 version of NPM
  .github/workflows/check-docs.yml
  .github/workflows/cron-test.yaml
  .github/workflows/daily-alpha.yml
  .github/workflows/linter.yml
  .github/workflows/mkdocs-manual.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-release-npm.yml
  .github/workflows/test.yml
  package.json
Labels: area/ci

#7735 chore: Fixup dependencies and ensure no duplication between kinds of dependencies
  .github/workflows/linter.yml
  open-lens/package.json
  package-lock.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/infrastructure/typescript/package.json
  packages/utility-features/utilities/package.json
  scripts/lint-package-dependencies.sh
  scripts/lint-publish-configs.sh
Labels: dependencies

#7739 switch back to arm64
  packages/ensure-binaries/src/index.ts
Labels: chore

#7745 fix: Remove erroneous prefixes when using loggerInjectable and prefixLoggerInjectable
  packages/logger/index.ts
  packages/logger/src/logger.injectable.ts
  packages/logger/src/logger.test.ts
  packages/logger/src/logger.ts
  packages/logger/src/prefixed-logger.injectable.ts
  packages/logger/src/transports.ts
Labels: bug

#7746 fix: Use correct path for node-shell shell PTY
  packages/core/src/main/shell-session/node-shell-session/node-shell-session.ts
Labels: bug, area/terminal

#7749 chore: Remove previous daily alpha when trying to create a new one
  packages/release-tool/src/index.ts
Labels: area/ci

#7753 Fix: wrong order of ids when sendToFrame is called
  packages/technical-features/messaging/electron/main/src/send-message-to-channel/send-message-to-channel.injectable.test.ts
  packages/technical-features/messaging/electron/main/src/send-message-to-channel/send-message-to-channel.injectable.ts
Labels: bug, blocker

#7760 Release 6.5.0-alpha.14
  open-lens/package.json
  package-lock.json
  packages/business-features/keyboard-shortcuts/package.json
  packages/cluster-settings/package.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/infrastructure/webpack/package.json
  packages/kube-object/package.json
  packages/kubectl-versions/package.json
  packages/legacy-extension-example/package.json
  packages/legacy-global-di/package.json
  packages/list-layout/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/release-tool/package.json
  packages/routing/package.json
  packages/technical-features/application/agnostic/package.json
  packages/technical-features/application/electron-main/package.json
  packages/technical-features/application/legacy-extensions/package.json
  packages/technical-features/feature-core/package.json
  packages/technical-features/messaging/agnostic/package.json
  packages/technical-features/messaging/computed-channel/package.json
  packages/technical-features/messaging/electron/main/package.json
  packages/technical-features/messaging/electron/renderer/package.json
  packages/technical-features/messaging/message-bridge-fake/package.json
  packages/technical-features/react-application/package.json
  packages/ui-components/button/package.json
  packages/ui-components/error-boundary/package.json
  packages/ui-components/resizing-anchor/package.json
  packages/ui-components/tooltip/package.json
  packages/utility-features/event-emitter/package.json
  packages/utility-features/run-many/package.json
  packages/utility-features/startable-stoppable/package.json
  packages/utility-features/test-utils/package.json
  packages/utility-features/utilities/package.json
Labels: skip-changelog, release

#7762 fix: Switch to using authenticated GitHub API to increase rate limit
  package-lock.json
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: bug

#7766 fix: Fix setting milestone on new release PRs
  packages/release-tool/src/index.ts
Labels: bug

#7768 Release 6.5.0-alpha.15
  open-lens/CHANGELOG.md
  open-lens/package.json
  package-lock.json
  package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/extension-api/CHANGELOG.md
  packages/extension-api/package.json
  packages/kubectl-versions/CHANGELOG.md
  packages/kubectl-versions/package.json
  packages/legacy-extension-example/CHANGELOG.md
  packages/legacy-extension-example/package.json
  packages/release-tool/CHANGELOG.md
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: skip-changelog, release

#7778 Make application size not blow up by consolidating dependencies
  open-lens/package.json
  package-lock.json
  packages/core/package.json
Labels: bug

#7776 Handle log responses as text
  packages/core/src/common/k8s-api/endpoints/pod.api.ts
Labels: bug

#7754 Table component injection tokens
  open-lens/src/renderer/index.ts
  package-lock.json
  packages/core/package.json
  packages/core/src/features/table/table-component.injectable.ts
  packages/core/src/features/table/table-feature.ts
  packages/core/src/renderer/components/config-pod-disruption-budgets/__tests__/pod-distruption-budgets.test.tsx
  packages/core/src/renderer/components/item-object-list/content.tsx
  packages/core/src/renderer/components/item-object-list/list-layout.tsx
  packages/core/src/renderer/components/kube-object-list-layout/kube-object-list-layout.test.tsx
  packages/core/src/renderer/components/kube-object-list-layout/kube-object-list-layout.tsx
  packages/core/src/renderer/components/test-utils/get-application-builder.tsx
  packages/core/src/renderer/library.ts
  packages/logger/src/logger.injectable.ts
  packages/logger/src/logger.test.ts
  packages/logger/src/transports.ts
  packages/table/README.md
  packages/table/index.ts
  packages/table/package.json
  packages/table/tsconfig.json
  packages/table/webpack.config.js
Labels: chore

#7799 Release 6.5.1
  open-lens/package.json
  package-lock.json
  packages/core/package.json
  packages/extension-api/package.json
  packages/legacy-extension-example/package.json
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: skip-changelog, release

#7801 Temporary fix for extensions always disabled on startup
  packages/core/src/features/extensions/enabled/common/storage.injectable.ts
Labels: bug
