Repository lensapp/lens, pull requests merged in 2023-02, with the labels that each got.

#7081 Allow to develop & build on Windows powershell
  .github/workflows/test.yml
  package.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
  yarn.lock
Labels: area/windows, chore

#7078 Fix ensure-binaries bin
  .github/workflows/test.yml
  lerna.json
  packages/ensure-binaries/package.json
  packages/open-lens/package.json
Labels: bug

#7084 Release 6.4.0-beta.11
  lerna.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
Labels: skip-changelog, release

#7085 Fix publish release use of internal package
  .github/workflows/publish-release-npm.yml
  package.json
  yarn.lock
Labels: area/ci

#7086 Release 6.4.0-beta.12
  lerna.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
Labels: skip-changelog, release

#7094 Set core webpack dependencies as externals
  packages/core/package.json
  packages/core/webpack/common.ts
  packages/core/webpack/library-bundle.ts
  packages/core/webpack/main.ts
  packages/core/webpack/renderer.ts
  packages/core/webpack/vars.ts
  packages/core/yarn.lock
Labels: bug, area/build

#7101 Fix invalid bin links causing errors on windows
  package.json
Labels: bug, area/windows, area/build

#7100 Fix open-lens package missing fonts
  packages/open-lens/package.json
  packages/open-lens/webpack/renderer.ts
  packages/open-lens/yarn.lock
Labels: bug, area/ui

#7099 Fix common extension api bundling
  packages/core/src/common/library.ts
  packages/core/src/main/library.ts
  packages/core/src/renderer/library.ts
  packages/extension-api/src/extension-api.ts
  packages/open-lens/src/main/index.ts
  packages/open-lens/src/renderer/index.ts
Labels: bug, area/extension, blocker

#7106 Release 6.4.0-beta.13
  lerna.json
  package.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
  yarn.lock
Labels: skip-changelog, release

#6795 Renderer file logging transport
  packages/core/src/common/logger.injectable.ts
  packages/core/src/common/winston-logger.injectable.ts
  packages/core/src/renderer/bootstrap.tsx
  packages/core/src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.injectable.ts
  packages/core/src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
  packages/core/src/renderer/frames/root-frame/init-root-frame.injectable.ts
  packages/core/src/renderer/logger/close-renderer-log-file.injectable.ts
  packages/core/src/renderer/logger/file-transport.injectable.ts
Labels: enhancement

#7118 Use setCertificateVerifyProc to verify lens proxy certificate
  packages/core/src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts
Labels: bug

#7127 Add daily-alpha release for open-lens
  .github/workflows/daily-alpha.yml
  .github/workflows/publish-master-npm.yml
Labels: chore

#7130 Remove self-referencial from root package.json
  .github/workflows/publish-release-npm.yml
  package.json
  yarn.lock
Labels: chore

#7132 Mark subnamespaces in namespace list
  packages/core/src/renderer/components/+namespaces/namespaces.scss
  packages/core/src/renderer/components/+namespaces/route.tsx
  packages/core/src/renderer/components/+namespaces/subnamespace-badge.tsx
Labels: enhancement, area/ui, area/kubernetes-next

#7080 Namespace details tree view
  packages/core/src/common/k8s-api/endpoints/namespace.api.ts
  packages/core/src/renderer/components/+namespaces/__snapshots__/namespace-tree-view.test.tsx.snap
  packages/core/src/renderer/components/+namespaces/hierarchical-namespaces.injectable.ts
  packages/core/src/renderer/components/+namespaces/namespace-details.tsx
  packages/core/src/renderer/components/+namespaces/namespace-store.test.ts
  packages/core/src/renderer/components/+namespaces/namespace-tree-view.module.scss
  packages/core/src/renderer/components/+namespaces/namespace-tree-view.test.tsx
  packages/core/src/renderer/components/+namespaces/namespace-tree-view.tsx
  packages/core/src/renderer/components/+namespaces/namespaces.scss
  packages/core/src/renderer/components/+namespaces/route.tsx
  packages/core/src/renderer/components/+namespaces/store.ts
  packages/core/src/renderer/components/+namespaces/subnamespace-badge.module.scss
  packages/core/src/renderer/components/+namespaces/subnamespace-badge.tsx
Labels: enhancement, area/ui, area/kubernetes-next

#7124 Fix: create/edit resource tab Save & Close button behavior
  packages/core/src/features/cluster/namespaces/__snapshots__/edit-namespace-from-new-tab.test.tsx.snap
  packages/core/src/features/cluster/namespaces/edit-namespace-from-new-tab.test.tsx
  packages/core/src/renderer/components/dock/create-resource/view.tsx
  packages/core/src/renderer/components/dock/edit-resource/edit-resource-model/edit-resource-model.injectable.tsx
  packages/core/src/renderer/components/dock/info-panel.tsx
Labels: bug, area/dock

#7144 Fix typing issue with userStorePreferenceDescriptorsInjectable
  packages/core/src/common/user-store/preferences-helpers.ts
Labels: bug

#7129 Fix daily-cron failing to bump version
  .github/workflows/daily-alpha.yml
  packages/bump-version-for-cron/.gitignore
  packages/bump-version-for-cron/.swcrc
  packages/bump-version-for-cron/package.json
  packages/bump-version-for-cron/src/index.ts
  packages/bump-version-for-cron/tsconfig.json
  packages/bump-version-for-cron/yarn.lock
Labels: chore

#7147 Fix node shell not loading due to Host/certificate mismatch
  packages/core/src/main/k8s/api-base-host-header.injectable.ts
  packages/core/src/main/lens-proxy/lens-proxy-certificate-request-handler.injectable.ts
Labels: bug, area/terminal

#7152 Add a bit of spacing before Installed extensions title
  packages/core/src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/renderer/components/+extensions/extensions.tsx
Labels: bug, area/ui

#7107 Enable extension to specify storeName for persisting data
  packages/core/src/extensions/__tests__/configurable-directories.test.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/file-system-provisioner-store.injectable.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/file-system-provisioner-store.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-hash.injectable.ts
  packages/core/src/extensions/extension-store.ts
  packages/core/src/extensions/lens-extension.ts
Labels: enhancement, area/extension

#7161 Fix extension installation
  packages/core/src/extensions/extension-discovery/extension-discovery.ts
Labels: bug

#7163 Add bundled extension versions to 'About Lens'
  packages/core/src/features/application-menu/main/menu-items/special-menu-for-mac-application/show-about-application/about-bundled-extensions.injectable.ts
  packages/core/src/features/application-menu/main/menu-items/special-menu-for-mac-application/show-about-application/show-about.injectable.ts
Labels: enhancement

#7174 Fix configuration shown release details being stale
  packages/core/src/features/helm-releases/__snapshots__/showing-details-for-helm-release.test.ts.snap
  packages/core/src/features/helm-releases/showing-details-for-helm-release.test.ts
  packages/core/src/renderer/components/+helm-releases/release-details/release-details-content.tsx
Labels: bug

#7175 Change extension ipc registration log level from info to debug
  packages/core/src/extensions/ipc/ipc-main.ts
  packages/core/src/extensions/ipc/ipc-renderer.ts
Labels: chore, area/extension

#7180 Fix chromium net error codes
  packages/core/src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts
Labels: bug, blocker

#7178 Fix log tab double scrollbars bug
  packages/core/src/renderer/components/dock/logs/list.scss
Labels: bug, area/ui, area/logs

#7166 Add support for specifying orderNumber for ClusterPageMenus
  packages/core/src/features/cluster/__snapshots__/sidebar-and-tab-navigation-for-extensions.test.tsx.snap
  packages/core/src/features/cluster/sidebar-and-tab-navigation-for-extensions.test.tsx
  packages/core/src/renderer/components/layout/cluster-page-menu.ts
  packages/core/src/renderer/components/layout/extension-sidebar-item-registrator.injectable.tsx
Labels: enhancement, area/extension

#7167 Export requestMetrics to extension api
  packages/core/src/common/k8s-api/endpoints/metrics.api/request-metrics.injectable.ts
  packages/core/src/extensions/renderer-api/k8s-api.ts
Labels: enhancement, area/extension

#7177 Fix empty pod logs tab content
  packages/core/src/renderer/components/dock/logs/list.scss
  packages/core/src/renderer/components/dock/logs/logs-view-model.injectable.ts
  packages/core/src/renderer/components/dock/logs/view.tsx
Labels: bug, area/logs, area/dock

#7115 Switch to using NPM workspaces
  .github/workflows/check-docs.yml
  .github/workflows/daily-alpha.yml
  .github/workflows/linter.yml
  .github/workflows/main.yml
  .github/workflows/mkdocs-manual.yml
  .github/workflows/publish-release-npm.yml
  .github/workflows/test.yml
  .npmrc
  .yarnrc
  RELEASE_GUIDE.md
  lerna.json
  package-lock.json
  package.json
  packages/bump-version-for-cron/src/index.ts
  packages/bump-version-for-cron/yarn.lock
  packages/core/.yarnrc
  packages/core/package.json
  packages/core/webpack/main.ts
  packages/core/webpack/renderer.ts
  packages/core/yarn.lock
  packages/ensure-binaries/yarn.lock
  packages/extension-api/package.json
  packages/extension-api/yarn.lock
  packages/generate-tray-icons/yarn.lock
  packages/node-fetch/package.json
  packages/node-fetch/yarn.lock
  packages/open-lens/.yarnrc
  packages/open-lens/package.json
  packages/open-lens/webpack/main.ts
  packages/open-lens/webpack/renderer.ts
  packages/open-lens/webpack/vars.ts
  packages/open-lens/yarn.lock
  packages/release-tool/src/index.ts
  packages/release-tool/yarn.lock
  packages/semver/package.json
  packages/semver/yarn.lock
  yarn.lock
Labels: chore

#7197 Add package for sharing typescript configurations for upcoming Features
  package-lock.json
  packages/infrastructure/typescript/README.md
  packages/infrastructure/typescript/config/base.json
  packages/infrastructure/typescript/config/styles.d.ts
  packages/infrastructure/typescript/package.json
Labels: chore

#7202 Fix: removed duplicated labels & annotations for Node-details view
  packages/core/src/renderer/components/+nodes/details.tsx
Labels: bug

#7188 Fix ensure hashed directory for extension
  packages/core/src/common/utils/random-bytes.global-override-for-injectable.ts
  packages/core/src/common/utils/random-bytes.injectable.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/file-system-provisioner-store-injection-token.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/file-system-provisioner-store.injectable.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/file-system-provisioner-store.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.injectable.ts
  packages/core/src/extensions/extension-loader/file-system-provisioner-store/registered-extensions.injectable.ts
Labels: bug

#7203 [UX]: allow to navigate to namespace-details from other resource details view
  package-lock.json
  packages/core/src/features/cluster/kube-object-details/extension-api/__snapshots__/disable-kube-object-detail-items-when-cluster-is-not-relevant.test.tsx.snap
  packages/core/src/features/cluster/kube-object-details/extension-api/__snapshots__/reactively-hide-kube-object-detail-item.test.tsx.snap
  packages/core/src/renderer/components/kube-object-meta/kube-object-meta.tsx
Labels: enhancement

#7198 Add package for sharing jest configuration for upcoming Features
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  packages/infrastructure/jest/README.md
  packages/infrastructure/jest/bin/test.sh
  packages/infrastructure/jest/index.js
  packages/infrastructure/jest/monorepo-package-config.js
  packages/infrastructure/jest/monorepo-root-config.js
  packages/infrastructure/jest/package.json
  packages/infrastructure/jest/setup-react-tests.ts
Labels: chore

#7199 Add package for sharing webpack configurations for upcoming Features
  .gitignore
  package-lock.json
  packages/bump-version-for-cron/.gitignore
  packages/core/.gitignore
  packages/ensure-binaries/.gitignore
  packages/extension-api/.gitignore
  packages/generate-tray-icons/.gitignore
  packages/infrastructure/webpack/README.md
  packages/infrastructure/webpack/bin/build.sh
  packages/infrastructure/webpack/bin/remove-build.sh
  packages/infrastructure/webpack/index.js
  packages/infrastructure/webpack/jest.config.js
  packages/infrastructure/webpack/package.json
  packages/infrastructure/webpack/src/get-multi-export-config.js
  packages/infrastructure/webpack/src/get-multi-export-config.test.js
  packages/infrastructure/webpack/src/node-config.js
  packages/infrastructure/webpack/src/react-config.js
  packages/node-fetch/.gitignore
  packages/open-lens/.gitignore
  packages/release-tool/.gitignore
  packages/semver/.gitignore
Labels: chore

#7209 Fix dropdown items readability in Dock
  packages/core/src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-new-tab.test.ts.snap
  packages/core/src/features/helm-charts/installing-chart/__snapshots__/installing-helm-chart-from-previously-opened-tab.test.ts.snap
  packages/core/src/features/helm-charts/upgrade-chart/__snapshots__/upgrade-chart-new-tab.test.ts.snap
  packages/core/src/renderer/components/dock/create-resource/view.tsx
  packages/core/src/renderer/components/dock/install-chart/view.tsx
  packages/core/src/renderer/components/dock/upgrade-chart/view.tsx
  packages/core/src/renderer/components/select/select.scss
Labels: bug, area/ui

#7210 Fix command line argument not being passed to lerna
  packages/bump-version-for-cron/src/index.ts
Labels: bug

#7212 Fix PodList TableHead overflow
  packages/core/src/renderer/components/+workloads-deployments/deployment-replicasets.tsx
  packages/core/src/renderer/components/+workloads-pods/pod-details-list.tsx
  packages/core/src/renderer/components/table/table-head.scss
Labels: bug, area/ui

#7213 Release 6.4.0-beta.14
  lerna.json
  packages/bump-version-for-cron/package.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
Labels: skip-changelog, release

#7215 Remove notarize as unused
  package-lock.json
  packages/core/build/notarize.js
  packages/core/package.json
Labels: chore

#7216 Load release data on every details open
  packages/core/src/renderer/components/+helm-releases/release-details/release-details-content.tsx
Labels: bug

#7218 Release 6.4.0-beta.15
  lerna.json
  packages/bump-version-for-cron/package.json
  packages/core/package.json
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/semver/package.json
Labels: skip-changelog, release

#7220 Fix windows not being able to build new Feature packages
  package-lock.json
  packages/infrastructure/jest/package.json
  packages/infrastructure/webpack/bin/build.sh
  packages/infrastructure/webpack/bin/remove-build.sh
  packages/infrastructure/webpack/package.json
  packages/infrastructure/webpack/src/get-multi-export-config.js
  packages/infrastructure/webpack/src/get-multi-export-config.test.js
  packages/technical-features/application/package.json
Labels: bug

#7221 Add publish configuration to packages that are public
  packages/infrastructure/jest/package.json
  packages/infrastructure/typescript/package.json
  packages/infrastructure/webpack/package.json
  packages/technical-features/application/package.json
Labels: chore

#7226 Fix catalog avatar font size
  packages/core/src/renderer/components/+catalog/catalog.module.scss
Labels: bug, area/catalog

#7230 Release 6.4.0-beta.16
  lerna.json
  packages/bump-version-for-cron/package.json
  packages/core/package.json
  packages/core/src/renderer/components/+catalog/catalog.module.scss
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/node-fetch/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
  packages/semver/package.json
Labels: skip-changelog, release

#7235 Fix ApiManager not handling duplicate apiBases of KubeApis
  packages/core/src/common/k8s-api/__tests__/api-manager.test.ts
  packages/core/src/common/k8s-api/api-manager/api-manager.ts
Labels: bug, area/extension, blocker

#7217 Allow extensions to opt-out of KubeApi auto registering
  packages/core/src/extensions/common-api/k8s-api.ts
Labels: enhancement, area/extension

#7232 Various improvements to release-tool
  package-lock.json
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: chore

#7233 Remove all references to slack
  README.md
  docs/README.md
  mkdocs.yml
  packages/core/src/common/vars.ts
  packages/core/src/extensions/common-api/app.ts
  packages/core/src/features/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  packages/core/src/features/__snapshots__/navigate-to-extension-page.test.tsx.snap
  packages/core/src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  packages/core/src/features/application-update/__snapshots__/installing-update.test.ts.snap
  packages/core/src/features/application-update/child-features/application-update-using-top-bar/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  packages/core/src/features/application-update/child-features/application-update-using-tray/__snapshots__/installing-update-using-tray.test.ts.snap
  packages/core/src/features/application-update/child-features/force-update/__snapshots__/force-update.test.ts.snap
  packages/core/src/features/application-update/child-features/periodical-checking-of-updates/__snapshots__/periodical-checking-of-updates.test.ts.snap
  packages/core/src/features/application-update/child-features/selection-of-update-stability/__snapshots__/selection-of-update-stability.test.ts.snap
  packages/core/src/features/catalog/__snapshots__/opening-entity-details.test.tsx.snap
  packages/core/src/features/command-pallet/__snapshots__/keyboard-shortcuts.test.tsx.snap
  packages/core/src/features/entity-settings/__snapshots__/showing-settings-for-correct-entity.test.tsx.snap
  packages/core/src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  packages/core/src/features/status-bar/__snapshots__/status-bar-items-originating-from-extensions.test.tsx.snap
  packages/core/src/features/top-bar/extension-api/__snapshots__/extendability-using-extension-api.test.tsx.snap
  packages/core/src/features/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/main/weblinks-store/links.ts
  packages/core/src/main/weblinks-store/migrations/5.1.4.injectable.ts
  packages/core/src/main/weblinks-store/migrations/5.4.5-beta.1.injectable.ts
  packages/core/src/main/weblinks-store/migrations/currentVersion.injectable.ts
  packages/core/src/renderer/components/+welcome/welcome.tsx
  packages/core/src/renderer/components/error-boundary/error-boundary.tsx
Labels: chore

#7237 Release 6.4.0-beta.17
  README.md
  docs/README.md
  lerna.json
  mkdocs.yml
  packages/core/package.json
  packages/core/src/common/k8s-api/__tests__/api-manager.test.ts
  packages/core/src/common/k8s-api/api-manager/api-manager.ts
  packages/core/src/common/vars.ts
  packages/core/src/extensions/common-api/app.ts
  packages/core/src/extensions/common-api/k8s-api.ts
  packages/core/src/features/__snapshots__/extension-special-characters-in-page-registrations.test.tsx.snap
  packages/core/src/features/__snapshots__/navigate-to-extension-page.test.tsx.snap
  packages/core/src/features/add-cluster/__snapshots__/navigation-using-application-menu.test.tsx.snap
  packages/core/src/features/application-update/__snapshots__/installing-update.test.ts.snap
  packages/core/src/features/application-update/child-features/application-update-using-top-bar/__snapshots__/installing-update-using-topbar-button.test.tsx.snap
  packages/core/src/features/application-update/child-features/application-update-using-tray/__snapshots__/installing-update-using-tray.test.ts.snap
  packages/core/src/features/application-update/child-features/force-update/__snapshots__/force-update.test.ts.snap
  packages/core/src/features/application-update/child-features/periodical-checking-of-updates/__snapshots__/periodical-checking-of-updates.test.ts.snap
  packages/core/src/features/application-update/child-features/selection-of-update-stability/__snapshots__/selection-of-update-stability.test.ts.snap
  packages/core/src/features/catalog/__snapshots__/opening-entity-details.test.tsx.snap
  packages/core/src/features/command-pallet/__snapshots__/keyboard-shortcuts.test.tsx.snap
  packages/core/src/features/entity-settings/__snapshots__/showing-settings-for-correct-entity.test.tsx.snap
  packages/core/src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  packages/core/src/features/status-bar/__snapshots__/status-bar-items-originating-from-extensions.test.tsx.snap
  packages/core/src/features/top-bar/extension-api/__snapshots__/extendability-using-extension-api.test.tsx.snap
  packages/core/src/features/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/main/weblinks-store/links.ts
  packages/core/src/main/weblinks-store/migrations/5.1.4.injectable.ts
  packages/core/src/main/weblinks-store/migrations/5.4.5-beta.1.injectable.ts
  packages/core/src/main/weblinks-store/migrations/currentVersion.injectable.ts
  packages/core/src/renderer/components/+welcome/welcome.tsx
  packages/core/src/renderer/components/error-boundary/error-boundary.tsx
  packages/extension-api/package.json
  packages/open-lens/package.json
  packages/release-tool/package.json
  packages/release-tool/src/index.ts
Labels: skip-changelog, release

#7239 Throw on errors in kubectlApplyFolder
  packages/core/src/common/__tests__/create-resource-stack.test.ts
  packages/core/src/common/k8s/resource-stack.ts
Labels: bug

#7241 Upgrade and adapt to new version of libraries in ogre-tools
  package-lock.json
  packages/core/package.json
  packages/core/src/common/__tests__/cluster-store.test.ts
  packages/core/src/common/__tests__/user-store.test.ts
  packages/core/src/common/k8s-api/__tests__/api-manager.test.ts
  packages/core/src/common/k8s-api/__tests__/kube-api-version-detection.test.ts
  packages/core/src/common/k8s-api/__tests__/kube-api.test.ts
  packages/core/src/common/utils/channel/channel.test.ts
  packages/core/src/common/utils/with-orphan-promise/with-orphan-promise.injectable.ts
  packages/core/src/features/catalog/opening-entity-details.test.tsx
  packages/core/src/features/entity-settings/__snapshots__/showing-settings-for-correct-entity.test.tsx.snap
  packages/core/src/features/entity-settings/showing-settings-for-correct-entity.test.tsx
  packages/core/src/main/register-injectables.ts
  packages/core/src/renderer/components/kube-object-list-layout/kube-object-list-layout.test.tsx
  packages/core/src/renderer/getDiForUnitTesting.tsx
  packages/core/src/renderer/register-injectables.ts
  packages/open-lens/package.json
  packages/open-lens/src/main/index.ts
  packages/open-lens/src/renderer/index.ts
  packages/technical-features/application/package.json
Labels: chore

#7243 Quick fix for store migration version being wrong
  packages/core/src/common/vars/store-migration-version.injectable.ts
Labels: bug

#7238 General fixes for release-tool
  packages/release-tool/src/index.ts
Labels: chore

#7242 Introduce package for Features
  package-lock.json
  packages/technical-features/feature-core/README.md
  packages/technical-features/feature-core/index.ts
  packages/technical-features/feature-core/jest.config.js
  packages/technical-features/feature-core/package.json
  packages/technical-features/feature-core/src/deregister-feature.ts
  packages/technical-features/feature-core/src/feature-context-map-injectable.ts
  packages/technical-features/feature-core/src/feature-dependencies.test.ts
  packages/technical-features/feature-core/src/feature.ts
  packages/technical-features/feature-core/src/register-feature.ts
  packages/technical-features/feature-core/src/registration-of-feature.test.ts
  packages/technical-features/feature-core/tsconfig.json
  packages/technical-features/feature-core/webpack.config.js
Labels: enhancement

#7245 Revert "Renderer file logging transport (#6795)"
  packages/core/src/common/logger.injectable.ts
  packages/core/src/common/winston-logger.injectable.ts
  packages/core/src/renderer/bootstrap.tsx
  packages/core/src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.injectable.ts
  packages/core/src/renderer/frames/cluster-frame/init-cluster-frame/init-cluster-frame.ts
  packages/core/src/renderer/frames/root-frame/init-root-frame.injectable.ts
  packages/core/src/renderer/logger/close-renderer-log-file.injectable.ts
  packages/core/src/renderer/logger/file-transport.injectable.ts
Labels: bug
